### ISSUE TITLE
   Error: read ECONNRESET       at TCP.onStreamRead (internal/stream_base_commons.js:205:27)

### ISSUE THREAD

**Issue by WangJunJavaXX** [alibaba/macaca#1004]
一直在测试到 30秒的是后连接断开，重新连接从头开始在测试在来一遍，这是应为超时时间的问问题吗？

**Comment by WangJunJavaXX** [comment]
我们需要的是一直测试，测试到底，但是运行到30s 的时候程序自己停止了，重新开始冲头在测试一遍，每次到30多秒的是后就自动停止了，我们现在不知道怎么解决这个问题，能够人程序一次直接一直测试到最后在结束。










At 2021-11-18 17:01:06, "Macaca" ***@***.***> wrote:

This is the translated issue:

Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)

It has been tested to 30 seconds, and then the connection is disconnected, and the reconnection begins on the test in the test. Is this what should be asked for timeout?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WangJunJavaXX** [comment]
Error: Read Econnreset At TCP.OnStreamRead (Internal / stream_base_commons.js: 205: 27)   ，这个错误是每次 停止前的报错信息。
遇到这个错误，程序就自动退出了。这个不是我们想要的。我们想要的是程序一直运行一直测试，直到整个微信小程序 功能测试完成，再退出，并生成测试报告。
















At 2021-11-18 17:18:46, "Macaca" ***@***.***> wrote:

This is the translated issue comment: @WangJunJavaXX

What we need is to test, test it, but the program is stopped when running to 30s, and the restart of the punch is tested. After more than 30 seconds, it will automatically stop, we don't know how to solve this now. The problem, can be tested directly to the end at the end.

AT 2021-11-18 17:01:06, "Macaca" @.***> Wrote:

This is the translated is the the translated it

Error: Read Econnreset At TCP.OnStreamRead (Internal / stream_base_commons.js: 205: 27)

IT HAS Been Tested to 30 Seconds, and The Reconnection IS Disconnected, And The Reconnection Begins on The Test in The Test. Is this What Should Be Asked for Timeout?

You are receiving this because you authored the thread.
Reply to this email Directly, View It on GitHub, or Unsbscribe.
Triage Notifications On The Go with GitHub Mobile for iOS or Android.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
