### ISSUE TITLE
ios自动化测试运行macaca run --verbose后，出现cannot resolve path (or pattern) 'macaca-test'

### ISSUE THREAD

**Issue by ycx198927** [alibaba/macaca#114]
* **Macaca Version**: 1.1.0

* **Macaca Doctor**:   Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.3.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2333.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.6.0_65`
  JAVA_HOME is not set
  ANDROID_HOME is not set

  Installed driver list:

* **Platform**: mac os x.10.9

问题描述如下，运行macaca run --verbose 后报错，报错如下：
index.js:17:12 [master] pid:620 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.58.128',
  host: 'yanlideMac.local',
  loaded_time: '2016-08-16 02:08:59' }
>> middlewares.js:17:10 [master] pid:620 base middlewares attached
>> router.js:108:10 [master] pid:620 router set
>> webdriver sdk launched
>> /usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.2.4.5@mocha/lib/utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) 'macaca-test'
    at Object.lookupFiles (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.2.4.5@mocha/lib/utils.js:628:15)
    at /usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.2.4.5@mocha/bin/_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.2.4.5@mocha/bin/_mocha:325:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

>> Test completed!

**Comment by zenzhu** [comment]
应该是没有 macaca-test 文件夹，默认会遍历 macaca-test 文件夹，如果需要定制，可以用 macaca run -d ./test 这样
