### ISSUE TITLE
macaca-android-sample.test.js Error

### ISSUE THREAD

**Issue by AladdinGenie** [alibaba/macaca#119]
**Macaca Version:**1.1.0

**Macaca Doctor:**

  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v4.4.7

  Android checklist:

  JAVA version is `1.8.0_31`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_31`
  ANDROID_HOME is set to `D:\android-sdk-windows`
  Platforms is set to `D:\android-sdk-windows\platforms\android-24`
  Android tools is set to `D:\android-sdk-windows\tools\android.bat`
  ANT_HOME is set to `D:\apache-ant-1.9.7`

  Installed driver list:

  android: 1.0.25
  chrome: 1.0.1

**Platform:**win10 64-bit

**Error Info:**

D:\macaca\macaca-test-sample-master\macaca-test>macaca run -d macaca-android-sample.test.js --verbose
>> index.js:17:12 [master] pid:3940 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.56.1',
  host: 'USER-7U3T71DDHT',
  loaded_time: '2016-08-17 11:49:22' }
>> middlewares.js:17:10 [master] pid:3940 base middlewares attached
>> router.js:108:10 [master] pid:3940 router set
>> webdriver sdk launched
>>

>>

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:3940 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"Android","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:3940 Creating session, sessionId: 8d691cc7-4e44-4be6-965b-6f228c457160.
>> responseHandler.js:50:12 [master] pid:3940 Send Error Respone to Client: exec D:\android-sdk-windows/platform-tools/adb devices error with: Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\android-sdk-windows/platform-tools/adb devices"
ϵͳ�Ҳ���ָ����·����

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\koa\lib\context.js:91:23)
      at Object.module.exports (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\responseHandler.js:53:17)
      at throw (native)
      at onRejected (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:81:24)
      at process._tickCallback (node.js:369:9)

>>
>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:3940 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:19:14 [master] pid:3940 Send HTTP Respone to Client: 405 Method Not Allowed
>>
>>     2) "after all" hook

>>
  0 passing (6s)
  2 failing

  1) macaca mobile sample "before all" hook:
     Error: [init({"autoAcceptAlerts":true,"platformName":"Android"})] The environment you requested was unavailable.
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:134:15
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at null.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\callbacks.js:42:12)
      at cb (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:165:22)
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

>> Test completed!

D:\macaca\macaca-test-sample-master\macaca-test>browserNamebrowserName

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5483

**Comment by AladdinGenie** [comment]
就是看这个文档操作的，结果就是Android的sample跑不过，烦请看看还有啥可能

**Comment by zhuominjie** [comment]
@xudafeng 您提供的链接：win10环境折腾macaca没有找到答案。nternalServerError: Internal Server Error和后面两个fail是什么原因，怎么解决？
