### ISSUE TITLE
pip install -r requirements.txt时six uninstall旧版本时报错

### ISSUE THREAD

**Issue by hzg17** [alibaba/macaca#121]
* **Macaca Version**:
1.1.0
* **Macaca Doctor**:

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.7

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is not set
  ANDROID_HOME is not set

  Installed driver list:

  chrome: 1.0.1
  electron: 1.1.2
  ios: 1.0.31

* **Platform**:
mac os 10.11.6

pip install -r requirements.txt时six uninstall旧版本时报错，执行结果如下
Collecting wd (from -r requirements.txt (line 1))
  Downloading wd-0.1.1.zip
Requirement already satisfied (use --upgrade to upgrade): requests in /Library/Python/2.7/site-packages/requests-2.10.0-py2.7.egg (from wd->-r requirements.txt (line 1))
Collecting retrying (from wd->-r requirements.txt (line 1))
  Downloading retrying-1.3.3.tar.gz
Collecting six>=1.7.0 (from retrying->wd->-r requirements.txt (line 1))
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, retrying, wd
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-f_G1Nn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

在网络的帮助下，成功执行了sudo -H pip install -r requirements.txt --ignore-installed six
不知道会不会有影响

**Comment by zenzhu** [comment]
应该没问影响，不过你最好在 virtualenv 下运行，这样不会互相影响。
