### ISSUE TITLE
运行python示例报错

### ISSUE THREAD

**Issue by hzg17** [alibaba/macaca#122]
* **Macaca Version**:
1.1.0
* **Macaca Doctor**:

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.7

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is not set
  ANDROID_HOME is not set

  Installed driver list:

  chrome: 1.0.1
  electron: 1.1.2
  ios: 1.0.31

* **Platform**:
mac os 10.11.6

运行python示例报错
执行 python macaca-desktop-sample.test.py
提示错误：
Traceback (most recent call last):
  File "macaca-desktop-sample.test.py", line 3, in <module>
    from macaca import WebDriver
  File "/Library/Python/2.7/site-packages/macaca/__init__.py", line 25, in <module>
    from .webdriver import WebDriver
  File "/Library/Python/2.7/site-packages/macaca/webdriver.py", line 697
    *, asserter=lambda x: x):
     ^
SyntaxError: invalid syntax

**Comment by zenzhu** [comment]
请使用 Python 3.4 试试。

**Comment by hzg17** [comment]
3.5运行报错
python3 macaca-desktop-sample.test.py
E
======================================================================
ERROR: setUpClass (__main__.MacacaTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x10e1d73c8>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3456): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10e1d73c8>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "macaca-desktop-sample.test.py", line 19, in setUpClass
    cls.driver.init()
  File "/usr/local/lib/python3.5/site-packages/macaca/util.py", line 140, in fluent_interface
    ret = func(instance, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/macaca/webdriver.py", line 132, in init
    }, False)
  File "/usr/local/lib/python3.5/site-packages/macaca/webdriver.py", line 66, in _execute
    res = self.remote_invoker.execute(command, data)
  File "/usr/local/lib/python3.5/site-packages/macaca/remote_invoker.py", line 107, in execute
    return self._request(method, url, body)
  File "/usr/local/lib/python3.5/site-packages/macaca/remote_invoker.py", line 141, in _request
    res = s.send(prepped, timeout=self._timeout or None)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3456): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10e1d73c8>: Failed to establish a new connection: [Errno 61] Connection refused',))

----------------------------------------------------------------------
Ran 0 tests in 0.007s

FAILED (errors=1)

**Comment by hzg17** [comment]
solved！
原因：没有启动macaca server。
@zenzhu 抱歉
