### ISSUE TITLE
实例运行报错.throw new Error("cannot resolve path (or pattern) '" + path + "'");

### ISSUE THREAD

**Issue by wangbinyu** [alibaba/macaca#130]
macaca run -d macaca-desktop-sample.test.js --verbose
>> index.js:17:12 [master] pid:12448 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '10.25.118.183',
  host: 'WIN7-1607291458',
  loaded_time: '2016-08-24 16:43:13' }
>> middlewares.js:17:10 [master] pid:12448 base middlewares attached
>> router.js:108:10 [master] pid:12448 router set
>> webdriver sdk launched
>> D:\Developer\nodejs\nodejs\node_modules\macaca-cli\node_modules\mocha\lib\utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) 'macaca-desktop-sample.test.js'
    at Object.lookupFiles (D:\Developer\nodejs\nodejs\node_modules\macaca-cli\node_modules\mocha\lib\utils.js:628:15)
    at D:\Developer\nodejs\nodejs\node_modules\macaca-cli\node_modules\mocha\bin\_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (D:\Developer\nodejs\nodejs\node_modules\macaca-cli\node_modules\mocha\bin\_mocha:325:6)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

>> Test completed!

**Comment by xudafeng** [comment]
sample 下还有一层目录

macaca run -d ./macaca-test/macaca-desktop-sample.test.js --verbose
