### ISSUE TITLE
can't find end of central directory

### ISSUE THREAD

**Issue by gaye746560359** [alibaba/macaca#131]
win10系统。安装驱动时,报错如下：
C:\Users\Administrator>npm i macaca-chromedriver --save-dev
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
\
> macaca-chromedriver@1.0.17 install C:\Users\Administrator\node_modules\macaca-chromedriver
> node ./bin/macaca-chromedriver install

>> chromedriver cdn url: http://chromedriver.storage.googleapis.com/2.20/chromedriver_win32.zip
C:\Users\Administrator\node_modules\macaca-chromedriver\node_modules\jszip\lib\zipEntries.js:152
                throw new Error("Corrupted zip : can't find end of central directory");
                ^

Error: Corrupted zip : can't find end of central directory
    at Object.ZipEntries.readEndOfCentral (C:\Users\Administrator\node_modules\macaca-chromedriver\node_modules\jszip\lib\zipEntries.js:152:23)
    at Object.ZipEntries.load (C:\Users\Administrator\node_modules\macaca-chromedriver\node_modules\jszip\lib\zipEntries.js:215:14)
    at Object.ZipEntries (C:\Users\Administrator\node_modules\macaca-chromedriver\node_modules\jszip\lib\zipEntries.js:21:14)
    at Object.module.exports [as load] (C:\Users\Administrator\node_modules\macaca-chromedriver\node_modules\jszip\lib\load.js:11:18)
    at Object.JSZip (C:\Users\Administrator\node_modules\macaca-chromedriver\node_modules\jszip\lib\index.js:39:14)
    at UnZipStream._flush (C:\Users\Administrator\node_modules\macaca-chromedriver\lib\install.js:45:13)
    at UnZipStream.<anonymous> (_stream_transform.js:118:12)
    at UnZipStream.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at UnZipStream.emit (events.js:166:7)
 npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "macaca-chromedriver" "--save-dev"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! macaca-chromedriver@1.0.17 install: `node ./bin/macaca-chromedriver install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the macaca-chromedriver@1.0.17 install script 'node ./bin/macaca-chromedriver install'.
npm ERR! This is most likely a problem with the macaca-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/macaca-chromedriver install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs macaca-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls macaca-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log

**Comment by xudafeng** [comment]
网络问题没法安装chromedriver，看社区的解决办法
