### ISSUE TITLE
TypeError: _(...).each(...).value is not a function

### ISSUE THREAD

**Issue by fanguili** [alibaba/macaca#136]
* **Macaca Version**:
1.1.0
* **Macaca Doctor**:
 Node.js checklist:

  node env: /usr/node-v4.5.0-linux-x64/bin/node
  node version: v4.5.0

  Android checklist:

  JAVA version is `1.7.0_80`
  JAVA_HOME is set to `/usr/lib/jdk/jdk1.7.0_80`
  ANDROID_HOME is set to `/usr/android-sdk-linux`
  platforms directory is not exist

  Installed driver list:

  electron: 1.1.2

* **Operate System**:
Ubuntu 14.04.1 LTS 

* ***programming Language*:

root@ubuntu:/home/xxxx/macaca-test-sample-master# make test-pc
macaca doctor

  Node.js checklist:

  node env: /usr/node-v4.5.0-linux-x64/bin/node
  node version: v4.5.0

  Android checklist:

  JAVA version is `1.7.0_80`
  JAVA_HOME is set to `/usr/lib/jdk/jdk1.7.0_80`
  ANDROID_HOME is set to `/usr/android-sdk-linux`
  platforms directory is not exist

  Installed driver list:

  electron: 1.1.2

macaca run --verbose -d ./macaca-test/macaca-desktop-sample.test.js
>> index.js:17:12 [master] pid:7087 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.3.233',
  host: 'ubuntu',
  loaded_time: '2016-08-28 23:30:02' }
>> middlewares.js:17:10 [master] pid:7087 base middlewares attached
>> router.js:108:10 [master] pid:7087 router set
>> webdriver sdk launched
>> /home/fanguili/macaca-test-sample-master/node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/element.js:54

>> }).value();
   ^

TypeError: _(...).each(...).value is not a function
    at Object.<anonymous> (/home/fanguili/macaca-test-sample-master/node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/element.js:54:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/fanguili/macaca-test-sample-master/node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:14:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/fanguili/macaca-test-sample-master/node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/main.js:4:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Module.Object.defineProperty.get [as exports] (/home/fanguili/macaca-test-sample-master/node_modules/webdriver-client/node_modules/macaca-wd/lib/macaca-wd.js:765:20)
    at Function.Module._load (module.js:308:16)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports.list.forEach.promise (/home/fanguili/macaca-test-sample-master/node_modules/webdriver-client/lib/webdriver-client.js:27:14)
    at Object.<anonymous> (/home/fanguili/macaca-test-sample-master/macaca-test/macaca-desktop-sample.test.js:3:37)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/node-v4.5.0-linux-x64/lib/node_modules/macaca-cli/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/node-v4.5.0-linux-x64/lib/node_modules/macaca-cli/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/usr/node-v4.5.0-linux-x64/lib/node_modules/macaca-cli/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/usr/node-v4.5.0-linux-x64/lib/node_modules/macaca-cli/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

>> Test completed!

so,how to solve this issue?

**Comment by xudafeng** [comment]
@fanguili testcase write error

**Comment by fanguili** [comment]
The command I used is "macaca run --verbose -d ./macaca-test/macaca-desktop-sample.test.js". It is a sample case.

**Comment by xudafeng** [comment]
@fanguili https://travis-ci.org/macacajs/macaca-test-sample/builds/154411527
