### ISSUE TITLE
devtool已经安装但是无法使用

### ISSUE THREAD

**Issue by mercynoo** [alibaba/macaca#172]
% npm install devtool -g
/usr/local/bin/devtool -> /usr/local/lib/node_modules/devtool/bin/index.js
/usr/local/lib
└── devtool@2.2.0

16:52 leicl@leichengliangdeMacBook-Pro /Users/leicl/macaca-test-sample
% devtool --verbose
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/devtool/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/devtool/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

**Comment by xudafeng** [comment]
@mercynoo 装成功了吗？
