### ISSUE TITLE
ios真机遇到的问题

### ISSUE THREAD

**Issue by zhoujinjian** [alibaba/macaca#185]
@xudafeng ,
@brucejcw ,
@meowtec,

macaca python版代码，执行后，macaca server服务端报错日志:
(下述使用的是模拟器报的错，使用ios真机直接报证书问题)

mikezhoudeMac-mini:~ mikezhou$ macaca server --verbose
>> request.js:23:12 [master] pid:44913 get remote update info failed.
>> index.js:17:12 [master] pid:44914 webdriver server start with config:
 { port: 3456,
  verbose: true,
  ip: '172.17.21.11',
  host: 'mikezhoudeMac-mini.local',
  loaded_time: '2016-09-13 16:12:45' }
>> middlewares.js:17:10 [master] pid:44914 base middlewares attached
>> router.js:108:10 [master] pid:44914 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:44914 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"deviceName":"iPhone 6","platformName":"iOS","platform_Version":"9.2","udid":"12AEA3C5-41C0-4DDE-83AE-EABD1D72CDE5","bundleId":"com.kugou.fanxingappstore"}}
>> session.js:47:10 [master] pid:44914 Creating session, sessionId: 4265d9d3-5c2c-4c61-a566-1cf191d687f7.
>> xctest-client.js:43:14 [master] pid:44914 project path: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.25@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:130:10 [master] pid:44914 {
	"bundleId": "com.kugou.fanxingappstore",
	"platformName": "iOS"
}
>> xctest-client.js:183:12 [master] pid:44914 xcode version: 7.3.1
>> responseHandler.js:50:12 [master] pid:44914 Send Error Respone to Client: TypeError: this.device.getLogDir is not a function
>> responseHandler.js:56:14 [master] pid:44914 TypeError: this.device.getLogDir is not a function
    at XCTest.startSimLog (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.19@xctest-client/lib/xctest-client.js:64:43)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:118:63)
    at next (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:69:7)
    at process._tickCallback (internal/process/next_tick.js:103:7)

  TypeError: this.device.getLogDir is not a function
      at XCTest.startSimLog (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.19@xctest-client/lib/xctest-client.js:64:43)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:65:19)
      at /usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:50:10)
      at Object.toPromise (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:118:63)
      at next (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:99:29)
      at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:69:7)
      at process._tickCallback (internal/process/next_tick.js:103:7)

macaca python部分参数设置如下：
desired_caps = {
    'platformName': 'iOS', # iOS, Android, Desktop
    #'browserName': 'Chrome',    # Chrome, Electron
    "bundleId": "com.kugou.fanxingappstore",
    "udid": "12AEA3C5-41C0-4DDE-83AE-EABD1D72CDE5",
    "deviceName":"iPhone 6",
    "platform_Version":"9.2"
}

server_url = {
    'hostname': '127.0.0.1',
    'port': 3456
}

**Comment by xudafeng** [comment]
已支持真机，请升级macaca-ios

https://github.com/alibaba/macaca/issues/42

**Comment by zhoujinjian** [comment]
@xudafeng ,macaca-ios最新版本是多少，我刚重新安装了一下，还是1.0.36

**Comment by xudafeng** [comment]
@zhoujinjian 重装过就好

webdriveragent 1.0.27

**Comment by zhoujinjian** [comment]
@xudafeng
webdriveragent 这个单独重装命令是？

**Comment by xudafeng** [comment]
@zhoujinjian 运行起来就看到版本啦
