### ISSUE TITLE
Android 真机测试waitForElement失败

### ISSUE THREAD

**Issue by hujiachun** [alibaba/macaca#202]
# 部分脚本
driver.setWaitElementTimeInterval(1000);
driver.setWaitElementTimeout(60000);
System.out.println("timeout="+driver.getWaitElementTimeout());
System.out.println("interval="+driver.getWaitElementTimeInterval());
@Test
	public void test_case_1() throws Exception {
		driver.waitForElement("name","旺财").click();
		driver.waitForElement("name","旺财11").click();

	}

# IDEA编辑器log
200
Response content:{"sessionId":"badb9a35-3fa7-43de-afe3-d1cc78f9be0a","status":0,"value":{"app":"/Users/hujiachun/Downloads/hujiachunbackup/apk/macaca.apk","reuse":"2","package":"com.pingan.lifeinsurance","activity":".initialize.activity.LauncherActivity","platformName":"Android"}}
The command executed successfully.
timeout=60000
interval=1000
200
Response content:{"sessionId":"badb9a35-3fa7-43de-afe3-d1cc78f9be0a","status":0,"value":{"ELEMENT":"1"}}
The command executed successfully.
200
Response content:{"sessionId":"badb9a35-3fa7-43de-afe3-d1cc78f9be0a","status":0,"value":{"ELEMENT":"2"}}
The command executed successfully.
200
Response content:{"sessionId":"badb9a35-3fa7-43de-afe3-d1cc78f9be0a","status":0,"value":true}
The command executed successfully.
404
Response content:Not Found

com.alibaba.fastjson.JSONException: syntax error, pos 3, json : Not Found

	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1361)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1268)
	at com.alibaba.fastjson.JSON.parse(JSON.java:137)
	at com.alibaba.fastjson.JSON.parse(JSON.java:128)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:201)
	at macaca.client.common.Utils.postRequest(Utils.java:92)
	at macaca.client.common.Utils.request(Utils.java:132)
	at macaca.client.commands.Element.hasElement(Element.java:34)
	at macaca.client.MacacaClient.waitForElement(MacacaClient.java:380)
	at macaca.client.MacacaClient.waitForElement(MacacaClient.java:406)
	at macaca.client.AndroidTest.test_case_1(AndroidTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

# macaca日志
hujiachun:~ hujiachun$ macaca server --verbose
>> request.js:23:12 [master] pid:30789 get remote update info failed.
>> index.js:17:12 [master] pid:30793 webdriver server start with config:
 { port: 3456,
  verbose: true,
  ip: '10.180.184.138',
  host: 'hujiachun.local',
  loaded_time: '2016-09-19 10:54:34' }
>> middlewares.js:17:10 [master] pid:30793 base middlewares attached
>> router.js:108:10 [master] pid:30793 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:30793 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"/Users/hujiachun/Downloads/hujiachunbackup/apk/macaca.apk","reuse":"2","package":"com.pingan.lifeinsurance","activity":".initialize.activity.LauncherActivity","platformName":"Android"}}
>> session.js:47:10 [master] pid:30793 Creating session, sessionId: badb9a35-3fa7-43de-afe3-d1cc78f9be0a.
>> helper.js:191:12 [master] pid:30793 Using local app form /Users/hujiachun/Downloads/hujiachunbackup/apk/macaca.apk
INSTRUMENTATION_STATUS: numtests=1

INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: test=testStartServer
INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize
INSTRUMENTATION_STATUS: current=1

>> socket server ready
>> socket client ready
recive: {"cmd":"wake","args":{}}

return: {"data":true,"success":true}

>> responseHandler.js:43:14 [master] pid:30793 Send HTTP Respone to Client: {"sessionId":"badb9a35-3fa7-43de-afe3-d1cc78f9be0a","status":0,"value":"{\"app\":\"/Users/hujiachun/Downloads/hujiachunbackup/apk/macaca.apk\",\"reuse\":\"2\",\"package\":\"com.pingan.lifeinsurance\",\"activity\":\".initialize.activity.LauncherActivity\",\"platformName\":\"Android\"}"}
>> responseHandler.js:11:12 [master] pid:30793 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/badb9a35-3fa7-43de-afe3-d1cc78f9be0a/element, jsonBody: {"using":"name","value":"旺财"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"旺财","multiple":false}}

ignored selector

return: {"data":{"ELEMENT":"1"},"success":true}
>> responseHandler.js:43:14 [master] pid:30793 Send HTTP Respone to Client: {"sessionId":"badb9a35-3fa7-43de-afe3-d1cc78f9be0a","status":0,"value":"{\"ELEMENT\":\"1\"}"}

>> responseHandler.js:11:12 [master] pid:30793 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/badb9a35-3fa7-43de-afe3-d1cc78f9be0a/element, jsonBody: {"using":"name","value":"旺财"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"旺财","multiple":false}}

ignored selector

return: {"data":{"ELEMENT":"2"},"success":true}

>> responseHandler.js:43:14 [master] pid:30793 Send HTTP Respone to Client: {"sessionId":"badb9a35-3fa7-43de-afe3-d1cc78f9be0a","status":0,"value":"{\"ELEMENT\":\"2\"}"}
>> responseHandler.js:11:12 [master] pid:30793 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/badb9a35-3fa7-43de-afe3-d1cc78f9be0a/element/2/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"2"}}

return: {"data":true,"success":true}

>> responseHandler.js:43:14 [master] pid:30793 Send HTTP Respone to Client: {"sessionId":"badb9a35-3fa7-43de-afe3-d1cc78f9be0a","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:30793 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/badb9a35-3fa7-43de-afe3-d1cc78f9be0a/element, jsonBody: {"using":"name","value":"旺财11"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"旺财11","multiple":false}}

ignored selector

ignored selector
return: {"success":true}

>> responseHandler.js:19:14 [master] pid:30793 Send HTTP Respone to Client: 404 Not Found
>> responseHandler.js:11:12 [master] pid:30793 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/badb9a35-3fa7-43de-afe3-d1cc78f9be0a, jsonBody: {}
>> session.js:80:12 [master] pid:30793 Delete session, sessionId: badb9a35-3fa7-43de-afe3-d1cc78f9be0a
>> responseHandler.js:43:14 [master] pid:30793 Send HTTP Respone to Client: {"sessionId":"badb9a35-3fa7-43de-afe3-d1cc78f9be0a","status":0}

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-test-sample-java
