### ISSUE TITLE
IOS 真机app-inspector报错

### ISSUE THREAD

**Issue by hujiachun** [alibaba/macaca#205]
> inspector start at: http://10.180.184.138:5678
>> WebDriverAgent version: 1.0.28
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
>> iOS device started: ecab65eca01ae1d42874c26e645a33aee78296b6
  <-- GET /

  TypeError: Cannot read property 'type' of undefined
      at adaptor (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.8@app-inspector/lib/ios.js:12:20)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.8@app-inspector/lib/ios.js:48:48)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  <-- GET /favicon.ico
  --> GET /favicon.ico 404

**Comment by xudafeng** [comment]
npm 安装呢

**Comment by meowtec** [comment]
https://github.com/macacajs/app-inspector/issues/22 和这个一样的问题，我加一下 log

**Comment by meowtec** [comment]
升级 app-inspector@1.2.9 然后运行下，我需要详细的日志

**Comment by meowtec** [comment]
缺少更多信息
