### ISSUE TITLE
python的swipe问题

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#217]
通过如下方式更新包，就可以调用到swipe方法

```shell
$ pip install wd --upgrade
```

```shell
➟ pip install wd --upgrade
Collecting wd
  Downloading wd-0.1.3-py2.py3-none-any.whl
Requirement already up-to-date: retrying in /usr/local/lib/python2.7/site-packages (from wd)
Collecting requests (from wd)
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 92kB/s 
Collecting enum34 (from wd)
  Downloading enum34-1.1.6-py2-none-any.whl
Requirement already up-to-date: six>=1.7.0 in /usr/local/lib/python2.7/site-packages (from retrying->wd)
Installing collected packages: requests, enum34, wd
  Found existing installation: requests 2.11.0
    Uninstalling requests-2.11.0:
      Successfully uninstalled requests-2.11.0
  Found existing installation: wd 0.1.1
    Uninstalling wd-0.1.1:
      Successfully uninstalled wd-0.1.1
Successfully installed enum34-1.1.6 requests-2.11.1 wd-0.1.3
xdf@node4.2.2:~/prjs/macaca/wd.py[master]
➟ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from macaca import WebDriver
>>> wd=WebDriver({})
>>> wd.swipe()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "macaca/util.py", line 145, in fluent_interface
    ret = func(instance, *args, **kwargs)
TypeError: swipe() takes at least 5 arguments (1 given)
>>> wd.swipe()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "macaca/util.py", line 145, in fluent_interface
    ret = func(instance, *args, **kwargs)
TypeError: swipe() takes at least 5 arguments (1 given)
>>> wd.swipe
<bound method WebDriver.swipe of <WebDriver (session="None")>>
```

**Comment by xudafeng** [comment]
目前源码release到0.1.3版本

https://github.com/macacajs/wd.py
