### ISSUE TITLE
最新版本macaca-cli提示 Only support android sdk version between 16 and 23

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#223]
* **Macaca Version**:
  1.1.4
* **Macaca Doctor Logs**:
mac:macaca-cli mac$ macaca doctor

  macaca-doctor version: 1.0.20

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.5.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/mac/software/android-sdk-macosx`
  Only support android sdk version between 16 and 23

  Installed driver list:

  android: 1.0.29
  chrome: 1.0.2
  electron: 1.1.4
  ios: 1.0.37
* **Operate System**:
mac os
* **Programming Language**:

升级到最新版本的macaca-cli后，提示Only support android sdk version between 16 and 23
经查看github上最新的分支macaca-doctor/lib/android.js上代码进行了版本控制
var MAX_SDK_VERSION = 23;
var MIN_SDK_VERSION = 16;

  res = _.filter(res, n => {
      var version = parseInt(n.split('-').pop());
      return version >= MIN_SDK_VERSION && version <= MAX_SDK_VERSION;
    });

是否漏掉了24版本最新的Android7

**Comment by xudafeng** [comment]
@zenzhu 你那边下24了吗

**Comment by CodeToSurvive1** [comment]
下了啊 我原先就是24能用  更新npm后就报错了说只能再16-23之间

**Comment by xudafeng** [comment]
@zenzhu 试一下24ok就放开吧

**Comment by CodeToSurvive1** [comment]
@xudafeng 我现在临时先下了个23版本的，doctor检查没问题，但是运行官方案例报错

```
mac:macaca-test-sample mac$ macaca doctor

  macaca-doctor version: 1.0.20


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.5.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/mac/software/android-sdk-macosx`
  Platforms is set to `/Users/mac/software/android-sdk-macosx/platforms/android-23`
  Android tools is set to `/Users/mac/software/android-sdk-macosx/tools/android`
  ADB tool is set to `/Users/mac/software/android-sdk-macosx/platform-tools/adb`

  Installed driver list:

  android: 1.0.29
  chrome: 1.0.2
  electron: 1.1.4
  ios: 1.0.37

```
将官方例子macaca-mobile-sample.test.js改为Android后运行报错，说环境变量不可用The environment you requested was unavailable.

```
mac:macaca-test-sample mac$ macaca run -d macaca-test/macaca-mobile-sample.test.js --verbose
>> index.js:17:12 [master] pid:1062 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '172.31.219.225',
  host: 'mac.local',
  loaded_time: '2016-09-26 15:05:39' }
>> middlewares.js:17:10 [master] pid:1062 base middlewares attached
>> router.js:129:10 [master] pid:1062 router set
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:1062 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"Android","app":"/Users/mac/software/github/macaca/macaca-test-sample/app/android-app-bootstrap.zip","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:1062 Creating session, sessionId: 579f80a9-da3a-4bff-8a36-464a357a74bd.
>> helper.js:196:12 [master] pid:1062 Unzipping local app form /Users/mac/software/github/macaca/macaca-test-sample/app/android-app-bootstrap.zip
>> responseHandler.js:54:12 [master] pid:1062 Send Error Respone to Client: Error: Command failed: /bin/sh -c /Users/mac/software/android-sdk-macosx/platform-tools/adb -s DU2MYN146D002912 push /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.1.0.20@uiautomator-client/bin/uiautomator-bootstrap.jar /data/local/tmp

>> responseHandler.js:60:14 [master] pid:1062 Error: Command failed: /bin/sh -c /Users/mac/software/android-sdk-macosx/platform-tools/adb -s DU2MYN146D002912 push /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.1.0.20@uiautomator-client/bin/uiautomator-bootstrap.jar /data/local/tmp

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

  Error: Command failed: /bin/sh -c /Users/mac/software/android-sdk-macosx/platform-tools/adb -s DU2MYN146D002912 push /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.1.0.20@uiautomator-client/bin/uiautomator-bootstrap.jar /data/local/tmp
  
      at ChildProcess.exithandler (child_process.js:213:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:829:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>> 
>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:1062 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:1062 Send HTTP Respone to Client: 405 Method Not Allowed
>> 
>>     2) "after all" hook

>> 

>> 

>>   0 passing (2s)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     [init({"autoAcceptAlerts":true,"platformName":"Android","app":"/Users/mac/software/github/macaca/macaca-test-sample/app/android-app-bootstrap.zip"})] The environment you requested was unavailable.
  Error: [init({"autoAcceptAlerts":true,"platformName":"Android","app":"app/android-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)




>> Test completed!

```

**Comment by githublue** [comment]
终于有一个也出现错误的了 ， 我郁闷了好久

**Comment by githublue** [comment]
我用了一周时间没有安装成功、运行成功

**Comment by zenzhu** [comment]
你本地有没有 /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.1.0.20@uiautomator-client/bin/uiautomator-bootstrap.jar 看一下哈

**Comment by githublue** [comment]
我windows环境的，也没有uiautomator-bootstrap.jar 这个东东，安装macaca-android驱动时候一直没有编译成功。。。

**Comment by CodeToSurvive1** [comment]
@zenzhu 我这边没有.1.0.20@uiautomator-client,有.1.0.21@uiautomator-client,macaca-cli中配置的也是.1.0.21@uiautomator-client呀

**Comment by zenzhu** [comment]
刚才更新了一下 可以用 24 了，你现在重装 tnpm i -g macaca-android 会报错吗

**Comment by CodeToSurvive1** [comment]
@zenzhu  安装macaca-android不报错  更新macaca-cli已经好了 24版本已经能检测出来了 已经ok了

**Comment by githublue** [comment]
明天我这里再重新试试，刚才装chrome驱动，nodejs报错了，我的node是6版本的

**Comment by CodeToSurvive1** [comment]
@githublue node6好像有问题  我最开始用的也是node6 有问题就改回到v4.5.0了
