### ISSUE TITLE
wd.java 1.0.25  安卓默认内置浏览器又无法打开网址了

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#230]
更新wd.java 1.0.25  安卓默认内置浏览器
无法打开脚本中的网址
如图 
![image](https://cloud.githubusercontent.com/assets/18392901/18898577/12bff060-8565-11e6-98de-250f93b7a0e6.png)

cmd@TR:~$ macaca -v

  1.1.4

cmd@TR:~$ macaca doctor

  macaca-doctor version: 1.0.20

  Node.js checklist:

  node env: /opt/nodejs/bin/node
  node version: v4.4.7

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/opt/android-sdk-linux`
  Platforms is set to `/opt/android-sdk-linux/platforms/android-23`
  Android tools is set to `/opt/android-sdk-linux/tools/android`
  ADB tool is set to `/opt/android-sdk-linux/platform-tools/adb`

  Installed driver list:

  android: 1.0.32
  chrome: 1.0.2
  electron: 1.1.4

An unknown server-side error occurred while processing the command.
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 15.65 sec <<< FAILURE! - in uiauto.H5MobileTest
setUp(uiauto.H5MobileTest)  Time elapsed: 15.556 sec  <<< FAILURE!
java.lang.Exception: An unknown server-side error occurred while processing the command.
	at macaca.client.common.Utils.handleStatus(Utils.java:150)
	at macaca.client.common.Utils.postRequest(Utils.java:96)
	at macaca.client.common.Utils.request(Utils.java:135)
	at macaca.client.commands.Window.setWindowSize(Window.java:42)
	at macaca.client.MacacaClient.setWindowSize(MacacaClient.java:912)
	at uiauto.H5MobileTest.setUp(H5MobileTest.java:34)

求解决啊  这都1.0.26版本了  我记得不是修复过一次吗...

**Comment by Archer456** [comment]
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.472 sec <<< FAILURE! - in uiauto.H5MobileTest
test_case_1(uiauto.H5MobileTest)  Time elapsed: 2.049 sec  <<< FAILURE!
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String
	at macaca.client.commands.Element.getText(Element.java:83)
	at macaca.client.MacacaClient.text(MacacaClient.java:934)
	at uiauto.H5MobileTest.test_case_1(H5MobileTest.java:55)


cmd@TR:~$ macaca doctor

  macaca-doctor version: 1.0.21


  Node.js checklist:

  node env: /opt/nodejs/bin/node
  node version: v4.4.7

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/opt/android-sdk-linux`
  Platforms is set to `/opt/android-sdk-linux/platforms/android-24`
  Android tools is set to `/opt/android-sdk-linux/tools/android`
  ADB tool is set to `/opt/android-sdk-linux/platform-tools/adb`

  Installed driver list:

  android: 1.0.39
  chrome: 1.0.3
  electron: 1.1.4


cmd@TR:~$ macaca -v

  1.1.5

今天升级1.0.3报的错

**Comment by Archer456** [comment]
An unknown server-side error occurred while processing the command.
FAILED CONFIGURATION: @BeforeMethod setUp
java.lang.Exception: An unknown server-side error occurred while processing the command.
	at macaca.client.common.Utils.handleStatus(Utils.java:150)
	at macaca.client.common.Utils.postRequest(Utils.java:96)
	at macaca.client.common.Utils.request(Utils.java:135)
	at macaca.client.commands.Window.setWindowSize(Window.java:42)
	at macaca.client.MacacaClient.setWindowSize(MacacaClient.java:912)
	at uiauto.H5MobileTest.setUp(H5MobileTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)

SKIPPED CONFIGURATION: @AfterMethod tearDown
SKIPPED: test_case_1


C:\Users\cmd>macaca -v

  1.1.5


C:\Users\cmd>macaca doctor

  macaca-doctor version: 1.0.21


  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v4.4.7

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_91`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-24`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  ANT_HOME is set to `D:\apache-ant-1.9.7`

  Installed driver list:

  android: 1.0.39
  chrome: 1.0.3
  electron: 1.1.4


win10下

**Comment by Archer456** [comment]
![image](https://cloud.githubusercontent.com/assets/18392901/19261015/ff14f18a-8fc0-11e6-97b8-f90bcba46dae.png)
每日一催   安卓手机浏览器 无法打开请求网址  求解决!

**Comment by zenzhu** [comment]
你本地运行一下在 chromedriver 看看访问 9515 端口能不能打开页面？

**Comment by Archer456** [comment]
![image](https://cloud.githubusercontent.com/assets/18392901/19297765/89a5add0-907a-11e6-907b-29ce199cf1be.png)

**Comment by zenzhu** [comment]
我又看了一下日志，上面那个报错是在重试看chromedriver有没有启动，而且后面一句显示其实一句启动了。要看你具体打开网址的日志的哪个？你日志搜索一下你打开的URL，看一下附近的日志。

**Comment by Archer456** [comment]
经过我不懈的研究  今天弄到1.0.29版本后
发现脚本里的这句有问题
driver.initDriver(desiredCapabilities).setWindowSize(480, 800);

我去掉 setWindowSize改成driver.initDriver(desiredCapabilities);

就通过了...
