### ISSUE TITLE
After macaca   1.1.4, ios app bundle has to be mandatorily in .zip format instead of .app format.

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#238]
A change has been made in helper.js file inside webdriver-server after which the ios app path has to be mandatorily point to .zip file instead of .app file.

**Comment by zenzhu** [comment]
We can accept either .app or .zip file.

**Comment by mpreethi90** [comment]
when the app path points to .app file, error is thrown as below-

`Error: [init({"autoAcceptAlerts":false,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 6","reuse":2,"app":"/Users/xxxx/xx/xxxx/Xcode/DerivedData/taizi-alalntgnddbuckejxslhjxodtplh/Build/Products/Debug-iphonesimulator/taizi.app"})] The environment you requested was unavailable.`

**Comment by zenzhu** [comment]
We use app or zip interchangeably. Maybe it's not the problem, can u put more debug info before this error.

**Comment by mpreethi90** [comment]
> 

>> index.js:17:12 [master] pid:65395 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.1.83',
  host: 'Preethis-MacBook-Pro.local',
  loaded_time: '2016-09-29 15:12:44' }
>> middlewares.js:17:10 [master] pid:65395 base middlewares attached
>> router.js:129:10 [master] pid:65395 router set
>> webdriver sdk launched
>> 

>> 

>>   S03 - Create new site using Bright

>> responseHandler.js:11:12 [master] pid:65395 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":false,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 6","reuse":2,"app":"/Users/XX/XX/XX/Xcode/DerivedData/taizi-alalntgnddbuckejxslhjxodtplh/Build/Products/Debug-iphonesimulator/taizi.app"}}
>> session.js:47:10 [master] pid:65395 Creating session, sessionId: bde74939-cf8f-44f6-83c3-9b842c271c65.
>> responseHandler.js:54:12 [master] pid:65395 Send Error Respone to Client: Error: App path /Users/XX/XX/XX/Xcode/DerivedData/taizi-alalntgnddbuckejxslhjxodtplh/Build/Products/Debug-iphonesimulator/taizi.app does not exist!
>> responseHandler.js:60:14 [master] pid:65395 Error: App path /Users/XX/XX/XX/Xcode/DerivedData/taizi-alalntgnddbuckejxslhjxodtplh/Build/Products/Debug-iphonesimulator/taizi.app does not exist!
    at Object._.configApp (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/common/helper.js:186:13)
    at Object.createDevice (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:13:18)
    at next (native)
    at onFulfilled (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at /Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
    at /Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
    at /Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)

  Error: App path /Users/XX/XX/XX/Xcode/DerivedData/taizi-alalntgnddbuckejxslhjxodtplh/Build/Products/Debug-iphonesimulator/taizi.app does not exist!

**Comment by zenzhu** [comment]
```The app does not exist.```
Where is your app ? Why you put it into the simulator folder ? and it does not exist.

**Comment by mpreethi90** [comment]
No, the app exists. It is the default folder where .app file gets stored once you run your application from Xcode.
And, I even tried putting the .app in desktop and the same error throws.

**Comment by zenzhu** [comment]
You use the same folder but zip works?

**Comment by mpreethi90** [comment]
Yes. If I just zip this .app file in the same location, it works.

**Comment by zenzhu** [comment]
Sry, i looked into the source code, it was mistaken changed, mine local code is not the lastest. I will fix it soon.

**Comment by mpreethi90** [comment]
oops. Thank you very much (Y) :)

**Comment by zenzhu** [comment]
It's ok now, sry for the inconvenience. Update the macaca-cli.
