### ISSUE TITLE
macaca-simple-reportor throws error

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#252]
Here is my test command-

`platform=iOS  appLocation=/Users/preethi/Library/Developer/Xcode/DerivedData/taizi-alalntgnddbuckejxslhjxodtplh/Build/Products/Debug-iphonesimulator/taizi.app platformVersion=9.3 deviceName='iPhone 6'  macaca  run -d ./macaca-test/Onboarding/Login.test.js -f mocha --reporter macaca-simple-reportor --verbose`

and here is the output

>> index.js:17:12 [master] pid:29995 webdriver server start with config:
 { port: 3456,
  ip: '192.168.1.33',
  host: 'Preethis-MacBook-Pro.local',
  loaded_time: '2016-10-13 13:22:02' }
>> middlewares.js:17:10 [master] pid:29995 base middlewares attached
>> router.js:129:10 [master] pid:29995 router set
>> webdriver sdk launched
>> "macaca-simple-reportor" reporter not found

>> /Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/mocha/lib/mocha.js:180
      throw new Error('invalid reporter "' + reporter + '"');
      ^

Error: invalid reporter "macaca-simple-reportor"
    at Mocha.reporter (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/mocha/lib/mocha.js:180:13)
    at Object.<anonymous> (/Users/preethi/.npm-packages/lib/node_modules/macaca-cli/node_modules/mocha/bin/_mocha:207:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

>> Test completed!

**Comment by zenzhu** [comment]
You need to install macaca-simple-reportor under your project folder.

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/253
