### ISSUE TITLE
ios真机上跑Python脚本时遇到问题“xctest client proxy error with: Error: socket hang up”

### ISSUE THREAD

**Issue by fengytn** [alibaba/macaca#259]
- **Macaca Version**: 1.1.5
- **Macaca Doctor Logs**: 

bogon:~ bita$ macaca doctor

  macaca-doctor version: 1.0.21

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.7.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_73`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/bita/Library/Android/sdk`
  Platforms is set to `/Users/bita/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/bita/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/bita/Library/Android/sdk/platform-tools/adb`

  Installed driver list:

  electron: 1.1.4
  ios: 1.0.38
- **Operate System**:  mac 10.12
- **Programming Language**: python

真机环境搭建成功，跑github上的Python脚本时，修改了如下内容：
import unittest
import os
import time
from macaca import WebDriver

desired_caps = {
    'platformName': 'iOS',
    'platformVersion': '9.3',
    'deviceName': 'iPhone',
    'reuse': 2,
    'autoAcceptAlerts': True,
    'autoDismissAlerts': True,
    'bundleId': 'xudafeng.ios-app-bootstrap',
    'udid': 'ce837bc560d66876cb5bf4a54bbd82b602cfd160',
}

server_url = {
    'hostname': 'localhost',
    'port': 3456
}

....

然后运行时，会报如下错误：
bogon:~ bita$ macaca server

> > webdriver sdk launched
> > WebDriverAgent version: 1.0.28
> > proxy.js:58:18 [master] pid:26823 xctest client proxy error with: Error: socket hang up
> > /usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169
> >   throw new Error(res);
> >   ^

Error: >> proxy.js:58:18 [master] pid:26823 xctest client proxy error with: Error: socket hang up
    at Logger.error (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request.request [as _callback](/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:344:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by xudafeng** [comment]
升级iOS驱动，参考https://testerhome.com/topics/6314
