### ISSUE TITLE
macaca inspector测试ios的微信公众号微信直接崩掉后台报错，但是安卓没问题

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#263]
- **Macaca Version**:
- **Macaca Doctor Logs**:
- **Operate System**:
- **Programming Language**:

``` xml
The source may be wrong, please report with below message at:
    [object Object]
    ****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'origin' of undefined
      at node (/usr/local/lib/node_modules/app-inspector/lib/ios.js:28:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:61:22)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (node.js:369:9)
```

macaca inspector测试ios的微信公众号,点击具体的公众号，微信直接崩掉后台报错如上，但是安卓没问题

**Comment by meowtec** [comment]
又是 xctest 拿到 xml 里面没有结构的问题

**Comment by jessezyl** [comment]
webdriveragent也是同样的问题，进入公众号对话框，inspect或请求source都会崩溃，我在WDA提了个issue，作者说是app问题，跟wda无关：
[https://github.com/facebook/WebDriverAgent/issues/340](url)

**Comment by meowtec** [comment]
inspector 用的就是 webdriveragent.

其他一些应用的某些页面也出现了这种问题，很无奈。

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/421 已解决

**Comment by xudafeng** [comment]
@jessezyl 原因确实出自App本身，现在重新查这个问题。

追查到私有方法 [application resolve] 失败的，重复多次获取失败导致时间也变得很长
