### ISSUE TITLE
API sendKeys() 在不同的android设备上运行报错！

### ISSUE THREAD

**Issue by githublue** [alibaba/macaca#265]
在win7系统运行macaca-mobile-sample.test.js 用例一开始在小米的测试机上运行是OK的，后来换了一台android设备，发现sendKeys()方法运行报错，是不是sendKeys方法依赖底层的某种键盘服务？应该怎么解决呢？

这台android设备是我们的定制产品，不能换其它设备，后面还要在上面测试我们自己的app，谢谢！

**Comment by yaniswang** [comment]
sendKeys依赖macaca的输入法，第一次使用的时候会弹出输入法的安装，是否安装过程中被你取消了？

**Comment by githublue** [comment]
没遇到啊，你说的安装是在android设备上还是PC机上？ @yaniswang

**Comment by githublue** [comment]
能不能单独进行安装 @yaniswang @xudafeng

**Comment by githublue** [comment]
我第一次是用我们自己的App运行，老报错，后来为了检查问题，就换成了网上的例子，才发现是sendKeys不行 @yaniswang @xudafeng

**Comment by yaniswang** [comment]
我在小米手机上测试时，会弹出安装2个APP，输入法和bootstrap

**Comment by githublue** [comment]
我在小米手机上没弹出输入法，直接运行成功了，
我现在要测的这个设备是android的大平板 @yaniswang

**Comment by githublue** [comment]
各位大虾，如何解决啊？
macaca输入法能单独装吗？  @xudafeng

**Comment by xudafeng** [comment]
自动装啊

**Comment by githublue** [comment]
那sendKeys为啥失败了 @xudafeng

**Comment by githublue** [comment]
自动装要依赖哪些条件啊 ， 如何检验是否安装成功了，macaca输入法运行的进程名称是啥 @xudafeng

**Comment by xudafeng** [comment]
https://github.com/macacajs/android-unicode

**Comment by githublue** [comment]
哈哈  谢谢  我再试试 @xudafeng

**Comment by githublue** [comment]
不过android-unicode一开始我就已经装在macaca-android包里了，会是这个原因吗？ @xudafeng

**Comment by githublue** [comment]
试了下，我用adb shell input text 'add331'是可以的，而用sendKeys()就报错，说明不是发不了，而是编码的某种服务没有调成功，主要的错误信息如下：

Error in testStartServer:

java.lang.NoClassDefFoundError: com.android.uiautomator.core.Configurator

	at com.android.uiautomator.client.Element.setText(Element.java:59)

	at com.android.uiautomator.client.cmd.SetText.execute(SetText.java:41)

	at com.android.uiautomator.client.Command.handleInput(Command.java:46)

	at com.android.uiautomator.client.SocketServer.listen(SocketServer.java:60)

	at com.android.uiautomator.client.Initialize.testStartServer(Initialize.java:28)

	at java.lang.reflect.Method.invokeNative(Native Method)

	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:144)

	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:87)

	at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:90)

	at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)

	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)

	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)

	at dalvik.system.NativeStart.main(Native Method)

Error: [element.sendKeys("12345678")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command.[0m[90m
      at exports.newError (E:\macaca-test-sample\node_modules\webdriver-client\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at E:\macaca-test-sample\node_modules\webdriver-client\node_modules\macaca-wd\wd\lib\callbacks.js:33:23
      at E:\macaca-test-sample\node_modules\webdriver-client\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (E:\macaca-test-sample\node_modules\webdriver-client\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (E:\macaca-test-sample\node_modules\webdriver-client\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (E:\macaca-test-sample\node_modules\webdriver-client\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (E:\macaca-test-sample\node_modules\webdriver-client\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)
[0m

>> Test completed!

@xudafeng

**Comment by githublue** [comment]
我在小米手机上跑是OK的，在android定制的平板上就有问题，是不是输入法apk没有装成功呢？你给我的链接我看了，ADBKeyBoard.apk需要编译，我暂时编译不了，没法使用，你们nodejs封装好的是android_unicode_ime-debug.apk这个吗？我能直接把这个apk装到android设备里吗？装在什么路径下？

@xudafeng

**Comment by githublue** [comment]
网上搜了一下，我自己装了一个ADBKeyBoard.apk，默认键盘设为ADB Keyboard，sendKeys()方法仍然报上面的错误，任务结束后默认键盘又改成了以前的设置；

但是我手工输入时候，默认键盘弹出的是ADB Keyboard，没有被更改；

很奇怪的事情，修改默认键盘的行为是macaca的问题还是android系统的问题？

**Comment by CodeToSurvive1** [comment]
@githublue java.lang.NoClassDefFoundError: com.android.uiautomator.core.Configurator这个错误是你的安卓系统版本太低吧？

**Comment by githublue** [comment]
有可能，我这系统是第三方定制的，android版本是4.2.2，如何向下兼容呢？ @CodeToSurvive1 @xudafeng

**Comment by CodeToSurvive1** [comment]
@githublue 我那天也用了个小米三的手机，系统好久没更新了，忘记具体的4.几的版本了，也报你那个com.android.uiautomator.core.Configurator错误，升级了下系统就ok了

**Comment by githublue** [comment]
我这系统是定制的，升不了级，还有什么方法让sendKeys向下兼容4.x版本的？ @CodeToSurvive1 @xudafeng
