### ISSUE TITLE
真机跑脚本Internal Server Error

### ISSUE THREAD

**Issue by lengyao88** [alibaba/macaca#27]
我的脚本如下
const path = require('path');
const wd = require('wd'); // 引用 wd 模块

describe('macaca mobile sample', function() {
  this.timeout(5 * 60 * 1000); // mocha 设置超时时间

  var driver = wd.promiseChainRemote({ // 初始化 webdriver
    host: 'localhost',
    port: 3456
  });

  before(function() { 
    return driver.init({ 
	platformName: 'iOS',      
	udid: 'd8f6f0875320116fc5946b020a84b6dccba9d815',
  	bundleId: 'com.mosheberman.Surfboard'
    });
 });

  after(function() { // 所有测试用例的统一后置动作
    return driver 
      .sleep(1000)
      .quit();
  });

  it('#1 should login success', function() {
      return driver
      .elementByName('Tap Here To Surf Again')
      .click()
      .sleep(3000)
      .takeScreenshot(path);
    

  });

});

下面是错误

Last login: Tue Apr 12 15:53:23 on ttys000
clydeiMac:~ cly$ cd /Users/cly/Desktop/macaca-test/
clydeiMac:macaca-test cly$ make test
platform= macaca run --server --verbose

****************************************
*  version 1.0.13 is outdate           *
*  run: npm i -g macaca-client@1.0.10  *
****************************************

>> index.js:62:12 [master] pid:39068 webdriver server start with config:
 { port: 3456,
  ip: '192.168.3.70',
  host: 'clydeiMac.local',
  loaded_time: '2016-04-12 16:06:34' }
>> middlewares.js:31:10 [master] pid:39068 base middlewares attached
>> router.js:101:10 [master] pid:39068 router set
>> webdriver sdk launched
>> 
>> 
>>   macaca mobile sample
>> responseHandler.js:24:12 [master] pid:39068 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","udid":"d8f6f0875320116fc5946b020a84b6dccba9d815","bundleId":"com.mosheberman.Surfboard","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:22:10 [master] pid:39068 Creating session, sessionId: a4307991-cae2-4656-8e5b-5e6296358984.
>> responseHandler.js:56:12 [master] pid:39068 Send Error Respone to Client TypeError: Cannot read property 'substring' of undefined
>> responseHandler.js:62:14 [master] pid:39068 TypeError: Cannot read property 'substring' of undefined
    at Function._.sleep._.retry._.waitForCondition._.exec._.spawn.child.on._.configApp (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/common/helper.js:174:10)
    at WebdriverServer.start (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/server/index.js:39:16)
    at next (native)
    at onFulfilled (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:65:19)
    at /Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:54:5
    at Object.co (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:118:63)
    at next (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:69:7)
    at /Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:54:5
    at Object.co (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:118:63)
    at next (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:69:7)
    at /Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:54:5
    at Object.co (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:50:10)
>> responseHandler.js:81:14 [master] pid:39068 Unexcepted error TypeError

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/server/responseHandler.js:82:17)
      at throw (native)
      at onRejected (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/co/index.js:81:24)
      at process._tickCallback (node.js:369:9)

>> 
>>   1) "before all" hook
>> responseHandler.js:24:12 [master] pid:39068 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:48:14 [master] pid:39068 Send HTTP Respone to Client: {"sessionId":"","status":0}
>> 
>> 
>>   0 passing (4s)
>>   1 failing
>> 
>>   1) macaca mobile sample "before all" hook:
     Error: [init({"platformName":"iOS","udid":"d8f6f0875320116fc5946b020a84b6dccba9d815","bundleId":"com.mosheberman.Surfboard"})] The environment you requested was unavailable.
      at endReadableNT (_stream_readable.js:905:12)

>> 
>> Test completed!

**Comment by zenzhu** [comment]
@lengyao88 请你把macaca-client升降到最新版，另外 iOS 真机调试会有签名的问题，如果非越狱的话，可能会失败。

**Comment by lengyao88** [comment]
签名是必须开发者证书的？不能使用企业证书是吗？

**Comment by zenzhu** [comment]
@lengyao88 我们内部还使用了一个 App 安装到本测试的手机上面，这个过程可能需要在 Xcode 中手动 fix issue 生成 provision files，如果你需要的话，可以在日志中报出证书错误之后，找到该应用，手动打开 Xcode 工程重签一下就可以了。

**Comment by xudafeng** [comment]
@lengyao88 真机一定要重签的https://testerhome.com/topics/4549

**Comment by lylh** [comment]
@xudafeng 我的设备是越狱的，不需要重签了吧。

**Comment by xudafeng** [comment]
@lylh 你是Xcode 或者命令行build到手机里的吗？

**Comment by lengyao88** [comment]
Xcode

**Comment by zenzhu** [comment]
@lengyao88 你更新 macaca-clien t到最新版后 还是这个错吗

**Comment by lengyao88** [comment]
是的，还是这个错误。

**Comment by zenzhu** [comment]
@lengyao88 你看一下 安装之后 webdriver-server 的版本是不是 1.0.26

**Comment by lengyao88** [comment]
好像没升级成功，还是1.0.13

**Comment by zenzhu** [comment]
@lengyao88 不是这意思 是你安装macaca-client之后 它依赖的webdriver-server 的版本是不是 1.0.26，你安装完了会有一个很长的列表显示依赖的包名和版本的。

**Comment by lengyao88** [comment]
有直接查看的命令吗？
