### ISSUE TITLE
iOS模拟器跑，指定bundleId报错，官网的例子也跑不通

### ISSUE THREAD

**Issue by lengyao88** [alibaba/macaca#272]
Macaca Version: 1.1.6
node:v6.8.1
mac os :10.11.6
xcode:8.0
ios模拟器 ： iphone se 10.0

Macaca Doctor Logs:

clydeiMac:Wallpaper cly$ make test-ios
macaca doctor

  macaca-doctor version: 1.0.21

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.8.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is not set

  Installed driver list:

  ios: 1.0.38

platform=ios macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js

************************************
*  version 1.1.6 is outdate        *
*  run: npm i -g macaca-cli@1.1.7  *
************************************

>> index.js:17:12 [master] pid:2249 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.3.70',
  host: 'clydeiMac.local',
  loaded_time: '2016-10-19 19:08:24' }
>> middlewares.js:17:10 [master] pid:2249 base middlewares attached
>> router.js:129:10 [master] pid:2249 router set
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:2249 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"10.0","deviceName":"iPhone SE","bundleId":"com.gao7.wallpaper.pid37ch03Test"}}
>> session.js:47:10 [master] pid:2249 Creating session, sessionId: a8656482-b90a-46d7-9c18-a0a834701d57.
>> responseHandler.js:54:12 [master] pid:2249 Send Error Respone to Client: TypeError: Path must be a string. Received undefined
>> responseHandler.js:60:14 [master] pid:2249 TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.exports.getBundleId (/usr/local/lib/node_modules/macaca-ios/node_modules/ios-utils/lib/ios-utils.js:86:20)
    at IOS.startDevice (/usr/local/lib/node_modules/macaca-ios/lib/macaca-ios.js:117:38)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)

  TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.resolve (path.js:1146:7)
      at Object.exports.getBundleId (/usr/local/lib/node_modules/macaca-ios/node_modules/ios-utils/lib/ios-utils.js:86:20)
      at IOS.startDevice (/usr/local/lib/node_modules/macaca-ios/lib/macaca-ios.js:117:38)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)

>> 
>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:2249 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:2249 Send HTTP Respone to Client: 405 Method Not Allowed
>> 
>>     2) "after all" hook

>> 

>> 

>>   0 passing (2s)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     Error: [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"10.0","deviceName":"iPhone SE","bundleId":"com.gao7.wallpaper.pid37ch03Test"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at .<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> 

>> Test completed!
make: *** [test-ios] Error 2

**Comment by xudafeng** [comment]
node 4试一下
