### ISSUE TITLE
macaca ios js 版本sendkeys在默认使用第三方输入法时候报错

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#273]
- **Macaca Version**:
- **Macaca Doctor Logs**:
- **Operate System**:
- **Programming Language**:

目前系统中安装了第三方输入法：百度输入法
js版本的脚本在执行到sendkeys方法时候报错，

``` java

>> macaca-ios.js:267:10 [master] pid:19379 Stoping iOS driver...
>> macaca-ios.js:291:10 [master] pid:19379 iOS driver cleaned up.
>> session.js:80:12 [master] pid:19379 Delete session, sessionId: 02b27b31-2e9f-4783-bceb-dc54b1c36fec
>> responseHandler.js:47:14 [master] pid:19379 Send HTTP Respone to Client: {"sessionId":"02b27b31-2e9f-4783-bceb-dc54b1c36fec","status":0}
>> xctest-client.js:123:16 [master] pid:19379 
Exiting...

>> xctest-client.js:156:14 [master] pid:19379 ** BUILD INTERRUPTED **

>> xctest-client.js:131:16 [master] pid:19379 bootstrap exit with code: 0, signal: null
>> 

  0 passing (60s)
  1 failing

  1) macaca mobile sample #1 should login sucess:
     Error: [element.sendKeys("xxxxx")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command.
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:33:23
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

```

是否sendkeys依赖于ios自带输入法，如果依赖能否在sendkeys时候自动切换到系统输入法中输入？
对于第三方输入法，百度，搜狗，讯飞都失败

**Comment by xudafeng** [comment]
不依赖输入法

**Comment by githublue** [comment]
我是android的，不过也是相同的错误：utils.js:139:13   @xudafeng @CodeToSurvive1

**Comment by githublue** [comment]
https://github.com/alibaba/macaca/issues/265

**Comment by xudafeng** [comment]
iOS要切换成系统输入法啊

**Comment by CodeToSurvive1** [comment]
这个问题解决了是吧？

**Comment by xudafeng** [comment]
@CodeToSurvive1 切成系统输入法
