### ISSUE TITLE
使用macaca-chrome测试，浏览器显示“请停用以开发者模式运行的扩展程序”

### ISSUE THREAD

**Issue by thxl2010** [alibaba/macaca#274]
* **Macaca Version**: 1.1.7

* **Macaca Doctor Logs**:
```
 macaca-doctor version: 1.0.22


 Node.js checklist:

 node env: C:\Program Files\nodejs\node.exe
 node version: v4.4.4

 Android checklist:

 JAVA version is `1.8.0_60`
 JAVA_HOME is set to `D:\Java\jdk1.8.0_60`
 ANDROID_HOME is not set
 ANT_HOME is set to `D:\program files (x86)\apache-ant-1.9.7`

 Installed driver list:

 chrome: 1.0.3
```

* **Operate System**: Win7  64-bit

* **Programming Language**: javascript

问题：使用`macaca-chrome`测试，浏览器显示**请停用以开发者模式运行的扩展程序**
```
>> proxy.js:52:14 [master] pid:9752 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"autoAcceptAlerts":true,"browserName":"chrome","platformName":"desktop","versio
n":"","javascriptEnabled":true,"platform":"ANY","show":true}}
Error: chromedriver proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9515
    at Request._callback (C:\Users\swj\AppData\Roaming\nvm\v4.4.4\node_modules\.macaca-chrome_npminstall\node_modules\.1.0.19@macaca-chromedriver\lib\proxy.js:56:25)
    at self.callback (C:\Users\swj\AppData\Roaming\nvm\v4.4.4\node_modules\.macaca-chrome_npminstall\node_modules\.2.69.0@request\request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (C:\Users\swj\AppData\Roaming\nvm\v4.4.4\node_modules\.macaca-chrome_npminstall\node_modules\.2.69.0@request\request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
>> macaca-chromedriver.js:60:16 [master] pid:9752 create chromedriver session failed
>> macaca-chromedriver.js:62:14 [master] pid:9752 get chromedriver ready status failed
>> macaca-chromedriver.js:84:14 [master] pid:9752 chromedriver starting failed.
C:\Users\swj\AppData\Roaming\nvm\v4.4.4\node_modules\.macaca-chrome_npminstall\node_modules\.1.0.19@macaca-chromedriver\lib\macaca-chromedriver.js:86
        throw err;
        ^

Error: >> macaca-chromedriver.js:62:14 [master] pid:9752 get chromedriver ready status failed
    at Logger.error (C:\Users\swj\AppData\Roaming\nvm\v4.4.4\node_modules\.macaca-chrome_npminstall\node_modules\.1.0.5@xlogger\lib\xlogger.js:169:9)
    at C:\Users\swj\AppData\Roaming\nvm\v4.4.4\node_modules\.macaca-chrome_npminstall\node_modules\.1.0.19@macaca-chromedriver\lib\macaca-chromedriver.js:62:14
    at process._tickCallback (node.js:369:9)
```

**Comment by Archer456** [comment]
https://github.com/alibaba/macaca/issues/266

应该和这个问题是一样的，看下你的chrome浏览器版本是不是54的 你是在测试PC web浏览器网页吧
@thxl2010

**Comment by Archer456** [comment]
@thxl2010   你可以换chrome50版本的  nodejs版的脚本应该可以过的
