### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by edwardzhang121** [alibaba/macaca#275]
C:\Users\zhangmeihua\za>macaca server --port 4444

> > webdriver sdk launched

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (c:\Users\zhangmeihua\AppData\Roaming\npm\n
ode_modules\macaca-cli\node_modules\webdriver-server\node_modules\koa\lib\contex
t.js:91:23)
      at Object.module.exports (c:\Users\zhangmeihua\AppData\Roaming\npm\node_mo
dules\macaca-cli\node_modules\webdriver-server\lib\server\responseHandler.js:57:
17)
      at throw (native)
      at onRejected (c:\Users\zhangmeihua\AppData\Roaming\npm\node_modules\macac
a-cli\node_modules\co\index.js:81:24)
##       at process._tickCallback (node.js:369:9)
- **Macaca Version : 1.1.7**:
- **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.22
  
  Node.js checklist:
  
  node env: C:\Program Files\nodejs\node.exe
  node version: v4.4.7
  
  Android checklist:
  
  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_91`
  ANDROID_HOME is set to `C:\Program Files (x86)\Android\android-sdk`
  Platforms is set to `C:\Program Files (x86)\Android\android-sdk\platforms\andr
  id-23`
  Android tools is set to `C:\Program Files (x86)\Android\android-sdk\tools\andr
  id.bat`
  ADB tool is set to `C:\Program Files (x86)\Android\android-sdk\platform-tools\
  db.exe`
  ANT_HOME is set to `D:\apache-ant-1.8.2`
  
  Installed driver list:
  
  android: 1.0.39
  ios: 1.0.38 [out-of-date]

**Comment by edwardzhang121** [comment]
烦请大神麻烦解决下这个问题，运行macaca start --mobile，macaca后台出现的这个问题

**Comment by githublue** [comment]
你的问题先不说，android SDK 安装路径不能有空格，node路径也尽量不要有空格，如果npm包装在node路径下的话

**Comment by edwardzhang121** [comment]
C:\Users\zhangmeihua>macaca server --port 4444
>> webdriver sdk launched
no device, now create one from avd

  Error: no avd created! Please create one avd first
      at Android.stopDevice.Android.initDevice.data.filter.checkEmulator [as ini
tDevice] (C:\Users\zhangmeihua\AppData\Roaming\npm\node_modules\.macaca-android_
npminstall\node_modules\.1.0.39@macaca-android\lib\macaca-android.js:145:13)
      at next (native)
      at onFulfilled (C:\Users\zhangmeihua\AppData\Roaming\npm\node_modules\maca
ca-cli\node_modules\co\index.js:65:19)
      at process._tickCallback (node.js:369:9)
我再运行uirecorder start --mobile,macaca的后台报上面的错误

麻烦看看
----------------------------------下面是录制的
C:\Users\zhangmeihua>uirecorder start --mobile
? 测试用例文件名 test.spec.js
? App路径, 扩展名: apk, app d:\test.apk

录制服务器监听在端口: 9765
录制浏览器已开启

----------------------------------------------

Mobile app open failed! Internal Server Error

**Comment by edwardzhang121** [comment]
你好，我将node和Android sdk都重新安装了，安装路径没有空格，使用了Genymotion来作为安卓虚拟环境，但在录制的时候还是报下面这个问题，麻烦看看
C:\Users\zhangmeihua\za>macaca server --port 4444
>> webdriver sdk launched

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (C:\Users\zhangmeihua\AppData\Roaming\npm\n
ode_modules\macaca-cli\node_modules\webdriver-server\node_modules\koa\lib\contex
t.js:91:23)
      at Object.module.exports (C:\Users\zhangmeihua\AppData\Roaming\npm\node_mo
dules\macaca-cli\node_modules\webdriver-server\lib\server\responseHandler.js:57:
17)
      at throw (native)
      at onRejected (C:\Users\zhangmeihua\AppData\Roaming\npm\node_modules\macac
a-cli\node_modules\co\index.js:81:24)
      at process._tickCallback (node.js:369:9)

**Comment by edwardzhang121** [comment]
好的，回去我试试重新安装 ------------------ Original ------------------

**Comment by edwardzhang121** [comment]
哪位大神能帮忙下？感谢

**Comment by edwardzhang121** [comment]
Error: Command failed: adb devices
error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037:
通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (10048)
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon

    at checkExecSyncError (child_process.js:465:13)
    at Object.execSync (child_process.js:505:13)
    at getDeviceList (C:\Users\zhangmeihua\AppData\Roaming\npm\node_modules\uire
corder\lib\start.js:1024:22)
    at newMobileApp (C:\Users\zhangmeihua\AppData\Roaming\npm\node_modules\uirec
order\lib\start.js:1061:22)
    at onReady (C:\Users\zhangmeihua\AppData\Roaming\npm\node_modules\uirecorder
\lib\start.js:693:17)
    at Server.<anonymous> (C:\Users\zhangmeihua\AppData\Roaming\npm\node_modules
\uirecorder\lib\start.js:926:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1276:10)

**Comment by edwardzhang121** [comment]
录制的时候一直报这个问题，进程一直结束不了，麻烦看看，谢谢

**Comment by xudafeng** [comment]
@edwardzhang121 升级新版
