### ISSUE TITLE
第一次case运行结束后，run下一条case时会出现connect ECONNREFUSED**的问题

### ISSUE THREAD

**Issue by fengytn** [alibaba/macaca#278]
- **Macaca Version**:1.1.10
- **Macaca Doctor Logs**:
  bogon:tests bita$ macaca doctor
  
  macaca-doctor version: 1.0.23
  
  Node.js checklist:
  
  node env: /usr/local/bin/node
  node version: v6.9.1
  
  iOS checklist:
  
  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy
  
  Android checklist:
  
  JAVA version is `1.8.0_73`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/bita/Library/Android/sdk`
  Platforms is set to `/Users/bita/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/bita/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/bita/Library/Android/sdk/platform-tools/adb`
  
  Installed driver list:
  
  ios: 1.0.40
- **Operate System**: mac 10.12
- **Programming Language**: python

在进行case调试时，每次跑pass或者failed一条case，然后去修改脚本代码执行下一条case时，都会出现

> > proxy.js:58:18 [master] pid:14597 xctest client proxy error with: Error: connect ECONNREFUSED 192.168.19.39:8100
> > /usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169
> >   throw new Error(res);
> >   ^

Error: >> proxy.js:58:18 [master] pid:14597 xctest client proxy error with: Error: connect ECONNREFUSED 192.168.19.39:8100
    at Logger.error (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request.request [as _callback](/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

然后需要重启手机，现去跑另一条case时就能正常，再调试脚本，再重新run时又出现以上问题。每次都要重启手机。

**Comment by xudafeng** [comment]
升级iOS驱动，参考 https://testerhome.com/topics/6314
