### ISSUE TITLE
真机断点调试error

### ISSUE THREAD

**Issue by lylh** [alibaba/macaca#28]
****************************************
*  version 1.0.13 is outdate           *
*  run: npm i -g macaca-client@1.0.11  *
****************************************

`>> index.js:62:12 [master] pid:27215 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '100.84.92.213',
  host: 'lylh.local',
  loaded_time: '2016-04-12 10:00:08' }
>> middlewares.js:31:10 [master] pid:27215 base middlewares attached
>> router.js:101:10 [master] pid:27215 router set
>> webdriver sdk launched
>> responseHandler.js:24:12 [master] pid:27215 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"ios","platformVersion":"8.3","deviceName":"iPhone 5s","udid":"18e4f6e47b28db5adad04c6feab0d3a6716a6ddc","bundleId":"com.example.test"}}
>> session.js:22:10 [master] pid:27215 Creating session, sessionId: 8b58a0ce-61c5-420d-819a-30fd305ed549.
>> responseHandler.js:56:12 [master] pid:27215 Send Error Respone to Client TypeError: Cannot read property 'substring' of undefined
>> responseHandler.js:62:14 [master] pid:27215 TypeError: Cannot read property 'substring' of undefined
    at Function._.sleep._.retry._.waitForCondition._.exec._.spawn.child.on._.configApp (/usr/local/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/common/helper.js:174:10)
    at WebdriverServer.start (/usr/local/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/server/index.js:39:16)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:50:10)
>> responseHandler.js:81:14 [master] pid:27215 Unexcepted error TypeError

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/usr/local/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/server/responseHandler.js:82:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:81:24)
      at process._tickCallback (node.js:369:9)`

**Comment by zenzhu** [comment]
@lylh 升级一下 macaca-client 到 最新版 试试

**Comment by lylh** [comment]
@zenzhu 更新了提示这个，
>> xctest-client.js:245:12 [master] pid:68297 xcode version: 7.3
>> xctest-client.js:218:14 [master] pid:68297 xcodebuild: error: The run destination iPhone is not valid for Testing the scheme 'XCTUITestRunner'.
	iPhone’s iOS 8.1.2 doesn’t match XCTUITestRunner.xctest’s iOS 9.2 deployment target. Upgrade iPhone’s iOS version or lower XCTUITestRunner.xctest’s deployment target.

>> xctest-client.js:226:14 [master] pid:68297 xctest client exit with code: 70, signal: null
>> xctest-client.js:218:14 [master] pid:68297 xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ id:18e4f6e47b28db5adad04c6feab0d3a6716a6ddc }

	Unsupported device specifier option.
	The device “My Mac” does not support the following options: id
	Please supply only supported device specifier options.

	Available destinations for the "XCTUITestRunner" scheme:
		{ platform:iOS Simulator, id:859B6CEE-150F-4FC1-83C2-2240C3810B4B, OS:9.3, name:iPad 2 }
		{ platform:iOS Simulator, id:4FE19764-EC79-45F7-803C-A75FBD69D9BF, OS:9.3, name:iPad Air }
		{ platform:iOS Simulator, id:1C7C8505-4EA3-4CBA-9D8F-046C061716B3, OS:9.3, name:iPad Air 2 }
		{ platform:iOS Simulator, id:CAFB09A5-1B5A-498F-90CA-E31E2CAF2BB5, OS:9.3, name:iPad Pro }
		{ platform:iOS Simulator, id:5B07541B-E8BB-4C77-969A-6739397643DD, OS:9.3, name:iPad Retina }
		{ platform:iOS Simulator, id:71AF8177-4EA9-43C6-9F43-E4E6378154BD, OS:9.3, name:iPhone 4s }
		{ platform:iOS Simulator, id:DE14C761-8A0D-4410-B02E-EC91F6815128, OS:9.3, name:iPhone 5 }
		{ platform:iOS Simulator, id:BE068654-449A-4DEC-A325-2B861E11EFC6, OS:9.3, name:iPhone 5s }
		{ platform:iOS Simulator, id:65A8285E-D64A-4EA3-84E0-B517A7D9E25E, OS:9.3, name:iPhone 6 }
		{ platform:iOS Simulator, id:604B41F1-9FE3-429A-9BD4-F803E29474E6, OS:9.3, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:9D79EA4D-335C-4186-B947-69A3DEF3F5E5, OS:9.3, name:iPhone 6s }
		{ platform:iOS Simulator, id:13CED326-775B-47D3-B862-B1EB47FD0FA1, OS:9.3, name:iPhone 6s Plus }

	Ineligible destinations for the "XCTUITestRunner" scheme:
		{ platform:iOS, id:e94803524dccb1e8c79bfb18509b73b366e5cb83, name:iPhone, error:iPhone’s iOS 8.1.2 doesn’t match XCTUITestRunner.xctest’s iOS 9.2 deployment target. Upgrade iPhone’s iOS version or lower XCTUITestRunner.xctest’s deployment target. }

**Comment by xudafeng** [comment]
@lylh xcode 升级到最新

**Comment by xudafeng** [comment]
断点调试见 https://testerhome.com/topics/4563
