### ISSUE TITLE
运行官方实例到第4步，跑webView报错：Error: Device: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX does not exist.

### ISSUE THREAD

**Issue by IceEnd** [alibaba/macaca#284]
版本：
Xcode Version: 8.0
macOS Sierra: 10.12.1
iOS: 9.3 or 10.0
Macaca Version: 1.1.10

macaca doctor:

```
macaca-doctor version: 1.0.23


  Node.js checklist:

  node env: /Users/Cononico/.nvm/versions/node/v6.9.1/bin/node
  node version: v6.9.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is not set
  ANDROID_HOME is not set

  Installed driver list:

  electron: 1.1.4
  ios: 1.0.40
```

我想在跑iOS，没配Android的环境。
在运行官方实例：macaca-mobile-sample.test.js
执行到第4步，跑webView的时候就会报错：Error: Device: D9C8ACB9-0A5E-42A2-92AA-A52243429AAD does not exist.

Log:

```
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

CFBundleIdentifier is xudafeng.ios-app-bootstrap
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/_v/s4sv1d5x4d557c6pw99wxg3r0000gn/T/ios-app-bootstrap.app/Info.plist
>> WebDriverAgent version: 1.0.28
>> current window size {"width":375,"height":667}

>> 
>>     ✓ #1 should login success (17617ms)

>> { tree: 
   { bounds: '{{0, 0}, {375, 667}}',
     isEnabled: '1',
     isVisible: '1',
     children: [ [Object], [Object], [Object] ],
     rect: { origin: [Object], size: [Object] },
     value: null,
     label: 'ios-app-bootstrap',
     type: 'Application',
     name: 'ios-app-bootstrap',
     rawIdentifier: null } }

    ✓ #2 should display home (475ms)

>> list element origin:{"x":16,"y":527}

>> list element size:{"width":343,"height":40}

>> 
>>     ✓ #3 should scroll tableview (5770ms)

>> 
>>     ✓ #4 should display webview (8584ms)

ios_webkit_debug_proxy path: /usr/local/bin/ios_webkit_debug_proxy

  Error: Device: D9C8ACB9-0A5E-42A2-92AA-A52243429AAD does not exist.
      at request.get.then.then.devices (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/remote-debugger.js:39:17)
      at tryCatcher (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/promise.js:510:31)
      at Promise._settlePromiseAt (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/promise.js:584:18)
      at Promise._settlePromises (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/promise.js:700:14)
      at Async._drainQueue (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/async.js:15:14)
      at runCallback (timers.js:637:20)
      at tryOnImmediate (timers.js:610:5)
      at processImmediate [as _immediateCallback] (timers.js:582:5)

>> 
>>     1) #5 should go into webview


  RequestError: Error: connect ECONNREFUSED 127.0.0.1:80
      at new RequestError (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request-promise/lib/errors.js:11:15)
      at Request.RP$callback [as _callback] (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request-promise/lib/rp.js:60:32)
      at self.callback (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request/request.js:186:22)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.onRequestError (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request/request.js:824:8)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:310:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1276:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> 
>>     2) #6 should go into test


  RequestError: Error: connect ECONNREFUSED 127.0.0.1:80
      at new RequestError (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request-promise/lib/errors.js:11:15)
      at Request.RP$callback [as _callback] (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request-promise/lib/rp.js:60:32)
      at self.callback (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request/request.js:186:22)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.onRequestError (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request/request.js:824:8)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:310:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1276:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> 
>>     3) #7 should works with web


  RequestError: Error: connect ECONNREFUSED 127.0.0.1:80
      at new RequestError (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request-promise/lib/errors.js:11:15)
      at Request.RP$callback [as _callback] (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request-promise/lib/rp.js:60:32)
      at self.callback (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request/request.js:186:22)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.onRequestError (/Users/Cononico/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/request/request.js:824:8)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:310:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1276:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> 
>>     4) #8 should logout success

Listing devices on :9221
Connected :9222 to SIMULATOR (SIMULATOR)
Disconnected :9222 from SIMULATOR (SIMULATOR)

ios_webkit_debug_proxy exit with code: 0, signal: null
>> 

  4 passing (2m)
  4 failing


>>   1) macaca mobile sample #5 should go into webview:
     Error: [contexts()] Not JSON response
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) macaca mobile sample #6 should go into test:
     Error: [contexts()] Not JSON response
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  3) macaca mobile sample #7 should works with web:
     Error: [contexts()] Not JSON response
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  4) macaca mobile sample #8 should logout success:
     Error: [contexts()] Not JSON response
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)




>> Test completed!
```

另外在把

``` js
var iOSOpts = {
  platformVersion: '9.3',
  deviceName: 'iPhone 5s',
  platformName: 'iOS',
  //bundleId: 'xudafeng.ios-app-bootstrap',
  app: path.join(__dirname, '..', 'app', `${platform}-app-bootstrap.zip`)
};
```

如上platformVersion设置成了9.3,跑起来的虚拟机居然是 10.0的。
求大神解答。

**Comment by IceEnd** [comment]
后面我自己用macaca-wd这个包写例子，出错的位置都在调用了driver.contents()这个方法，看了一下/.nvm/versions/node/v6.9.1/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/remote-debugger.js中的代码，第34行，这个位置读取的devices有问题：
```js
[{ 
"deviceId": "SIMULATOR", 
"deviceName": "SIMULATOR",
"url": "localhost:9222"
}]
```
这个devices应该是默认的吧，没有得到正确的devices。强制修改deviceId为运行的模拟器，脚本可以跑起来。
另外driver.init()这个方法中没有提供更改iOS版本的变量吗，我把 platformVersion设置为9.3，但是启动的模拟器还是10.0的。

麻烦大神抽一点空闲时间回答我的问题。

**Comment by Finb** [comment]
我也是这个提示~
10.11 ,10.12 都试过
不知道怎么解决。期待解决办法

**Comment by xudafeng** [comment]
升级iOS驱动，参考 https://testerhome.com/topics/6314

**Comment by xudafeng** [comment]
ios_webkit_debug_proxy 升级到最新就好了

**Comment by IceEnd** [comment]
macaca-ios: 1.0.40
ios-webkit-debug-proxy: 1.7
usbmuxd: 1.0.10
macaca-cli: 1.1.16
node: 6.9.1
macOS Sierra: 10.12.1
iOS: 10.1
还是老错误，我是在模拟器上运行的。

**Comment by xudafeng** [comment]
ios_webkit_debug_proxy 没启动起来的原因啊

**Comment by IceEnd** [comment]
打开模拟器，直接启动ios_webkit_debug_proxy，它自己连接的得到的设备也是：
```js
[{ 
"deviceId": "SIMULATOR", 
"deviceName": "SIMULATOR",
"url": "localhost:9222"
}]
```
我再连上真机：
```js
[{
   "deviceId": "SIMULATOR",
   "deviceName": "SIMULATOR",
   "url": "localhost:9222"
},{
   "deviceId": "a11a05063f40bf7a730800045e7dbd1c76ea5121",
   "deviceName": "不好用的iPhone",
   "url": "localhost:9223"
}]
```
说明ios_webkit_debug_proxy启动了，只是模拟器它直接给个"SIMULATOR"的deviceId了，而macaca里面的deviceId还是那一串字符，我觉得你这个位置需要加个是不是模拟器的判断了。

**Comment by xudafeng** [comment]
https://github.com/macacajs/ios-utils/pull/4

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/pull/40

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-ios/pull/37

**Comment by xudafeng** [comment]
https://github.com/macacajs/remote-debugger/pull/7

**Comment by xudafeng** [comment]
https://github.com/libimobiledevice/ideviceinstaller/issues/54

**Comment by FrendEr** [comment]
@IceEnd 你的问题解决了吗？我遇到跟你一样的问题

**Comment by zwyxsyu** [comment]
这个问题需要将手机中的设置->safari->高级->Web检查器开启
