### ISSUE TITLE
用getAttribute方法获取content-desc和name属性时报错

### ISSUE THREAD

**Issue by xiaoxiao86** [alibaba/macaca#285]
- **Macaca Version**:    1.1.10
- **Macaca Doctor Logs**:

com.alibaba.fastjson.JSONException: syntax error, pos 3, json : Not Implemented
    at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1361)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1268)
    at com.alibaba.fastjson.JSON.parse(JSON.java:137)
    at com.alibaba.fastjson.JSON.parse(JSON.java:128)
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:201)
    at macaca.client.common.Utils.getRequest(Utils.java:57)
    at macaca.client.common.Utils.request(Utils.java:133)
    at macaca.client.commands.Element.getAttribute(Element.java:108)
    at macaca.client.MacacaClient.getAttribute(MacacaClient.java:691)
    at com.macaca.test.macaca.HomeTest.trip(HomeTest.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    at org.testng.TestRunner.privateRun(TestRunner.java:782)
    at org.testng.TestRunner.run(TestRunner.java:632)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
    at org.testng.TestNG.run(TestNG.java:1064)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
- **Operate System**: win7 64位
- **Programming Language**: JAVA

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/commit/3bd44ac9020438dec01f9ffc62ff786713141fdd

**Comment by xudafeng** [comment]
https://github.com/macacajs/wd.java/pull/52

**Comment by xudafeng** [comment]
update andrioid driver
