### ISSUE TITLE
[macaca-ios][python3.5] 运行实例代码macaca-ios-sample.test.py报错 “requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:3456/wd/hub/session”

### ISSUE THREAD

**Issue by leopeng1983** [alibaba/macaca#288]
1. 启动server:  macaca server --verbose
2. 运行示例代码。
   报错如下：

/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 /Applications/PyCharm.app/Contents/helpers/pycharm/utrunner.py /Users/jingoal_user/leo/macaca-test-sample-python/tests/macaca-ios-sample.test.py true
Testing started at 6:17 PM ...

Error
Traceback (most recent call last):
  File "/Users/jingoal_user/leo/macaca-test-sample-python/tests/macaca-ios-sample.test.py", line 35, in setUpClass
    cls.driver.init()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/util.py", line 145, in fluent_interface
    ret = func(instance, _args, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/webdriver.py", line 132, in init
    }, False)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/webdriver.py", line 66, in _execute
    res = self.remote_invoker.execute(command, data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/remote_invoker.py", line 110, in execute
    return self._request(method, url, body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/remote_invoker.py", line 145, in _request
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:3456/wd/hub/session

Process finished with exit code 0

请问如何解决？
另外如果要测试app，是否需要开发者证书，或者如何配置webdriveragent，麻烦说明下，谢谢！

**Comment by zenzhu** [comment]
感觉你服务器没有启动成功啊，直接没开始就结束了。真机测试参考 [Macaca iOS 真机测试](https://testerhome.com/topics/5804)

**Comment by xudafeng** [comment]
请升级iOS驱动，参考https://testerhome.com/topics/6314
