### ISSUE TITLE
换包后安装包出错

### ISSUE THREAD

**Issue by TediWang** [alibaba/macaca#29]
第一次用新版本的测试包能正常的工作，然后用上个版本的包进行测试报错，错误信息：
>> responseHandler.js:24:12 [master] pid:57356 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"/Users/yb.wang/Test/macaca/app/ios-app-bootstrap.zip"}}
>> session.js:22:10 [master] pid:57356 Creating session, sessionId: d5bbc783-4dbc-48e9-9acf-941ddbac2980.
>> helper.js:205:12 [master] pid:57356 Unzipping local app form /Users/yb.wang/Test/macaca/app/ios-app-bootstrap.zip
>> responseHandler.js:56:12 [master] pid:57356 Send Error Respone to Client There is a file in the way: /var/folders/xl/fqsc3cgd4bj8mhsc67_7xy6m0000gn/T/CTRIP_WIRELESS.app/CTHomeSalesViewCell.nib

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/usr/local/lib/node_modules/macaca-client/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/server/responseHandler.js:59:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:81:24)
      at process._tickCallback (node.js:401:9)

两个包通过xcode在模拟器上都能正常工作。

**Comment by xudafeng** [comment]
@TediWang debug 还是 release？

**Comment by TediWang** [comment]
@xudafeng 两个包只是宏不一样，有些调试代码没有编译进去。

**Comment by xudafeng** [comment]
@TediWang 这需要你们团队自己排查了

**Comment by TediWang** [comment]
@xudafeng 奇怪之处在于同一个版本的包，宏不一样可以工作。不同版本，后面那个包就有问题。
