### ISSUE TITLE
关于API文档中move_to的操作是否能用于ios手机上？

### ISSUE THREAD

**Issue by fengytn** [alibaba/macaca#305]
* **Macaca Version**: 1.1.16

* **Macaca Doctor Logs**:

  macaca-doctor version: 1.0.27

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_73`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/bita/Library/Android/sdk`
  Platforms is set to `/Users/bita/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/bita/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/bita/Library/Android/sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.41

* **Operate System**: mac 10.12.1

* **Programming Language**: python

我用的是ios10的真机测试，用的python编写。
我调用Move_to这个API时报错，我导入了下面的三个库：
from macaca import WebDriver
from macaca import Keys
from macaca import WebElement
我的写法如下：
self.driver \
      .element_by_name('社区') \
      .move_to(207, 711)
报错如下：
Traceback (most recent call last):
  File "shequ.py", line 419, in test02_BBS_02_Cards_05_Add
    .move_to(207, 711)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/util.py", line 145, in fluent_interface
    ret = func(instance, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/webelement.py", line 383, in move_to
    self._driver.move_to(self, x, y)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/util.py", line 145, in fluent_interface
    ret = func(instance, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/webdriver.py", line 344, in move_to
    'y': y
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/webdriver.py", line 68, in _execute
    ret.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/macaca/webdriverresult.py", line 54, in raise_for_status
    raise WebDriverException(error, message, screen, stacktrace)
macaca.webdriverexception.WebDriverException: 
Error: None
Message: Unhandled endpoint: /session/B3B6ADB7-1E4A-4573-B8A7-456E2E1B0EB1/moveto -- http://127.0.0.1:8914/ with parameters {
    wildcards =     (
        "session/B3B6ADB7-1E4A-4573-B8A7-456E2E1B0EB1/moveto"
    );
}
其实我想实现的一个操作是，把某个标签长按移动到另一个位置，现在能读出此标签的name...但是我用move_to这个方法实现不了，或者有没有其它的方法能实现。
下面是我查看相关API文档看到，我也不确定我的写法是法有问题。
move_to(x=0, y=0)
Move the mouse by an offset of the specificed element.

Parameters:	
x (float) – X offset to move to, relative to the top-left corner of the element.
y (float) – Y offset to move to, relative to the top-left corner of the element.
Returns:	
WebElement object.

**Comment by xudafeng** [comment]
不能

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/300

**Comment by xudafeng** [comment]
关注此issue https://github.com/alibaba/macaca/issues/366
