### ISSUE TITLE
能否增加一个isEnabled的方法或者有什么办法能实现这个判断

### ISSUE THREAD

**Issue by septem123** [alibaba/macaca#307]
macaca-doctor version: 1.0.27

  Node.js checklist:

  node env: /usr/bin/node
  node version: v4.2.6

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/home/cj/android-sdk-linux`
  Platforms is set to `/home/cj/android-sdk-linux/platforms/android-19`
  Android tools is set to `/home/cj/android-sdk-linux/tools/android`
  ADB tool is set to `/home/cj/android-sdk-linux/platform-tools/adb`

  Installed driver list:

  android: 1.0.39

在做安卓自动化测试的时候经常会有一些按钮是输入了正确的字符串才可以点击的，我在API里面没有看见类似的方法

直接使用会报错：
Error: [element.isEnabled()] Not JSON response
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:905:12)

**Comment by xudafeng** [comment]
isEnabled 是app的业务逻辑啊，应该自己控制的

**Comment by septem123** [comment]
确实是业务逻辑 
不过程序确实无法判断是否能点击
难道只能用截图了？

**Comment by xudafeng** [comment]
点击按钮后的改变能够作为断言依据吗

**Comment by septem123** [comment]
有道理 web写太多 思维有些定式了 
我回去试试
