### ISSUE TITLE
小米 4 真机测试 sendKeys 有点问题

### ISSUE THREAD

**Issue by septem123** [alibaba/macaca#312]
macaca-doctor version: 1.0.27
  Node.js checklist:

  node env: /usr/bin/node
  node version: v4.2.6

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/home/cj/android-sdk-linux`
  Platforms is set to `/home/cj/android-sdk-linux/platforms/android-21`
  Android tools is set to `/home/cj/android-sdk-linux/tools/android`
  ADB tool is set to `/home/cj/android-sdk-linux/platform-tools/adb`

  Installed driver list:

  android: 1.0.39

输入框输入数字 例如银行卡之类的 会被混淆 
比如说输入 62258878 在机器上会显示 66227788

然后直接用adb shell input text
                  adb shell input keyevent
也是如此 我判断是系统的限制

倒是用adb shell input tap可以解决这个问题

但是macaca 好像没有什么地方可以运行这些命令

强制用nodejs的  child_process.exec运行adb命令的话

macaca再跑就会报错
报错信息如下
Error: [elementByName("登录")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command.
      at exports.newError (cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/callbacks.js:75:19
      at cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (cctv/macaca-test-sample/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (cctv/macaca-test-sample/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (cctv/macaca-test-sample/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:905:12)

还有就是所有的element方法在找不到元素的时候会抛错.......后续的所有操作都不能运行
连hasElement 都不行.....难道不能返回false?
Error: [elementByLinkText("充值")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.
      at exports.newError (cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/callbacks.js:75:19
      at cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (cctv/macaca-test-sample/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (cctv/macaca-test-sample/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (cctv/macaca-test-sample/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:905:12)

**Comment by xudafeng** [comment]
直接用adb模块，试试呢 https://github.com/macacajs/macaca-adb

**Comment by septem123** [comment]
还有就是所有的element方法在找不到元素的时候会抛错
这个问题有解吗？

**Comment by xudafeng** [comment]
哪个issue

**Comment by septem123** [comment]
没有单独提issue  写在一起了

还有就是所有的element方法在找不到元素的时候会抛错.......后续的所有操作都不能运行
连hasElement 都不行.....难道不能返回false?
Error: [elementByLinkText("充值")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.
at exports.newError (cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/utils.js:139:13)
at cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/callbacks.js:75:19
at cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
at Request._callback (cctv/macaca-test-sample/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
at Request.self.callback (cctv/macaca-test-sample/node_modules/macaca-wd/node_modules/request/request.js:368:22)
at Request. (cctv/macaca-test-sample/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
at IncomingMessage. (cctv/macaca-test-sample/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
at endReadableNT (_stream_readable.js:905:12)

**Comment by xudafeng** [comment]
hasElement 问题 @Yinxl

**Comment by xudafeng** [comment]
Yinxl

**Comment by Yinxl** [comment]
[https://github.com/macacajs/wd.java/pull/61](https://github.com/macacajs/wd.java/pull/61)

控件不存在时报错问题已经解决。

**Comment by septem123** [comment]
好像只修了java版本的? nodejs版本的没修复？
