### ISSUE TITLE
ios真机运行总是出现socket hang up

### ISSUE THREAD

**Issue by fengerapple** [alibaba/macaca#317]
**模拟器没问题，真机能运行成功一次，然后在运行就不行了**

>> index.js:17:12 [master] pid:13206 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '30.96.89.192',
  host: 'fengdeMacBook-Air.local',
  loaded_time: '2016-11-18 18:40:21' }
>> middlewares.js:17:10 [master] pid:13206 base middlewares attached
>> router.js:129:10 [master] pid:13206 router set
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:13206 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 6 Plus","udid":"fd2d4a71ffb6d15d955c837cec7884281e1561d4","bundleId":"dgf.ios-app-bootstrap"}}
>> session.js:47:10 [master] pid:13206 Creating session, sessionId: 843ce30e-b883-4e7f-8ac9-9977a392f82e.
>> xctest-client.js:48:14 [master] pid:13206 project path: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.30@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:144:10 [master] pid:13206 {
	"bundleId": "dgf.ios-app-bootstrap",
	"platformName": "iOS",
	"platformVersion": "9.3"
}
>> xctest-client start with port: 8900
>> xctest-client.js:223:12 [master] pid:13206 xcode version: 8.1
>> WebDriverAgent version: 1.0.30
>> xctest-client.js:162:14 [master] pid:13206 2016-11-18 18:40:24.167 xcodebuild[13215:558068]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/feng/Library/Developer/Xcode/DerivedData/WebDriverAgent-eyhoetpiytlhwffsxpabgoqlaanm/Logs/Test/65A0C6F3-8717-45A8-B2B2-862294CC868E/Session-WebDriverAgentRunner-2016-11-18_184024-gGyN7K.log

>> xctest-client.js:163:14 [master] pid:13206 please check project: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.30@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:162:14 [master] pid:13206 2016-11-18 18:40:24.167 xcodebuild[13215:558066] [MT] IDETestOperationsObserverDebug: (5A95DFD2-15ED-40EC-B2A0-32438B88CC6E) Beginning test session WebDriverAgentRunner-5A95DFD2-15ED-40EC-B2A0-32438B88CC6E at 2016-11-18 18:40:24.165 with Xcode 8B62 on target <DVTiOSDevice: 0x7ff8ac195910> {
		deviceSerialNumber:         FK1NP1CJG5QQ
		identifier:                 fd2d4a71ffb6d15d955c837cec7884281e1561d4
		deviceClass:                iPhone
		deviceName:                 boss
		deviceIdentifier:           fd2d4a71ffb6d15d955c837cec7884281e1561d4
		productVersion:             9.3.5
		buildVersion:               13G36
		deviceSoftwareVersion:      9.3.5 (13G36)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12524146688
		deviceAvailableCapacity:    1894354944
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7ff8abf79690 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.5 (13G36))

>> xctest-client.js:163:14 [master] pid:13206 please check project: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.30@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:162:14 [master] pid:13206 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/gv/pws8vdzn6fx01vzb4_5dt3r40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/6717a2ffe13755d0eb5faf7110cbc359/fd2d4a71ffb6d15d955c837cec7884281e1561d4/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/feng/Library/Developer/Xcode/DerivedData/WebDriverAgent-eyhoetpiytlhwffsxpabgoqlaanm/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/gv/pws8vdzn6fx01vzb4_5dt3r40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.xn4IeI/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/gv/pws8vdzn6fx01vzb4_5dt3r40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.xn4IeI/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:163:14 [master] pid:13206 please check project: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.30@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:162:14 [master] pid:13206 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/gv/pws8vdzn6fx01vzb4_5dt3r40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.xn4IeI/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:163:14 [master] pid:13206 please check project: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.30@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:162:14 [master] pid:13206 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/gv/pws8vdzn6fx01vzb4_5dt3r40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.xn4IeI/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:163:14 [master] pid:13206 please check project: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.30@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:54:14 [master] pid:13206 Proxy: /session:POST to http://127.0.0.1:8900/session:POST with body: {"desiredCapabilities":{"bundleId":"dgf.ios-app-bootstrap","platformName":"iOS","platformVersion":"9.3"}}
>> proxy.js:58:18 [master] pid:13206 xctest client proxy error with: Error: socket hang up
/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.5@xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^

Error: >> proxy.js:58:18 [master] pid:13206 xctest client proxy error with: Error: socket hang up
    at Logger.error (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.5@xlogger/lib/xlogger.js:169:9)
    at Request.request [as _callback] (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.22@xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.2.69.0@request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.2.69.0@request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:344:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by fengerapple** [comment]
ps -ef 看890x的端口有好几个，手动kill掉再运行还是不行，手机上表现就是wda一直自动打开关闭打开关闭。。

**Comment by xudafeng** [comment]
@fengerapple 重启电脑试试

**Comment by fengerapple** [comment]
@xudafeng 重启后也是一样的

> macaca doctor

  macaca-doctor version: 1.0.27


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.7.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_65`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/feng/Documents/tools/android-sdk-macosx`
  Platforms is set to `/Users/feng/Documents/tools/android-sdk-macosx/platforms/android-24`
  Android tools is set to `/Users/feng/Documents/tools/android-sdk-macosx/tools/android`
  ADB tool is set to `/Users/feng/Documents/tools/android-sdk-macosx/platform-tools/adb`

  Installed driver list:

  android: 1.1.1
  electron: 1.1.4
  ios: 1.0.42

**Comment by zenzhu** [comment]
@fengerapple 每次用例结束的时候是否调用了 driver.quit() 方法。

**Comment by fengerapple** [comment]
@zenzhu 
python 的tearDownClass方法应该会自动调用的
` def tearDownClass(cls):` 
`       cls.driver.quit()`

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/299

**Comment by xudafeng** [comment]
https://github.com/macacajs/xctest-client/commit/ef5aa5f6260a32aa2a80dfb70a567c7109cbd1b1

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-ios/commit/5c121ecdfcbfa7d95344602e698499709c9fbfe8

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/304

**Comment by fengytn** [comment]
刚刚更新了macaca-ios后，跑了大概有5条case，还是出现此情况，下面的Log像个死循环

>> responseHandler.js:11:12 [master] pid:4374 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/f7068ce3-f372-4965-923b-1dbd931112d6/element/temp/swipe, jsonBody: {"endX":205,"startY":712,"endY":710,"duration":5,"startX":208}
>> proxy.js:54:14 [master] pid:4374 Proxy: /wd/hub/session/temp/accept_alert:POST to http://127.0.0.1:8901/session/AAB1C3CD-848D-4911-85F5-84EF228A0717/accept_alert:POST with body: {}
>> proxy.js:58:18 [master] pid:4374 xctest client proxy error with: Error: socket hang up
>> responseHandler.js:54:12 [master] pid:4374 Send Error Respone to Client: Error: socket hang up
>> responseHandler.js:60:14 [master] pid:4374 Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

  Error: socket hang up
      at createHangUpError (_http_client.js:254:15)
      at Socket.socketOnEnd (_http_client.js:346:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:185:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> xctest-client.js:167:14 [master] pid:4374 Failing tests:

>> xctest-client.js:168:14 [master] pid:4374 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:167:14 [master] pid:4374 	-[UITestingUITests testRunner]
** TEST FAILED **

>> xctest-client.js:168:14 [master] pid:4374 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:177:14 [master] pid:4374 xctest client exit with code: 65, signal: null
>> responseHandler.js:11:12 [master] pid:4374 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/f7068ce3-f372-4965-923b-1dbd931112d6/element/temp/swipe, jsonBody: {"endX":205,"startY":712,"endY":710,"duration":5,"startX":208}
>> proxy.js:54:14 [master] pid:4374 Proxy: /wd/hub/session/temp/accept_alert:POST to http://127.0.0.1:8901/session/AAB1C3CD-848D-4911-85F5-84EF228A0717/accept_alert:POST with body: {}
>> proxy.js:58:18 [master] pid:4374 xctest client proxy error with: Error: socket hang up
>> responseHandler.js:54:12 [master] pid:4374 Send Error Respone to Client: Error: socket hang up
>> responseHandler.js:60:14 [master] pid:4374 Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

  Error: socket hang up
      at createHangUpError (_http_client.js:254:15)
      at Socket.socketOnEnd (_http_client.js:346:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:185:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> responseHandler.js:11:12 [master] pid:4374 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/f7068ce3-f372-4965-923b-1dbd931112d6/element/temp/swipe, jsonBody: {"endX":205,"startY":712,"endY":710,"duration":5,"startX":208}
>> proxy.js:54:14 [master] pid:4374 Proxy: /wd/hub/session/temp/accept_alert:POST to http://127.0.0.1:8901/session/AAB1C3CD-848D-4911-85F5-84EF228A0717/accept_alert:POST with body: {}
>> proxy.js:58:18 [master] pid:4374 xctest client proxy error with: Error: socket hang up
>> responseHandler.js:54:12 [master] pid:4374 Send Error Respone to Client: Error: socket hang up
>> responseHandler.js:60:14 [master] pid:4374 Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

  Error: socket hang up
      at createHangUpError (_http_client.js:254:15)
      at Socket.socketOnEnd (_http_client.js:346:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:185:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> responseHandler.js:11:12 [master] pid:4374 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/f7068ce3-f372-4965-923b-1dbd931112d6/element/temp/swipe, jsonBody: {"endX":205,"startY":712,"endY":710,"duration":5,"startX":208}
>> proxy.js:54:14 [master] pid:4374 Proxy: /wd/hub/session/temp/accept_alert:POST to http://127.0.0.1:8901/session/AAB1C3CD-848D-4911-85F5-84EF228A0717/accept_alert:POST with body: {}
>> proxy.js:58:18 [master] pid:4374 xctest client proxy error with: Error: socket hang up
>> responseHandler.js:54:12 [master] pid:4374 Send Error Respone to Client: Error: socket hang up
>> responseHandler.js:60:14 [master] pid:4374 Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

  Error: socket hang up
      at createHangUpError (_http_client.js:254:15)
      at Socket.socketOnEnd (_http_client.js:346:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:185:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by zsmjluo** [comment]
@xudafeng 之前出现的socket hang up问题更新驱动后暂未复现，挺稳定

**Comment by fengerapple** [comment]
更新macaca-ios 1.0.43后，仍然是socket hang up
>> proxy.js:58:18 [master] pid:1058 xctest client proxy error with: Error: socket hang up
 responseHandler.js:54:12 [master] pid:1058 Send Error Respone to Client: Error: socket hang up
 responseHandler.js:60:14 [master] pid:1058 Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

  >>Error: socket hang up
      at createHangUpError (_http_client.js:252:15)
      at Socket.socketOnEnd (_http_client.js:344:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:185:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)_

**Comment by fengerapple** [comment]
更换设备为iphone7，ios10之后，问题不再复现，很稳定，之前出问题的为iphone6Plus，ios9.3

**Comment by wangtao169447** [comment]
@xudafeng 
用app-inspector查看真机页面布局，会出现
`>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.41
>> app-inspector:66:44 [master] pid:28943 Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(node:28943) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:28943 Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`
错误
这个有哪些手段能协助排查？
谢谢
