### ISSUE TITLE
模拟器运行官方例子报错

### ISSUE THREAD

**Issue by zhuominjie** [alibaba/macaca#339]
>> xctest-client.js:171:14 [master] pid:23057 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:267:14 [master] pid:23057 killing deviceLogProc pid: 23070
>> xctest-client.js:272:14 [master] pid:23057 killing runnerProc pid: 23071
>> xctest-client.js:181:14 [master] pid:23057 xctest client exit with code: 65, signal: null
>> xctest-client.js:107:16 [master] pid:23057 simulator log process exit with code: null, signal: SIGKILL
>> xctest-client.js:255:14 [master] pid:23057 Fail to start xctest: undefined
>> responseHandler.js:54:12 [master] pid:23057 Send Error Respone to Client: undefined

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:57:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (node.js:369:9)

>> 
>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:23057 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:23057 Send HTTP Respone to Client: 405 Method Not Allowed
>> 
>>     2) "after all" hook

>> 

>> 

>>   0 passing (4s)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     [init({"autoAcceptAlerts":true,"platformName":"iOS","deviceName":"iPhone 5s","app":"/Users/zhuominjie/Downloads/macaca-test-sample/app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
  Error: [init({"autoAcceptAlerts":true,"platformName":"iOS","deviceName":"iPhone 5s","app":"app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

**Comment by xudafeng** [comment]
doctor 贴一下

**Comment by zwyxsyu** [comment]
运行android、ios手机样例 会报这个错误   报错：环境不可用

**Comment by zwyxsyu** [comment]
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize
INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: test=testStartServer
INSTRUMENTATION_STATUS_CODE: 1
uiautomator start socket server.

>> socket server ready


>> socket client ready
>> responseHandler.js:54:12 [master] pid:2779 Send Error Respone to Client: get PIDs failed with TypeError: Cannot read property '0' of null

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:57:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (node.js:369:9)

>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:2779 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:2779 Send HTTP Respone to Client: 405 Method Not Allowed
>>     2) "after all" hook

>> 

>> 

>>   0 passing (3s)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     Error: [init({"platformName":"Android","autoAcceptAlerts":false,"package":"com.github.android_app_bootstrap","activity":"com.github.android_app_bootstrap.activity.WelcomeActivity"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)


>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

**Comment by scheibe1874** [comment]
我也遇到这个问题了，请问怎么解决的？

**Comment by xudafeng** [comment]
adb 没连接成功吧 https://github.com/macaca-sample/mobile-app-sample-nodejs 看CI
