### ISSUE TITLE
app-inspector升级到 1.2.16版本后，启动报错：

### ISSUE THREAD

**Issue by xiaoxiao86** [alibaba/macaca#355]
* **Macaca Version**:     1.1.19

* **Macaca Doctor Logs**:

C:\Users\dell>app-inspector -u T3Q6T16514012351
>> uiautomator-client.js:31:12 [master] pid:5568 uiautomator-bootstrap was not found in: C:\Users\dell\AppData\Roaming\npm\node_modules\.app-inspector_npminstall\node_modules\.1.0.36@uiautomator-client\bin\uiautomator-bootstrap.jar, please check your Android ENV
>> app-inspector:66:44 [master] pid:5568 Error: >> uiautomator-client.js:31:12 [master] pid:5568 uiautomator-bootstrap was not found in: C:\Users\dell\AppData\Roaming\npm\node_modules\.app-inspector_npminstall\node_modules\.1.0.36@uiautomator-client\bin\uiautomator-bootstrap.jar, please check your A
ndroid ENV
    at Logger.error (C:\Users\dell\AppData\Roaming\npm\node_modules\.app-inspector_npminstall\node_modules\.1.0.5@xlogger\lib\xlogger.js:169:9)
    at UIAutomator.init (C:\Users\dell\AppData\Roaming\npm\node_modules\.app-inspector_npminstall\node_modules\.1.0.36@uiautomator-client\lib\uiautomator-client.js:31:12)
    at next (native)

* **Operate System**:

* **Programming Language**:

**Comment by CleverPotato** [comment]
我现在升到了1.2.17刷新页面好慢

**Comment by CleverPotato** [comment]
刷不出来 一直卡着
