### ISSUE TITLE
使用UIrecorder录制ios脚本，传入app报错

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#360]
* **Macaca Version**:

* **Macaca Doctor Logs**:

```xml

macaca-doctor version: 1.0.28


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.4

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/mac/software/android-sdk-macosx`
  Platforms is set to `/Users/mac/software/android-sdk-macosx/platforms/android-24`
  Android tools is set to `/Users/mac/software/android-sdk-macosx/tools/android`
  ADB tool is set to `/Users/mac/software/android-sdk-macosx/platform-tools/adb`

  Installed driver list:

  android: 1.1.3
  chrome: 1.0.5
  electron: 1.1.4
  ios: 1.0.51

```

* **Operate System**:

* **Programming Language**:

更新为最新版的macaca及驱动后 执行uirecorder     

```xml

uirecorder start --mobile
    __  ______   ____                           __         
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /    
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.2.12

------------------------------------------------------------------

? 配置文件 config.json
? 测试脚本文件名 test.spec.js
? App路径, 扩展名: apk, app /Users/mac/software/github/macacajs/macaca-test-sample/app
/ios-app-bootstrap.app

录制服务器监听在端口: 9765
录制浏览器已开启

------------------------------------------------------------------

手机打开失败，请检查macaca是否配置正确？ Failed to install app "undefined", please install the app manually

```

录制ios脚本时候，传入app报错  

macaca日志如下 

```xml

macaca server --port 4444 --verbose
>> request.js:24:12 [master] pid:46688 get remote update info failed.
>> index.js:17:12 [master] pid:46689 webdriver server start with config:
 { port: '4444',
  verbose: true,
  always: true,
  ip: '172.31.216.80',
  host: 'mac.local',
  loaded_time: '2016-12-09 14:36:46' }
>> middlewares.js:17:10 [master] pid:46689 base middlewares attached
>> router.js:129:10 [master] pid:46689 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:46689 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","udid":"7286ffb19da8cb913b629211fad1f6c8b547ba15","app":"/Users/mac/software/github/macaca/macaca-test-sample/app/ios-app-bootstrap.app"}}
>> session.js:47:10 [master] pid:46689 Creating session, sessionId: 9590d101-6a15-48e5-8a78-c54496f7e93c.
>> helper.js:193:12 [master] pid:46689 Using local app form /Users/mac/software/github/macaca/macaca-test-sample/app/ios-app-bootstrap.app
>> macaca-ios.js:261:12 [master] pid:46689 App "undefined" is not installed.
>> macaca-ios.js:266:14 [master] pid:46689 2016-12-09 14:36:54.561 ios-deploy[46699:407780] [ !! ] Error 0xe8008014: unknown. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

>> responseHandler.js:54:12 [master] pid:46689 Send Error Respone to Client: UnknownError: Failed to install app "undefined", please install the app manually.
>> responseHandler.js:60:14 [master] pid:46689 UnknownError: Failed to install app "undefined", please install the app manually.
    at IOS.whiteList.IOS.startSafari.IOS.getSimulatorUdid.IOS.startRealDevice (/usr/local/lib/node_modules/macaca-ios/lib/macaca-ios.js:267:13)
    at throw (native)
    at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
>> responseHandler.js:76:14 [master] pid:46689 Send Bad HTTP Respone to Client: {"sessionId":"9590d101-6a15-48e5-8a78-c54496f7e93c","status":13,"value":{"message":"Failed to install app \"undefined\", please install the app manually."}}
>> responseHandler.js:11:12 [master] pid:46689 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","udid":"7286ffb19da8cb913b629211fad1f6c8b547ba15","app":"/Users/mac/software/github/macacajs/macaca-test-sample/app/ios-app-bootstrap.app"}}
>> session.js:47:10 [master] pid:46689 Creating session, sessionId: aa728f53-cd64-4868-b5e3-d65b1de1cd57.
>> helper.js:193:12 [master] pid:46689 Using local app form /Users/mac/software/github/macacajs/macaca-test-sample/app/ios-app-bootstrap.app
>> macaca-ios.js:261:12 [master] pid:46689 App "undefined" is not installed.
>> macaca-ios.js:266:14 [master] pid:46689 2016-12-09 14:37:37.753 ios-deploy[46741:408500] [ !! ] Error 0xe8008014: unknown. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

>> responseHandler.js:54:12 [master] pid:46689 Send Error Respone to Client: UnknownError: Failed to install app "undefined", please install the app manually.
>> responseHandler.js:60:14 [master] pid:46689 UnknownError: Failed to install app "undefined", please install the app manually.
    at IOS.whiteList.IOS.startSafari.IOS.getSimulatorUdid.IOS.startRealDevice (/usr/local/lib/node_modules/macaca-ios/lib/macaca-ios.js:267:13)
    at throw (native)
    at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
    at process._tickCallback (node.js:369:9)
>> responseHandler.js:76:14 [master] pid:46689 Send Bad HTTP Respone to Client: {"sessionId":"aa728f53-cd64-4868-b5e3-d65b1de1cd57","status":13,"value":{"message":"Failed to install app \"undefined\", please install the app manually."}}

```

UnknownError: Failed to install app "undefined"

**Comment by Kirkowo** [comment]
请问ios driver 是怎么装的？ npm install -g ios 吗？
