### ISSUE TITLE
启动mcaca时报错，一直循环不停的刷

### ISSUE THREAD

**Issue by ythinker** [alibaba/macaca#365]
* **Macaca Version**: 1.0.28

* **Macaca Doctor Logs**:

* **Operate System**:  Mac 10.12

* **Programming Language**: Python

启动macaca **服务时，下面报错
从 responseHandler.js 这句开始一直死循环不停的刷，昨天还好好的，今天运行的时候就这样了！

```
➜  ~ macaca server --verbose
>> index.js:17:12 [master] pid:50463 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '172.16.xx.xx',
  host: 'XXXX-3.local',
  loaded_time: '2016-12-13 10:55:22' }
>> middlewares.js:17:10 [master] pid:50463 base middlewares attached
>> router.js:129:10 [master] pid:50463 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:50463 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/a556b792-68bc-4537-9113-207d728b2adf/element, jsonBody: {"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeButton[1]"}
>> responseHandler.js:54:12 [master] pid:50463 Send Error Respone to Client: NoSuchDriver: A session is either terminated or not started
>> responseHandler.js:60:14 [master] pid:50463 NoSuchDriver: A session is either terminated or not started
    at Object.sessionAvailable (/usr/local/lib/node_modules/macaca-cli/node_modules/.1.0.68@webdriver-server/lib/server/controllers/session.js:112:11)
    at next (native)
    at Object.middleware (/usr/local/lib/node_modules/macaca-cli/node_modules/.5.4.0@koa-router/lib/layer.js:166:14)
    at next (native)
    at Object.dispatch (/usr/local/lib/node_modules/macaca-cli/node_modules/.5.4.0@koa-router/lib/router.js:336:14)
    at next (native)
    at Object.allowedMethods (/usr/local/lib/node_modules/macaca-cli/node_modules/.5.4.0@koa-router/lib/router.js:374:12)
    at next (native)
    at Object.dispatch (/usr/local/lib/node_modules/macaca-cli/node_modules/.5.4.0@koa-router/lib/router.js:336:14)
    at next (native)
>> responseHandler.js:76:14 [master] pid:50463 Send Bad HTTP Respone to Client: {"sessionId":"","status":6,"value":{"message":"A session is either terminated or not started"}}

```

**Comment by zenzhu** [comment]
看代码很奇怪啊，怎么一启动就发查找元素的请求？不是应该先启动 driver 吗

**Comment by ythinker** [comment]
对，什么都没改动，昨天还正常跑，今天一启动就挂了。。。
