### ISSUE TITLE
ios真机启动报错ios-deploy找不到问题

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#373]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

现在安装macaca-ios默认安装ios-deploy，但是启动报错，找不到ios-deploy

手工安装brew install ios-deploy之后运行就不报错了

**Comment by RexHM** [comment]
在模拟器运行的时候没有问题，在真机运行的时候，我的发生这个错误，brew install ios-deploy 安装之后就没有问题，错误提示如下：

>> responseHandler.js:54:12 [master] pid:647 Send Error Respone to Client: Error: spawn ios-deploy ENOENT
>> responseHandler.js:60:14 [master] pid:647 Error: spawn ios-deploy ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by zenzhu** [comment]
已修复 https://github.com/zenzhu/ios-device/commit/c67e9b50c36491108d537234be019f336d331767
