### ISSUE TITLE
app-inspector异常

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#381]
在获取部分页面属性时，出现如下错误：
>> inspector start at: http://192.168.1.5:5678
  <-- GET /
>> ios.js:67:10 [master] pid:19415 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
  --> GET / 200
  <-- GET /
>> ios.js:67:10 [master] pid:19415 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
  --> GET / 200
  <-- GET /
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'origin' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)
inpector版本1.2.17

**Comment by xudafeng** [comment]
请升级版本
