### ISSUE TITLE
真机测试获取不到上下文，在模拟器上正常

### ISSUE THREAD

**Issue by GeorgeZh** [alibaba/macaca#403]
Error: [contexts()] Not JSON response
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by GeorgeZh** [comment]
ios_webkit_debug_proxy path: /usr/local/bin/ios_webkit_debug_proxy
Could not connect to lockdownd. Exiting.: Permission denied

Unable to attach 0edb9cee7e8f607d7a0c9e76d6fbd7483d259eb3 inspector


  Error: Device: 0edb9cee7e8f607d7a0c9e76d6fbd7483d259eb3 does not exist.
      at request.get.then.then.devices (/usr/local/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/remote-debugger.js:47:17)
      at tryCatcher (/usr/local/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/promise.js:510:31)
      at Promise._settlePromiseAt (/usr/local/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/promise.js:584:18)
      at Promise._settlePromises (/usr/local/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/promise.js:700:14)
      at Async._drainQueue (/usr/local/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (/usr/local/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues (/usr/local/lib/node_modules/macaca-ios/node_modules/bluebird/js/main/async.js:15:14)
      at runCallback (timers.js:637:20)
      at tryOnImmediate (timers.js:610:5)
      at processImmediate [as _immediateCallback] (timers.js:582:5)

>>
>>     2) #5 should go into webview


  RequestError: Error: connect ECONNREFUSED 127.0.0.1:80
      at new RequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/request-promise/lib/errors.js:11:15)
      at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/macaca-ios/node_modules/request-promise/lib/rp.js:60:32)
      at self.callback (/usr/local/lib/node_modules/macaca-ios/node_modules/request/request.js:186:22)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.onRequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/request/request.js:845:8)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:310:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1278:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by xudafeng** [comment]
ios_webkit_debug_proxy 问题，解决掉就好
