### ISSUE TITLE
reliable-slave无法连接reliable-master

### ISSUE THREAD

**Issue by zwyxsyu** [alibaba/macaca#408]
Macaca Version: 1.1.21
Operate System:mac

mac上已经创建reliable-master并启动，同一台mac上安装reliable-slave（按照官网安装），之后，连接master和slave：reliable server -m masterip:masterport --verbose  ,之后一直报错，报下面的错，只能ctrl+c停止
错误log：
reliable-macaca-docker-compose makeblock$ reliable server -m 192.168.1.11:8080 --verbose
>> index.js:58:14 [master] pid:5138 worker fork success
>> index.js:61:14 [master] pid:5138 worker online
/usr/local/lib/node_modules/reliable-macaca-slave/core/slave/channel.js:17
    constructor(options = {}) {
                        ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/reliable-macaca-slave/core/slave/index.js:10:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
>> index.js:67:14 [master] pid:5138 worker disconnect
>> index.js:58:14 [master] pid:5138 worker fork success
>> index.js:71:14 [master] pid:5138 worker exit code: 1 signal: null
>> index.js:61:14 [master] pid:5138 worker online

**Comment by CodeToSurvive1** [comment]
这个应该是nodejs版本问题吧  没兼容低版本的node

**Comment by xudafeng** [comment]
@zwyxsyu 升级Node，看文档
