### ISSUE TITLE
ios真机测试api相关问题

### ISSUE THREAD

**Issue by GeorgeZh** [alibaba/macaca#410]
使用getComputed,getProperty,getRect,isDisplayed,waitForVisible都报这个错误，请问这意思是这些方法都还没在真机上实现吗？我理解是这样的

NotImplementedError: The method is not implemented yet.
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:79:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at runMicrotasksCallback (internal/process/next_tick.js:58:5)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by xudafeng** [comment]
@GeorgeZh 你的这些api是从哪个文档看到的？

**Comment by GeorgeZh** [comment]
就macaca官方文档https://macacajs.github.io/macaca-wd/#waitForElement，getComputedCss/getProperty/getRect/waitForVisibleByCss，在PC可以正常使用，在真机就报错了

**Comment by xudafeng** [comment]
PC和iOS当然不一样

**Comment by GeorgeZh** [comment]
可是文档上写着支持webview的，我已经切换到webview操作了，其他api都可以正常使用，我的是ios10.12

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/466
