### ISSUE TITLE
偶尔出：An unknown server-side error occurred while processing the command

### ISSUE THREAD

**Issue by wangyunshuai** [alibaba/macaca#429]
#### 自动化程序每半小时执行一次，偶尔会出现，webdriver 初始化成功了，在使用时发生下面错误。
* **Test Device**:
```Android 自带模拟器：x86_64 Nexus_5X_API_23```

* **Macaca Version**:
```1.1.21```

* **Macaca Doctor Logs**:
```
➜  ~ macaca doctor

  macaca-doctor version: 1.0.28


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/smzdm/android-sdk`
  Platforms is set to `/Users/smzdm/android-sdk/platforms/android-22`
  Android tools is set to `/Users/smzdm/android-sdk/tools/android`
  ADB tool is set to `/Users/smzdm/android-sdk/platform-tools/adb`

  Installed driver list:

  android: 1.1.15
  ios: 1.0.53
```
* **Operate System**:
`Mac OS: 10.12.1`
* **Programming Language**:
`Python`

* **macaca server --version**:
```
1/15/2017, 7:20:23 AM>> index.js:17:12 [master] pid:903 webdriver server start with config:
 { port: '3457',
  verbose: true,
  always: true,
  ip: '172.16.24.15',
  host: 'localhost',
  loaded_time: '2017-01-15 07:20:23' }
1/15/2017, 7:20:23 AM>> middlewares.js:17:10 [master] pid:903 base middlewares attached
1/15/2017, 7:20:23 AM>> router.js:127:10 [master] pid:903 router set
1/15/2017, 7:20:23 AM>> webdriver sdk launched
1/15/2017, 7:20:38 AM>> responseHandler.js:11:12 [master] pid:903 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"deviceName":"Nexus 5x","reuse":"3","package":"com.smzdm.client.android","app":"/data/AppBrowse/package/smzdm-7.4.1-smzdm_i.apk","activity":"com.smzdm.client.android/.activity.WelComeActivity","platformVersion":"6.0","platformName":"Android"}}
1/15/2017, 7:20:38 AM>> session.js:47:10 [master] pid:903 Creating session, sessionId: 59feac03-ede2-4343-bc48-cf341040de8f.
1/15/2017, 7:20:43 AM>> helper.js:208:12 [master] pid:903 Using local app form /data/AppBrowse/package/smzdm-7.4.1-smzdm_i.apk
INSTRUMENTATION_STATUS: numtests=1

INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: test=testStartServer

INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize
INSTRUMENTATION_STATUS: current=1

INSTRUMENTATION_STATUS_CODE: 1

uiautomator start socket server.

>> socket server ready
>> socket client ready
recive: {"cmd":"wake","args":{}}

return: {"success":true,"data":{"status":0,"value":true}}

1/15/2017, 7:20:59 AM>> responseHandler.js:47:14 [master] pid:903 Send HTTP Respone to Client: {"sessionId":"59feac03-ede2-4343-bc48-cf341040de8f","status":0,"value":"{\"deviceName\":\"Nexus 5x\",\"reuse\":\"3\",\"package\":\"com.smzdm.client.android\",\"app\":\"/data/AppBrowse/package/smzdm-7.4.1-smzdm_i.apk\",\"activity\":\"com.smzdm.client.android/.activity.WelComeActivity\",\"platformVersion\":\"6.0\",\"platformName\":\"Android\"}"}
>> uiautomator-client.js:70:14 [master] pid:903 connect lost
1/15/2017, 7:21:12 AM>> responseHandler.js:11:12 [master] pid:903 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/59feac03-ede2-4343-bc48-cf341040de8f/element, jsonBody: {"using":"xpath","value":"//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]"}
>> macaca-android.js:313:12 [master] pid:903 UnknownError from uiautomator Error: This socket has been ended by the other party
1/15/2017, 7:21:12 AM>> responseHandler.js:54:12 [master] pid:903 Send Error Respone to Client: UnknownError: An unknown server-side error occurred while processing the command.
1/15/2017, 7:21:12 AM>> responseHandler.js:60:14 [master] pid:903 UnknownError: An unknown server-side error occurred while processing the command.
    at Android.send (/usr/local/lib/node_modules/macaca-android/lib/macaca-android.js:314:11)
    at throw (native)
    at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/.4.6.0@co/index.js:81:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)
1/15/2017, 7:21:12 AM>> responseHandler.js:76:14 [master] pid:903 Send Bad HTTP Respone to Client: {"sessionId":"59feac03-ede2-4343-bc48-cf341040de8f","status":13,"value":{"message":"An unknown server-side error occurred while processing the command."}}
```

**Comment by xudafeng** [comment]
@wangyunshuai 跑monkey遇到的吗？

**Comment by wangyunshuai** [comment]
@xudafeng 不是monkey，是ui自动化

**Comment by xudafeng** [comment]
@wangyunshuai 现在的log很难判断，能尝试打内部模块log看下原因吗？

https://github.com/macacajs/macaca-android/blob/master/lib/macaca-android.js#L311

https://github.com/macacajs/uiautomator-client/blob/master/lib/uiautomator-client.js#L86

**Comment by wangyunshuai** [comment]
@xudafeng 对js不熟，能提示下具体如何打印吗，打印哪个内容，log输出到哪了？

**Comment by xudafeng** [comment]
@wangyunshuai 用console 打印一下

**Comment by xudafeng** [comment]
@wangyunshuai 可以提供下你的sample吗？

如 https://github.com/macaca-sample/sample-python

**Comment by wangyunshuai** [comment]
@xudafeng {可以提供下你的sample吗？}
后来我改为每次跑完后关闭 Macaca server，之后就没有再报这个错了

**Comment by xudafeng** [comment]
@wangyunshuai ok
