### ISSUE TITLE
macaca  iOS真机wda安装成功  但是测试app跑不起来

### ISSUE THREAD

**Issue by mhlee0514** [alibaba/macaca#430]
* **Macaca Version**:

 1.1.21

* **Macaca Doctor Logs**:

macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.5.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.7.0_79`
  JAVA_HOME is not set
  ANDROID_HOME is not set

  Installed driver list:

  ios: 1.0.53

* **Operate System**:
macOS 10.12.1
* **Programming Language**:
node.js   官方示例

mhleedeMacBook-Pro:mobile-app-sample-nodejs mhlee$ macaca run
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

ios-deploy
>> get /Users/mhlee/.macaca-temp/ios-app-bootstrap.zip from cache
>> sha:d2e65bba467659ef610b369f2ee599c1

  Error: spawn ios-deploy ENOENT
      at exports._errnoException (util.js:907:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
      at onErrorNT (internal/child_process.js:344:16)
      at nextTickCallbackWith2Args (node.js:442:9)
      at process._tickCallback (node.js:356:17)

>>     1) "before all" hook

>>     2) "after all" hook

>> 

>> 

>>   0 passing (2s)

>>   2 failing

>>   1) macaca mobile sample "before all" hook:
     Error: [init({"deviceName":"李明浩的 iPhone","platformName":"iOS","autoAcceptAlerts":false,"reuse":3,"udid":"1a852ed84aa0d5c542e280d885af80d9f7b5cf5d","bundleId":"xudafeng.ios-app-bootstrap","app":"https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

>> Test completed!

**Comment by Archer456** [comment]
Error: spawn ios-deploy ENOENT

请安装下 brew install ios-deploy

参考 https://testerhome.com/topics/6507
