### ISSUE TITLE
macaca运行真机测试报错

### ISSUE THREAD

**Issue by liweiyue** [alibaba/macaca#432]
连接真机进行ios测试，执行用例时报以下错误： 
错误日志：
responseHandler.js:11:12 [master] pid:1075 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"/Users/****/Documents/macaca_sample/bootstrap-master/app/*****","reuse":"1","bundleId":"*******","platformName":"iOS","udid":"*******","deviceName":"iPhone7plus"}}
>> session.js:47:10 [master] pid:1075 Creating session, sessionId: 321eda98-8e70-45fd-858c-72b47f48bf09.
>> helper.js:194:12 [master] pid:1075 Unzipping local app form /Users/****/Documents/macaca_sample/bootstrap-master/app/********.zip
>> responseHandler.js:54:12 [master] pid:1075 Send Error Respone to Client: Error: spawn ios-deploy ENOENT
>> responseHandler.js:60:14 [master] pid:1075 Error: spawn ios-deploy ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

  Error: spawn ios-deploy ENOENT
      at exports._errnoException (util.js:1022:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
      at onErrorNT (internal/child_process.js:359:16)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

环境：
macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.4

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/opt/android-sdk`
  Platforms is set to `/usr/local/opt/android-sdk/platforms/android-23`
  Android tools is set to `/usr/local/opt/android-sdk/tools/android`
  ADB tool is set to `/usr/local/opt/android-sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.53

请帮助，谢谢

**Comment by xudafeng** [comment]
@liweiyue 到社区去解决
