### ISSUE TITLE
安装安卓驱动时，提示以下错误，能帮忙看下什么原因吗？

### ISSUE THREAD

**Issue by linlin547** [alibaba/macaca#438]
Total time: 1 second
Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/script/build.js:15
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "macaca-android" "-g"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! android-unicode@1.0.9 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the android-unicode@1.0.9 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the android-unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs android-unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls android-unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/cnpm/npm-debug.log

**Comment by xudafeng** [comment]
macaca doctor 看下

**Comment by linlin547** [comment]
问题解决了，我的环境问题，谢谢你
