### ISSUE TITLE
Ubuntu 16.10 运行安卓APP测试报错

### ISSUE THREAD

**Issue by zjhiphop** [alibaba/macaca#442]
* **Macaca Version**:
1.1.21
* **Macaca Doctor Logs**:
```
➜  mobile-app-sample-nodejs git:(master) ✗ macaca doctor

  macaca-doctor version: 1.0.28


  Node.js checklist:

  node env: /usr/bin/node
  node version: v4.2.6

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/usr/lib/jvm/jdk1.8.0_121`
  ANDROID_HOME is set to `/home/jade/Android/Sdk`
  Platforms is set to `/home/jade/Android/Sdk/platforms/android-24`
  Android tools is set to `/home/jade/Android/Sdk/tools/android`
  ADB tool is set to `/home/jade/Android/Sdk/platform-tools/adb`

  Installed driver list:
```
* **Operate System**:
Platform: Linux jade-H81M-DS2 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* **Programming Language**:
NodeJS

* **Run android test details**:
```
➜  mobile-app-sample-nodejs git:(master) ✗ make test-android
macaca doctor

  macaca-doctor version: 1.0.28


  Node.js checklist:

  node env: /usr/bin/node
  node version: v4.2.6

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/usr/lib/jvm/jdk1.8.0_121`
  ANDROID_HOME is set to `/home/jade/Android/Sdk`
  Platforms is set to `/home/jade/Android/Sdk/platforms/android-24`
  Android tools is set to `/home/jade/Android/Sdk/tools/android`
  ADB tool is set to `/home/jade/Android/Sdk/platform-tools/adb`

  Installed driver list:



platform=android macaca run --verbose -d ./macaca-test/mobile-app-sample.test.js
>> request.js:24:12 [master] pid:5134 get remote update info failed.
>> port: 3456 was occupied, changed port: 33753
>> index.js:17:12 [master] pid:5139 webdriver server start with config:
 { port: 33753,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.1.112',
  host: 'jade-H81M-DS2',
  loaded_time: '2017-02-09 16:26:47' }
>> middlewares.js:17:10 [master] pid:5139 base middlewares attached
>> router.js:127:10 [master] pid:5139 router set
>> webdriver sdk launched
[ '/home/jade/workspace/mobile-app-sample-nodejs/node_modules/.bin/mocha',
  './macaca-test/mobile-app-sample.test.js',
  '--colors',
  '--verbose' ]
>> 

>> 

>>   macaca mobile sample

>>     1) "before all" hook

>>     2) "after all" hook

>> 

>> 

>>   0 passing (1s)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     Error: [init({"platformName":"Android","autoAcceptAlerts":false,"app":"https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk"})] Invalid protocol: 127.0.0.1:
      at Request.init (node_modules/macaca-wd/node_modules/request/request.js:640:31)
      at new Request (node_modules/macaca-wd/node_modules/request/request.js:272:8)
      at request (node_modules/macaca-wd/node_modules/request/index.js:56:10)
      at Object.requestWithRetry (node_modules/macaca-wd/wd/lib/http-utils.js:74:3)
      at Webdriver._init (node_modules/macaca-wd/wd/lib/webdriver.js:104:13)
      at commands.init (node_modules/macaca-wd/wd/lib/commands.js:34:14)
      at Webdriver.(anonymous function) [as init] (node_modules/macaca-wd/wd/lib/webdriver.js:230:15)
      at null.init (node_modules/macaca-wd/wd/lib/promise-webdriver.js:60:10)
      at Context.<anonymous> (macaca-test/mobile-app-sample.test.js:67:8)


>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Invalid protocol: 127.0.0.1:
      at Request.init (node_modules/macaca-wd/node_modules/request/request.js:640:31)
      at new Request (node_modules/macaca-wd/node_modules/request/request.js:272:8)
      at request (node_modules/macaca-wd/node_modules/request/index.js:56:10)
      at Object.requestWithRetry (node_modules/macaca-wd/wd/lib/http-utils.js:74:3)
      at Webdriver._jsonWireCall (node_modules/macaca-wd/wd/lib/webdriver.js:176:13)
      at commands.quit (node_modules/macaca-wd/wd/lib/commands.js:484:8)
      at Webdriver.(anonymous function) [as quit] (node_modules/macaca-wd/wd/lib/webdriver.js:230:15)
      at null.quit (node_modules/macaca-wd/wd/lib/promise-webdriver.js:60:10)
      at node_modules/macaca-wd/wd/lib/promise-webdriver.js:196:35
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)



>> 

>> Test completed!
Makefile:16: recipe for target 'test-android' failed
make: *** [test-android] Error 2
```

**Comment by xudafeng** [comment]
示例apk是否下载成功？

**Comment by xudafeng** [comment]
@zjhiphop 试试小马合集？ https://testerhome.com/wiki/macaca
