### ISSUE TITLE
Travis CI环境中出现client连接不稳定,socket超时的情况

### ISSUE THREAD

**Issue by sospartan** [alibaba/macaca#447]
在travis中运行，使用的是android-19 arm v7a的模拟器(巨慢无比，但虚拟环境中也没有其他选择）。
根据日志看到的情况是，第一个test执行完后，出现`connect lost`的情况：
```
...
>> responseHandler.js:47:14 [master] pid:7416 Send HTTP Respone to Client: {"sessionId":"9bb8884f-b769-49fd-9c1e-2b5b98b47d40","status":0,"value":"{\"description\":\"-1012.5\"}"}
    ✓ #1 Drag list (15398ms)

  scroller scroll event

>> responseHandler.js:11:12 [master] pid:7416 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"Android","app":"/Users/travis/build/sospartan/weex/android/playground/app/build/outputs/apk/playground.apk","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:7416 Creating session, sessionId: 6cf39a61-f237-4247-983c-91e804c424af.
>> helper.js:208:12 [master] pid:7416 Using local app form /Users/travis/build/sospartan/weex/android/playground/app/build/outputs/apk/playground.apk
>> uiautomator-client.js:70:14 [master] pid:7416 connect lost
INSTRUMENTATION_STATUS: numtests=1
...
```
更多日志见：https://travis-ci.org/sospartan/weex/builds/201770556
出现connect lost后，会自动进行重试，[有时候能成功](https://travis-ci.org/sospartan/weex/builds/201775856)，[有时候失败](https://travis-ci.org/sospartan/weex/builds/201770556)

**Comment by sospartan** [comment]
还有另外一个`ESOCKETTIMEDOUT`,出现的概率也很高，在`init`,或者`elements`调用时。

这是ios在`init`时报的错：

```
   1) list scroll event "before all" hook:
     Error: [init({"autoAcceptAlerts":true,"platformName":"iOS","deviceName":"iPhone 6","slowEnv":true,"app":"/Users/travis/build/alibaba/weex/ios/playground/build/Debug-iphonesimulator/WeexDemo.app"})] ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:984:19)
      at Socket.socket.once (_http_client.js:565:38)
      at Socket._onTimeout (net.js:342:8)
```

**Comment by xudafeng** [comment]
InternalServerError: Internal Server Error
      at Object.throw (/Users/travis/.nvm/versions/node/v7.0.0/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/Users/travis/.nvm/versions/node/v7.0.0/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:57:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/Users/travis/.nvm/versions/node/v7.0.0/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by xudafeng** [comment]
https://travis-ci.org/apache/incubator-weex/jobs/207325502#L3716

**Comment by xudafeng** [comment]
https://travis-ci.org/apache/incubator-weex/jobs/208696695
