### ISSUE TITLE
quit() method not closing browser (WEB)

### ISSUE THREAD

**Issue by sachinGirish** [alibaba/macaca#453]
Platform:  Windows,  64-bit.

macaca-doctor version: 1.0.28

 Node.js checklist:

 node env: C:\moolya\nodejs\node.exe
 node version: v7.2.1

 Android checklist:

 JAVA version is `1.8.0_101`
 JAVA_HOME is set to `C:\Program Files\Java\jre1.8.0_101`
 ANDROID_HOME is set to `C:\ADB\sdk`
 Platforms is set to `C:\ADB\sdk\platforms\android-23`
 Android tools is set to `C:\ADB\sdk\tools\android.bat`
 ADB tool is set to `C:\ADB\sdk\platform-tools\adb.exe`
 ANT_HOME is set to `C:\apache-ant-1.9.6-bin\apache-ant-1.9.6\bin`

 Installed driver list:

 android: 1.1.15 [out-of-date]
 chrome: 1.0.5
 electron: 1.1.5

>> responseHandler.js:11:12 [master] pid:5580 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/758bd8c0-64a5-42d1-913a-f969ff2495ff/window/current/maximize, jsonBody: {}
>> proxy.js:52:14 [master] pid:5580 Proxy: /wd/hub/session/758bd8c0-64a5-42d1-913a-f969ff2495ff/window/current/maximize:POST to http://localhost:9515/wd/hub/session/910dca148c5ea5bbcef20b37dfcfc099/window/current/maximize:POST with body: {}
>> responseHandler.js:11:12 [master] pid:5580 Recieve HTTP Request from Client: method: GET url: /wd/hub/sessions, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:5580 Send HTTP Respone to Client: {"sessionId":"","status":0,"value":"[{\"id\":\"758bd8c0-64a5-42d1-913a-f969ff2495ff\"}]"}
>> responseHandler.js:11:12 [master] pid:5580 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/758bd8c0-64a5-42d1-913a-f969ff2495ff, jsonBody: {}
>> responseHandler.js:54:12 [master] pid:5580 Send Error Respone to Client: Error: chromedriver proxy error with: Error: read ECONNRESET
>> responseHandler.js:60:14 [master] pid:5580 Error: chromedriver proxy error with: Error: read ECONNRESET
    at Request.request [as _callback] (C:\Users\Sachin-PC\AppData\Roaming\npm\node_modules\macaca-chrome\node_modules\macaca-chromedriver\lib\proxy.js:56:25)
    at self.callback (C:\Users\Sachin-PC\AppData\Roaming\npm\node_modules\macaca-chrome\node_modules\request\request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\Sachin-PC\AppData\Roaming\npm\node_modules\macaca-chrome\node_modules\request\request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

  Error: chromedriver proxy error with: Error: read ECONNRESET
      at Request.request [as _callback] (C:\Users\Sachin-PC\AppData\Roaming\npm\node_modules\macaca-chrome\node_modules\macaca-chromedriver\lib\proxy.js:56:25)
      at self.callback (C:\Users\Sachin-PC\AppData\Roaming\npm\node_modules\macaca-chrome\node_modules\request\request.js:199:22)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.onRequestError (C:\Users\Sachin-PC\AppData\Roaming\npm\node_modules\macaca-chrome\node_modules\request\request.js:821:8)

**Comment by xudafeng** [comment]
reinstall macaca-chrome
