### ISSUE TITLE
获取页面元素时报：TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by cattywei** [alibaba/macaca#477]
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'x' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by xudafeng** [comment]
更细最新版
