### ISSUE TITLE
微信朋友圈出现emoji表情时，调用elementsByXPath会报错.

### ISSUE THREAD

**Issue by whitiancai** [alibaba/macaca#493]
* **Macaca Version**:1.20

* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: H:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `D:\sdk`
  Platforms is set to `D:\sdk\platforms\android-24`
  Android tools is set to `D:\sdk\tools\android.bat`
  ADB tool is set to `D:\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `H:\apache-ant-1.9.6`

  Installed driver list:

  android: 1.1.27 [out-of-date]
  chrome: 1.0.5

* **Operate System**:win7 64bit

* **Programming Language**:nodejs

在三星s4,5.0版本上，微信朋友圈出现emoji表情时，调用elementsByXPath会报错。
当前XmlSerializer类不支持emoji，求解决。

>> recive: {"cmd":"find","args":{"strategy":"xpath","selector":"//android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.FrameLayout[2]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.ListView[1]/android.widget.LinearLayout","multiple":true}}

>> java.lang.IllegalArgumentException: Illegal character (d83d)

>> 	at org.kxml2.io.KXmlSerializer.reportInvalidCharacter(KXmlSerializer.java:144)
	at org.kxml2.io.KXmlSerializer.writeEscaped(KXmlSerializer.java:130)
	at org.kxml2.io.KXmlSerializer.attribute(KXmlSerializer.java:465)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:101)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)

>> 
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at 
com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)

>> 
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:127)
	at com.android.uiautomator.client.xmlUtils.AccessibilityNodeInfoDumper.getWindowXMLHierarchy(AccessibilityNodeInfoDumper.java:78)
	at com.android.uiautomator.client.xmlUtils.XmlUtils.getUiXmlHierarchyFromAndroid(XmlUtils.java:89)
	at com.android.uiautomator.client.xmlUtils.XmlUtils.getSelectors(XmlUtils.java:37)
	at com.android.uiautomator.client.cmd.Find.getSelectors(Find.java:121)
	at com.android.uiautomator.client.cmd.Find.execute(Find.java:38)
	at com.android.uiautomator.client.Command.handleInput(Command.java:51)
	at 

>> com.android.uiautomator.client.SocketServer.listen(SocketServer.java:60)
	at com.android.uiautomator.client.Initialize.testStartServer(Initialize.java:28)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:115)
	at 

>> junit.framework.TestResult.runProtected(TestResult.java:133)
	at junit.framework.TestResult.run(TestResult.java:118)
	at junit.framework.TestCase.run(TestCase.java:124)
	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
	at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
	at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:255)
return: {"success":true,"data":{"status":32,"value":"Argument was an invalid selector (e.g. XPath\/CSS)."}}

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/commit/622142f5cf2848d8759562b37f1e92325eb3448d
