### ISSUE TITLE
app-inspector报错，WebDriverAgent没有正常解压

### ISSUE THREAD

**Issue by magaofei** [alibaba/macaca#497]
```shell
app-inspector -u 'xxxxx' --verbose
```

```shell

>> request.js:24:12 [master] pid:13140 get remote update info failed.
>> server.js:16:12 [master] pid:13140 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'b43c63aac03fb48c3b40fd3cf886ad30bef9f73f',
  ip: '10.1.29.224',
  host: 'localhost',
  loaded_time: '2017-03-30 14:55:07' }
>> app-inspector.js:42:10 [master] pid:13140 server start at: http://10.1.29.224:5678
>> xctest-client.js:58:14 [master] pid:13140 project path not found
>> app-inspector:66:44 [master] pid:13140 Error: >> xctest-client.js:58:14 [master] pid:13140 project path not found
    at Logger.error (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.6@xlogger/lib/xlogger.js:169:9)
    at XCTest.checkProjectPath (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.30@xctest-client/lib/xctest-client.js:58:14)
    at XCTest.init (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.30@xctest-client/lib/xctest-client.js:51:10)
    at XCTest (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.30@xctest-client/lib/xctest-client.js:39:10)
    at Object.exports.initDevice (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.20@app-inspector/lib/ios.js:90:12)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:54:5
    at co (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:118:63)
(node:13140) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: >> app-inspector:66:44 [master] pid:13140 Error: >> xctest-client.js:58:14 [master] pid:13140 project path not found
    at Logger.error (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.6@xlogger/lib/xlogger.js:169:9)
    at XCTest.checkProjectPath (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.30@xctest-client/lib/xctest-client.js:58:14)
    at XCTest.init (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.30@xctest-client/lib/xctest-client.js:51:10)
    at XCTest (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.30@xctest-client/lib/xctest-client.js:39:10)
    at Object.exports.initDevice (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.20@app-inspector/lib/ios.js:90:12)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:54:5
    at co (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:118:63)
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200

```

```shell
app-inspector -v

 1.2.20
```

**Comment by magaofei** [comment]
我自己手动找到 `/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.44@webdriveragent` 这个目录，发现WebDriverAgent.zip， 自己解压后可以了

**Comment by xudafeng** [comment]
@magaofei 可以查查你那边为什么解压失败的原因吗?

**Comment by magaofei** [comment]
不知道怎么查😢

**Comment by magaofei** [comment]
@xudafeng 今天安装新版本的`app-inspector`时又遇到了这个情况，我把日志贴上来
```shell
MAMIAN at MarkMBP.lan in [~/GitHub/Downloads/tester/WebDriverAgent]  on git:master ✗  6a9d218 "Add capability to set typing speed"
18:18:53 › cnpm install -g app-inspector
⠼ Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.44@webdriveragent/WebDriverAgent'
    at Error (native)
npminstall version: 2.10.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/Users/MAMIAN/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org -g app-inspector

MAMIAN at MarkMBP.lan in [~/GitHub/Downloads/tester/WebDriverAgent]  on git:master ✗  6a9d218 "Add capability to set typing speed"
18:19:04 › cnpm i -g app-inspector
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home
The android command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.9@uiautomator-client/scripts/build.js:177
      throw e;
      ^

Error: setup failed
    at ChildProcess.createProcess.on.code (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.9@uiautomator-client/scripts/build.js:133:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
app-inspector@1.2.23 › uiautomator-client@1.1.9 optional error: Error: Run "sh -c node ./scripts/build.js" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
deprecate app-inspector@1.2.23 › xutil@1.0.3 › node-uuid@1.4.8 Use uuid module instead
deprecate app-inspector@1.2.23 › xctest-client@1.1.0 › request@2.69.0 › tough-cookie@2.2.2 ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
deprecate app-inspector@1.2.23 › uiautomator-client@1.1.9 › win-spawn@2.0.0 use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
deprecate app-inspector@1.2.23 › webdriveragent@1.1.4 › xcode@0.8.9 › node-uuid@1.4.7 Use uuid module instead
✔ All packages installed (255 packages installed from npm registry, use 9s, speed 350.83kB/s, json 293(469.91kB), tarball 2.77MB)
Recently updated (since 2017-03-28): 8 packages (detail see file node_modules/.recently_updates.txt)

MAMIAN at MarkMBP.lan in [~/GitHub/Downloads/tester/WebDriverAgent]  on git:master ✗  6a9d218 "Add capability to set typing speed"
18:19:42 › app-inspector

  Usage: app-inspector [options]

  Options:

    -h, --help      output usage information
    -p, --port <d>  port to use (5678 default)
    -u, --udid <s>  udid of device
    -s, --silent    start without opening browser
    --verbose       show more debugging information
    -v, --versions  output version infomation


MAMIAN at MarkMBP.lan in [~/GitHub/Downloads/tester/WebDriverAgent]  on git:master ✗  6a9d218 "Add capability to set typing speed"
18:19:49 › app-inspector -u npm i -g app-inspec
^C

MAMIAN at MarkMBP.lan in [~/GitHub/Downloads/tester/WebDriverAgent]  on git:master ✗  6a9d218 "Add capability to set typing speed"
18:20:01 › app-inspector -u 4fde6542011bd1a001a41edac73f0e492af603b4
>> xctest-client.js:58:14 [master] pid:75073 project path not found
>> app-inspector:66:44 [master] pid:75073 Error: >> xctest-client.js:58:14 [master] pid:75073 project path not found
    at Logger.error (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.6@xlogger/lib/xlogger.js:169:9)
    at XCTest.checkProjectPath (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.0@xctest-client/lib/xctest-client.js:58:14)
    at XCTest.init (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.0@xctest-client/lib/xctest-client.js:51:10)
    at XCTest (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.0@xctest-client/lib/xctest-client.js:39:10)
    at Object.exports.initDevice (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.23@app-inspector/lib/ios.js:90:12)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:54:5
    at co (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:118:63)
(node:75073) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: >> app-inspector:66:44 [master] pid:75073 Error: >> xctest-client.js:58:14 [master] pid:75073 project path not found
    at Logger.error (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.6@xlogger/lib/xlogger.js:169:9)
    at XCTest.checkProjectPath (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.0@xctest-client/lib/xctest-client.js:58:14)
    at XCTest.init (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.0@xctest-client/lib/xctest-client.js:51:10)
    at XCTest (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.0@xctest-client/lib/xctest-client.js:39:10)
    at Object.exports.initDevice (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.23@app-inspector/lib/ios.js:90:12)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:54:5
    at co (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:118:63)

```
