### ISSUE TITLE
app-inspector报错

### ISSUE THREAD

**Issue by jaychang1989** [alibaba/macaca#499]
安装报错log 
```
C:\Users\Administrator>npm uninstall -g app-inspector
unbuild app-inspector@1.2.22

C:\Users\Administrator>npm install -g app-inspector
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm WARN optional dep failed, continuing fsevents@1.1.1
/
> uiautomator-client@1.1.9 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomator-client
> node ./scripts/build.js

JAVA_HOME is set to D:\Program Files\Java\jdk1.8.0_25
**************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools\bin\sdkmanager.bat
and tools\bin\avdmanager.bat
**************************************************************************

Invalid or unsupported command "create uitest-project -n uiautomator-bootstrap -t android-24 -p ."

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomator-client\scripts\build.js:177
      throw e;
      ^

Error: setup failed
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomator-client\scripts\build.js:133:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm WARN optional dep failed, continuing uiautomator-client@1.1.9
\
> webdriveragent@1.1.2 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector\node_modules\webdriveragent
> node ./scripts/install.js

Successfully updated Bundle Id, but no Team Id was provided. Please update your team id manually in C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector\node_modules\webdriveragent\WebDriverAgent\WebDriverAgent.xcodeproj\project.pbxproj, or reinstall the module with DEVELOPMENT_TEAM_ID in environment variable.
C:\Users\Administrator\AppData\Roaming\npm\inspector -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector\bin\app-inspector
C:\Users\Administrator\AppData\Roaming\npm\app-inspector -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector\bin\app-inspector
app-inspector@1.2.22 C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector
├── co@4.6.0
├── co-request@1.0.0
├── xlogger@1.0.6
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── npm-update@1.0.5 (co-request@0.2.1)
├── macaca-adb@1.0.22 (macaca-utils@0.1.9)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── koa-router@5.4.1 (methods@1.1.2, path-to-regexp@1.7.0, http-errors@1.6.1, debug@2.6.3)
├── detect-port@1.1.1 (debug@2.6.3)
├── ios-utils@1.0.4 (bplist-parser@0.1.1)
├── koa@1.4.0 (error-inject@1.0.0, escape-html@1.0.3, koa-compose@2.5.1, destroy@1.0.4, koa-is-json@1.0.0, content-type@1.0.2, vary@1.1.1, content-disposition@0.5.2, parseurl@1.3.1, fresh@0.3.0, only@0.0.2, statuses@1.3.1, delegates@1.0.0, on-finished@2.3.0, type-is@1.6.14, http-errors@1.6.1, mime-types@2.1.15, accepts@1.3.3, cookies@0.7.0, debug@2.6.3, http-assert@1.2.0, composition@2.3.0)
├── xml2map@1.0.2 (xml-writer@1.7.0, sax@0.4.2)
├── koa-bodyparser@2.5.0 (copy-to@2.0.1, co-body@5.1.1)
├── koa-static@2.1.0 (debug@2.6.3, koa-send@3.3.0)
├── nunjucks@2.5.2 (asap@2.0.5, yargs@3.32.0, chokidar@1.6.1)
├── request@2.81.0 (aws-sign2@0.6.0, tunnel-agent@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, caseless@0.12.0, is-typedarray@1.0.0, stringstream@0.0.5, safe-buffer@5.0.1, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, performance-now@0.2.0, uuid@3.0.1, qs@6.4.0, combined-stream@1.0.5, mime-types@2.1.15, tough-cookie@2.3.2, form-data@2.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@4.2.1)
├── xutil@1.0.3 (ipv4@0.0.4, node-uuid@1.4.8, mkdirp@0.5.1, rimraf@2.5.4, moment@2.10.6, lodash@3.10.1)
├── ios-simulator@1.0.10 (plist@1.2.0)
├── xctest-client@1.1.0 (macaca-utils@0.1.9, webdriver-dfn-error-code@1.0.4, ios-deviceconsole@1.0.1, request@2.69.0)
└── webdriveragent@1.1.2 (adm-zip@0.4.7, xcode@0.8.9)
```

* **Macaca Version**:
1.2.0

* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: D:\Program Files\nodejs\node.exe
  node version: v4.5.0

  Android checklist:

  JAVA version is `1.8.0_25`
  JAVA_HOME is set to `D:\Program Files\Java\jdk1.8.0_25`
  ANDROID_HOME is set to `D:\Android\sdk`
  Platforms is set to `D:\Android\sdk\platforms\android-24`
  Android tools is set to `D:\Android\sdk\tools\android.bat`
  ADB tool is set to `D:\Android\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `D:\Program Files (x86)\apache-ant-1.9.7`

  Installed driver list:

  android: 1.1.34
  chrome: 1.0.5
  electron: 1.1.6

* **Operate System**:
window10 64-bit

**Comment by jaychang1989** [comment]
启动报错log
```
C:\Users\Administrator>app-inspector -u 80QBDNN235U9 --verbose
>> server.js:16:12 [master] pid:51576 server start with config:
 { port: 5678,
  verbose: true,
  udid: '80QBDNN235U9',
  ip: '192.168.16.122',
  host: 'SKY-20160709E86',
  loaded_time: '2017-04-01 10:43:53' }
>> app-inspector.js:42:10 [master] pid:51576 server start at: http://192.168.16.122:5678
>> app-inspector:66:44 [master] pid:51576 Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\Android\sdk/platform-tools/adb -s 80QBDNN235U9 push C:\Users\Administrator\node_modules\.1.0.34@uiautomator-client\bin\uiautomator-bootstrap.jar /data/local/tmp"

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by xudafeng** [comment]
https://travis-ci.org/macacajs/app-inspector/builds @jaychang1989 检查下环境
