### ISSUE TITLE
make test-android error

### ISSUE THREAD

**Issue by fhqfhvtx** [alibaba/macaca#50]
* **Macaca Version**:
 1.0.24

* **Macaca Doctor**:
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v4.4.4

  Android checklist:
  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/usr/java/jdk1.8.0_91`
  ANDROID_HOME is set to `/home/zsmarter/.linuxbrew/opt/android-sdk`

* **Platform**:
 centos 6 64bit

* **command**
macaca test-android

* **npm-debug.log**
[npm-debug.zip](https://github.com/alibaba/macaca/files/260968/npm-debug.zip)

* **error info**

`npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-android/node_modules/unlock-apk/script/build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-android/node_modules/unlock-apk/node_modules/ant-build/lib/ant-build.js:98:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! Linux 2.6.32-358.el6.x86_64
npm ERR! argv "/usr/local/node-v4.4.4-linux-x64/bin/node" "/usr/local/bin/npm" "install" "macaca-android" "--registry=https://registry.npmjs.org/"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! unlock-apk@0.1.13 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unlock-apk@0.1.13 install script 'node ./script/build.js'.
npm ERR! This is most likely a problem with the unlock-apk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unlock-apk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls unlock-apk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/npm-debug.log

npm install exited with code 1 and signal null
install macaca-android failed with Error: npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-android/node_modules/unlock-apk/script/build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-android/node_modules/unlock-apk/node_modules/ant-build/lib/ant-build.js:98:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! Linux 2.6.32-358.el6.x86_64
npm ERR! argv "/usr/local/node-v4.4.4-linux-x64/bin/node" "/usr/local/bin/npm" "install" "macaca-android" "--registry=https://registry.npmjs.org/"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! unlock-apk@0.1.13 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unlock-apk@0.1.13 install script 'node ./script/build.js'.
npm ERR! This is most likely a problem with the unlock-apk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unlock-apk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls unlock-apk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/npm-debug.log

>> responseHandler.js:63:12 [master] pid:17860 Send Error Respone to Client: TypeError: Android is not a function
>> responseHandler.js:69:14 [master] pid:17860 TypeError: Android is not a function
    at WebdriverServer.detectDevice (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:62:14)
    at WebdriverServer.start (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:40:22)
    at next (native)
    at onFulfilled (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at /usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
    at /usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5

  TypeError: Android is not a function
      at WebdriverServer.detectDevice (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:62:14)
      at WebdriverServer.start (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:40:22)
      at next (native)
      at onFulfilled (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at /usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
      at /usr/local/node-v4.4.4-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5

>> 
>>     1) "before all" hook

>> responseHandler.js:24:12 [master] pid:17860 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:32:14 [master] pid:17860 Send HTTP Respone to Client: 405 Method Not Allowed
>> 
>>     2) "after all" hook

>> 

>> 

>>   0 passing (1m)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     [init({"autoAcceptAlerts":true,"platformName":"Android","app":"/home/zsmarter/works/macaca-test-sample/app/android-app-bootstrap.zip"})] The environment you requested was unavailable.
  Error: [init({"autoAcceptAlerts":true,"platformName":"Android","app":"app/android-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)
`

**Comment by xudafeng** [comment]
@fhqfhvtx  请重新安装 macaca-cli 运行 macaca doctor

**Comment by xudafeng** [comment]
#52

**Comment by xudafeng** [comment]
#62
