### ISSUE TITLE
App-inspector does not start after iOS 10.3, xCode 8.3 update. 

### ISSUE THREAD

**Issue by freddy2** [alibaba/macaca#504]
Last Friday I updated to iOS 10.0 and xCode 8.3. I am testing with an iPhone SE.  Last Friday I tried too run app-inspector and had to update to 1.2.22 and it didn't work. Today I see 1.2.23 and still not working. 

I uninstalled and reinstalled app-inspector. Go to xCode and reset team names for web driver agent, etc.  Run app inspector, install web driver on iPhone, launches web driver, seems to wait about 10-15 seconds and about the time I expect to see safari launch I get an error. 

>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.1.4
>> app-inspector:66:44 [master] pid:7826 Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(node:7826) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:7826 Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(node:7826) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I went back and updated node and everything else to make sure all are up-to-date. Same.

**Comment by freddy2** [comment]
moving
