### ISSUE TITLE
error with win7 x64（chrome desktop）

### ISSUE THREAD

**Issue by p2227** [alibaba/macaca#507]
* **Chrome Version**: win7: 57.0.2987.133, mac: 56

* **Macaca Version**:1.2.0

* **Macaca Doctor Logs**:
 macaca-doctor version: 1.0.28

 Node.js checklist:
```
 node env: C:\Program Files\nodejs\node.exe
 node version: v6.10.0

 Android checklist:

 JAVA version get not found
 JAVA_HOME is not set
 ANDROID_HOME is not set
 ANT_HOME is not set

 Installed driver list:

 chrome: 1.0.5
 electron: 1.1.6
```

* **Operate System**:
win7 x64

* **Programming Language**:
nodejs

```
E:\Program\git\macaca\sample-nodejs>set browser=chrome

E:\Program\git\macaca\sample-nodejs> node_modules\.bin\macaca run --verbose -d .
/macaca-test/desktop-browser-sample.test.js
>> index.js:17:12 [master] pid:2136 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '10.20.7.236',
  host: 'user-PC',
  loaded_time: '2017-04-05 21:06:27' }
>> middlewares.js:17:10 [master] pid:2136 base middlewares attached
>> router.js:127:10 [master] pid:2136 router set
>> webdriver sdk launched
[ './macaca-test/desktop-browser-sample.test.js',
  '--colors',
  '--verbose' ]
>>

>>

>>   macaca desktop sample

>> responseHandler.js:11:12 [master] pid:2136 Recieve HTTP Request from Client:
method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformNa
me":"desktop","browserName":"chrome","version":"","javascriptEnabled":true,"plat
form":"ANY"}}
>> session.js:47:10 [master] pid:2136 Creating session, sessionId: e753e7de-6cfc
-4e1e-8441-1048a465cbc5.
>> chromedriver bin path: E:\Program\git\macaca\sample-nodejs\node_modules\macac
a-chromedriver\exec\chromedriver.exe
>> Starting ChromeDriver 2.29.461591 (62ebf098771772160f391d75e589dc567915b233)
on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:52:14 [master] pid:2136 Proxy: /status:GET to http://localhost:9515/
wd/hub/status:GET with body:
>> proxy.js:58:16 [master] pid:2136 Got response with status 404: "unknown comma
nd: wd/hub/status"
>> proxy.js:64:20 [master] pid:2136 Fail to parse body: SyntaxError: Unexpected
token u in JSON at position 0
>> proxy.js:52:14 [master] pid:2136 Proxy: /session:POST to http://localhost:951
5/wd/hub/session:POST with body: {"desiredCapabilities":{"platformName":"desktop
","browserName":"chrome","version":"","javascriptEnabled":true,"platform":"ANY",
"show":true}}
>> proxy.js:58:16 [master] pid:2136 Got response with status 404: "unknown comma
nd: wd/hub/session"
>> proxy.js:64:20 [master] pid:2136 Fail to parse body: SyntaxError: Unexpected
token u in JSON at position 0
>> chromedriver ready with: "unknown command: wd/hub/session"
>> responseHandler.js:47:14 [master] pid:2136 Send HTTP Respone to Client: {"ses
sionId":"e753e7de-6cfc-4e1e-8441-1048a465cbc5","status":0,"value":"{\"platformNa
me\":\"desktop\",\"browserName\":\"chrome\",\"version\":\"\",\"javascriptEnabled
\":true,\"platform\":\"ANY\",\"show\":true}"}
>> responseHandler.js:11:12 [master] pid:2136 Recieve HTTP Request from Client:
method: POST url: /wd/hub/session/e753e7de-6cfc-4e1e-8441-1048a465cbc5/window/cu
rrent/size, jsonBody: {"width":1280,"height":800}
>> proxy.js:52:14 [master] pid:2136 Proxy: /wd/hub/session/e753e7de-6cfc-4e1e-84
41-1048a465cbc5/window/current/size:POST to http://localhost:9515/wd/hub/wd/hub/
session/e753e7de-6cfc-4e1e-8441-1048a465cbc5/window/current/size:POST with body:
 {"width":1280,"height":800}
>> proxy.js:58:16 [master] pid:2136 Got response with status 404: "unknown comma
nd: wd/hub/wd/hub/session/e753e7de-6cfc-4e1e-8441-1048a465cbc5/window/current/si
ze"
>> proxy.js:64:20 [master] pid:2136 Fail to parse body: SyntaxError: Unexpected
token u in JSON at position 0
>> session.js:107:14 [master] pid:2136 Send HTTP Respone to Client: "unknown com
mand: wd/hub/wd/hub/session/e753e7de-6cfc-4e1e-8441-1048a465cbc5/window/current/
size"
>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:2136 Recieve HTTP Request from Client:
method: DELETE url: /wd/hub/session/e753e7de-6cfc-4e1e-8441-1048a465cbc5, jsonBo
dy: {}
>> macaca-chromedriver.js:123:18 [master] pid:2136 chromedriver exit with code:
null, signal: SIGTERM
>> session.js:80:12 [master] pid:2136 Delete session, sessionId: e753e7de-6cfc-4
e1e-8441-1048a465cbc5
>> responseHandler.js:47:14 [master] pid:2136 Send HTTP Respone to Client: {"ses
sionId":"e753e7de-6cfc-4e1e-8441-1048a465cbc5","status":0}
>>

>>
  0 passing (353ms)
  1 failing

  1) macaca desktop sample "before all" hook:
     Error: [setWindowSize(1280,800)] Unexpected data in simpleCallback.
      at exports.newError (node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at node_modules\macaca-wd\wd\lib\callbacks.js:42:12
      at node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (node_modules\macaca-wd\node_modules\request\requ
est.js:368:22)
      at Request.<anonymous> (node_modules\macaca-wd\node_modules\request\reques
t.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules\macaca-wd\node_modules\reques
t\request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)




>> Test completed!
```

在window的机器上可以运行electron

按照这个issue的说明，升级了chromedriver的版本之后 
https://github.com/alibaba/macaca/issues/266
mac 的机器也能跑了，就是win7 x64的机器运行不了，报上面的错。

**Comment by xudafeng** [comment]
chromedriver升级到最新版，或者使用其它驱动
