### ISSUE TITLE
Linux 系统运行 chrome 兼容问题

### ISSUE THREAD

**Issue by yuxinwei** [alibaba/macaca#52]
1) macaca desktop sample "before all" hook:
     Error: [init({"autoAcceptAlerts":true,"browserName":"electron","platformName":"desktop"})] The environment you requested was unavailable.
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

  2) macaca desktop sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

**Comment by xudafeng** [comment]
环境信息呢？log也不全啊

**Comment by yuxinwei** [comment]
macaca -v : 1.0.24

macaca doctor:
Node.js checklist:
 node env: /data/nodejs/bin/node
 node version: v4.4.4
Android checklist:

log:

>>   macaca desktop sample

macaca-electron is installing for the first time with args: ["install","macaca-electron","--registry=https://registry.npmjs.org/"]


  /     loading...
> electron-prebuilt@0.37.8 postinstall /data/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-electron/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.37.8-linux-x64.zip
Error: socket hang up

/data/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-electron/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1049:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "/data/nodejs/bin/node" "/data/nodejs/bin/npm" "install" "macaca-electron" "--registry=https://registry.npmjs.org/"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.37.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.37.8 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/npm-debug.log

npm install exited with code 1 and signal null
install macaca-electron failed with Error: /data/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-electron/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1049:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "/data/nodejs/bin/node" "/data/nodejs/bin/npm" "install" "macaca-electron" "--registry=https://registry.npmjs.org/"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.37.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.37.8 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/npm-debug.log


  TypeError: Electron is not a function
      at WebdriverServer.detectDevice (/data/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:80:14)
      at WebdriverServer.start (/data/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:40:22)
      at next (native)
      at onFulfilled (/data/nodejs/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at /data/nodejs/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/data/nodejs/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/data/nodejs/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/data/nodejs/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/data/nodejs/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
      at /data/nodejs/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5

>> 
>>     1) "before all" hook

    2) "after all" hook



>>   0 passing (41s)
  2 failing


>>   1) macaca desktop sample "before all" hook:
     Error: [init({"autoAcceptAlerts":true,"browserName":"electron","platformName":"desktop"})] The environment you requested was unavailable.
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

  2) macaca desktop sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)




>> Test completed!

**Comment by xudafeng** [comment]
export CHROMEDRIVER_CDNURL=http://npm.taobao.org/mirrors/chromedriver/
export ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/

**Comment by yuxinwei** [comment]
配上环境变量后,再次运行提示：
err:tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8118
我是否可以下载electron到本地安装
谢谢

**Comment by xudafeng** [comment]
添加了环境变量还下载失败吗?

**Comment by yuxinwei** [comment]
linux是命令行模式没法调起chrome浏览器吧



weiyuxin1985@163.com
 
发件人： xdf
发送时间： 2016-05-19 17:01
收件人： alibaba/macaca
抄送： yuxinwei; Author
主题： Re: [alibaba/macaca] macaca run运行提示 (#52)
添加了环境变量还下载失败吗?

**Comment by xudafeng** [comment]
#61

**Comment by xudafeng** [comment]
#62
