### ISSUE TITLE
npm i macaca-android -g安装报错

### ISSUE THREAD

**Issue by mijiawei** [alibaba/macaca#522]
```
Error: build failed
    at ChildProcess.<anonymous> (/Users/micky/node_modules/ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm WARN uirecorderTest@1.0.0 No repository field.
npm WARN uirecorderTest@1.0.0 scripts['server'] should probably be scripts['start'].
npm WARN uirecorderTest@1.0.0 No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! android-unicode@1.0.11 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the android-unicode@1.0.11 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the android-unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs android-unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls android-unicode
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/micky/.npm/_logs/2017-04-19T15_12_21_776Z-debug.log
```
macaca doctor
```
macaca-doctor version: 1.0.28


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.7.0
Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/micky/Library/Android/sdk`
  Platforms is set to `/Users/micky/Library/Android/sdk/platforms/android-24`
  Android tools is set to `/Users/micky/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/micky/Library/Android/sdk/platform-tools/adb`
```

**Comment by mijiawei** [comment]
已解决。

**Comment by yushuanggui** [comment]
我也出现了这个问题，是怎么解决的呀
