### ISSUE TITLE
运行 make test-ios 2条失败，提示The environment you requested was unavailable和Error: [quit()] Unexpected data in simpleCallback

### ISSUE THREAD

**Issue by cherrycumtb** [alibaba/macaca#533]
macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.8.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/Cherry/Development/sdk`
  Platforms is set to `/Users/Cherry/Development/sdk/platforms/android-20`
  Android tools is set to `/Users/Cherry/Development/sdk/tools/android`
  ADB tool is set to `/Users/Cherry/Development/sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.67

platform=ios macaca run --verbose -d ./macaca-test/mobile-app-sample.test.js
>> index.js:17:12 [master] pid:14855 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.1.104',
  host: 'cherrys-macbook.local',
  loaded_time: '2017-04-30 21:33:40' }
>> middlewares.js:17:10 [master] pid:14855 base middlewares attached
>> router.js:127:10 [master] pid:14855 router set
>> webdriver sdk launched
[ '/Users/Cherry/sample-nodejs/node_modules/.bin/mocha',
  './macaca-test/mobile-app-sample.test.js',
  '--colors',
  '--verbose' ]
>> 

>> 

>> (node:14857) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:14855 Recieve HTTP Request from Client[2017-04-30 21:33:40]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"deviceName":"iPhone 6","platformName":"iOS","autoAcceptAlerts":false,"app":"https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip"}}
>> session.js:47:10 [master] pid:14855 Creating session, sessionId: eb750463-a645-4b00-9473-024f1301d3da.
ios-deploy
>> start to download: https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip
Error: socket hang up
    at doRequest (/usr/local/lib/node_modules/macaca-cli/node_modules/sync-request/index.js:37:11)
    at downloadAndWriteSha1 (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/common/helper.js:139:20)
    at downloadWithCache (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/common/helper.js:161:14)
    at Object._.configApp (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/common/helper.js:182:15)
    at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:13:18)
    at createDevice.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
>> responseHandler.js:54:12 [master] pid:14855 Send Error Respone to Client: TypeError: Cannot read property 'substring' of undefined
>> responseHandler.js:60:14 [master] pid:14855 TypeError: Cannot read property 'substring' of undefined
    at Object._.configApp (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/common/helper.js:191:28)
    at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:13:18)
    at createDevice.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)

  TypeError: Cannot read property 'substring' of undefined
      at Object._.configApp (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/common/helper.js:191:28)
      at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:13:18)
      at createDevice.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)

>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:14855 Recieve HTTP Request from Client[2017-04-30 21:33:58]: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:14855 Send HTTP Respone to Client[2017-04-30 21:33:58]: 405 Method Not Allowed
>>     2) "after all" hook

  0 passing (17s)
  2 failing

>>   1) macaca mobile sample "before all" hook:
     Error: [init({"deviceName":"iPhone 6","platformName":"iOS","autoAcceptAlerts":false,"app":"https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at PromiseWebdriver.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

>> Test completed!
make: *** [test-ios] Error 2

**Comment by xudafeng** [comment]
mac 欢迎以ci为准

https://travis-ci.org/macaca-sample/sample-nodejs/jobs/232860239
