### ISSUE TITLE
macaca指定udid为ip:port格式(192.168.31.2:5555)时报错

### ISSUE THREAD

**Issue by whitiancai** [alibaba/macaca#539]
* **Macaca Version**:1.2.2

* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: H:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `D:\sdk`
  Platforms is set to `D:\sdk\platforms\android-24`
  Android tools is set to `D:\sdk\tools\android.bat`
  ADB tool is set to `D:\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `H:\apache-ant-1.9.6`

  Installed driver list:

  android: 1.1.34
  chrome: 1.0.5

* **Operate System**:win7 64bit

* **Programming Language**:node

使用genymotion模拟器时，genymotion的udid为ip:port格式（比如192.168.31.2:5555），跑脚本的时候会报错。
 1) 给某人的发消息 "before all" hook:
     Error: [init({"platformName":"Android","autoAcceptAlerts":true,"reuse":2,"udid":"192.168.13.102:5555","package":"com.tencent.mm","activity":".ui.LauncherUI"})] The environment you requested was unavailable.
      at D:\NodeProjects\AutoMobile\node_modules\.1.0.16@macaca-wd\wd\lib\webdriver.js:134:15
      at Request._callback (D:\NodeProjects\AutoMobile\node_modules\.1.0.16@macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\NodeProjects\AutoMobile\node_modules\.2.55.0@request\request.js:368:22)
      at Request.<anonymous> (D:\NodeProjects\AutoMobile\node_modules\.2.55.0@request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\NodeProjects\AutoMobile\node_modules\.2.55.0@request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by whitiancai** [comment]
@xudafeng @Archer456

**Comment by Archer456** [comment]
给的信息太少   你是跑的自己的java脚本 还是nodejs脚本？ 
 The environment you requested was unavailable  来看  好像是你脚本里的 package activity 或其他没指定对   要么就是基础macaca环境没安装好 但不好判断出来。你先检查下脚本 确认demo能跑起来  再改自己的apk路径

adb devices -l
List of devices attached
192.168.236.101:5555   device product:vbox86p model:Samsung_Galaxy_S6___6_0_0___API_23___1440x2560 device:vbox86p  

这里 adb devices -l 一定要保证这样 才算adb是正常连同模拟器或真机的。怀疑这里有问题的话，
adb kill-server
taskkill /f /im adb.exe

然后在执行adb device -l 来确认和机器的连通性。    

详细可看https://testerhome.com/topics/5483  FAQ

**Comment by whitiancai** [comment]
我自己跑的node脚本，脚本没问题，只要把udid不是ip:port格式的设备就可以正常的跑。比如模拟器的udid是emulator-5554或者是真机的SODMDIQ499999999这种，都可以正常的跑。当使用genymotion时或者使用adb wifi连接时，设备的udid为192.168.31.2:5555这种，就会初始化失败报上述错误。

同一台设备，显示为不同的udid，非ip:port格式可以跑，ip:port格式就会报错。
$ adb devices -l
List of devices attached
192.168.31.2:8088      device product:hermes model:Redmi_Note_2 device:hermes
SODMDIQ499999999       device product:hermes model:Redmi_Note_2 device:hermes

**Comment by Archer456** [comment]
脚本中
reuse: 3,
//udid: '192.168.31.2:8088',    试下不用传udid这个  只启动一个模拟器 不连真机

**Comment by whitiancai** [comment]
同样无法启动，genymotion模拟器无法使用吗。我设置的使用genymotion自带的sdk tools，因为我如果把genymotion设置成使用我环境中的sdk tools会使得adb devices -l 报错。


>> >> webdriver sdk launched

>> [ 'macaca-test/wx_chat.test.js', '--colors', '--verbose' ]

>> >> 


>> >> 


>> >>   给某人的发消息


>> >> androidOpts：{ platformName: 'Android',
  autoAcceptAlerts: true,
  reuse: 3,
  udid: undefined,
  package: 'com.tencent.mm',
  activity: '.ui.LauncherUI',
  androidProcess: undefined }


>> >>     1) "before all" hook


>> >>     2) "after all" hook


>> >> 


>> >> 


>> >>   0 passing (4s)
  2 failing



>> >>   1) 给某人的发消息 "before all" hook:
     Error: [init({"platformName":"Android","autoAcceptAlerts":true,"reuse":3,"package":"com.tencent.mm","activity":".ui.LauncherUI"})] The environment you requested was unavailable.
      at D:\NodeProjects\AutoMobile\node_modules\.1.0.16@macaca-wd\wd\lib\webdriver.js:134:15
      at Request._callback (D:\NodeProjects\AutoMobile\node_modules\.1.0.16@macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\NodeProjects\AutoMobile\node_modules\.2.55.0@request\request.js:368:22)
      at Request.<anonymous> (D:\NodeProjects\AutoMobile\node_modules\.2.55.0@request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\NodeProjects\AutoMobile\node_modules\.2.55.0@request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)


>>   2) 给某人的发消息 "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (D:\NodeProjects\AutoMobile\node_modules\.1.0.16@macaca-wd\wd\lib\utils.js:139:13)
      at .<anonymous> (D:\NodeProjects\AutoMobile\node_modules\.1.0.16@macaca-wd\wd\lib\callbacks.js:42:12)
      at cb (D:\NodeProjects\AutoMobile\node_modules\.1.0.16@macaca-wd\wd\lib\webdriver.js:165:22)
      at D:\NodeProjects\AutoMobile\node_modules\.1.0.16@macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\NodeProjects\AutoMobile\node_modules\.1.0.16@macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\NodeProjects\AutoMobile\node_modules\.2.55.0@request\request.js:368:22)
      at Request.<anonymous> (D:\NodeProjects\AutoMobile\node_modules\.2.55.0@request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\NodeProjects\AutoMobile\node_modules\.2.55.0@request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)





>> >> Test completed!

**Comment by Archer456** [comment]
package: 'com.tencent.mm',
activity: '.ui.LauncherUI',   

去掉这两个

  换app  用apk安装路径试下

**Comment by whitiancai** [comment]
还是不行。udid有值和无值时都报同样的错。
>> >> androidOpts：{ platformName: 'Android',
  autoAcceptAlerts: true,
  reuse: 3,
  udid: '192.168.13.102:5555',
  package: undefined,
  activity: undefined,
  androidProcess: undefined,
  app: 'apps/com.tencent.mm_1041.apk' }

**Comment by Archer456** [comment]
额  你看下 你genymotion   虚拟机用的是 哪个版本的安卓API  
adb devices -l
List of devices attached
192.168.236.101:5555 device product:vbox86p model:Samsung_Galaxy_S6___6_0_0___API_23___1440x2560 device:vbox86p

类似这样的信息贴出来

**Comment by whitiancai** [comment]
这是我使用的genymotion虚拟机信息。我再换5.1和6.0试试
$ adb devices -l
List of devices attached
192.168.13.102:5555    device product:vbox86p model:Google_Nexus_5___5_0_0___API_21___1080x1920 device:vbox86p

另外我还使用了adb wifi连真机来执行macaca，但是在用例执行初始化阶段无线设备会断开，然后就会报找不到该device，请问这个是什么原因。
