### ISSUE TITLE
运行make test-ios报错.bin/mocha ENOENT

### ISSUE THREAD

**Issue by mingyu0519** [alibaba/macaca#54]
* **Macaca Version**:1.0.25

* **Macaca Doctor**:
```
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v5.1.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.7.0_55`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.7.0_55.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/Cellar/android-sdk/22.6.2`
  Platforms is set to `/usr/local/Cellar/android-sdk/22.6.2/platforms/android-8`
  Android tools is set to `/usr/local/Cellar/android-sdk/22.6.2/tools/android`

  Installed driver list:


```
* **Platform**:  OSX 10.11.4 (15E65)

```
➜  macaca-test-sample git:(master) ✗ make test-ios
platform=ios macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js
>> index.js:93:12 [master] pid:32475 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.1.109',
  host: 'localhost',
  loaded_time: '2016-05-18 22:38:00' }
>> middlewares.js:30:10 [master] pid:32475 base middlewares attached
>> router.js:117:10 [master] pid:32475 router set
>> webdriver sdk launched
{ '0':
   { [Error: spawn /usr/local/lib/node_modules/.macaca-cli_npminstall/mocha/2.4.5/.bin/mocha ENOENT]
     code: 'ENOENT',
     errno: 'ENOENT',
     syscall: 'spawn /usr/local/lib/node_modules/.macaca-cli_npminstall/mocha/2.4.5/.bin/mocha',
     path: '/usr/local/lib/node_modules/.macaca-cli_npminstall/mocha/2.4.5/.bin/mocha',
     spawnargs:
      [ '--colors',
        './macaca-test/macaca-mobile-sample.test.js',
        '--require',
        'should' ] } } true 'digest'
TypeError: res.match is not a function
    at Logger._format (/usr/local/lib/node_modules/.macaca-cli_npminstall/xlogger/1.0.2/xlogger/lib/xlogger.js:86:17)
    at Logger.warn (/usr/local/lib/node_modules/.macaca-cli_npminstall/xlogger/1.0.2/xlogger/lib/xlogger.js:149:18)
    at Runner.<anonymous> (/usr/local/lib/node_modules/.macaca-cli_npminstall/macaca-cli/1.0.25/macaca-cli/bin/macaca-cli-run:89:10)
    at emitOne (events.js:77:13)
    at Runner.emit (events.js:169:7)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.macaca-cli_npminstall/macaca-cli/1.0.25/macaca-cli/lib/run/index.js:72:10)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
>> macaca-cli-run:89:10 [master] pid:32475 Error: spawn /usr/local/lib/node_modules/.macaca-cli_npminstall/mocha/2.4.5/.bin/mocha ENOENT
>> Test completed!
make: *** [test-ios] Error 254
```

**Comment by zenzhu** [comment]
@mingyu0519 这是用了 CNPM 导致的不兼容，请更新一下 tnpm i -g macaca-cli，最新的 1.0.26 版本已经 Fix 了。

**Comment by mingyu0519** [comment]
@zenzhu 谢谢，升级1.0.26后这个问题解决了，但是又碰到了模拟器起不来的问题，见[issue](https://github.com/alibaba/macaca/issues/55)
