### ISSUE TITLE
macaca-android升级2.0后无法使用

### ISSUE THREAD

**Issue by whitiancai** [alibaba/macaca#542]
* **Macaca Version**:1.2.3

* **Macaca Doctor Logs**:
  macaca-doctor version: 1.1.1

  Node.js checklist:

  node env: H:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `D:\sdk`
  Platforms is set to `D:\sdk\platforms\android-25`
  Android tools is set to `D:\sdk\tools\android.bat`
  ADB tool is set to `D:\sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\Users\huangjianbo\.gradle\wrapper\dists\gradle-3.3-all\55gk2rcmfc6p2dg9u9ohc3hw9\gradle-3.3`

  Installed driver list:

  android: 2.0.0

* **Operate System**:win 7 64bit

* **Programming Language**:nodeJs

升级macaca-android 2.0版本后，执行用例直接报错。
>> >> webdriver sdk launched

>> [ 'macaca-test/wx_chat.test.js', '--colors', '--verbose' ]

>> >> (node:8388) DeprecationWarning: `DEBUG_FD` is deprecated. Override `debug.log` if you want to use a different log function (https://git.io/vMUyr)

>> >>   给某人的发消息

>> >> androidOpts：{ platformName: 'Android',
  autoAcceptAlerts: true,
  reuse: 2,
  udid: 'SODMDIQ499999999',
  package: 'com.tencent.mm',
  activity: '.ui.LauncherUI',
  androidProcess: undefined }

>> >>     1) "before all" hook

>> >>     2) "after all" hook

>> >>   0 passing (1s)
  2 failing

>> >>   1) 给某人的发消息 "before all" hook:
     Error: [init({"platformName":"Android","autoAcceptAlerts":true,"reuse":2,"udid":"SODMDIQ499999999","package":"com.tencent.mm","activity":".ui.LauncherUI"})] The environment you requested was unavailable.
      at node_modules\macaca-wd\wd\lib\webdriver.js:137:15
      at Request._callback (node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> >>   2) 给某人的发消息 "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at .<anonymous> (node_modules\macaca-wd\wd\lib\callbacks.js:42:12)
      at cb (node_modules\macaca-wd\wd\lib\webdriver.js:168:22)
      at node_modules\macaca-wd\wd\lib\webdriver.js:182:5
      at Request._callback (node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> >> Test completed!

查看源码macaca-android.js的startDevice方法没走，直接走的webdriver.js的_init方法，发送请求之后响应err是null，data是Internal Server Error.
@xudafeng @Archer456 @CodeToSurvive1

**Comment by upengfei** [comment]
同样出现问题。。。
>> responseHandler.js:54:12 [master] pid:8524 Send Error Respone to Client: Erro
r: Command failed: D:\android\android-sdk-windows/platform-tools/adb -s 17a8606b
 push C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-android\nod
e_modules\._uiautomatorwd@1.0.2@uiautomatorwd\app\build\outputs\apk\app-debug.ap
k /data/local/tmp/undefined

>> responseHandler.js:60:14 [master] pid:8524 Error: Command failed: D:\android\
android-sdk-windows/platform-tools/adb -s 17a8606b push C:\Users\Administrator\A
ppData\Roaming\npm\node_modules\macaca-android\node_modules\._uiautomatorwd@1.0.
2@uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/undefined

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by whitiancai** [comment]
看这个cmd命令，push的apk文件是不存在的，估计要手动编译出来，然后push的远程地址最后又一个undefined，是因为uiautomatorwd.js中缺少CLASSNAME的值，估计得等官方放出修复。我现在正在编译apk,CLASSNAME使用了一个存在的文件夹代替。
@xudafeng 求修复

**Comment by whitiancai** [comment]
@xudafeng 在uiautomatorwd工程下执行gradle build报错，提示在build.gradle中加入
android{
	lintOptions {
			abortOnError false
		}
}
加入之后编译成功，但是执行用例报错：
>>INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.example.android.testing.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.android.testing.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
	at 

>> com.android.commands.am.Am.runInstrument(Am.java:951)
	at com.android.commands.am.Am.onRun(Am.java:316)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:99)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:252)

**Comment by whitiancai** [comment]
@upengfei @xudafeng 
我的解决方案：
1.uiautomatorwd.js
加入
`exports.CLASS_NAME='com.macaca.android.testing'`
修改
`exports.APK_BUILD_PATH = path.join(__dirname, '..', 'app', 'build', 'outputs', 'apk', 'app-debug-androidTest.apk');
exports.TEST_PACKAGE = 'com.macaca.android.testing';`
2.uiautomatorwd工程中AndroidManifest.xml
加入
`<instrumentation android:name="android.support.test.runner.AndroidJUnitRunner"
android:targetPackage="com.macaca.android.testing"
android:label="Test"/>`
修改
`package="com.macaca.android.testing"`
3.使用android studio执行UIAutomatorWD中的测试，执行过程中会在app>build>outputs>apk目录下生成app-debug-androidTest.apk

这个时候已经可以正常执行测试用例了。官方例子可以正常跑，但是我自己之前写好的例子会报错。
我使用elementByName('我的')会识别成xpath/css方式？
`Error: [elementByName("我的")] Error response status: 32, , InvalidSelector - Argument was an invalid selector (e.g. XPath/CSS).`

**Comment by xudafeng** [comment]
https://github.com/macacajs/UIAutomatorWD/commit/dd54d28b4920a652a869286e6ad829306becee77

**Comment by upengfei** [comment]
@xudafeng 还会出错。。
>> responseHandler.js:60:14 [master] pid:7544 Error: Command failed: D:\android
android-sdk-windows/platform-tools/adb -s 17a8606b push C:\Users\Administrator\
ppData\Roaming\npm\node_modules\macaca-android\node_modules\uiautomatorwd\app\b
ild\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing.uiauto
ator

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

  Error: Command failed: D:\android\android-sdk-windows/platform-tools/adb -s 1
a8606b push C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-andr
id\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/t
p/com.macaca.android.testing.uiautomator

      at ChildProcess.exithandler (child_process.js:204:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:886:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by whitiancai** [comment]
@upengfei 你没有app-debug.apk文件吧，你编译过uiautomatorwd工程了吗？

**Comment by whitiancai** [comment]
@upengfei 已经修复，重新安装最新版本即可

**Comment by upengfei** [comment]
ok

**Comment by upengfei** [comment]
@whitiancai  还需要编译uiautomatorwd工程吗？ 为什么我重新安装完macaca-android后还是出现这个错误？
>> responseHandler.js:60:14 [master] pid:9712 Error: Command failed: D:\android\
android-sdk-windows/platform-tools/adb -s 17a8606b push C:\Users\Administrator\A
ppData\Roaming\npm\node_modules\macaca-android\node_modules\uiautomatorwd\app\bu
ild\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

  Error: Command failed: D:\android\android-sdk-windows/platform-tools/adb -s 17
a8606b push C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-andro
id\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tm
p/com.macaca.android.testing

      at ChildProcess.exithandler (child_process.js:204:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:886:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by upengfei** [comment]
@whitiancai 整个node_modules删除了，而且确认是新版本2.0.2，可还是出这个错误：>> responseHandler.js:60:14 [master] pid:1648 Error: Command failed: D:\android\
android-sdk-windows/platform-tools/adb -s 17a8606b push C:\Users\Administrator\A
ppData\Roaming\npm\node_modules\macaca-android\node_modules\uiautomatorwd\app\bu
ild\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

  Error: Command failed: D:\android\android-sdk-windows/platform-tools/adb -s 17
a8606b push C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-andro
id\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tm
p/com.macaca.android.testing

      at ChildProcess.exithandler (child_process.js:204:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:886:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by xudafeng** [comment]
@upengfei gradle 装了吗？

**Comment by upengfei** [comment]
装了，版本号3.5

**Comment by upengfei** [comment]
@xudafeng

**Comment by upengfei** [comment]
是不是必须安装android7.1.1(api25)?

**Comment by upengfei** [comment]
> node ./script/build.js

The JavaCompile.setDependencyCacheDir() method has been deprecated and is schedu
led to be removed in Gradle 4.0.
Thread(png-cruncher_2): ????????????
java.io.IOException: ????????????
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82
)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.j
ava:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:745)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: java.io.IOException: ?????????
???

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
(node:7744) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: build failed
The TaskInputs.source(Object) method has been deprecated and is scheduled to be
removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instea
d.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
Exception while processing task java.io.IOException: ????????????
Error: java.util.concurrent.ExecutionException: java.io.IOException: ???????????
?
:app:mergeDebugResources FAILED

**Comment by upengfei** [comment]
A larger heap for the Gradle daemon is recommended for running jack.

It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at le
ast 1536 MB.
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environ
ment.html
Checking the license for package Android Support Repository in D:\android\androi
d-sdk-windows\licenses
Warning: License for package Android Support Repository not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
[Android Support Repository].

Before building your project, you need to accept the license agreements and comp
lete the installation of the missing components using the Android Studio SDK Man
ager.

Alternatively, to learn how to transfer the license agreements from one workstat
ion to another, go to http://d.android.com/r/studio-ui/export-licenses.html


* Try:

Run with
--stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

BUILD FAILED

**Comment by upengfei** [comment]
@xudafeng @loftyet 这都是啥原因？能否不要强制升级？工作进度耽搁了不少啊。。。

**Comment by whitiancai** [comment]
@upengfei 试试装gradle3.5

**Comment by upengfei** [comment]
@whitiancai 我现在gradle版本就是3.5.



C:\Users\Administrator>gradle -v

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 7 6.1 amd64

**Comment by upengfei** [comment]
![image](https://cloud.githubusercontent.com/assets/18410330/25929040/45d94874-3632-11e7-95fa-e7d99e135bc0.png)
gradle 换成4.0后的错误。之前我将整个node_modules删了，所有的都是重新安装。

**Comment by whitiancai** [comment]
你在macaca群里吗？

**Comment by upengfei** [comment]
没有。。群满了我加不进去
@whitiancai

**Comment by whitiancai** [comment]
我qq 303296119

**Comment by bujiduli** [comment]
出现了同样的问题，apk文件存在，macaca也重新安装了。gradle3.5

**Comment by whitiancai** [comment]
@bujiduli  试试 https://testerhome.com/topics/8618

**Comment by bujiduli** [comment]
![image](https://cloud.githubusercontent.com/assets/27192729/26040864/46fdf552-395b-11e7-97eb-4246b42dae1e.png)
试过了。重新安装macaca-android，两个apk也存在，检查了sdk没有问题，安装日志也没有fail。但出现了上图的错误，看error说是push出错

**Comment by whitiancai** [comment]
你把这个命令直接拷贝到命令行执行试试，如果报错但是apk都存在，可能是手机问题了

**Comment by rubbishkim** [comment]
@xudafeng @Archer456 @CodeToSurvive1
我想问下我的windows下nodejs安装在C盘 但是我的目录中没有你们所说的nodejs/node_global  我的nodejs目录下只有nodejs\node_modules
我的macaca-android路径是这个C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-android\node_modules\uiautomatorwd
请问这样是错误的么 我需要重新装Nodejs么
