### ISSUE TITLE
运行make test-ios报错Shutdown simulator 2DA37BDF-CF01-49B5-AA21-E0111E5AFBC2 failed Error: Command failed: /bin/sh -c xcrun simctl shutdown

### ISSUE THREAD

**Issue by mingyu0519** [alibaba/macaca#55]
* **Macaca Version**:1.0.26

* **Macaca Doctor**:
```
➜  macaca-test-sample git:(master) ✗ macaca doctor

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v5.1.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.7.0_55`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.7.0_55.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/Cellar/android-sdk/22.6.2`
  Platforms is set to `/usr/local/Cellar/android-sdk/22.6.2/platforms/android-8`
  Android tools is set to `/usr/local/Cellar/android-sdk/22.6.2/tools/android`

  Installed driver list:

  macaca-ios: ^1.0.29
```

* **Platform**: OSX 10.11.4 (15E65)

```
➜  macaca-test-sample git:(master) ✗ make test-ios
platform=ios macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js
>> index.js:93:12 [master] pid:33171 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.1.109',
  host: 'localhost',
  loaded_time: '2016-05-19 22:04:40' }
>> middlewares.js:30:10 [master] pid:33171 base middlewares attached
>> router.js:117:10 [master] pid:33171 router set
>> webdriver sdk launched
>>

>>

>>   macaca mobile sample

>> responseHandler.js:24:12 [master] pid:33171 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 6","bundleId":"xudafeng.ios-app-bootstrap","app":"/Users/wangmingyu/Homefile/macaca-test-sample/app/ios-app-bootstrap.zip"}}
>> session.js:24:10 [master] pid:33171 Creating session, sessionId: 2f07a52d-4b56-41c0-be2a-1a9f2beeaae9.
>> helper.js:205:12 [master] pid:33171 Unzipping local app form /Users/wangmingyu/Homefile/macaca-test-sample/app/ios-app-bootstrap.zip
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/lx/4kqd6w9n2rx7v6r5lsgkhmn80000gn/T/ios-app-bootstrap.app/Info.plist
>> macaca-ios.js:181:10 [master] pid:33171 Get available devices [{"name":"iPhone 4s","udid":"7B3E77D2-F2E4-4E3E-A24D-248EAAFC0D6F","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 5","udid":"928D4A7A-A745-449A-987A-30079C8DEF29","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 5s","udid":"0C37F9F2-FA20-49C7-A99F-2B37C274A050","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6","udid":"2DA37BDF-CF01-49B5-AA21-E0111E5AFBC2","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6 Plus","udid":"80320804-DA8C-42E1-A349-FFE318825802","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6s","udid":"2BD4B4E8-C52B-4382-A428-56B958BC3286","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6s Plus","udid":"F36009BD-E5AC-4AF7-BD02-294CE701F3AB","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad 2","udid":"D8CD99E0-42D5-4940-99AC-3B8CF17794D6","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Retina","udid":"FCC3125B-9543-418A-860C-59FE43CE9775","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Air","udid":"18AEEAFA-3E6C-4837-A167-3B957A3C13CA","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Air 2","udid":"87B9161C-1806-400A-9889-502E0EF4DE1B","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Pro","udid":"1E7D6FCC-22B3-450E-A1F5-5B35AA513FAC","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"Apple TV 1080p","udid":"761A2CDE-28DE-49C5-998B-DE30426B1591","state":"Shutdown","available":true,"runtime":"tvOS 9.2"},{"name":"Apple Watch - 38mm","udid":"7CD2658A-9F4B-4120-9769-221FADCDBD25","state":"Shutdown","available":true,"runtime":"watchOS 2.2"},{"name":"Apple Watch - 42mm","udid":"3B7498B7-8B1D-4833-B1C3-40A56E31F192","state":"Shutdown","available":true,"runtime":"watchOS 2.2"}]
>> macaca-ios.js:214:12 [master] pid:33171 Kill simulator failed Error: Command failed: /bin/sh -c killAll Simulator
No matching processes belonging to you were found

>> macaca-ios.js:220:12 [master] pid:33171 Shutdown simulator 2DA37BDF-CF01-49B5-AA21-E0111E5AFBC2 failed Error: Command failed: /bin/sh -c xcrun simctl shutdown "2DA37BDF-CF01-49B5-AA21-E0111E5AFBC2"
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to shutdown device in current state: Shutdown

>> responseHandler.js:63:12 [master] pid:33171 Send Error Respone to Client: Error: Command failed: /bin/sh -c open -a Simulator --args -CurrentDeviceUDID "2DA37BDF-CF01-49B5-AA21-E0111E5AFBC2"
The application /Applications/Cocos/cocos-simulator-bin/ios/Simulator.app cannot be opened because it has an incorrect executable format.

>> responseHandler.js:69:14 [master] pid:33171 Error: Command failed: /bin/sh -c open -a Simulator --args -CurrentDeviceUDID "2DA37BDF-CF01-49B5-AA21-E0111E5AFBC2"
The application /Applications/Cocos/cocos-simulator-bin/ios/Simulator.app cannot be opened because it has an incorrect executable format.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

  Error: Command failed: /bin/sh -c open -a Simulator --args -CurrentDeviceUDID "2DA37BDF-CF01-49B5-AA21-E0111E5AFBC2"
  The application /Applications/Cocos/cocos-simulator-bin/ios/Simulator.app cannot be opened because it has an incorrect executable format.

      at ChildProcess.exithandler (child_process.js:213:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:818:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at Pipe._onclose (net.js:469:12)

>>
>>     1) "before all" hook

>> responseHandler.js:24:12 [master] pid:33171 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:32:14 [master] pid:33171 Send HTTP Respone to Client: 405 Method Not Allowed
>>
>>     2) "after all" hook

>>

>>

>>   0 passing (3s)

>>   2 failing

>>

>>   1) macaca mobile sample "before all" hook:
     [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 6","bundleId":"xudafeng.ios-app-bootstrap","app":"/Users/wangmingyu/Homefile/macaca-test-sample/app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
  Error: [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 6","bundleId":"xudafeng.ios-app-bootstrap","app":"app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:905:12)


>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:905:12)




>> Test completed!
make: *** [test-ios] Error 2
```

**Comment by xudafeng** [comment]
@mingyu0519 你的 Simulator 自己装的？

**Comment by mingyu0519** [comment]
@xudafeng 用xcode安装的ios模拟器

**Comment by xudafeng** [comment]
`/Applications/Cocos/cocos-simulator-bin/`? 这不是xcode

**Comment by mingyu0519** [comment]
@xudafeng 这是cocos2dx的文件，删除了以后就没这个问题了。谢谢，但是可以排查一下为什么没有找到默认的系统simulator。

**Comment by xudafeng** [comment]
@cocos 把工具地址改了
