### ISSUE TITLE
macaca 2.0  wd.java 2.0.7 macaca-android2.0.16 sendKeys(""); 不可用

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#568]
C:\Users\cmd>macaca -v

  2.0.0

C:\Users\cmd>macaca doctor

  macaca-doctor version: 1.1.9

  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-25`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\gradle-3.5`

  Installed driver list:

  android: 2.0.16
  chrome: 1.0.5
  electron: 1.1.6

遇到报错脚本段:
		driver.elementById("com.acp.aicaitencent:id/etUserName");
		element.sendKeys("888888");
		driver.sleep(3000);
			  
		driver.elementById(" com.acp.aicaitencent:id/viewPwd");
		element.sendKeys("777777");
		driver.sleep(3000);

mvn test 日志：
2017-05-19 09:54:58 Request:http://127.0.0.1:3456/wd/hub/session/28a3c541-bf17-4588-9043-b72197e495b5/element:{"using":"id","value":"com.acp.main:id/layoutLogin"}
2017-05-19 09:54:58 Response:{"status":0,"value":{"ELEMENT":"1"},"sessionId":"28a3c541-bf17-4588-9043-b72197e495b5"}
2017-05-19 09:54:58 Request:http://127.0.0.1:3456/wd/hub/session/28a3c541-bf17-4588-9043-b72197e495b5/element/1/click:{}
2017-05-19 09:54:58 Response:{"status":0,"sessionId":"28a3c541-bf17-4588-9043-b72197e495b5"}
2017-05-19 09:55:01 Request:http://127.0.0.1:3456/wd/hub/session/28a3c541-bf17-4588-9043-b72197e495b5/element:{"using":"id","value":"com.acp.aicaitencent:id/etUserName"}
2017-05-19 09:55:01 Response:{"status":0,"value":{"ELEMENT":"1"},"sessionId":"28a3c541-bf17-4588-9043-b72197e495b5"}
2017-05-19 09:55:01 Request:http://127.0.0.1:3456/wd/hub/session/28a3c541-bf17-4588-9043-b72197e495b5/element/1/value:{"value":["888888"]}
2017-05-19 09:55:01 Response:{"status":0,"sessionId":"28a3c541-bf17-4588-9043-b72197e495b5"}
2017-05-19 09:55:04 Request:http://127.0.0.1:3456/wd/hub/session/28a3c541-bf17-4588-9043-b72197e495b5/element:{"using":"id","value":" com.acp.aicaitencent:id/viewPwd"}
2017-05-19 09:55:04 Response:{"status":32,"value":"Argument was an invalid selector (e.g. XPath/CSS).","sessionId":"28a3c541-bf17-4588-9043-b72197e495b5"}
200
2017-05-19 09:55:04 Response:{"sessionId":"28a3c541-bf17-4588-9043-b72197e495b5","status":0}
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.184 sec <<< FAILURE! - in TestSuite
test_case_1(uiauto.AndroidAcpTest)  Time elapsed: 9.756 sec  <<< FAILURE!
java.lang.Exception: Argument was an invalid selector (e.g. XPath/CSS).
        at macaca.client.common.Utils.handleStatus(Utils.java:171)
        at macaca.client.common.Utils.postRequest(Utils.java:118)
        at macaca.client.common.Utils.request(Utils.java:157)
        at macaca.client.MacacaClient.findElement(MacacaClient.java:185)
        at macaca.client.MacacaClient.elementById(MacacaClient.java:241)
        at uiauto.AndroidAcpTest.test_case_1(AndroidAcpTest.java:86)

Results :

Failed tests:
  AndroidAcpTest.test_case_1:86 ?  Argument was an invalid selector (e.g. XPath/...

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.532 s
[INFO] Finished at: 2017-05-19T09:55:05+08:00
[INFO] Final Memory: 12M/309M

**Comment by Archer456** [comment]
以前 这里是 driver.elementById("com.acp.aicaitencent:id/etPwd");     前天用app-inspector 新的 发现是
com.acp.aicaitencent:id/viewPwd  改成这个了  脚本跑到密码输入就报错     

刚升级了下macaca-cli 2.0.1   

我又改回了 com.acp.aicaitencent:id/etPwd   结果就通过了   为什么新的app-inspector对　密码输入框　识别会是viewPwd　　而以前识别出来的是etPwd

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/commit/622142f5cf2848d8759562b37f1e92325eb3448d
