### ISSUE TITLE
升级完macaca 1.0.26后，运行 macaca docotor出现报错

### ISSUE THREAD

**Issue by ftvbftvbq** [alibaba/macaca#57]
* **Macaca Version**:
1.0.26
* **Macaca Doctor**:
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.2.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_31`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/edison/Library/Android/sdk`
  Platforms is set to `/Users/edison/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/edison/Library/Android/sdk/tools/android`

  Installed driver list:

{ Error: Cannot find module '/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/package.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.exports.checkInstalled.e [as checkInstalled] (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/driver.js:13:27)
    at Doctor.check (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/macaca-doctor.js:36:10)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19) code: 'MODULE_NOT_FOUND' }

* **Platform**:mac

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.2.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_31`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/edison/Library/Android/sdk`
  Platforms is set to `/Users/edison/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/edison/Library/Android/sdk/tools/android`

  Installed driver list:

{ Error: Cannot find module '/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/node-installer/package.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.exports.checkInstalled.e [as checkInstalled] (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/driver.js:13:27)
    at Doctor.check (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/macaca-doctor.js:36:10)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19) code: 'MODULE_NOT_FOUND' }

**Comment by ftvbftvbq** [comment]
FYI

**Comment by xudafeng** [comment]
@ftvbftvbq https://testerhome.com/topics/4973
