### ISSUE TITLE
source()提示TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by mingyu0519** [alibaba/macaca#58]
* **Macaca Version**:1.0.26

* **Macaca Doctor**:
```
➜  macaca-test-sample git:(master) ✗ macaca doctor

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v5.1.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.7.0_55`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.7.0_55.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/Cellar/android-sdk/22.6.2`
  Platforms is set to `/usr/local/Cellar/android-sdk/22.6.2/platforms/android-8`
  Android tools is set to `/usr/local/Cellar/android-sdk/22.6.2/tools/android`

  Installed driver list:

  macaca-ios: ^1.0.29
```

* **Platform**: OSX 10.11.4 (15E65)

```
>> responseHandler.js:24:12 [master] pid:4853 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/1cc09ae4-0985-4a6d-a58f-5474cbc8645a/touch/click, jsonBody: {"element":"6"}
>> proxy.js:67:14 [master] pid:4853 Proxy: /wd/hub/session/temp/tap/6:POST to http://192.168.1.109:8100/session/23EB233F-B7A7-46D6-9D14-EA667C111F47/tap/6:POST with body: {}
>> proxy.js:80:16 [master] pid:4853 Got response with status 200: {"value":{},"sessionId":"temp","status":0}
>> responseHandler.js:56:14 [master] pid:4853 Send HTTP Respone to Client: {"sessionId":"1cc09ae4-0985-4a6d-a58f-5474cbc8645a","status":0,"value":"{\"value\":{},\"sessionId\":\"temp\",\"status\":0}"}
>> responseHandler.js:24:12 [master] pid:4853 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/1cc09ae4-0985-4a6d-a58f-5474cbc8645a/source, jsonBody: {}
>> proxy.js:67:14 [master] pid:4853 Proxy: /wd/hub/session/temp/accept_alert:POST to http://192.168.1.109:8100/session/23EB233F-B7A7-46D6-9D14-EA667C111F47/accept_alert:POST with body: {}
>> proxy.js:80:16 [master] pid:4853 Got response with status 200: {"value":"unable to find an alert","sessionId":"temp","status":7}
>> proxy.js:67:14 [master] pid:4853 Proxy: /wd/hub/session/1cc09ae4-0985-4a6d-a58f-5474cbc8645a/source:GET to http://192.168.1.109:8100/session/23EB233F-B7A7-46D6-9D14-EA667C111F47/source:GET with body: {}
>> proxy.js:80:16 [master] pid:4853 Got response with status 400:
>> responseHandler.js:63:12 [master] pid:4853 Send Error Respone to Client: TypeError: Cannot read property 'value' of undefined
>> responseHandler.js:69:14 [master] pid:4853 TypeError: Cannot read property 'value' of undefined
    at Object.sessionAvailable (/usr/local/lib/node_modules/.macaca-cli_npminstall/webdriver-server/1.0.40/webdriver-server/lib/server/controllers/session.js:76:14)
    at next (native)
    at Object.middleware (/usr/local/lib/node_modules/.macaca-cli_npminstall/koa-router/5.4.0/koa-router/lib/layer.js:166:7)
    at next (native)
    at Object.dispatch (/usr/local/lib/node_modules/.macaca-cli_npminstall/koa-router/5.4.0/koa-router/lib/router.js:336:7)
    at next (native)
    at Object.allowedMethods (/usr/local/lib/node_modules/.macaca-cli_npminstall/koa-router/5.4.0/koa-router/lib/router.js:374:5)
    at next (native)
    at Object.dispatch (/usr/local/lib/node_modules/.macaca-cli_npminstall/koa-router/5.4.0/koa-router/lib/router.js:336:7)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/co/4.6.0/co/index.js:65:19)
    at process._tickCallback (node.js:379:9)

  TypeError: Cannot read property 'value' of undefined
      at Object.sessionAvailable (/usr/local/lib/node_modules/.macaca-cli_npminstall/webdriver-server/1.0.40/webdriver-server/lib/server/controllers/session.js:76:14)
      at next (native)
      at Object.middleware (/usr/local/lib/node_modules/.macaca-cli_npminstall/koa-router/5.4.0/koa-router/lib/layer.js:166:7)
      at next (native)
      at Object.dispatch (/usr/local/lib/node_modules/.macaca-cli_npminstall/koa-router/5.4.0/koa-router/lib/router.js:336:7)
      at next (native)
      at Object.allowedMethods (/usr/local/lib/node_modules/.macaca-cli_npminstall/koa-router/5.4.0/koa-router/lib/router.js:374:5)
      at next (native)
      at Object.dispatch (/usr/local/lib/node_modules/.macaca-cli_npminstall/koa-router/5.4.0/koa-router/lib/router.js:336:7)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/co/4.6.0/co/index.js:65:19)
      at process._tickCallback (node.js:379:9)

>>
>>     1) #1 should login success

>> responseHandler.js:24:12 [master] pid:4853 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/1cc09ae4-0985-4a6d-a58f-5474cbc8645a, jsonBody: {}
>> macaca-ios.js:253:10 [master] pid:4853 Stoping iOS driver...
>> xctest-client.js:219:14 [master] pid:4853 ** BUILD INTERRUPTED **

>> xctest-client.js:158:16 [master] pid:4853 bootstrap exit with code: null, signal: SIGTERM
>> xctest-client.js:227:14 [master] pid:4853 xctest client exit with code: null, signal: SIGTERM
>> macaca-ios.js:279:10 [master] pid:4853 iOS driver cleaned up.
>> session.js:52:12 [master] pid:4853 Delete session, sessionId: 1cc09ae4-0985-4a6d-a58f-5474cbc8645a
>> responseHandler.js:56:14 [master] pid:4853 Send HTTP Respone to Client: {"sessionId":"1cc09ae4-0985-4a6d-a58f-5474cbc8645a","status":0}
>>

>>

>>   0 passing (49s)

>>   1 failing

>>

>>   1) macaca mobile sample #1 should login success:
     Error: [source()] Not JSON response
      at exports.newError (/usr/local/lib/node_modules/.webdriver-client_npminstall/macaca-wd/1.0.3/macaca-wd/wd/lib/utils.js:139:13)
      at /usr/local/lib/node_modules/.webdriver-client_npminstall/macaca-wd/1.0.3/macaca-wd/wd/lib/callbacks.js:59:17
      at /usr/local/lib/node_modules/.webdriver-client_npminstall/macaca-wd/1.0.3/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (/usr/local/lib/node_modules/.webdriver-client_npminstall/macaca-wd/1.0.3/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (/usr/local/lib/node_modules/.webdriver-client_npminstall/request/2.55.0/request/request.js:368:22)
      at Request.<anonymous> (/usr/local/lib/node_modules/.webdriver-client_npminstall/request/2.55.0/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/.webdriver-client_npminstall/request/2.55.0/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:905:12)


>>


>> Test completed!
```

错误部分的代码：

```
  it('#1 should login success', function() {
    return driver
      .elementById("TextField1")
      .sendKeys("111")
      .elementById("TextField2")
      .sendKeys("111")
      .elementById("ComputeSumButton")
      .tap()
      .source()
      .then(function(html){
      	console.log(html);
      })
      .sleep(1000);
  });
```

**Comment by xudafeng** [comment]
@mingyu0519 

只有web上下文才有source哦

**Comment by mingyu0519** [comment]
@xudafeng 嗯，那打印当前native页面用哪个api？类似appium中的pageSource方法

**Comment by xudafeng** [comment]
打印当前native页面？？

**Comment by xudafeng** [comment]
只有web才有source，如果需要输出可以先切换到web

**Comment by mingyu0519** [comment]
@xudafeng appium中的pageSource方法可以直接把当前页面xml结构打印出来，macaca有没有类似的方法，这个可以在方法执行失败的时候检查错误，和定位元素。

**Comment by xudafeng** [comment]
@mingyu0519 目前没有支持Native view xml的dump功能，可以考虑后续添加

**Comment by mingyu0519** [comment]
@xudafeng 👌 好的

**Comment by xudafeng** [comment]
@zenzhu 这个是要考虑实现的

**Comment by xudafeng** [comment]
@mingyu0519 Android端已支持。https://testerhome.com/topics/5473

**Comment by xudafeng** [comment]
@mingyu0519 iOS 端已支持，请升级 ios驱动
