### ISSUE TITLE
driver.source接口报错，无法获取数据

### ISSUE THREAD

**Issue by ztwo** [alibaba/macaca#597]
* **Macaca Version**: 2.0.4

* **Macaca Doctor Logs**:
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/joko/Library/Android/sdk`
  Platforms is set to `/Users/joko/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/joko/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.22
  ios: 2.0.15

* **Operate System**:
macos ：10.12.4
Android虚拟机：5.0系统

* **Programming Language**:python

* 步骤：初始化环境后，python调用driver.source，
* 问题描述：控制台报404
* 备注：iOS可正常获取，之前版本偶尔成功，新版百分百失败

* python控制台：
```python

Traceback (most recent call last):
  File "/Users/joko/Desktop/smzdm/test_env8/AppBrowse/for_debug.py", line 82, in <module>
    Anroid_run()
  File "/Users/joko/Desktop/smzdm/test_env8/AppBrowse/for_debug.py", line 69, in Anroid_run
    print b.driver.source
  File "/Users/joko/Desktop/smzdm/test_env8/lib/python2.7/site-packages/macaca/webdriver.py", line 578, in source
    return self._execute(Command.GET_PAGE_SOURCE)
  File "/Users/joko/Desktop/smzdm/test_env8/lib/python2.7/site-packages/macaca/webdriver.py", line 66, in _execute
    res = self.remote_invoker.execute(command, data)
  File "/Users/joko/Desktop/smzdm/test_env8/lib/python2.7/site-packages/macaca/remote_invoker.py", line 110, in execute
    return self._request(method, url, body)
  File "/Users/joko/Desktop/smzdm/test_env8/lib/python2.7/site-packages/macaca/remote_invoker.py", line 145, in _request
    res.raise_for_status()
  File "/Users/joko/Desktop/smzdm/test_env8/lib/python2.7/site-packages/requests/models.py", line 934, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:3457/wd/hub/session/f684aec2-b909-4726-9495-6f84f9005b37/source

```

* macaca-cli
```log

>> session.js:47:10 [master] pid:1221 Creating session, sessionId: f684aec2-b909-4726-9495-6f84f9005b37.
>> uiautomator-client.js:56:14 [master] pid:1221 WARNING: linker: libhoudini.so has text relocations. This is wasting memory and prevents security hardening. Please fix.

>> uiautomator-client.js:56:14 [master] pid:1221 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:56:14 [master] pid:1221 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9010<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> responseHandler.js:47:14 [master] pid:1221 Send HTTP Respone to Client[2017-06-13 17:38:24]: {"sessionId":"f684aec2-b909-4726-9495-6f84f9005b37","status":0,"value":"{\"device\":\"d676675\",\"package\":\"com.smzdm.client.android\",\"platformName\":\"Android\",\"reuse\":3,\"activity\":\".activity.WelComeActivity\"}"}
>> responseHandler.js:11:12 [master] pid:1221 Recieve HTTP Request from Client[2017-06-13 17:38:34]: method: GET url: /wd/hub/session/f684aec2-b909-4726-9495-6f84f9005b37/source, jsonBody: {}
>> proxy.js:55:14 [master] pid:1221 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9010/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:83:20 [master] pid:1221 Got response with status 200: {"status":0,"value":"","sessionId":null}
>> responseHandler.js:23:14 [master] pid:1221 Send HTTP Respone to Client[2017-06-13 17:38:34]: 404 Not Found

```

**Comment by ztwo** [comment]
补充一下信息：android真机获取无问题，虚拟机获取失败，提示404。虚拟机：genymotion google nexus4 5.0.0

**Comment by qichuan** [comment]
@ztwo can you please update macaca-android to the latest version 2.0.40 and try again?
