### ISSUE TITLE
iOS-部分name属性无法获取

### ISSUE THREAD

**Issue by ztwo** [alibaba/macaca#598]
* **Macaca Version**: 2.0.4

* **Macaca Doctor Logs**:
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/joko/Library/Android/sdk`
  Platforms is set to `/Users/joko/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/joko/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.22
  ios: 2.0.15

* **Operate System**:
macos ：10.12.4
iOS模拟器：iphone6s 10.3

* **Programming Language**:python

* 步骤：iOS使用name方式点击控件（首页）
* 问题描述：无法找到相应name控件，控制台报错500（当前页无重复name）
* 分析：在找name前，打印出当前driver.source，查看数据，实际上有相关name控件坐标点（如需完整数据，请在钉钉群询问）

> driver.source数据

```json
                          {
                              "label" : "  首页",
                              "name" : "  首页",
                              "value" : true,
                              "isVisible" : true,
                              "rect" : {
                                "height" : 49.5,
                                "x" : 0,
                                "y" : 617.5,
                                "width" : 75
                              },
                              "type" : "Button",
                              "frame" : "{{0, 617}, {75, 50}}",
                              "isEnabled" : true
                            },

```

> python控制台

```python
  File "/Users/joko/Desktop/smzdm/test_env8/lib/python2.7/site-packages/macaca/webdriver.py", line 66, in _execute
    res = self.remote_invoker.execute(command, data)
  File "/Users/joko/Desktop/smzdm/test_env8/lib/python2.7/site-packages/macaca/remote_invoker.py", line 110, in execute
    return self._request(method, url, body)
  File "/Users/joko/Desktop/smzdm/test_env8/lib/python2.7/site-packages/macaca/remote_invoker.py", line 145, in _request
    res.raise_for_status()
  File "/Users/joko/Desktop/smzdm/test_env8/lib/python2.7/site-packages/requests/models.py", line 934, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:3457/wd/hub/session/6af5180b-e3e5-49b7-ad4a-36c14b4de253/elements

```

macaca-cli
```log
>> responseHandler.js:11:12 [master] pid:2174 Recieve HTTP Request from Client[2017-06-13 17:54:01]: method: POST url: /wd/hub/session/6af5180b-e3e5-49b7-ad4a-36c14b4de253/elements, jsonBody: {"using":"class name","value":"首页"}
>> proxy.js:55:14 [master] pid:2174 Proxy: /wd/hub/session/6af5180b-e3e5-49b7-ad4a-36c14b4de253/elements:POST to http://localhost:8001/wd/hub/session/9BFF2C1E-316C-40EF-A949-D76083686E96/elements:POST with body: {"using":"class name","value":"首页"}
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:172:14 [master] pid:2174 2017-06-13 17:54:03.105 xcodebuild[2191:43045]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/joko/Library/Developer/Xcode/DerivedData/XCTestWD-clmoeenobfwogxghaovnwjtlhvvu/Logs/Test/1C8B436B-3E8B-4EB7-98C6-F664FF0FB75B/Session-XCTestWDUITests-2017-06-13_175403-1RySty.log

>> xctest-client.js:173:14 [master] pid:2174 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/._xctestwd@1.0.33@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:2174 2017-06-13 17:54:03.105 xcodebuild[2191:42429] [MT] IDETestOperationsObserverDebug: (8669D110-5BB9-42EC-A171-DA0E344C9BD0) Beginning test session XCTestWDUITests-8669D110-5BB9-42EC-A171-DA0E344C9BD0 at 2017-06-13 17:54:03.105 with Xcode 8E2002 on target <DVTiPhoneSimulator: 0x7fd04a02c2d0> {
		SimDevice: SimDevice : iPhone 6s (4B29D047-C36E-4228-8AB8-06687B6D1A7E) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6s } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))

>> xctest-client.js:173:14 [master] pid:2174 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/._xctestwd@1.0.33@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:172:14 [master] pid:2174 Failing tests:

>> xctest-client.js:173:14 [master] pid:2174 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/._xctestwd@1.0.33@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:2174 	-[XCTextWDRunner testRunner()]
** TEST FAILED **


>> xctest-client.js:173:14 [master] pid:2174 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/._xctestwd@1.0.33@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:2174 killing deviceLogProc pid: 2192
>> xctest-client.js:260:14 [master] pid:2174 killing runnerProc pid: 2191
>> xctest-client.js:183:14 [master] pid:2174 xctest client exit with code: 65, signal: null
>> xctest-client.js:108:18 [master] pid:2174 simulator log process exit with code: null, signal: SIGKILL
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2174 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:54:12 [master] pid:2174 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:60:14 [master] pid:2174 Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)


```

**Comment by SamuelZhaoY** [comment]
请更新至最新版本
