### ISSUE TITLE
不支持Android 8.0

### ISSUE THREAD

**Issue by jack30639** [alibaba/macaca#615]
不支持Android 8.0

>> UIAutomatorWD http server ready
>> responseHandler.js:54:12 [master] pid:6127 Send Error Respone to Client: get PIDs failed with TypeError: Cannot read property '0' of null

  InternalServerError: Internal Server Error
      at Object.throw (/opt/nodejs/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/opt/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:57:17)
      at throw (native)
      at onRejected (/opt/nodejs/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by xudafeng** [comment]
支持
