### ISSUE TITLE
运行官网的的快速入手报错如图

### ISSUE THREAD

**Issue by sdlbp** [alibaba/macaca#616]
![snip20170623_8](https://user-images.githubusercontent.com/16012134/27468756-4de2127c-581e-11e7-8a3e-4a2cb05e69d6.png)

**Comment by sdlbp** [comment]
Last login: Fri Jun 23 11:42:27 on ttys001
localhost:~ lbp$ cd /Users/lbp/Desktop/sample-nodejs 
localhost:sample-nodejs lbp$ make

make test-ios               Test sample for iOS
make test-android           Test sample for Android
make test-ios-safari        Test sample for iOS Safari
make test-android-chrome    Test sample for Android Chrome
make test-desktop-electron  Test sample for Desktop PC
make test-desktop-chrome    Test sample for Desktop PC
make custom-reporter        Test sample for PC with custom reporter
localhost:sample-nodejs lbp$ make test-ios
macaca doctor

  macaca-doctor version: 2.0.1


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.11.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.18


platform=ios macaca run --verbose -d ./macaca-test/mobile-app-sample.test.js
>> index.js:18:12 [master] pid:42938 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '10.12.141.52',
  host: 'localhost',
  loaded_time: '2017-06-23 14:08:09' }
>> middlewares.js:17:10 [master] pid:42938 base middlewares attached
>> router.js:127:10 [master] pid:42938 router set
>> webdriver sdk launched
[ '/Users/lbp/Desktop/sample-nodejs/node_modules/.bin/mocha',
  './macaca-test/mobile-app-sample.test.js',
  '--colors',
  '--verbose' ]
>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:42938 Recieve HTTP Request from Client[2017-06-23 14:08:10]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"deviceName":"iPhone 6s","platformName":"iOS","autoAcceptAlerts":false,"app":"https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip"}}
>> session.js:47:10 [master] pid:42938 Creating session, sessionId: b4363dad-e4eb-4973-805a-3c1986a6f95b.
ios-deploy
>> please run: `npm install macaca-ios -g`
>> session.js:40:14 [master] pid:42938 Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/macaca-ios/node_modules/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.sync [as mkdir] (/usr/local/lib/node_modules/macaca-ios/node_modules/mkdirp/index.js:71:13)
    at Logger._init (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:44:5)
    at new Logger (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:40:8)
    at Logger.module.exports.Logger (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:175:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/logger.js:10:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/remote-debugger.js:8:16)
    at Module._compile (module.js:570:32)
>> responseHandler.js:54:12 [master] pid:42938 Send Error Respone to Client: Error: >> session.js:40:14 [master] pid:42938 Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/macaca-ios/node_modules/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.sync [as mkdir] (/usr/local/lib/node_modules/macaca-ios/node_modules/mkdirp/index.js:71:13)
    at Logger._init (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:44:5)
    at new Logger (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:40:8)
    at Logger.module.exports.Logger (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:175:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/logger.js:10:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/remote-debugger.js:8:16)
    at Module._compile (module.js:570:32)
>> responseHandler.js:60:14 [master] pid:42938 Error: >> session.js:40:14 [master] pid:42938 Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/macaca-ios/node_modules/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.sync [as mkdir] (/usr/local/lib/node_modules/macaca-ios/node_modules/mkdirp/index.js:71:13)
    at Logger._init (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:44:5)
    at new Logger (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:40:8)
    at Logger.module.exports.Logger (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:175:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/logger.js:10:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/remote-debugger.js:8:16)
    at Module._compile (module.js:570:32)
    at Logger.error (/usr/local/lib/node_modules/macaca-cli/node_modules/xlogger/lib/xlogger.js:169:9)
    at detectDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:40:14)
    at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:10:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5

  Error: >> session.js:40:14 [master] pid:42938 Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/macaca-ios/node_modules/logs'
      at Error (native)
      at Object.fs.mkdirSync (fs.js:923:18)
      at Object.sync [as mkdir] (/usr/local/lib/node_modules/macaca-ios/node_modules/mkdirp/index.js:71:13)
      at Logger._init (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:44:5)
      at new Logger (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:40:8)
      at Logger.module.exports.Logger (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:175:10)
      at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/logger.js:10:25)
      at Module._compile (module.js:570:32)
      at Object.Module._extensions..js (module.js:579:10)
      at Module.load (module.js:487:32)
      at tryModuleLoad (module.js:446:12)
      at Function.Module._load (module.js:438:3)
      at Module.require (module.js:497:17)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/remote-debugger/lib/remote-debugger.js:8:16)
      at Module._compile (module.js:570:32)
      at Logger.error (/usr/local/lib/node_modules/macaca-cli/node_modules/xlogger/lib/xlogger.js:169:9)
      at detectDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:40:14)
      at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:10:18)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5

>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:42938 Recieve HTTP Request from Client[2017-06-23 14:08:12]: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:42938 Send HTTP Respone to Client[2017-06-23 14:08:12]: 405 Method Not Allowed
>>     2) "after all" hook

>> 

>> 

>>   0 passing (2s)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     Error: [init({"deviceName":"iPhone 6s","platformName":"iOS","autoAcceptAlerts":false,"app":"https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)


>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at .<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)


>> 


>> Test completed!
make: *** [test-ios] Error 2
localhost:sample-nodejs lbp$

**Comment by sdlbp** [comment]
在线等，急

**Comment by SamuelZhaoY** [comment]
macaca 没装好， 自己去百度查查为啥会没有permission  /usr/local/lib/node_modules/macaca-ios/node_modules/logs
