### ISSUE TITLE
跑iOSMonkey时报错

### ISSUE THREAD

**Issue by 303404405** [alibaba/macaca#623]
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at macaca.client.common.Utils.postRequest(Utils.java:98)
	at macaca.client.common.Utils.request(Utils.java:144)
	at macaca.client.commands.Session.createSession(Session.java:35)
	at macaca.client.MacacaClient.initDriver(MacacaClient.java:1166)
	at com.pingan.monkey.Monkey.init(Monkey.java:155)
	at com.pingan.monkey.Monkey.run(Monkey.java:71)
	at com.pingan.monkey.Monkey.executeParameter(Monkey.java:61)
	at com.pingan.monkey.Monkey.main(Monkey.java:29)

**Comment by xiaoluosun** [comment]
检查你的macaca环境

**Comment by xudafeng** [comment]
试试 NoSmoke https://github.com/macacajs/NoSmoke
