### ISSUE TITLE
android真机运行的时候出现错误谁能帮忙看下么

### ISSUE THREAD

**Issue by rubbishkim** [alibaba/macaca#625]
Error: Command failed: C:\Android\android-sdk/platform-tools/adb -s LE66A06250
268085 push C:\Program Files\nodejs\node_global\node_modules\macaca-android\node
_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.m
acaca.android.testing

 at ChildProcess.exithandler (child_process.js:270:12)
 at emitTwo (events.js:125:13)
 at ChildProcess.emit (events.js:213:7)
 at maybeClose (internal/child_process.js:897:16)
 at Socket.stream.socket.on (internal/child_process.js:340:11)
 at emitOne (events.js:115:13)
 at Socket.emit (events.js:210:7)
 at Pipe._handle.close [as _onclose] (net.js:548:12)

**Comment by wujunfeng1991** [comment]
应该是这个apk没有生成，重新装macaca-android试试，确保gradle安装好了的。不然也build不出来C:\Program Files\nodejs\node_global\node_modules\macaca-android\node
_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk

**Comment by summerww** [comment]
我也遇到了一样的问题，重装了nodejs，路径中不要有空格，比如Program Files这样的路径不要用，之前我也是将nodejs装在了Program Files下就一直报错，app-inspector -u也不能用，重装之后就都好了
