### ISSUE TITLE
测试小程序切换context时报错no such session

### ISSUE THREAD

**Issue by iamcxy** [alibaba/macaca#635]
安卓真机对微信小程序测试，打开小程序后 driver.contexts()报错。微信版本6.5.8。

在`/usr/local/lib/node_modules/macaca-android/node_modules/macaca-chromedriver/exec/` 更换过多个chromedriver版本，还是都不行。

参考过：https://testerhome.com/topics/9057 https://testerhome.com/topics/7147

```
var androidOpts = {
  platformName: 'Android',
  reuse: '3',
  autoAcceptAlerts: 'true',
  package: 'com.tencent.mm',
  udid: "HEE6R15C23008337",
  activity: 'com.tencent.mm.ui.LauncherUI',
  androidProcess: 'com.tencent.mm:appbrand0'
};

```

```
>> proxy.js:52:14 [master] pid:26305 Proxy: /wd/hub/session/:sessionId/window_handles:GET to http://localhost:9515/wd/hub/session/cc92452370d31c1cfe67147eb2bda529/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:26305 Got response with status 200: {"sessionId":"cc92452370d31c1cfe67147eb2bda529","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X...
>> responseHandler.js:54:12 [master] pid:26305 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.12.3 x86_64)
>> responseHandler.js:60:14 [master] pid:26305 NoSuchDriver: no such session
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.12.3 x86_64)
    at Object._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-android/lib/helper.js:72:11)
    at Android.getWebviews (/usr/local/lib/node_modules/macaca-android/lib/macaca-android.js:305:16)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
>> responseHandler.js:76:14 [master] pid:26305 Send Bad HTTP Respone to Client[2017-07-08 18:57:49]: {"sessionId":"352349f6-3bec-4af5-8228-54c1dc68fc44","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.12.3 x86_64)"}}
>>     1) #1 should login success

>> responseHandler.js:11:12 [master] pid:26305 Recieve HTTP Request from Client[2017-07-08 18:57:50]: method: DELETE url: /wd/hub/session/352349f6-3bec-4af5-8228-54c1dc68fc44, jsonBody: {}
>> session.js:80:12 [master] pid:26305 Delete session, sessionId: 352349f6-3bec-4af5-8228-54c1dc68fc44
>> responseHandler.js:47:14 [master] pid:26305 Send HTTP Respone to Client[2017-07-08 18:57:50]: {"sessionId":"352349f6-3bec-4af5-8228-54c1dc68fc44","status":0}
>> macaca-chromedriver.js:123:18 [master] pid:26305 chromedriver exit with code: null, signal: SIGTERM
>>

  0 passing (26s)
  1 failing

  1) macaca mobile sample #1 should login success:
     Error: [contexts()] Error response status: 6,  Selenium error: no such session
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.12.3 x86_64)
```

* **Macaca Version**:  2.0.4

* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.2.1 lower than 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  Command Line Tools: ios_webkit_debug_proxy is uninstalled
  carthage is uninstalled

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/cxyang/Library/Android/sdk`
  Platforms is set to `/Users/cxyang/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/cxyang/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.18 [out-of-date]
  chrome: 1.0.5
  ios: 2.0.22

* **Operate System**: OSX 10.12.3 (16D30)

* **Programming Language**: Javascript

**Comment by upengfei** [comment]
你mac下的chrome版本是多少？

**Comment by iamcxy** [comment]
mac下chrome `Version 59.0.3071.115`， 这和chrome版本有关系？

**Comment by upengfei** [comment]
我个人觉得有关系。。我看你的chromedriver驱动是2.26对应chrome版本应该是Chrome v53-55，所以你可以下载个2.30版本试试。

**Comment by xudafeng** [comment]
看faq
