### ISSUE TITLE
MAC环境下，运行安卓的sample，一直报错找不到设备。请问可能是什么问题？

### ISSUE THREAD

**Issue by wujunfeng1991** [alibaba/macaca#636]
我开了模拟器，也连接了真机，并且adb devices能够看到这两个设备，但是代码却貌似识别不了。。请救。
>> index.js:18:12 [master] pid:2241 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '192.168.40.129',
  host: 'MacBook-Pro.local',
  loaded_time: '2017-07-10 11:18:32' }
>> middlewares.js:17:10 [master] pid:2241 base middlewares attached
>> router.js:127:10 [master] pid:2241 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:2241 Recieve HTTP Request from Client[2017-07-10 11:19:44]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"Downloads/android_app_bootstrap-debug.apk","platformName":"android"}}
>> session.js:47:10 [master] pid:2241 Creating session, sessionId: 2805cb6c-f732-4577-99a6-4c2f6cdde657.
>> helper.js:208:12 [master] pid:2241 Using local app form /Users/wujunfeng/Downloads/android_app_bootstrap-debug.apk
no device, now create one from avd
>> responseHandler.js:54:12 [master] pid:2241 Send Error Respone to Client: Error: no avd created! Please create one avd first
>> responseHandler.js:60:14 [master] pid:2241 Error: no avd created! Please create one avd first
    at Android.initDevice (/usr/local/lib/node_modules/macaca-android/lib/macaca-android.js:172:13)
    at Android.initDevice.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/_co@4.6.0@co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

  Error: no avd created! Please create one avd first
      at Android.initDevice (/usr/local/lib/node_modules/macaca-android/lib/macaca-android.js:172:13)
      at Android.initDevice.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/_co@4.6.0@co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by wujunfeng1991** [comment]
这个会和python的版本有关系么？
