### ISSUE TITLE
iphone多设备（真机加虚拟机）并行，xctestwd会互相干扰

### ISSUE THREAD

**Issue by ztwo** [alibaba/macaca#643]
* **Macaca Version**: 2.0.4

* **Macaca Doctor Logs**:
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/joko/Library/Android/sdk`
  Platforms is set to `/Users/joko/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/joko/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.23 [out-of-date]
  ios: 2.0.22

* 3456
```
.1:8002
>> responseHandler.js:54:12 [master] pid:74035 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8002
>> responseHandler.js:60:14 [master] pid:74035 Error: connect ECONNREFUSED 127.0.0.1:8002
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

  Error: connect ECONNREFUSED 127.0.0.1:8002
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

>> xctest-client.js:172:14 [master] pid:74035 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/sc/3gh9_f3d3_5bmj4pplwzkc3h0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/bd556bf007da8b5cd27669e16fe1131a/b42c1a3a92537c258854f1e2f148c06c80aa60f0/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:74035 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> responseHandler.js:11:12 [master] pid:74035 Recieve HTTP Request from Client[2017-07-12 20:33:51]: method: GET url: /wd/hub/session/3ce60dbf-48b8-46a9-bab4-9b82d4ab7f23/source, jsonBody: {}
>> proxy.js:55:14 [master] pid:74035 Proxy: /wd/hub/session/3ce60dbf-48b8-46a9-bab4-9b82d4ab7f23/source:GET to http://127.0.0.1:8002/wd/hub/session/1AF15C47-621C-4887-94E3-7ED3E41F079B/source:GET with body: {}
```
* 3458
```
	"bundleId": "com.**",
	"app": "/Users/joko/Downloads/**.app",
	"platformVersion": "10",
	"platformName": "iOS"
}
>> macaca-ios.js:166:12 [master] pid:73688 Trying to start xctestwd server...
>> xctestwd start with port: 8003
>> xctest-client.js:224:14 [master] pid:73688 xcode version: 8.3.3
>> XCTestWD version: 1.1.0
>> xctest-client.js:172:14 [master] pid:73688 2017-07-12 20:32:50.708 xcodebuild[74556:1548195]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/joko/Library/Developer/Xcode/DerivedData/XCTestWD-gulhlqttpkdvbldvsjjkqmcgbggo/Logs/Test/904A178D-C868-4540-9F12-6999E3EF1C35/Session-XCTestWDUITests-2017-07-12_203250-6zE8oW.log

>> xctest-client.js:173:14 [master] pid:73688 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:73688 2017-07-12 20:32:50.709 xcodebuild[74556:1547721] [MT] IDETestOperationsObserverDebug: (894BAA0F-85F3-4875-AAFB-4FB5BFED9680) Beginning test session XCTestWDUITests-894BAA0F-85F3-4875-AAFB-4FB5BFED9680 at 2017-07-12 20:32:50.708 with Xcode 8E3004b on target <DVTiPhoneSimulator: 0x7fe9cd6cfa50> {
		SimDevice: SimDevice : iPhone 6s (4B29D047-C36E-4228-8AB8-06687B6D1A7E) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6s } runtime={ SimRuntime : 10.3.1 (14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3.1 (14E8301))

>> xctest-client.js:173:14 [master] pid:73688 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:55:14 [master] pid:73688 Proxy: /wd/hub/session:POST to http://localhost:8003/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"com.**","app":"/Users/joko/Downloads/**","platformVersion":"10","platformName":"iOS"}}

```

* **Operate System**:
macos ：10.12.5
虚拟机：iphone6s
真机：iphone6 9.3

* **Programming Language**:
python：2.7

问题描述：iphone多设备（真机加虚拟机）并行，xctestwd会互相干扰
现象：3456端口（真机）一切正常，已经开始执行测试用例。此时启动3458（虚拟机）安装xctestwd时，此时查看3456的真机，3456xctestwd会重新启动，导致后续用例无法执行。此时3458可正常执行用例

**Comment by zsmjluo** [comment]
分别启动两个server,请求都会往3456端口的server发：
macaca server 默认3456
macaca server -p 4567

**Comment by SamuelZhaoY** [comment]
目前xctestwd 还没支多设备同时测试

**Comment by wangtao169447** [comment]
@SamuelZhaoY 
多设备这个有计划支持吗？预计什么时候可以

是哪方面的原因，导致不支持？
截图方式导致，还是iproxy方面？

谢谢！

目前实验下来，macaca在page_source和截图上，速度优势非常明显
