### ISSUE TITLE
ios java版initDriver异常(日志齐全)

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#658]
macaca doctor：
  macaca-doctor version: 2.0.1
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v6.11.1

  iOS checklist:
  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Installed driver list:
  ios: 2.0.22

**服务端日志：**
BundleId XCTestWD.XCTestWD does not exist.
>> responseHandler.js:54:12 [master] pid:28312 Send Error Respone to Client: Error: 2017-07-26 18:22:34.076 ios-deploy[28317:505964] [ !! ] [ ERROR ] Could not uninstall package with bundle id XCTestWD.XCTestWD

>> responseHandler.js:60:14 [master] pid:28312 Error: 2017-07-26 18:22:34.076 ios-deploy[28317:505964] [ !! ] [ ERROR ] Could not uninstall package with bundle id XCTestWD.XCTestWD

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/ios-device/lib/helper.js:46:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

  Error: 2017-07-26 18:22:34.076 ios-deploy[28317:505964] [ !! ] [ ERROR ] Could not uninstall package with bundle id XCTestWD.XCTestWD
  
      at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/ios-device/lib/helper.js:46:17)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:891:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**java 客户端堆栈：**
com.alibaba.fastjson.JSONException: syntax error, pos 1, json : Internal Server Error
  at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1361)
  at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1268)
  at com.alibaba.fastjson.JSON.parse(JSON.java:137)
  at com.alibaba.fastjson.JSON.parse(JSON.java:128)
  at com.alibaba.fastjson.JSON.parseObject(JSON.java:201)
  at macaca.client.common.Utils.postRequest(Utils.java:114)
  at macaca.client.common.Utils.request(Utils.java:154)
  at macaca.client.commands.Session.createSession(Session.java:35)
  at macaca.client.MacacaClient.initDriver(MacacaClient.java:1174)

使用新版本驱动经常出现这个问题。

**Comment by yidaxia** [comment]
同样有这个问题，有谁能看下吗？

**Comment by liweiting** [comment]
这个问题在macaca-ios2.0.24 也就是最新版本里面也遇到了，目前还是不能解决吗@xudafeng

**Comment by Chan-Chun** [comment]
请更新最新版本的sample-java
