### ISSUE TITLE
Error Domain=IDETestOperationsObserverErrorDomain Code=4

### ISSUE THREAD

**Issue by Leo-80** [alibaba/macaca#659]
>> server.js:16:12 [master] pid:28353 server start with config:
 { port: '7890',
  verbose: true,
  udid: '554e176306e7676c031dddo63ed5237415b1ce78',
  ip: '192.168.1.100',
  host: 'MacBook-Pro.local',
  loaded_time: '2017-07-28 15:08:49' }
>> app-inspector.js:43:12 [master] pid:28353 server start at: http://192.168.1.100:7890
>> xctest-client.js:52:14 [master] pid:28353 project path: /usr/local/lib/node_modules/app-inspector/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:28353 xcode version: 8.3.3
>> XCTestWD version: 1.1.0
>> xctest-client.js:172:14 [master] pid:28353 2017-07-28 15:08:52.251 xcodebuild[28359:6216173]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/leo/Library/Developer/Xcode/DerivedData/XCTestWD-cjjifngpihhjhyfhgosknggigonn/Logs/Test/DE975535-6FB5-49CF-AF22-8E51911A496D/Session-XCTestWDUITests-2017-07-28_150852-zFqWYs.log

>> xctest-client.js:173:14 [master] pid:28353 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:28353 2017-07-28 15:08:52.252 xcodebuild[28359:6216036] [MT] IDETestOperationsObserverDebug: (D7E5A97B-43C5-4686-BA2E-F0B7FDA54FAD) Beginning test session XCTestWDUITests-D7E5A97B-43C5-4686-BA2E-F0B7FDA54FAD at 2017-07-28 15:08:52.252 with Xcode 8E3004b on target <DVTiOSDevice: 0x7fba44440fe0> {
		deviceSerialNumber:         F17MLBZUFFG8
		identifier:                 554e176306e7676c031dddo63ed5237415b1ce78
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           554e176306e7676c031dddo63ed5237415b1ce78
		productVersion:             9.1
		buildVersion:               13B143
		deviceSoftwareVersion:      9.1 (13B143)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12699631616
		deviceAvailableCapacity:    9986375680
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fba40e36260 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (9.1 (13B143))

>> xctest-client.js:173:14 [master] pid:28353 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:28353 2017-07-28 15:08:56.948 xcodebuild[28359:6216036] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/leo/Library/Developer/Xcode/DerivedData/XCTestWD-cjjifngpihhjhyfhgosknggigonn/Logs/Test/DE975535-6FB5-49CF-AF22-8E51911A496D/Session-XCTestWDUITests-2017-07-28_150852-zFqWYs.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/leo/Library/Developer/Xcode/DerivedData/XCTestWD-cjjifngpihhjhyfhgosknggigonn/Logs/Test/DE975535-6FB5-49CF-AF22-8E51911A496D/Session-XCTestWDUITests-2017-07-28_150852-zFqWYs.log}

>> xctest-client.js:173:14 [master] pid:28353 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:28353
Testing failed:
	Command /bin/sh failed with exit code 127
** TEST FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script Build/Intermediates/XCTestWD.build/Debug-iphoneos/XCTestWDUITests.build/Script-7FA43F311F0CB57400FB2332.sh
(1 failure)

>> xctest-client.js:173:14 [master] pid:28353 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:28353 killing deviceLogProc pid: 28356
>> xctest-client.js:260:14 [master] pid:28353 killing runnerProc pid: 28359
>> xctest-client.js:266:14 [master] pid:28353 killing iproxyProc pid: 28358
>> xctest-client.js:183:14 [master] pid:28353 xctest client exit with code: 65, signal: null
>> xctest-client.js:145:16 [master] pid:28353 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:247:14 [master] pid:28353 Fail to start xctest: undefined
undefined
>> iOS device started: 554e176306e7676c031dddo63ed5237415b1ce78
>> inspector start at: http://192.168.1.100:7890
>> xctest-client.js:211:14 [master] pid:28353 iproxy exit with code: null, signal: SIGKILL
  <-- GET /
>> helper.js:94:16 [master] pid:28353 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by Leo-80** [comment]
@zhuzhaoyuan

**Comment by Leo-80** [comment]
Command /bin/sh failed with exit code 127 关键在于这句话，打开XCTestWD工程 选择Build Phases->第一个Run Script->勾选Run script only when installing
![1234](https://user-images.githubusercontent.com/2002280/28767876-12f1382a-7608-11e7-9fab-bbd1b1a16196.png)
