### ISSUE TITLE
macaca在一个真机上进行录制的时候，爆出了一下错误

### ISSUE THREAD

**Issue by adudurant** [alibaba/macaca#666]
在后端的报错 ：
 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
偶尔会录制成功 但是回放的时候报错
xctest client proxy error with: Error: socket hang up

在前端的报错：
手机打开失败，请检查macaca是否配置正确？ { Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET'

**Comment by liyaoyao6342** [comment]
我也遇到这个问题，怎么解决的呀，请大佬指点
