### ISSUE TITLE
执行macaca-Android-sample以及自己写的例子报TypeError: _.truncate is not a function，

### ISSUE THREAD

**Issue by zthua** [alibaba/macaca#672]
* **Macaca Version**:

2.0.4

* **Macaca Doctor Logs**:
![image](https://user-images.githubusercontent.com/4081273/29053146-ef378212-7c20-11e7-974d-47ce427a046f.png)

* **Operate System**:
windows x64

* **Programming Language**:
python3.4
更多的日志信息：
>> router.js:127:10 [master] pid:6012 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:6012 Recieve HTTP Request from Client[2017-08-08 09:51:05]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk",
latformName":"android"}}
>> session.js:47:10 [master] pid:6012 Creating session, sessionId: 33cb9738-c66b-4cce-a3fe-b1430239cac0.
>> get C:\Users\Administrator\.macaca-temp\android_app_bootstrap-debug.apk from cache
>> sha:9656cdf14170f899681bebe9d58a1de4
>> helper.js:208:12 [master] pid:6012 Using local app form C:\Users\Administrator\.macaca-temp\android_app_bootstrap-debug.apk
>> uiautomator-client.js:56:14 [master] pid:6012 INSTRUMENTATION_STATUS: numtests=1

>> uiautomator-client.js:56:14 [master] pid:6012 INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:56:14 [master] pid:6012 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9003<-UIAutomatorWD

>> UIAutomatorWD http server ready
>> uiautomator-client.js:56:14 [master] pid:6012 INSTRUMENTATION_STATUS_CODE: 0

>> macaca-android.js:293:10 [master] pid:6012 start app with: {"package":"com.github.android_app_bootstrap","activity":"com.github.android_app_bootstrap.activity.WelcomeActivity"}
>> responseHandler.js:47:14 [master] pid:6012 Send HTTP Respone to Client[2017-08-08 09:51:24]: {"sessionId":"33cb9738-c66b-4cce-a3fe-b1430239cac0","status":0,"value":"{\"app\":\"C:\\\\Users\\\\Administrator\\\\.macaca-temp\\\\android_app_bootstrap-debug.apk\",\"platformName\":\"android\"}"}
>> responseHandler.js:11:12 [master] pid:6012 Recieve HTTP Request from Client[2017-08-08 09:51:24]: method: POST url: /wd/hub/session/33cb9738-c66b-4cce-a3fe-b1430239cac0/elements, jsonBody: {"value":"android.widget.EditText","using":"class name"}
>> responseHandler.js:54:12 [master] pid:6012 Send Error Respone to Client: TypeError: _.truncate is not a function
>> responseHandler.js:60:14 [master] pid:6012 TypeError: _.truncate is not a function
    at Promise (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:55:83)
    at Promise (<anonymous>)
    at WDProxy.send (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:33:12)
    at UIAutomator.sendCommand (C:\Users\Administrator\node_modules\uiautomatorwd\lib\uiautomator-client.js:75:21)
    at Android.proxyCommand (C:\Users\Administrator\node_modules\macaca-android\lib\macaca-android.js:110:21)
    at Android.proxyCommand.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:50:10)

  TypeError: _.truncate is not a function
      at Promise (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:55:83)
      at Promise (<anonymous>)
      at WDProxy.send (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:33:12)
      at UIAutomator.sendCommand (C:\Users\Administrator\node_modules\uiautomatorwd\lib\uiautomator-client.js:75:21)
      at Android.proxyCommand (C:\Users\Administrator\node_modules\macaca-android\lib\macaca-android.js:110:21)
      at Android.proxyCommand.next (<anonymous>)
      at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:65:19)
      at C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:54:5
      at Promise (<anonymous>)
      at Object.co (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:50:10)

>> responseHandler.js:11:12 [master] pid:6012 Recieve HTTP Request from Client[2017-08-08 09:51:24]: method: POST url: /wd/hub/session/33cb9738-c66b-4cce-a3fe-b1430239cac0/element, jsonBody: {"value":"HOME","using":"name"}
>> responseHandler.js:54:12 [master] pid:6012 Send Error Respone to Client: TypeError: _.truncate is not a function
>> responseHandler.js:60:14 [master] pid:6012 TypeError: _.truncate is not a function
    at Promise (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:55:83)
    at Promise (<anonymous>)
    at WDProxy.send (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:33:12)
    at UIAutomator.sendCommand (C:\Users\Administrator\node_modules\uiautomatorwd\lib\uiautomator-client.js:75:21)
    at Android.proxyCommand (C:\Users\Administrator\node_modules\macaca-android\lib\macaca-android.js:110:21)
    at Android.proxyCommand.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:50:10)

  TypeError: _.truncate is not a function
      at Promise (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:55:83)
      at Promise (<anonymous>)
      at WDProxy.send (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:33:12)
      at UIAutomator.sendCommand (C:\Users\Administrator\node_modules\uiautomatorwd\lib\uiautomator-client.js:75:21)
      at Android.proxyCommand (C:\Users\Administrator\node_modules\macaca-android\lib\macaca-android.js:110:21)
      at Android.proxyCommand.next (<anonymous>)
      at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:65:19)
      at C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:54:5
      at Promise (<anonymous>)
      at Object.co (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:50:10)

>> responseHandler.js:11:12 [master] pid:6012 Recieve HTTP Request from Client[2017-08-08 09:51:29]: method: POST url: /wd/hub/session/33cb9738-c66b-4cce-a3fe-b1430239cac0/element, jsonBody: {"value":"Alert","using":"name"}
>> responseHandler.js:54:12 [master] pid:6012 Send Error Respone to Client: TypeError: _.truncate is not a function
>> responseHandler.js:60:14 [master] pid:6012 TypeError: _.truncate is not a function
    at Promise (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:55:83)
    at Promise (<anonymous>)
    at WDProxy.send (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:33:12)
    at UIAutomator.sendCommand (C:\Users\Administrator\node_modules\uiautomatorwd\lib\uiautomator-client.js:75:21)
    at Android.proxyCommand (C:\Users\Administrator\node_modules\macaca-android\lib\macaca-android.js:110:21)
    at Android.proxyCommand.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:50:10)

  TypeError: _.truncate is not a function
      at Promise (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:55:83)
      at Promise (<anonymous>)
      at WDProxy.send (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:33:12)
      at UIAutomator.sendCommand (C:\Users\Administrator\node_modules\uiautomatorwd\lib\uiautomator-client.js:75:21)
      at Android.proxyCommand (C:\Users\Administrator\node_modules\macaca-android\lib\macaca-android.js:110:21)
      at Android.proxyCommand.next (<anonymous>)
      at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:65:19)
      at C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:54:5
      at Promise (<anonymous>)
      at Object.co (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:50:10)

>> responseHandler.js:11:12 [master] pid:6012 Recieve HTTP Request from Client[2017-08-08 09:51:29]: method: POST url: /wd/hub/session/33cb9738-c66b-4cce-a3fe-b1430239cac0/element, jsonBody: {"value":"Webview","using":"name"}
>> responseHandler.js:54:12 [master] pid:6012 Send Error Respone to Client: TypeError: _.truncate is not a function
>> responseHandler.js:60:14 [master] pid:6012 TypeError: _.truncate is not a function
    at Promise (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:55:83)
    at Promise (<anonymous>)
    at WDProxy.send (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:33:12)
    at UIAutomator.sendCommand (C:\Users\Administrator\node_modules\uiautomatorwd\lib\uiautomator-client.js:75:21)
    at Android.proxyCommand (C:\Users\Administrator\node_modules\macaca-android\lib\macaca-android.js:110:21)
    at Android.proxyCommand.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:50:10)

  TypeError: _.truncate is not a function
      at Promise (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:55:83)
      at Promise (<anonymous>)
      at WDProxy.send (C:\Users\Administrator\node_modules\uiautomatorwd\lib\proxy.js:33:12)
      at UIAutomator.sendCommand (C:\Users\Administrator\node_modules\uiautomatorwd\lib\uiautomator-client.js:75:21)
      at Android.proxyCommand (C:\Users\Administrator\node_modules\macaca-android\lib\macaca-android.js:110:21)
      at Android.proxyCommand.next (<anonymous>)
      at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:65:19)
      at C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:54:5
      at Promise (<anonymous>)
      at Object.co (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\_co@4.6.0@co\index.js:50:10)

>> responseHandler.js:11:12 [master] pid:6012 Recieve HTTP Request from Client[2017-08-08 09:51:30]: method: GET url: /wd/hub/session/33cb9738-c66b-4cce-a3fe-b1430239cac0/contexts, jsonBody: {}
>> No webview version found from adb shell!
>> use default chromedriver version!
>> starting chromedriver service!
>> chromedriver bin path: C:\Users\Administrator\node_modules\macaca-chromedriver\exec\chromedriver2.20.exe
>> Starting ChromeDriver 2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
TypeError: _.truncate is not a function
    at Promise (C:\Users\Administrator\node_modules\macaca-chromedriver\lib\proxy.js:51:83)
    at Promise (<anonymous>)
    at DriverProxy.send (C:\Users\Administrator\node_modules\macaca-chromedriver\lib\proxy.js:31:12)
    at ChromeDriver.sendCommand (C:\Users\Administrator\node_modules\macaca-chromedriver\lib\macaca-chromedriver.js:86:23)
    at ChromeDriver.getStatus (C:\Users\Administrator\node_modules\macaca-chromedriver\lib\macaca-chromedriver.js:90:17)
    at Promise (C:\Users\Administrator\node_modules\macaca-chromedriver\lib\helper.js:32:5)
    at Promise (<anonymous>)
    at Object._.retry (C:\Users\Administrator\node_modules\macaca-chromedriver\lib\helper.js:31:10)
    at ChromeDriver.waitReadyStatus (C:\Users\Administrator\node_modules\macaca-chromedriver\lib\macaca-chromedriver.js:72:14)
    at <anonymous>
TypeError: _.truncate is not a function
    at Promise (C:\Users\Administrator\node_modules\macaca-chromedriver\lib\proxy.js:51:83)

**Comment by zthua** [comment]
运行web测试的时候，报
  at Socket.emit (events.js:210:7)
 macaca-chromedriver.js:168:18 [master] pid:10396 chromedriver exit with code: 3221225477, signal: null

自己重新安装 npm i install macaca-wd -g  ,也不行 ，这个咱回事呢 

![image](https://user-images.githubusercontent.com/4081273/29053842-e867d668-7c24-11e7-9844-f7ec0f51fa84.png)

**Comment by xudafeng** [comment]
npm i macaca-cli -g

**Comment by zthua** [comment]
@xudafeng   是啊  我也是通过这个解决的 正准备更新啊   ，然后又来坑了 ，chromedriver ，一直更新不成功 ，索性直接下载2.31版本，放在安装目录下，现在还有点问题  ，待解决后在更新
