### ISSUE TITLE
 Cannot find module 'macaca-undefined'

### ISSUE THREAD

**Issue by zhoulinxiang** [alibaba/macaca#688]
错误信息：
>> please run: `npm install macaca-undefined -g`
>> session.js:40:14 [master] pid:78027 Error: Cannot find module 'macaca-undefined'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at detectDevice (/Users/zlx/.nvm/versions/node/v7.10.1/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:36:20)
    at Object.createDevice (/Users/zlx/.nvm/versions/node/v7.10.1/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:10:18)
    at createDevice.next (<anonymous>)
    at onFulfilled (/Users/zlx/.nvm/versions/node/v7.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at /Users/zlx/.nvm/versions/node/v7.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/Users/zlx/.nvm/versions/node/v7.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)

**macaca-undefined 这个包就没有发布到npm上吧？**
npm装不上这个包

$ npm install macaca-undefined -g
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/zlx/.nvm/versions/node/v7.10.1/bin/node" "/Users/zlx/.nvm/versions/node/v7.10.1/bin/npm" "install" "macaca-undefined" "-g"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zlx/.npm/_logs/2017-08-29T08_05_50_100Z-debug.log

**Comment by xudafeng** [comment]
看sample
