### ISSUE TITLE
Android Connection reset by peer

### ISSUE THREAD

**Issue by wilischan** [alibaba/macaca#710]
* **Macaca Version**:
2.0.10
* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.3

Node.js checklist:

node env: /usr/local/bin/node
node version: v8.1.2

iOS checklist:

Xcode Command Line Tools is ready, version: 2347.
xcodebuild version: 9.0
iproxy[usbmuxd] is installed at: /usr/local/bin/iproxy
ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy
carthage is installed, version: 0.23.0

Android checklist:

JAVA version is 1.8.0_131
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
ANDROID_HOME is set to /Users/wilis/Library/Android/sdk
Platforms is set to /Users/wilis/Library/Android/sdk/platforms/android-25
ADB tool is set to /Users/wilis/Library/Android/sdk/platform-tools/adb
gradle is installed, version: 3.5

Installed driver list:

android: 2.0.36
ios: 2.0.24
* **Operate System**:
mac
* **Programming Language**:
python

[2017-09-28 21:46:27,885: WARNING/PoolWorker-4] Time Elapsed: 0:01:35.375746
[2017-09-28 21:47:39,814: ERROR/PoolWorker-4] Task app.messageMonitors.views.monitorsTask[52d6ca0e-279c-47fd-995d-7566227411cc] raised unexpected: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')),)
Traceback (most recent call last):
  File "/Users/wilis/env1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/wilis/env1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/wilis/env1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/var/pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/local/var/pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/var/pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/var/pyenv/versions/3.5.2/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

**Comment by xudafeng** [comment]
升级wd.py
