### ISSUE TITLE
执行macaca用例期间能否使用adb？

### ISSUE THREAD

**Issue by nostarli** [alibaba/macaca#711]
在执行macaca用例期间，同时使用了adb，server报错如下

想问下是环境问题还是macaca也需要占用adb的问题？（在执行macaca期间，命令行使用adb devices -l也会提示
adb server is out of date.  killing...
* daemon started successfully *
List of devices attached 
在重启） 
responseHandler.js:11:12 [master] pid:14464 Recieve HTTP Request from Client[2017-09-30 15:45:47]: method: POST url: /wd/hub/session/5390b12d-9bed-4ac1-a4ae-
01fcfe3829/element, jsonBody: {"using":"id","value":"com.kugou.android:id/n"}
 proxy.js:55:14 [master] pid:14464 Proxy: /wd/hub/session/5390b12d-9bed-4ac1-a4ae-8301fcfe3829/element:POST to http://127.0.0.1:9002/wd/hub/session/5390b12d-9
d-4ac1-a4ae-8301fcfe3829/element:POST with body: {"using":"id","value":"com.kugou.android:id/n"}
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 proxy.js:63:22 [master] pid:14464 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9002
 responseHandler.js:56:12 [master] pid:14464 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:9002
 responseHandler.js:62:14 [master] pid:14464 Error: connect ECONNREFUSED 127.0.0.1:9002
  at Object.exports._errnoException (util.js:1020:11)
  at exports._exceptionWithHostPort (util.js:1043:20)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

Error: connect ECONNREFUSED 127.0.0.1:9002
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

 responseHandler.js:11:12 [master] pid:14464 Recieve HTTP Request from Client[2017-09-30 15:46:18]: method: DELETE url: /wd/hub/session/5390b12d-9bed-4ac1-a4a
8301fcfe3829, jsonBody: {}
 session.js:80:12 [master] pid:14464 Delete session, sessionId: 5390b12d-9bed-4ac1-a4ae-8301fcfe3829
 responseHandler.js:49:14 [master] pid:14464 Send HTTP Respone to Client[2017-09-30 15:46:18]: {"sessionId":"5390b12d-9bed-4ac1-a4ae-8301fcfe3829","status":0}

**Comment by nostarli** [comment]
是adb版本不同导致，已解决。
