### ISSUE TITLE
The webpage says Internal Server Error when inspecting in xiaomi 5

### ISSUE THREAD

**Issue by qichuan** [alibaba/macaca#712]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor

macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.11.3

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.25.0

  Android checklist:

  JAVA version is `1.8.0_144`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/sean/Library/Android/sdk`
  Platforms is set to `/Users/sean/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/sean/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.2

  Installed driver list:

  android: 2.0.37
  chrome: 1.0.6
  ios: 2.0.27

```
---

- app inspector version / 版本号:
2.0.7

- os version / 系统:
Mac OS 10.13

- device  information / 设备版本:
xiaomi 5/ Android 6.0.1

- terminal log / 终端输出信息:

```
app-inspector -u xxxxxxxx --verbose
>> server.js:16:12 [master] pid:38733 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'xxxxxxxx',
  ip: '30.56.214.152',
  host: 'Seans-MacBook-Pro.local',
  loaded_time: '2017-10-02 14:14:32' }
>> app-inspector.js:43:12 [master] pid:38733 server start at: http://30.56.214.152:5678
>> uiautomator-client.js:56:14 [master] pid:38733 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:56:14 [master] pid:38733 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:63893<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> Android device started: xxxxxxxx
>> inspector start at: http://30.56.214.152:5678
  <-- GET /
>> proxy.js:55:14 [master] pid:38733 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:63893/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:85:20 [master] pid:38733 Got response with status 200: {"status":0,"value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\r\n<hierarchy rotation=\"0\">\r\n  <node index=\"0\" text=\"\" resource-id=\"\" class=\"android.widget.FrameLayout\" pa...
>> Dump Android XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/android.json

  Error: Command failed: /Users/sean/Library/Android/sdk/platform-tools/adb -s xxxxxxxx pull /data/local/tmp/screenshot.png /usr/local/lib/node_modules/app-inspector/.temp/android-screenshot.png
  
      at ChildProcess.exithandler (child_process.js:198:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:920:16)
      at Socket.<anonymous> (internal/child_process.js:351:11)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at Pipe._handle.close [as _onclose] (net.js:497:12)
```

> try `app-inspector -u xxxx --verbose` for more log detail.

There are two pop-ups being prompted in every run, they are the app installation confirmation dialogs from xiaomi OS, I have given my consent to both installs and also checked the 'Remember my choices' option.

![screenshot_2017-10-02-14-14-49-293_com miui securitycenter](https://user-images.githubusercontent.com/410850/31066265-3d623bac-a77e-11e7-85b3-f25d43ed22e7.png)
![screenshot_2017-10-02-14-14-38-608_com miui securitycenter](https://user-images.githubusercontent.com/410850/31066266-3f03b7b0-a77e-11e7-96c7-3b318ddacb1e.png)

The log says there is something wrong during the execution of screenshot pull command, it could be due to file permission in Android 6.0 or xiaomi 5 phone.

Perhaps we shall display more helpful information in the error page to help for the troubleshooting?

I have masked my device ID with `xxxxxxxx` for privacy reason.

**Comment by qichuan** [comment]
Update: The `Internal Server Error` is gone after using another USB cable, however the repetitive install dialogs issue still happen.

**Comment by qichuan** [comment]
Fixed the repetitive install dialog issue in https://github.com/macacajs/UIAutomatorWD/pull/16
