### ISSUE TITLE
执行脚本时，一直连接不上真机启动不了xctestwd，提示'Connection aborted.', RemoteDisconnected('Remote end closed connection without response'

### ISSUE THREAD

**Issue by xiaozhaoyi** [alibaba/macaca#713]
* **Macaca Version**:
2.0.10
* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.6.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.25.0

  Android checklist:

  JAVA version is `1.8.0_65`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/ios3rd/Desktop/Test/Tools/adt-bundle-mac-x86_64-20131030/sdk`
  Platforms is set to `/Users/ios3rd/Desktop/Test/Tools/adt-bundle-mac-x86_64-20131030/sdk/platforms/android-19`
  ADB tool is set to `/Users/ios3rd/Desktop/Test/Tools/adt-bundle-mac-x86_64-20131030/sdk/platform-tools/adb`
  gradle is installed, version: 4.2

  Installed driver list:

  android: 2.0.36 [out-of-date]
  chrome: 1.0.6
  electron: 1.1.11
  ios: 2.0.27
* **Operate System**:
Mac：10.13   Apple7p：10.1.1
* **Programming Language**:
python

ERROR: setUpClass (__main__.LoginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cbb_login.py", line 29, in setUpClass
    cls.driver.init()
  File "/usr/local/lib/python3.6/site-packages/macaca/util.py", line 145, in fluent_interface
    ret = func(instance, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/macaca/webdriver.py", line 148, in init
    }, False)
  File "/usr/local/lib/python3.6/site-packages/macaca/webdriver.py", line 66, in _execute
    res = self.remote_invoker.execute(command, data)
  File "/usr/local/lib/python3.6/site-packages/macaca/remote_invoker.py", line 110, in execute
    return self._request(method, url, body)
  File "/usr/local/lib/python3.6/site-packages/macaca/remote_invoker.py", line 144, in _request
    res = s.send(prepped, timeout=self._timeout or None)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
请问这个是什么原因导致的。

**Comment by xudafeng** [comment]
真机需要配置证书
