### ISSUE TITLE
404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by wilischan** [alibaba/macaca#715]
* **Macaca Version**:
2.0.9
* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.3

Node.js checklist:

node env: /usr/local/bin/node
node version: v8.1.2

iOS checklist:

Xcode Command Line Tools is ready, version: 2347.
xcodebuild version: 9.0
iproxy[usbmuxd] is installed at: /usr/local/bin/iproxy
ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy
carthage is installed, version: 0.23.0

Android checklist:

JAVA version is 1.8.0_131
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
ANDROID_HOME is set to /Users/wilis/Library/Android/sdk
Platforms is set to /Users/wilis/Library/Android/sdk/platforms/android-25
ADB tool is set to /Users/wilis/Library/Android/sdk/platform-tools/adb
gradle is installed, version: 3.5

Installed driver list:

android: 2.0.36
ios: 2.0.24
* **Operate System**:
mac os
* **Programming Language**:
python

用例执行过程中，提示：404 Client Error: Not Found for url: http://127.0.0.1:3458/wd/hub/session/34d0a517-7059-4eca-a58a-1a32ea134b25/source
Detail Logs：
[2017-10-13 09:54:57,038: WARNING/PoolWorker-3] 2017-10-13 09:54:57,037 - default - ERROR - Exception, 404 Client Error: Not Found for url: http://127.0.0.1:3458/wd/hub/session/34d0a517-7059-4eca-a58a-1a32ea134b25/source
[2017-10-13 09:54:57,039: WARNING/PoolWorker-3] 2017-10-13 09:54:57,037 - 0861508b251cf1ff - ERROR - Exception, 404 Client Error: Not Found for url: http://127.0.0.1:3458/wd/hub/session/34d0a517-7059-4eca-a58a-1a32ea134b25/source
[2017-10-13 09:54:57,040: WARNING/PoolWorker-3] 2017-10-13 09:54:57,037 - default - ERROR - Exception, 404 Client Error: Not Found for url: http://127.0.0.1:3458/wd/hub/session/34d0a517-7059-4eca-a58a-1a32ea134b25/source
[2017-10-13 09:54:57,040: WARNING/PoolWorker-3] 2017-10-13 09:54:57,037 - 0861508b251cf1ff - ERROR - Exception, 404 Client Error: Not Found for url: http://127.0.0.1:3458/wd/hub/session/34d0a517-7059-4eca-a58a-1a32ea134b25/source
[2017-10-13 09:54:57,041: WARNING/PoolWorker-3] 2017-10-13 09:54:57,037 - default - ERROR - Exception, 404 Client Error: Not Found for url: http://127.0.0.1:3458/wd/hub/session/34d0a517-7059-4eca-a58a-1a32ea134b25/source
[2017-10-13 09:54:57,041: WARNING/PoolWorker-3] 2017-10-13 09:54:57,037 - 00fab2706aacd4f6 - ERROR - Exception, 404 Client Error: Not Found for url: http://127.0.0.1:3458/wd/hub/session/34d0a517-7059-4eca-a58a-1a32ea134b25/source
[2017-10-13 09:54:57,037: ERROR/PoolWorker-3] Exception, 404 Client Error: Not Found for url: http://127.0.0.1:3458/wd/hub/session/34d0a517-7059-4eca-a58a-1a32ea134b25/source
[2017-10-13 09:54:57,042: WARNING/PoolWorker-3] 2017-10-13 09:54:57,042 - default - ERROR - 	<-- CompetitMonitor.cycleMonitNotification, Exception, Error
[2017-10-13 09:54:57,043: WARNING/PoolWorker-3] 2017-10-13 09:54:57,042 - 0861508b251cf1ff - ERROR - 	<-- CompetitMonitor.cycleMonitNotification, Exception, Error
[2017-10-13 09:54:57,043: WARNING/PoolWorker-3] 2017-10-13 09:54:57,042 - default - ERROR - 	<-- CompetitMonitor.cycleMonitNotification, Exception, Error
[2017-10-13 09:54:57,044: WARNING/PoolWorker-3] 2017-10-13 09:54:57,042 - 0861508b251cf1ff - ERROR - 	<-- CompetitMonitor.cycleMonitNotification, Exception, Error
[2017-10-13 09:54:57,045: WARNING/PoolWorker-3] 2017-10-13 09:54:57,042 - default - ERROR - 	<-- CompetitMonitor.cycleMonitNotification, Exception, Error
[2017-10-13 09:54:57,045: WARNING/PoolWorker-3] 2017-10-13 09:54:57,042 - 00fab2706aacd4f6 - ERROR - 	<-- CompetitMonitor.cycleMonitNotification, Exception, Error
[2017-10-13 09:54:57,042: ERROR/PoolWorker-3] 	<-- CompetitMonitor.cycleMonitNotification, Exception, Error
[2017-10-13 09:55:42,801: WARNING/PoolWorker-3] 2017-10-13 09:55:42,800 - default - ERROR - Exception, IMAGE:CompetitMonitor.cycleMonitNotification-20171013095457.PNG
[2017-10-13 09:55:42,802: WARNING/PoolWorker-3] 2017-10-13 09:55:42,800 - 0861508b251cf1ff - ERROR - Exception, IMAGE:CompetitMonitor.cycleMonitNotification-20171013095457.PNG
[2017-10-13 09:55:42,802: WARNING/PoolWorker-3] 2017-10-13 09:55:42,800 - default - ERROR - Exception, IMAGE:CompetitMonitor.cycleMonitNotification-20171013095457.PNG
[2017-10-13 09:55:42,803: WARNING/PoolWorker-3] 2017-10-13 09:55:42,800 - 0861508b251cf1ff - ERROR - Exception, IMAGE:CompetitMonitor.cycleMonitNotification-20171013095457.PNG
[2017-10-13 09:55:42,803: WARNING/PoolWorker-3] 2017-10-13 09:55:42,800 - default - ERROR - Exception, IMAGE:CompetitMonitor.cycleMonitNotification-20171013095457.PNG
[2017-10-13 09:55:42,804: WARNING/PoolWorker-3] 2017-10-13 09:55:42,800 - 00fab2706aacd4f6 - ERROR - Exception, IMAGE:CompetitMonitor.cycleMonitNotification-20171013095457.PNG
[2017-10-13 09:55:42,800: ERROR/PoolWorker-3] Exception, IMAGE:CompetitMonitor.cycleMonitNotification-20171013095457.PNG
[2017-10-13 09:55:42,805: WARNING/PoolWorker-3] 2017-10-13 09:55:42,804 - default - ERROR - <-- MonitorTest.test_android_monitor, Exception, Error
[2017-10-13 09:55:42,805: WARNING/PoolWorker-3] 2017-10-13 09:55:42,804 - 0861508b251cf1ff - ERROR - <-- MonitorTest.test_android_monitor, Exception, Error
[2017-10-13 09:55:42,805: WARNING/PoolWorker-3] 2017-10-13 09:55:42,804 - default - ERROR - <-- MonitorTest.test_android_monitor, Exception, Error
[2017-10-13 09:55:42,806: WARNING/PoolWorker-3] 2017-10-13 09:55:42,804 - 0861508b251cf1ff - ERROR - <-- MonitorTest.test_android_monitor, Exception, Error
[2017-10-13 09:55:42,806: WARNING/PoolWorker-3] 2017-10-13 09:55:42,804 - default - ERROR - <-- MonitorTest.test_android_monitor, Exception, Error
[2017-10-13 09:55:42,807: WARNING/PoolWorker-3] 2017-10-13 09:55:42,804 - 00fab2706aacd4f6 - ERROR - <-- MonitorTest.test_android_monitor, Exception, Error
[2017-10-13 09:55:42,804: ERROR/PoolWorker-3] <-- MonitorTest.test_android_monitor, Exception, Error

**Comment by wilischan** [comment]
补充一下：在获取下拉状态栏的source时失败了
macaca serverlog:
>> index.js:18:12 [master] pid:10892 webdriver server start with config:
 { port: 3458,
  verbose: true,
  always: true,
  ip: '100.84.199.45',
  host: 'Wilis.local',
  loaded_time: '2017-10-13 10:39:40' }
>> middlewares.js:17:10 [master] pid:10892 base middlewares attached
>> router.js:127:10 [master] pid:10892 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:10892 Recieve HTTP Request from Client[2017-10-13 10:39:41]: method: GET url: /wd/hub/status, jsonBody: {}
>> responseHandler.js:49:14 [master] pid:10892 Send HTTP Respone to Client[2017-10-13 10:39:41]: {"sessionId":"","status":0,"value":"{\"build\":{},\"os\":{\"arch\":\"x64\",\"name\":\"darwin\",\"version\":\"\"}}"}
>> responseHandler.js:11:12 [master] pid:10892 Recieve HTTP Request from Client[2017-10-13 10:39:41]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformVersion":"6.0.1\n","udid":"00fab2706aacd4f6","resultPath":"/Users/wilis/Job/ucnews-ci/app/templates/results/messageMonitors/241","autoAcceptAlert":"True","uuid":"00fab2706aacd4f6","app":"/Users/wilis/Job/ucnews-ci/pkg/778/UCNewsIntl_V1.7.1.988_android_pf178_en-us_autotest_Build170918130204.apk","config":{"class_name":"messageMonitors","appName":"UC News","type":"post","devicesName":"PRA","case_path":"TestCase","flowertaskid":"8f38b795-d3d2-4b9d-9fa6-f7d5b456cfb8","deviceID":"00fab2706aacd4f6","diff_app":"android","uuid":"BKFDU17418007099","package":{"android":"/Users/wilis/Job/ucnews-ci/pkg/778/UCNewsIntl_V1.7.1.988_android_pf178_en-us_autotest_Build170918130204.apk","ios":"/Users/wilis/Job/ucnews-ci/pkg/154/UCNewsApp_V1.5.4.991_IP4X_pf196_en-us_love_Build170712182633.ipa"},"iosAppPath":"/Users/wilis/Job/ucnews-ci/pkg/154/UCNewsApp_V1.5.4.991_IP4X_pf196_en-us_love_Build170712182633.ipa","platform":"android","udid":"BKFDU17418007099","title":"time task article publish 1015 on 1012","country":"India","androidAppPath":"/Users/wilis/Job/ucnews-ci/pkg/778/UCNewsIntl_V1.7.1.988_android_pf178_en-us_autotest_Build170918130204.apk","devicesid":14,"taskid":241,"osver":"7.0\n","tags":"develop","suite_path":"TestMessageSuite_"},"autoDismissAlert":"True","deviceName":"Nexus","platformName":"Android","reuse":3}}
>> session.js:47:10 [master] pid:10892 Creating session, sessionId: 56d0a7e2-2801-4439-ac58-c233c583be01.
>> helper.js:208:12 [master] pid:10892 Using local app form /Users/wilis/Job/ucnews-ci/pkg/778/UCNewsIntl_V1.7.1.988_android_pf178_en-us_autotest_Build170918130204.apk
>> uiautomator-client.js:61:14 [master] pid:10892 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:61:14 [master] pid:10892 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9001<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> responseHandler.js:49:14 [master] pid:10892 Send HTTP Respone to Client[2017-10-13 10:40:20]: {"sessionId":"56d0a7e2-2801-4439-ac58-c233c583be01","status":0,"value":"{\"platformVersion\":\"6.0.1\\n\",\"udid\":\"00fab2706aacd4f6\",\"resultPath\":\"/Users/wilis/Job/ucnews-ci/app/templates/results/messageMonitors/241\",\"autoAcceptAlert\":\"True\",\"uuid\":\"00fab2706aacd4f6\",\"app\":\"/Users/wilis/Job/ucnews-ci/pkg/778/UCNewsIntl_V1.7.1.988_android_pf178_en-us_autotest_Build170918130204.apk\",\"config\":{\"class_name\":\"messageMonitors\",\"appName\":\"UC News\",\"type\":\"post\",\"devicesName\":\"P..."}
>> responseHandler.js:11:12 [master] pid:10892 Recieve HTTP Request from Client[2017-10-13 10:41:56]: method: GET url: /wd/hub/session/56d0a7e2-2801-4439-ac58-c233c583be01/source, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:10892 Send HTTP Respone to Client[2017-10-13 10:41:56]: 404 Not Found
>> responseHandler.js:11:12 [master] pid:10892 Recieve HTTP Request from Client[2017-10-13 10:42:32]: method: GET url: /wd/hub/session/56d0a7e2-2801-4439-ac58-c233c583be01/source, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:10892 Send HTTP Respone to Client[2017-10-13 10:42:32]: 404 Not Found
>> responseHandler.js:11:12 [master] pid:10892 Recieve HTTP Request from Client[2017-10-13 10:43:14]: method: GET url: /wd/hub/session/e63a7d18-fa05-4318-8d33-6190a87a141e/source, jsonBody: {}
>> responseHandler.js:56:12 [master] pid:10892 Send Error Respone to Client: NoSuchDriver: A session is either terminated or not started
>> responseHandler.js:62:14 [master] pid:10892 NoSuchDriver: A session is either terminated or not started
    at Object.sessionAvailable (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:114:11)
    at sessionAvailable.next (<anonymous>)
    at Object.middleware (/usr/local/lib/node_modules/macaca-cli/node_modules/koa-router/lib/layer.js:167:14)
    at middleware.next (<anonymous>)
    at Object.dispatch (/usr/local/lib/node_modules/macaca-cli/node_modules/koa-router/lib/router.js:334:12)
    at dispatch.next (<anonymous>)
    at Object.allowedMethods (/usr/local/lib/node_modules/macaca-cli/node_modules/koa-router/lib/router.js:369:12)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (/usr/local/lib/node_modules/macaca-cli/node_modules/koa-router/lib/router.js:334:12)
    at dispatch.next (<anonymous>)
>> responseHandler.js:78:14 [master] pid:10892 Send Bad HTTP Respone to Client[2017-10-13 10:43:14]: {"sessionId":"","status":6,"value":{"message":"A session is either terminated or not started"}}
>> responseHandler.js:11:12 [master] pid:10892 Recieve HTTP Request from Client[2017-10-13 10:43:14]: method: GET url: /favicon.ico, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:10892 Send HTTP Respone to Client[2017-10-13 10:43:14]: 404 Not Found
>> responseHandler.js:11:12 [master] pid:10892 Recieve HTTP Request from Client[2017-10-13 10:43:21]: method: GET url: /wd/hub/session/56d0a7e2-2801-4439-ac58-c233c583be01/source, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:10892 Send HTTP Respone to Client[2017-10-13 10:43:21]: 404 Not Found

**Comment by xudafeng** [comment]
本地网络环境问题

**Comment by wilischan** [comment]
补充log：
>> uiautomator-client.js:61:14 [master] pid:21491 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:61:14 [master] pid:21491 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9006<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> responseHandler.js:49:14 [master] pid:21491 Send HTTP Respone to Client[2017-10-17 18:11:53]: {"sessionId":"cd6ef839-ffcb-4da1-9c88-e8cbb86d64e4","status":0,"value":"{\"app\":\"/Users/wilis/Job/ucnews-ci/pkg/783/UCNewsIntl_V1.7.3.993_android_pf178_en-us_autotest_Build171013181306.apk\",\"udid\":\"BKFDU17418007099\",\"autoDismissAlert\":\"True\",\"deviceName\":\"PRA\",\"platformVersion\":\"7.0\\n\",\"autoAcceptAlert\":\"True\",\"config\":{\"androidAppPath\":\"/Users/wilis/Job/ucnews-ci/pkg/783/UCNewsIntl_V1.7.3.993_android_pf178_en-us_autotest_Build171013181306.apk\",\"type\":\"post\",\"suite_..."}
>> responseHandler.js:11:12 [master] pid:21491 Recieve HTTP Request from Client[2017-10-17 18:13:55]: method: POST url: /wd/hub/session/cd6ef839-ffcb-4da1-9c88-e8cbb86d64e4/actions, jsonBody: {"actions":[{"toY":800,"toX":0,"fromX":0,"fromY":0,"duration":0.8,"type":"drag"}]}
>> session.js:109:14 [master] pid:21491 Send HTTP Respone to Client[2017-10-17 18:13:55]: {}
>> uiautomator-client.js:61:14 [master] pid:21491 INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

>> responseHandler.js:11:12 [master] pid:21491 Recieve HTTP Request from Client[2017-10-17 18:14:32]: method: GET url: /wd/hub/session/cd6ef839-ffcb-4da1-9c88-e8cbb86d64e4/source, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:21491 Send HTTP Respone to Client[2017-10-17 18:14:32]: 404 Not Found
