### ISSUE TITLE
app-inspector 使用期间刷新页面报Unexpected end of JSON input错误

### ISSUE THREAD

**Issue by ownehe** [alibaba/macaca#716]
Macaca Version:   2.0.10
Macaca Doctor:  2.0.3
Platform: MacBook-Pro 10.13

日志入下：
 SyntaxError: Unexpected end of JSON input
      at Object.parse (native)
      at Object.exports.dumpXMLAndScreenShot (/Users/longfei.he/nodejs/lib/node_modules/app-inspector/lib/ios.js:53:21)
      at next (native)
      at onFulfilled (/Users/longfei.he/nodejs/lib/node_modules/app-inspector/node_modules/_co@4.6.0@co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

语言环境：Java版

**Comment by ownehe** [comment]
反复重试发现，在有回退按钮的页面刷新，必现，如果APP切换到没有回退按钮的页面，则不会报这个错误。是否是process._tickCallback 方法哪里有问题。

**Comment by ownehe** [comment]
Mac 10.13系统，IOS，app-inspector版本为： 2.0.8 。XCTestWD为：1.2.6 。

**Comment by SamuelZhaoY** [comment]
请使用最新的XCTestWD 版本 更新 app inspector，
