### ISSUE TITLE
macaca 安卓驱动截屏报错

### ISSUE THREAD

**Issue by SamuelZhaoY** [alibaba/macaca#718]
```
  Error: Command failed: /Users/Gangdooz/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "/system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png"
  error: closed
  
      at ChildProcess.exithandler (child_process.js:205:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:194:7)
      at maybeClose (internal/child_process.js:899:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by xudafeng** [comment]
adb socket 断掉了
