### ISSUE TITLE
使用nosmoke 跑demo时 macaca server端报Cannot find module "/android_app_bootstrap/build/outputs" in package android-app-bootstrap@1.0.7

### ISSUE THREAD

**Issue by qileilove** [alibaba/macaca#719]
* **Macaca Version**:
  1.0.35
* **Macaca Doctor Logs**:
************************************
*  version 1.0.35 is outdate        *
*  run: npm i -g macaca-cli@2.0.10  *
*************************************

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.5.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/opt/android-sdk`
  Platforms is set to `/usr/local/opt/android-sdk/platforms/android-26`
  Android tools is set to `/usr/local/opt/android-sdk/tools/android`

  Installed driver list:

  android: 1.0.11
  ios: 1.0.30
* **Operate System**:
Darwin CNlqi-3.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
* **Programming Language**:
js

```
>> responseHandler.js:63:12 [master] pid:3333 Send Error Respone to Client: Error: Server responded with status code 404:
Cannot find module "/android_app_bootstrap/build/outputs" in package android-app-bootstrap@1.0.7
>> responseHandler.js:69:14 [master] pid:3333 Error: Server responded with status code 404:
Cannot find module "/android_app_bootstrap/build/outputs" in package android-app-bootstrap@1.0.7
    at Response.getBody (/usr/local/lib/node_modules/macaca-cli/node_modules/http-response-object/index.js:34:15)
    at downloadWithCache (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/common/helper.js:156:20)
    at Object._.configApp (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/common/helper.js:188:15)
    at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:26:18)
    at createDevice.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)

```
如log描述，造成nosmoke 测试执行失败
```
2): FetchError: invalid json response body at http://localhost:3456/wd/hub/session reason: Unexpected token S in JSON at position 0
(node:53667) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by xudafeng** [comment]
https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk

check your network
