### ISSUE TITLE
ubuntu下运行macaca-test-sample-master报错（andriod真机）

### ISSUE THREAD

**Issue by 0805** [alibaba/macaca#72]
root@ubuntu:/home/zhangxiang/Downloads/macaca-test-sample-master# make test-android
macaca doctor

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.5

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/opt/java/jdk/jdk1.8`
  ANDROID_HOME is set to `/home/zhangxiang/Downloads/android-sdk-linux`
  Platforms is set to `/home/zhangxiang/Downloads/android-sdk-linux/platforms/android-18`
  Android tools is set to `/home/zhangxiang/Downloads/android-sdk-linux/tools/android`

  Installed driver list:

  android: 1.0.11

platform=android macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js
>> index.js:30:12 [master] pid:3014 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.254.130',
  host: 'ubuntu',
  loaded_time: '2016-06-22 21:32:03' }
>> middlewares.js:30:10 [master] pid:3014 base middlewares attached
>> router.js:118:10 [master] pid:3014 router set
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"Android","app":"/home/zhangxiang/Downloads/macaca-test-sample-master/app/android-app-bootstrap.zip","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:60:10 [master] pid:3014 Creating session, sessionId: 045c58da-6861-4914-8ada-e5fb84039292.
>> helper.js:205:12 [master] pid:3014 Unzipping local app form /home/zhangxiang/Downloads/macaca-test-sample-master/app/android-app-bootstrap.zip
>> socket server ready
>> socket client ready
recive: {"cmd":"wake","args":{}}

return: {"data":true,"success":true}

>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"{\"autoAcceptAlerts\":true,\"platformName\":\"Android\",\"app\":\"/tmp/android_app_bootstrap-debug.apk\",\"browserName\":\"firefox\",\"version\":\"\",\"javascriptEnabled\":true,\"platform\":\"ANY\",\"window\":true}"}
>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/elements, jsonBody: {"using":"class name","value":"android.widget.EditText"}
recive: {"cmd":"find","args":{"strategy":"class name","selector":"android.widget.EditText","multiple":true}}

return: {"data":[{"ELEMENT":"1"},{"ELEMENT":"2"}],"success":true}

>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"[{\"ELEMENT\":\"1\"},{\"ELEMENT\":\"2\"}]"}
>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/element/1/value, jsonBody: {"value":["12345678"]}
recive: {"cmd":"setText","args":{"elementId":"1","text":"12345678"}}

return: {"data":true,"success":true}

>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"true"}
>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/elements, jsonBody: {"using":"class name","value":"android.widget.EditText"}
recive: {"cmd":"find","args":{"strategy":"class name","selector":"android.widget.EditText","multiple":true}}

return: {"data":[{"ELEMENT":"3"},{"ELEMENT":"4"}],"success":true}

>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"[{\"ELEMENT\":\"3\"},{\"ELEMENT\":\"4\"}]"}
>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/element/4/value, jsonBody: {"value":["111111"]}
recive: {"cmd":"setText","args":{"elementId":"4","text":"111111"}}

return: {"data":true,"success":true}

>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"true"}
>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/elements, jsonBody: {"using":"name","value":"Login"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"Login","multiple":true}}

return: {"data":[{"ELEMENT":"5"}],"success":true}

>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"[{\"ELEMENT\":\"5\"}]"}
>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/element/5/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"5"}}

return: {"data":true,"success":true}

>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"true"}
>> 
>>     ✓ #1 should login success (28875ms)

>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/screenshot, jsonBody: {}
>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzs3Xd4VOW6xuFnUghptIRQpARCkBLpUoTQo2AAC1UFNkixbBAQAaWFohSRLnpkqyhsqijSVMBCU6RIR3qTDgkthUDKnD84mZNh0jNJZsHvvi6u12fNzLfWymaTmXe+9S2TJLMAAAAAAAAMzCmvDwAAAAAAACC7aHAAAAAAAADDo8EBAAAAAAAMjwYHAAAAAAAwPBocAAAAAADA8GhwAAAAAAAAw6PBAQAAAAAADI8GBwAAAAAAMDwaHAAAAAAAwPBocAAAAAAAAMOjwQEAAAAAAAyPBgcAAAAAADA8GhwAAAAAAMDwaHAAAAAAAADD..."}
>> 
>>     ✓ #2 should display home (1319ms)

>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/element, jsonBody: {"using":"name","value":"Webview"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"Webview","multiple":false}}

ignored selector

return: {"data":{"ELEMENT":"6"},"success":true}

>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"{\"ELEMENT\":\"6\"}"}
>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/element/6/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"6"}}

return: {"data":true,"success":true}

>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"true"}
>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/screenshot, jsonBody: {}
>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzs3XdYU9f/B/B3SADZynAgU0RFKSpuBRdioai1ddZVraLVutCKW9x7r1ZqnXVbrXu1Ko5aFfdWVBw4GKJsZOT3Bz/yJSQBEhJI9P16Hp/HnNz7uScQkns/95zPEQAQg4iIiIiIiIhIh+mVdgeIiIiIiIiIiIqLCQ4iIiIiIiIi0nlMcBARERERERGRzmOCg4iIiIiIiIh0HhMcRERERERERKTzmOAgIiIiIiIiIp3HBAcRERERERER6TwmOIiIiIiIiIhI5zHBQUREREREREQ6jwkOIiIiIiIiItJ5THAQERERERERkc5jgoOIiIiI..."}
>> 
>>     ✓ #3 should display webview (5358ms)

>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/contexts, jsonBody: {}
>> chromedriver bin path: /usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/node_modules/macaca-chromedriver/exec/chromedriver
>> Kill all running chromedriver process by: ps -ef | grep chromedriver | grep -v grep | grep -e '--port=' | awk '{ print $2 }' | xargs -r kill -15
>> kill all chromedriver process success!
>> Starting ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:52:14 [master] pid:3014 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body: 
>> proxy.js:58:16 [master] pid:3014 Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Linux\",\"version\":\"3.19.0-15-generic\"}}}"
>> proxy.js:52:14 [master] pid:3014 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.github.android_app_bootstrap","androidUseRunningApp":true,"androidDeviceSerial":"RWYDCA8SMFJNHUEQ"}}}
>> proxy.js:58:16 [master] pid:3014 Got response with status 200: {"sessionId":"197da6e09a82b1cc55b62937eae7bf33","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=L...
>> chromedriver ready with: {"sessionId":null,"status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.19.0-15-generic x86_64)"}}
>> proxy.js:52:14 [master] pid:3014 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/197da6e09a82b1cc55b62937eae7bf33/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:3014 Got response with status 200: {"sessionId":"197da6e09a82b1cc55b62937eae7bf33","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3....
>> responseHandler.js:63:12 [master] pid:3014 Send Error Respone to Client: ReferenceError: getErrorByCode is not defined
>> responseHandler.js:69:14 [master] pid:3014 ReferenceError: getErrorByCode is not defined
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/helper.js:65:23)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/macaca-android.js:194:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:369:9)

  ReferenceError: getErrorByCode is not defined
      at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/helper.js:65:23)
      at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/macaca-android.js:194:18)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at process._tickCallback (node.js:369:9)

>> 
>>     1) #4 should go into webview

>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/contexts, jsonBody: {}
>> proxy.js:52:14 [master] pid:3014 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/197da6e09a82b1cc55b62937eae7bf33/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:3014 Got response with status 200: {"sessionId":"197da6e09a82b1cc55b62937eae7bf33","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3....
>> responseHandler.js:63:12 [master] pid:3014 Send Error Respone to Client: ReferenceError: getErrorByCode is not defined
>> responseHandler.js:69:14 [master] pid:3014 ReferenceError: getErrorByCode is not defined
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/helper.js:65:23)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/macaca-android.js:194:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:369:9)

  ReferenceError: getErrorByCode is not defined
      at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/helper.js:65:23)
      at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/macaca-android.js:194:18)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at process._tickCallback (node.js:369:9)

    2) #5 should go into test

>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/contexts, jsonBody: {}
>> proxy.js:52:14 [master] pid:3014 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/197da6e09a82b1cc55b62937eae7bf33/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:3014 Got response with status 200: {"sessionId":"197da6e09a82b1cc55b62937eae7bf33","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3....
>> responseHandler.js:63:12 [master] pid:3014 Send Error Respone to Client: ReferenceError: getErrorByCode is not defined
>> responseHandler.js:69:14 [master] pid:3014 ReferenceError: getErrorByCode is not defined
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/helper.js:65:23)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/macaca-android.js:194:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:369:9)

  ReferenceError: getErrorByCode is not defined
      at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/helper.js:65:23)
      at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/macaca-android.js:194:18)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at process._tickCallback (node.js:369:9)

    3) #6 should works with web

>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292/contexts, jsonBody: {}
>> proxy.js:52:14 [master] pid:3014 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/197da6e09a82b1cc55b62937eae7bf33/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:3014 Got response with status 200: {"sessionId":"197da6e09a82b1cc55b62937eae7bf33","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3....
>> responseHandler.js:63:12 [master] pid:3014 Send Error Respone to Client: ReferenceError: getErrorByCode is not defined
>> responseHandler.js:69:14 [master] pid:3014 ReferenceError: getErrorByCode is not defined
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/helper.js:65:23)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/macaca-android.js:194:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:369:9)

  ReferenceError: getErrorByCode is not defined
      at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/helper.js:65:23)
      at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-android/lib/macaca-android.js:194:18)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at process._tickCallback (node.js:369:9)

    4) #7 should logout success

>> responseHandler.js:24:12 [master] pid:3014 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/045c58da-6861-4914-8ada-e5fb84039292, jsonBody: {}
>> macaca-android.js:56:14 [master] pid:3014 Error: Command failed: /bin/sh -c /home/zhangxiang/Downloads/android-sdk-linux/platform-tools/adb emu kill
error: no emulator detected

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
>> session.js:93:12 [master] pid:3014 Delete session, sessionId: 045c58da-6861-4914-8ada-e5fb84039292
>> responseHandler.js:56:14 [master] pid:3014 Send HTTP Respone to Client: {"sessionId":"045c58da-6861-4914-8ada-e5fb84039292","status":0}
>> 

>> 

>>   3 passing (2m)

>>   4 failing

>> 

>>   1) macaca mobile sample #4 should go into webview:
     Error: [contexts()] Not JSON response
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

>>   2) macaca mobile sample #5 should go into test:
     Error: [contexts()] Not JSON response
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

>>   3) macaca mobile sample #6 should works with web:
     Error: [contexts()] Not JSON response
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

>>   4) macaca mobile sample #7 should logout success:
     Error: [contexts()] Not JSON response
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:59:17
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

>> 

>> 

>> Test completed!

**Comment by 0805** [comment]
我ubuntu 确实没装chrome 浏览器，但是我在另外一台机器上有chrome浏览器的也是报相同的错误。

**Comment by oatsuper** [comment]
我在mac 环境下，也出现了该问题，在login后，进行webview的测试是，日志报错一致
ReferenceError: getErrorByCode is not defined
。。。。

**Comment by zenzhu** [comment]
这个应该已经修复了，可以再试试看会报什么错。

**Comment by oatsuper** [comment]
能问下，类似你们修复后，我该按照什么样的顺序来进行更新呢？
macaca-cli macaca-android macaca-ios macaca-chromedriver

**Comment by zenzhu** [comment]
重新装下 macaca-android 就可以了。

**Comment by 0805** [comment]
@oatsuper  你又试了没？在mac 下可以了么? 我在ubuntu上还是不行

**Comment by oatsuper** [comment]
可以了

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5509
