### ISSUE TITLE
Android虚拟机运行官方示例失败

### ISSUE THREAD

**Issue by pcyan** [alibaba/macaca#722]
* **Macaca Version**:
2.0.10
* **Macaca Doctor Logs**:
```shell
C:\workspace\macaca\sample-nodejs>macaca doctor

  macaca-doctor version: 2.0.3


  Node.js checklist:

  node env: D:\Program1\nodejs\node.exe
  node version: v6.9.2

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `C:\android_tool\sdk`
  Platforms is set to `C:\android_tool\sdk\platforms\android-26`
  ADB tool is set to `C:\android_tool\sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\android_tool\gradle-4.0-milestone-1`

  Installed driver list:

  android: 2.0.40
  electron: 1.1.11

```
* **Operate System**:
windows 64
* **Programming Language**:
js

Android虚拟机运行`mobile-app-sample.test.js`失败

```shell
C:\workspace\macaca\sample-nodejs>macaca run -d macaca-test/mobile-app-sample.test.js
>> webdriver sdk launched
>>

>>
  macaca mobile sample

>> get C:\Users\yanpeicai.TIMESGROUP\.macaca-temp\android_app_bootstrap-debug.apk from cache
>> sha:9656cdf14170f899681bebe9d58a1de4
>> UIAutomatorWD http server ready
>> restart UIAutomatorWD server
>> UIAutomatorWD http server ready
>> current window size {"height":1776,"width":1080}

>> restart UIAutomatorWD server
>> UIAutomatorWD http server ready
>> restart UIAutomatorWD server
>> UIAutomatorWD http server ready
>>     1) #1 should login success

>>

>>
  0 passing (1m)
  1 failing

  1) macaca mobile sample #1 should login success:
     Error: [element.clear()] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command.
      at exports.newError (node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at node_modules\macaca-wd\wd\lib\callbacks.js:33:23
      at node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)




>> Test completed!

```

**Comment by pcyan** [comment]
自己编写了一个测试用例，`touch`和`saveScreenshot`操作都是OK的，但是`waitForElements`之后进行`clear`或者`sendKeys`都会报上面同样的错，是定位Element的问题吗？

**Comment by pcyan** [comment]
@xudafeng 确认是bug了吗，因为连示例都跑不了，所以我想问一下什么时候能解决这个问题。

**Comment by shutiger** [comment]
总算有人遇到相似的问题了，我升级后，也是用例都跑不了了，好像大家都在忙着解ios的问题，已经三天没人理我了，最郁闷的就是回退版本也不行了。
touch,tap事件都能处理，就是isElementExist这个方法，明明看log已经找到了元素了，但是还是报了An unknown server-side error occurred错误，issue链接：https://github.com/macacajs/macaca-android/issues

**Comment by pcyan** [comment]
@shutiger 你们是IOS能跑，Android不能跑是吗？

**Comment by shutiger** [comment]
没，我这边只写了android的用例，ios的不知道，其实android能跑，就是找不到元素所以用例全挂

**Comment by xudafeng** [comment]
升级版本
