### ISSUE TITLE
UIRecoder 在linux上录制时报错

### ISSUE THREAD

**Issue by bingjiesan** [alibaba/macaca#727]
报错信息如下
? Test spec file name: sample/test.spec.js
? Open checker browser? Yes
? Browser size (example: 1024 x 768): maximize

Recorder server listen on: 9765
Chrome init failed!
{ Error: connect ECONNREFUSED 127.0.0.1:9766
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9766 }

* **Macaca Version**:
2.0.10
* **Macaca Doctor Logs**:
  Node.js checklist:

  node env: /data01/QA/node-v8.7.0-linux-x64/bin/node
  node version: v8.7.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/usr/java/jdk1.8.0_101`
  ANDROID_HOME is set to `/data01/android-sdk-linux`
  Platforms is set to `/data01/android-sdk-linux/platforms/android-9`
  ADB tool is set to `/data01/android-sdk-linux/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  electron: 1.1.11

* **Operate System**:centos 7.0

* **Programming Language**: js

**Comment by bingjiesan** [comment]
更新了webdriver的版本后可以解决此问题，chromedriver与chrome之间是有一一对应关系的。需要将下载的chromedriver替换到node目录的lib\node_modules\macaca-chrome\node_modules\chromedriver下面的执行文件，且必须与原有文件命名一致。
