### ISSUE TITLE
macaca client发送请求后，UIAutomaterWD server 就重启了

### ISSUE THREAD

**Issue by zuiaibohe** [alibaba/macaca#731]
D:\gittests\autotestscripts>macaca doctor

  macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v8.2.1

  Android checklist:

  JAVA version is `1.8.0_144`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_144`
  ANDROID_HOME is set to `E:\Android\android-sdk\android-sdk`
  Platforms is set to `E:\Android\android-sdk\android-sdk\platforms\android-27`
  ADB tool is set to `E:\Android\android-sdk\android-sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\gradle-4.0.2`

  Installed driver list:

  android: 2.0.40
  chrome: 1.0.7

执行测试用例：
>> responseHandler.js:11:12 [master] pid:4980 Recieve HTTP Request from Client[2017-10-27 14:36:49]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"Android","udid
":"ec1acd0","autoAcceptAlerts":false,"package":"cmccwm.mobilemusic","activity":"cmccwm.mobilemusic.ui.base.PreSplashActivityMigu","reuse":"3","app":"D:\\gittests\\autotestscripts\\build\\android-app-d
ebug.apk","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:4980 Creating session, sessionId: febd8839-4126-4b65-bafc-79393cb0ff05.
>> helper.js:176:12 [master] pid:4980 Using local app form D:\gittests\autotestscripts\build\android-app-debug.apk
>> uiautomator-client.js:61:14 [master] pid:4980 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:61:14 [master] pid:4980 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9005<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> macaca-android.js:294:10 [master] pid:4980 start app with: {"package":"cmccwm.mobilemusic","activity":""}
>> responseHandler.js:49:14 [master] pid:4980 Send HTTP Respone to Client[2017-10-27 14:37:06]: {"sessionId":"febd8839-4126-4b65-bafc-79393cb0ff05","status":0,"value":"{\"platformName\":\"Android\",\"
udid\":\"ec1acd0\",\"autoAcceptAlerts\":false,\"package\":\"cmccwm.mobilemusic\",\"activity\":\"cmccwm.mobilemusic.ui.base.PreSplashActivityMigu\",\"reuse\":\"3\",\"app\":\"D:\\\\gittests\\\\autotests
cripts\\\\build\\\\android-app-debug.apk\",\"browserName\":\"firefox\",\"version\":\"\",\"javascriptEnabled\":true,\"platform\":\"ANY\",\"show\":true}"}
>> responseHandler.js:11:12 [master] pid:4980 Recieve HTTP Request from Client[2017-10-27 14:37:06]: method: POST url: /wd/hub/session/febd8839-4126-4b65-bafc-79393cb0ff05/elements, jsonBody: {"using"
:"name","value":"乐库"}
>># restart UIAutomatorWD server
>> uiautomator-client.js:61:14 [master] pid:4980 INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

>> uiautomator-client.js:61:14 [master] pid:4980 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:61:14 [master] pid:4980 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9005<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> proxy.js:55:14 [master] pid:4980 Proxy: /wd/hub/session/febd8839-4126-4b65-bafc-79393cb0ff05/elements:POST to http://127.0.0.1:9005/wd/hub/session/febd8839-4126-4b65-bafc-79393cb0ff05/elements:POST
 with body: {"using":"name","value":"乐库"}
>> proxy.js:85:20 [master] pid:4980 Got response with status 200: {"status":0,"value":[{"ELEMENT":"1"}],"sessionId":null}
>> session.js:109:14 [master] pid:4980 Send HTTP Respone to Client[2017-10-27 14:37:11]: {"status":0,"value":"[{\"ELEMENT\":\"1\"}]","sessionId":null}
>> responseHandler.js:11:12 [master] pid:4980 Recieve HTTP Request from Client[2017-10-27 14:37:11]: method: POST url: /wd/hub/session/febd8839-4126-4b65-bafc-79393cb0ff05/element/1/click, jsonBody: {
}
>> restart UIAutomatorWD server
>> uiautomator-client.js:61:14 [master] pid:4980 INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

>> uiautomator-client.js:61:14 [master] pid:4980 java.lang.SecurityException: Calling from not trusted UID!
        at android.os.Parcel.readException(Parcel.java:1546)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.app.ActivityManagerProxy.startInstrumentation(ActivityManagerNative.java:3787)
        at com.android.commands.am.Am.runInstrument(Am.java:976)
        at com.android.commands.am.Am.onRun(Am.java:317)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:97)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

**Comment by jerrylizilong** [comment]
got the same error while testing on  Android 4.4、 Android 5.0 devices

**Comment by njf1107** [comment]
me too
