### ISSUE TITLE
iOS-切换context时报错：http://localhost:null/json

### ISSUE THREAD

**Issue by ztwo** [alibaba/macaca#732]
* **Macaca Version**:2.0.10

* **Macaca Doctor Logs**:

  node env: /usr/local/bin/node
  node version: v6.11.4

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.26.2

  Android checklist:

  JAVA version is `1.8.0_151`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/smzdm/Library/Android/sdk`
  Platforms is set to `/Users/smzdm/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/smzdm/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.2

  Installed driver list:

  android: 2.0.36 [out-of-date]
  ios: 2.0.26 [out-of-date]

* **Operate System**: macos 10.12.5

* **Programming Language**: python 2.7

备注：我有两台相同环境的mac，其中一台无异常，另一台有此问题，唯一区别是libplist版本有差别，请协助看下报错日志

```sh
没问题机器ios_webkit_debug_proxy版本
➜  / ios_webkit_debug_proxy -V
ios_webkit_debug_proxy 1.7.1
Built with libimobiledevice v1.2.0, libplist v1.12
```

```sh
有问题机器ios_webkit_debug_proxy版本
➜  / ios_webkit_debug_proxy -V
ios_webkit_debug_proxy 1.7.1
Built with libimobiledevice v1.2.1, libplist v2.0.0
```

问题描述：iOS 虚拟机在webview页面切换时，问题日志如下

```sh
>> proxy.js:85:20 [master] pid:15662 Got response with status 200: {"sessionId":"","status":0,"value":""}
>> responseHandler.js:49:14 [master] pid:15662 Send HTTP Respone to Client[2017-10-27 14:42:57]: {"sessionId":"6927fcae-e94c-4998-8d05-56746aaeeb4c","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:15662 Recieve HTTP Request from Client[2017-10-27 14:43:02]: method: GET url: /wd/hub/session/6927fcae-e94c-4998-8d05-56746aaeeb4c/context, jsonBody: {}
>> remote-debugger.js:63:12 [master] pid:15662 Getting pages from url: http://localhost:null/json
>> responseHandler.js:56:12 [master] pid:15662 Send Error Respone to Client: RequestError: Error: connect ECONNREFUSED 127.0.0.1:80
>> responseHandler.js:62:14 [master] pid:15662 RequestError: Error: connect ECONNREFUSED 127.0.0.1:80
    at new RequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/_request-promise@2.0.1@request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/macaca-ios/node_modules/_request-promise@2.0.1@request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/macaca-ios/node_modules/_request@2.83.0@request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/_request@2.83.0@request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
>> responseHandler.js:11:12 [master] pid:15662 Recieve HTTP Request from Client[2017-10-27 14:43:02]: method: GET url: /wd/hub/session/6927fcae-e94c-4998-8d05-56746aaeeb4c/window/current/size, jsonBody: {}
```

**Comment by SamuelZhaoY** [comment]
请使用 最新版本xcode， IDE 更新后私有库接口产生了很大改动，不能保证老版本稳定性

**Comment by ztwo** [comment]
@SamuelZhaoY macaca-iOS使用的也是老版本，并不是最新，xctestwd是1.1.8.相同环境，另一台mac无此问题
