### ISSUE TITLE
macaca-chrome更新到最新版本后，可以打开chrome浏览器，当调用MacacaClient.quit()方法时，报错：Internal Server Error

### ISSUE THREAD

**Issue by xyhzchn** [alibaba/macaca#736]
执行方法：
/**
     * 关闭驱动
     *通过传递过来的MacacaClient对象，调用对象的quit()方法
     */
    public void tearDown(MacacaClient driver){

            try {
                if(driver != null){
                    driver.quit();
                }
            }catch (Exception e){
                //关闭驱动失败
                e.printStackTrace();
            }
    }
错误信息：
500
2017-11-01 15:55:02 Response:Internal Server Error

===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

com.alibaba.fastjson.JSONException: syntax error, pos 1, json : Internal Server Error
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1361)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1268)
	at com.alibaba.fastjson.JSON.parse(JSON.java:137)
	at com.alibaba.fastjson.JSON.parse(JSON.java:128)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:201)
	at macaca.client.common.Utils.deleteRequest(Utils.java:142)
	at macaca.client.common.Utils.request(Utils.java:156)
	at macaca.client.commands.Session.delSession(Session.java:45)
	at macaca.client.MacacaClient.quit(MacacaClient.java:1198)
	at aixue.commonUtils.CommonFunctions.tearDown(CommonFunctions.java:384)
	at aixue.testCases.core.TeaLoginAllEmpty.tearDown(TeaLoginAllEmpty.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.afterRun(TestRunner.java:958)
	at org.testng.TestRunner.run(TestRunner.java:606)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
简单描述：
实现功能为打开chrome浏览器，不输入用户名和密码，点击登录按钮，验证提示信息是否正确后，关闭浏览器驱动。
自动化测试脚本可以正常打开chrome浏览器，执行验证操作，在关闭浏览器时，调用quit()方式时，报以上错误。

**Comment by Chan-Chun** [comment]
https://github.com/macacajs/macaca-chromedriver/blob/master/README.md#default-version

**Comment by Chan-Chun** [comment]
https://macacajs.com/zh/environment-setup

更新了文档的chromedriver版本
