### ISSUE TITLE
Samsung Galaxy C5回放录制脚本报错，是否安卓兼容性问题？

### ISSUE THREAD

**Issue by litingjun2015** [alibaba/macaca#738]
* **Macaca Version**:
2.0.12

* **Macaca Doctor Logs**:
$ macaca doctor

  macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v7.10.1

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `C:\soft\android_sdk\sdk`
  Platforms is set to `C:\soft\android_sdk\sdk\platforms\android-26`
  ADB tool is set to `C:\soft\android_sdk\sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\devtools\gradle-4.2.1`

  Installed driver list:

  android: 2.0.40
  chrome: 1.0.7

* **Operate System**:
Win 7 SP1

* **Programming Language**:

锤子手机录制的脚本，在锤子手机运行正常，

```
$ macaca run -p 4444 -d  ./scripts/simple.js --verbose -o ./output
>> port: 4444 was occupied, changed port: 4445
>> index.js:18:12 [master] pid:6724 webdriver server start with config:
 { port: 4445,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.0.72',
  host: 'macaca',
  loaded_time: '2017-11-02 09:37:42' }
>> middlewares.js:17:10 [master] pid:6724 base middlewares attached
>> router.js:133:10 [master] pid:6724 router set
>> webdriver sdk launched
[ './scripts/simple.js', '--colors', '--verbose' ]
>>


>>   scripts/simple : 592efe7b

>>     √ tap: 请输入手机号 ( //*[@text="请输入手机号"] ) (4570ms)

>>     √ sendKeys: demo{ESCAPE} (1407ms)

>>     √ tap: 请输入密码 ( //*[@text="请输入密码"] ) (795ms)

>>     √ tap: 请输入密码 ( //*[@text="请输入密码"] )

>>     √ sendKeys: 123456{ESCAPE} (1092ms)

>>     √ tap: 登 录 ( //*[@text="登 录"] )

>>     √ tap: 登 录 ( //*[@text="登 录"] )

>>

  7 passing (58s)


>> Test completed!
```

在 Samsung 手机运行失败，

```
$ macaca run -p 4444 -d  ./scripts/simple.js --verbose -o ./output
>> port: 4444 was occupied, changed port: 4445
>> index.js:18:12 [master] pid:6840 webdriver server start with config:
 { port: 4445,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.0.72',
  host: 'macaca',
  loaded_time: '2017-11-02 09:45:52' }
>> middlewares.js:17:10 [master] pid:6840 base middlewares attached
>> router.js:133:10 [master] pid:6840 router set
>> webdriver sdk launched
[ './scripts/simple.js', '--colors', '--verbose' ]
>>


>>   scripts/simple : 4df7aded08b340f9

>>     1) tap: 请输入手机号 ( //*[@text="请输入手机号"] )

>>     √ sendKeys: demo{ESCAPE} (3932ms)

>>     2) tap: 请输入密码 ( //*[@text="请输入密码"] )

>>     3) tap: 请输入密码 ( //*[@text="请输入密码"] )

>>     √ sendKeys: 123456{ESCAPE} (4040ms)

>>     4) tap: 登 录 ( //*[@text="登 录"] )

>>     5) tap: 登 录 ( //*[@text="登 录"] )

>>

  2 passing (4m)
  5 failing


>>   1) scripts/simple : 4df7aded08b340f9 tap: 请输入手机号 ( //*[@text="请输入手机号"] ):
     Error: the string "An unknown server-side error occurred while processing the command." was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@3.1.2@mocha\lib\runner.js:233:11)
      at node_modules\_mocha@3.1.2@mocha\lib\runner.js:566:18
      at done (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:293:5)
      at node_modules\_mocha@3.1.2@mocha\lib\runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)

  2) scripts/simple : 4df7aded08b340f9 tap: 请输入密码 ( //*[@text="请输入密码"] ):
     Error: the string "Wait element displayed timeout: //*[@text=\"请输入密码\"] ,30000ms" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@3.1.2@mocha\lib\runner.js:233:11)
      at node_modules\_mocha@3.1.2@mocha\lib\runner.js:566:18
      at done (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:293:5)
      at node_modules\_mocha@3.1.2@mocha\lib\runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)

  3) scripts/simple : 4df7aded08b340f9 tap: 请输入密码 ( //*[@text="请输入密码"] ):
     Error: the string "Wait element displayed timeout: //*[@text=\"请输入密码\"] ,30000ms" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@3.1.2@mocha\lib\runner.js:233:11)
      at node_modules\_mocha@3.1.2@mocha\lib\runner.js:566:18
      at done (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:293:5)
      at node_modules\_mocha@3.1.2@mocha\lib\runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)

  4) scripts/simple : 4df7aded08b340f9 tap: 登 录 ( //*[@text="登 录"] ):
     Error: the string "Wait element displayed timeout: //*[@text=\"登 录\"] ,30000ms" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@3.1.2@mocha\lib\runner.js:233:11)
      at node_modules\_mocha@3.1.2@mocha\lib\runner.js:566:18
      at done (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:293:5)
      at node_modules\_mocha@3.1.2@mocha\lib\runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)

  5) scripts/simple : 4df7aded08b340f9 tap: 登 录 ( //*[@text="登 录"] ):
     Error: the string "Wait element displayed timeout: //*[@text=\"登 录\"] ,30000ms" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@3.1.2@mocha\lib\runner.js:233:11)
      at node_modules\_mocha@3.1.2@mocha\lib\runner.js:566:18
      at done (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:293:5)
      at node_modules\_mocha@3.1.2@mocha\lib\runnable.js:354:11
      at process._tickCallback (internal/process/next_tick.js:109:7)




>> Test completed!

```

**Comment by litingjun2015** [comment]
发现三星手机无法录制脚本
https://github.com/alibaba/macaca/issues/739

**Comment by litingjun2015** [comment]
发现有些操作需要改一下：

> it('tap: 请输入密码 ( //*[@text="请输入密码"] )', async function(){
>         await driver.wait('//*[@text="请输入密码"]', 30000).sendElementActions('tap');
>     });

=>

> it('tap: //*[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.EditText', async function(){
>         await driver.wait('//*[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.EditText', 30000).sendElementActions('tap');
>     });

```
C:\bizapp3\sturdy\BizAppV3\tests\macaca (master) (uirecorderTest@1.0.0)
$ macaca run -p 4444 -d  ./scripts/simple.samsung.js --verbose -o ./output
>> port: 4444 was occupied, changed port: 4445
>> index.js:18:12 [master] pid:7456 webdriver server start with config:
 { port: 4445,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.0.72',
  host: 'macaca',
  loaded_time: '2017-11-02 11:32:28' }
>> middlewares.js:17:10 [master] pid:7456 base middlewares attached
>> router.js:133:10 [master] pid:7456 router set
>> webdriver sdk launched
[ './scripts/simple.samsung.js', '--colors', '--verbose' ]
>>

  scripts/simple.samsung : c0cdc4b1

>>     √ tap: 请输入手机号 ( //*[@text="请输入手机号"] ) (9797ms)

>>     √ sendKeys: demo{ESCAPE} (890ms)

>>     √ tap: //*[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.EditText

>>     √ tap: //*[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.EditText (561ms)

>>     √ sendKeys: 123456{ESCAPE} (828ms)

>>     √ tap: 登 录 ( //*[@text="登 录"] ) (577ms)

>>     √ tap: 登 录 ( //*[@text="登 录"] ) (564ms)

>>

>>
  7 passing (2m)


>> Test completed!
```
