### ISSUE TITLE
Android调用rect方法报错：JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by hivencent** [alibaba/macaca#748]
* **Macaca Version**:
2.0.10
* **Macaca Doctor Logs**:

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/jinlong/Library/Android/sdk`
  Platforms is set to `/Users/jinlong/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/jinlong/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.40
  chrome: 1.0.6 [out-of-date]
  electron: 1.1.11 [out-of-date]
  ios: 2.0.24 [out-of-date]

* **Operate System**:
OS X 10.10.5 

* **Programming Language**:
python 2.7

问题1：在WEBVIEW模式调用rect方法报错：
示例：self.driver.element("xpath","/html/body/div[4]/div/div[2]/div[2]/div[2]/div/div/table/tbody/tr/td[1]/div/div[2]").rect
客户端Log：
Traceback (most recent call last):
  File "/Users/jinlong/Desktop/datebao-app-test/test_case/order_flow.py", line 82, in test_flow
    self._order_flow(product_info)
  File "/Users/jinlong/Desktop/datebao-app-test/test_case/order_flow.py", line 71, in _order_flow
    ProductDetailPage().product_detail_configuration(product_deital_configuration)
  File "/Users/jinlong/Desktop/datebao-app-test/pages/product_deital_page.py", line 27, in product_detail_configuration
    print self.driver.element("xpath","/html/body/div[4]/div/div[2]/div[2]/div[2]/div/div/table/tbody/tr/td[1]/div/div[2]").rect
  File "/Users/jinlong/Desktop/env/lib/python2.7/site-packages/macaca/webelement.py", line 368, in rect
    return self._execute(Command.GET_ELEMENT_RECT)
  File "/Users/jinlong/Desktop/env/lib/python2.7/site-packages/macaca/webelement.py", line 60, in _execute
    return self._driver._execute(command, data, unpack)
  File "/Users/jinlong/Desktop/env/lib/python2.7/site-packages/macaca/webdriver.py", line 66, in _execute
    res = self.remote_invoker.execute(command, data)
  File "/Users/jinlong/Desktop/env/lib/python2.7/site-packages/macaca/remote_invoker.py", line 110, in execute
    return self._request(method, url, body)
  File "/Users/jinlong/Desktop/env/lib/python2.7/site-packages/macaca/remote_invoker.py", line 147, in _request
    return res.json()
  File "/Users/jinlong/Desktop/env/lib/python2.7/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/Users/jinlong/Desktop/env/lib/python2.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/Users/jinlong/Desktop/env/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/jinlong/Desktop/env/lib/python2.7/site-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 1 test in 42.370s

FAILED (errors=1)

服务端Log：
>> proxy.js:59:16 [master] pid:1530 Got response with status 200: {"sessionId":"bcb7fb4dd7285a1c54e9bb6ec9c3ff15","status":27,"value":{"message":"no alert open\n  (Session info: chrome=53.0.2785.49)\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1d...
>> proxy.js:51:14 [master] pid:1530 Proxy: /wd/hub/session/6e6c0598-aa8d-4f36-bde2-d8d825350b86/element/0.8816601663393053-3/rect:GET to http://localhost:9515/wd/hub/session/bcb7fb4dd7285a1c54e9bb6ec9c3ff15/element/0.8816601663393053-3/rect:GET with body: {}
>> proxy.js:59:16 [master] pid:1530 Got response with status 404: "unknown command: session/bcb7fb4dd7285a1c54e9bb6ec9c3ff15/element/0.8816601663393053-3/rect"
>> proxy.js:67:20 [master] pid:1530 Fail to parse body: SyntaxError: Unexpected token u in JSON at position 0
>> session.js:109:14 [master] pid:1530 Send HTTP Respone to Client[2017-11-07 17:11:55]: "unknown command: session/bcb7fb4dd7285a1c54e9bb6ec9c3ff15/element/0.8816601663393053-3/rect"
>> responseHandler.js:11:12 [master] pid:1530 Recieve HTTP Request from Client[2017-11-07 17:11:55]: method: DELETE url: /wd/hub/session/6e6c0598-aa8d-4f36-bde2-d8d825350b86, jsonBody: {}
>> session.js:80:12 [master] pid:1530 Delete session, sessionId: 6e6c0598-aa8d-4f36-bde2-d8d825350b86
>> responseHandler.js:49:14 [master] pid:1530 Send HTTP Respone to Client[2017-11-07 17:11:55]: {"sessionId":"6e6c0598-aa8d-4f36-bde2-d8d825350b86","status":0}

**Comment by xudafeng** [comment]
用 GET_ELEMENT_SIZE 

rect 标准还不支持
