### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by wangtao169447** [alibaba/macaca#763]
* **Macaca Version**:2.0.12

* **Macaca Doctor Logs**:
error info is:
  Error: socket hang up
      at createHangUpError (_http_client.js:331:15)
      at Socket.socketOnEnd (_http_client.js:423:23)
      at emitNone (events.js:111:20)
      at Socket.emit (events.js:208:7)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

* **Operate System**:
app-inspector -u xxxx

Macaca Version: 2.0.12
Macaca Doctor:2.0.4
Platform:mac os High Sierra
xctestwd:1.3.9

**Comment by Chan-Chun** [comment]
Please describe more info
