### ISSUE TITLE
macaca创建avd报错、checking permissionPatterns后报错

### ISSUE THREAD

**Issue by sheeeeep** [alibaba/macaca#779]
* **Macaca Version**:
2.0.12
* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.4

```
  Node.js checklist:

  node env: /Users/caoy/.nvm/versions/node/v9.2.0/bin/node
  node version: v9.2.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.27.0

  Android checklist:

  JAVA version is `1.8.0_144`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/caoy/Library/Android/sdk`
  Platforms is set to `/Users/caoy/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/caoy/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.4

  Installed driver list:

  android: 2.0.43
  chrome: 1.0.7
  ios: 2.0.29
  puppeteer: 1.0.2
```
* **Operate System**:
OSX
* **Programming Language**:
javascript 

执行uirecorder后，macaca创建avd报错，但是从Android Studio启动虚拟机是没问题的
```
no device, now create one from avd
(node:18585) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: /Users/caoy/Library/Android/sdk/tools/emulator -avd undefined
PANIC: Unknown AVD name [undefined], use -list-avds to see valid list.
ANDROID_AVD_HOME is defined but there is no file undefined.ini in $ANDROID_AVD_HOME
(Note: Directories are searched in the order $ANDROID_AVD_HOME, $ANDROID_SDK_HOME/avd, and $HOME/.android/avd)
```
如果先启动虚拟机，然后运行uirecorder，报错如下：
```
>> webdriver sdk launched
>> checking permissionPatterns: []

  Error: Command failed: /Users/caoy/Library/Android/sdk/platform-tools/adb -s emulator-5554 push /Users/caoy/.nvm/versions/node/v9.2.0/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing

      at ChildProcess.exithandler (child_process.js:272:12)
      at ChildProcess.emit (events.js:159:13)
      at maybeClose (internal/child_process.js:943:16)

```

**Comment by Kingatnuaa0528** [comment]
我和你出现一样的问题，请问解决了么？

**Comment by deadvia** [comment]
同此问题

**Comment by Kingatnuaa0528** [comment]
我发现，我这边的报错原因是/opt/android-sdk-macosx/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing

**Comment by Kingatnuaa0528** [comment]
我发现，我这边的问题貌似是：/opt/android-sdk-macosx/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing 这条命令中，apk地址找不到导致的

**Comment by deadvia** [comment]
@Kingatnuaa0528 恩  是这个问题。想办法编译一个apk 就解决了

**Comment by Kingatnuaa0528** [comment]
@deadvia 我编译apk了，只是apk的地址和这个不一致，按照我的理解，macaca应该是会拷贝到指定目录下吧

**Comment by Kingatnuaa0528** [comment]
@deadvia hi，我的问题解决了，原因是macaca-android安装失败。你可以使用cnpm来试一下。安装过程中应该会打出很多日志的。

**Comment by zivyll** [comment]
@sheeeeep  使用 cnpm 试试。
