### ISSUE TITLE
Macaca执行android脚本时报错

### ISSUE THREAD

**Issue by Kingatnuaa0528** [alibaba/macaca#781]
#

* **Macaca Version**:
2.0.13
* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.4

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.25.0

  Android checklist:

  JAVA version is `1.8.0_20`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home`
  ANDROID_HOME is set to `/opt/android-sdk-macosx`
  Platforms is set to `/opt/android-sdk-macosx/platforms/android-26`
  ADB tool is set to `/opt/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 4.4

  Installed driver list:

  android: 2.0.46
  electron: 1.1.19
  ios: 2.0.30
* **Operate System**:

* **Programming Language**:
js

执行macaca脚本时，报错信息如下：
>> responseHandler.js:56:12 [master] pid:13670 Send Error Respone to Client: Error: Command failed: /opt/android-sdk-macosx/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing

>> responseHandler.js:62:14 [master] pid:13670 Error: Command failed: /opt/android-sdk-macosx/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

  Error: Command failed: /opt/android-sdk-macosx/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing

      at ChildProcess.exithandler (child_process.js:204:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:886:16)
      at Socket.<anonymous> (internal/child_process.js:342:11)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at Pipe._handle.close [as _onclose] (net.js:501:12)

report.html的信息如下：
Error: [init({"platformName":"Android","target":"android","slowEnv":false,"autoAcceptAlerts":false,"app":"/Users/hanqing.ghq/program/weex_qa/incubator-weex/android/playground/app/build/outputs/apk/playground-debug.apk"})] The environment you requested was unavailable.
    at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
    at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
    at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
    at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
    at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

请问大神们，这个问题该咋解决？

**Comment by zivyll** [comment]
看看模拟器目录下是不是有 /data/local/tmp/ 目录？

**Comment by xudafeng** [comment]
@Kingatnuaa0528 看样子是没有装成功。重装即可
