### ISSUE TITLE
启动app-inspector时一直提示Error: Cannot find module 'xctestwd'

### ISSUE THREAD

**Issue by xiaolong520lei** [alibaba/macaca#782]
app-inspector版本：app-inspector@2.0.10
mac os 版本：10.12.6
xcode 版本：9.2
启动时报的信息如下：
{ Error: Cannot find module 'xctestwd'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/app-inspector/lib/ios.js:6:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3) code: 'MODULE_NOT_FOUND' }

另外我在/usr/local/lib/node_modules/app-inspector/node_modules目录下没有找到xctestwd 这个文件夹
是不是我安装的时候少了什么呢，为什么会这个样子，求大神帮忙。

**Comment by xiaolong520lei** [comment]
我xcode有问题，已解决

**Comment by AnneJJ** [comment]
请教一下,是怎么解决的呢
