### ISSUE TITLE
An error MacacaJS+UIRecorder

### ISSUE THREAD

**Issue by Haribolka** [alibaba/macaca#791]
I installed and set up Macaca properly on MacBook.
I also installed UIRecorder v.2.5.10, Android Studio with devices (AVD) to emulate Android device and record scripts.

And when starting UIRecorder I get this an error in UIRecorder terminal output:
_Mobile open failed, please check macaca config. Internal Server Error_

And in Macaca output terminal I get this error:

  _InternalServerError: Internal Server Error
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:59:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)_

Please, help.

* **Macaca Version**: 2.0.13
* **Macaca Doctor Logs**:   
Android checklist:
  JAVA version is `1.8.0_162`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/fedor/Library/Android/sdk`
  Platforms is set to `/Users/fedor/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/fedor/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.5
  Installed driver list:
  android: 2.0.46
* **Operation System**: MacOS High Sierra 10.13.1

**Comment by xudafeng** [comment]
装最新版macaca吧
