### ISSUE TITLE
macaca升级之后，doctor检测正常，使用提示MacacaClient Not Found

### ISSUE THREAD

**Issue by Hardworking-tester** [alibaba/macaca#793]
* **问题描述**:macaca升级之后，doctor检测正常，使用提示MacacaClient Not Found
* **问题日志**:
Exception in thread "main" java.lang.NoClassDefFoundError: macaca/client/MacacaClient
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.javademo.cases.Test3.<clinit>(Test3.java:19)
Caused by: java.lang.ClassNotFoundException: macaca.client.MacacaClient
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more

* **Macaca Version**:2.1.0

* **Macaca Doctor Logs**:macaca-doctor version: 2.0.7

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v8.9.2

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_144`
  ANDROID_HOME is set to `F:\software\android-sdk`
  Platforms is set to `F:\software\android-sdk\platforms\android-23`
  ADB tool is set to `F:\software\android-sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\Users\DELL\.gradle\wrapper\dists\gradle-3.3-all\2n0i7hqatcbtk57vvql575dbap\gradle-3.3\bin`

  Installed driver list:

  android: 2.0.46
  chrome: 1.0.7
  electron: 1.1.19

* **Operate System**:win 10X64

* **Programming Language**:CN

**Comment by xudafeng** [comment]
@Hardworking-tester 
maven 配置问题
