### ISSUE TITLE
[已解决]Not accepted Android SDK license agreements

### ISSUE THREAD

**Issue by willysys** [alibaba/macaca#794]
Not accepted Android SDK license agreements 如何解决

当前发现的一些场景：
    如果使用 Android Studio 等工具，在首次启动时，Android Studio 会引导安装 platform-tools 等工具，但是不会要求用户做 licenses accept 的操作。在安装 macaca android 时，如果用户没有 accept 过 android 的licenses，则会出现这个错误。

解决：
1、你可以通过在 Terminate 下运行这个指令，主动的安装 对应的 platforms 等工具，安装过程中，android 会引导你 accept licenses：
${ANDROID_HOME}tools/bin/sdkmanager "build-tools;25.0.2" "platforms;android-26" "extras;android;m2repository"
2、你也可以通过下面的指令，同意所有的 android licenses（包括但不局限于 macaca android 需要使用的licenses)
${ANDROID_HOME}tools/bin/sdkmanager --licenses

备注：我的  {ANDROID_HOME} 环境变量
/Users/.../Library/Android/sdk/

**Comment by willysys** [comment]
提示uiautomatorwd包下的app-debug.apk找不到

**Comment by liyinchigithub** [comment]
window  平台有没有什么解决办法？ @xudafeng @willysys

**Comment by liyinchigithub** [comment]
@Archer456 
解决了，太感谢你了，万分感谢

**Comment by ydx123mike** [comment]
> Not accepted Android SDK license agreements 如何解决
> 
> 当前发现的一些场景：
> 如果使用 Android Studio 等工具，在首次启动时，Android Studio 会引导安装 platform-tools 等工具，但是不会要求用户做 licenses accept 的操作。在安装 macaca android 时，如果用户没有 accept 过 android 的licenses，则会出现这个错误。
> 
> 解决：
> 1、你可以通过在 Terminate 下运行这个指令，主动的安装 对应的 platforms 等工具，安装过程中，android 会引导你 accept licenses：
> ${ANDROID_HOME}tools/bin/sdkmanager "build-tools;25.0.2" "platforms;android-26" "extras;android;m2repository"
> 2、你也可以通过下面的指令，同意所有的 android licenses（包括但不局限于 macaca android 需要使用的licenses)
> ${ANDROID_HOME}tools/bin/sdkmanager --licenses
> 
> 备注：我的 {ANDROID_HOME} 环境变量
> /Users/.../Library/Android/sdk/

Java10以上会报错
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
