### ISSUE TITLE
执行java版macaca脚本，跑移动端用例，服务端显示proxy.js:63:22 [master] pid:8704 UIAutomatorWD client proxy error with: Error: read ECONNRESET

### ISSUE THREAD

**Issue by RuoKing** [alibaba/macaca#800]
服务端日志：
![Uploading 图片.png…]()
>> proxy.js:63:22 [master] pid:8704 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:55:14 [master] pid:8704 Proxy: /wd/hub/session/3a2257cf-9b64-4984-8a55-b532bdc11473/el
ents:POST to http://127.0.0.1:9002/wd/hub/session/3a2257cf-9b64-4984-8a55-b532bdc11473/elements:PO
 with body: {"using":"xpath","value":"//*[@text=\"论坛大全\"]"}
>> proxy.js:63:22 [master] pid:8704 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:8704 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:8704 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> responseHandler.js:11:12 [master] pid:8704 Recieve HTTP Request from Client[2018-03-19 11:15:59
 method: POST url: /wd/hub/session/3a2257cf-9b64-4984-8a55-b532bdc11473/elements, jsonBody: {"usin
:"xpath","value":"//*[@text=\"论坛大全\"]"}
>> proxy.js:63:22 [master] pid:8704 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:8704 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:8704 UIAutomatorWD client proxy error with: Error: read ECONNRESET

脚本端日志：
org.apache.http.NoHttpResponseException: localhost:3456 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at macaca.client.common.Utils.postRequest(Utils.java:117)
	at macaca.client.common.Utils.request(Utils.java:162)
	at macaca.client.MacacaClient.findElements(MacacaClient.java:206)
	at macaca.client.MacacaClient.elementsByXPath(MacacaClient.java:621)
	at macaca.client.MacacaClient.getElement(MacacaClient.java:330)
	at macaca.client.MacacaClient.isElementExist(MacacaClient.java:959)
	at macaca.java.biz.BaseMacacaClient.isElementExist(BaseMacacaClient.java:124)
	at macaca.java.biz.BaseMacacaClient.isElementExistAfterWaiting(BaseMacacaClient.java:161)
	at macaca.java.biz.Assertions.AssertionTextEquals(Assertions.java:39)
	at com.javademo.cases.ShouTest.a_shouYe_init(ShouTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
attempt to search the element for 0 times
2018-03-19 11:13:59 Request:http://localhost:3456/wd/hub/session/3a2257cf-9b64-4984-8a55-b532bdc11473/elements:{"using":"xpath","value":"//*[@text=\"论坛大全\"]"}
org.apache.http.NoHttpResponseException: localhost:3456 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at macaca.client.common.Utils.postRequest(Utils.java:117)
	at macaca.client.common.Utils.request(Utils.java:162)
	at macaca.client.MacacaClient.findElements(MacacaClient.java:206)
	at macaca.client.MacacaClient.elementsByXPath(MacacaClient.java:621)
	at macaca.client.MacacaClient.getElement(MacacaClient.java:330)
	at macaca.client.MacacaClient.isElementExist(MacacaClient.java:959)
	at macaca.client.MacacaClient.waitForElement(MacacaClient.java:476)
	at macaca.java.biz.BaseMacacaClient.waitForElement(BaseMacacaClient.java:94)
	at macaca.java.biz.BaseMacacaClient.isElementExistAfterWaiting(BaseMacacaClient.java:164)
	at macaca.java.biz.Assertions.AssertionTextEquals(Assertions.java:39)
	at com.javademo.cases.ShouTest.a_shouYe_init(ShouTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
attempt to search the element for 1 times

**Comment by feng317** [comment]
几乎每次都能出现

**Comment by YuanJiaShuai** [comment]
同样每次都会出现

**Comment by xinxinga** [comment]
有解决方案吗？同样问题
Xcode 10.2 + mac os 10.14.5

**Comment by BeForever** [comment]
有解决方案吗？同样问题
Xcode 10.3 + mac os 10.14.6 macaca 2.2.0
