### ISSUE TITLE
>> android.util.AndroidException: INSTRUMENTATION_FAILED: com.macaca.android.testing.test/android.support.test.runner.AndroidJUnitRunner

### ISSUE THREAD

**Issue by liyinchigithub** [alibaba/macaca#801]
执行app-inspector -u 2f1c68127cf4 
提示
>> android.util.AndroidException: INSTRUMENTATION_FAILED: com.macaca.android.testing.test/android.support.test.runner.AndroidJUnitRunner

>>      at com.android.commands.am.Am.runInstrument(Am.java:898)
        at com.android.commands.am.Am.onRun(Am.java:406)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:124)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

-------------------------------------------------------------------------------------
* **Macaca Version**: 2.1.2

* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.10

  Node.js checklist:

  node env: C:\lyc\nodejs\node.exe
  node version: v8.9.3

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `C:\lyc\Java`
  ANDROID_HOME is set to `C:\lyc\android-sdk-windows_SDK24API21`
  Platforms is set to `C:\lyc\android-sdk-windows_SDK24API21\platforms\android-25`
  ADB tool is set to `C:\lyc\android-sdk-windows_SDK24API21\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\lyc\gradle-4.1-bin\gradle-4.1`

  Installed driver list:

  android: 2.0.47
  chrome: 1.0.7

* **Operate System**:wind10

* **Programming Language**: java

**Comment by liyinchigithub** [comment]
完整内容，如下：
C:\Users\admin>macaca server --verbose
>> index.js:18:12 [master] pid:12528 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '192.168.5.188',
  host: 'DESKTOP-2F1BIDV',
  loaded_time: '2018-03-20 13:57:59' }
>> middlewares.js:17:10 [master] pid:12528 base middlewares attached
>> router.js:133:10 [master] pid:12528 router set
>> Macaca server started
>> responseHandler.js:11:12 [master] pid:12528 Recieve HTTP Request from Client[2018-03-20 13:58:15]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"browserName":"Chrome","platformName":"android","autoAcceptAlerts":true}}
>> session.js:58:10 [master] pid:12528 Creating session, sessionId: 4102ba76-35d3-4dbb-b78c-85bf064dd97a.
>> checking permissionPatterns: []
>> uiautomator-client.js:31:12 [master] pid:12528 Error: Command failed: C:\lyc\android-sdk-windows_SDK24API21/platform-tools/adb -s 2f1c68127cf4 shell "pm clear "com.macaca.android.testing""
Failed

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
>> android.util.AndroidException: INSTRUMENTATION_FAILED: com.macaca.android.testing.test/android.support.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Am.runInstrument(Am.java:898)

>> uiautomator-client.js:75:14 [master] pid:12528 INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.macaca.android.testing.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1

>>      at com.android.commands.am.Am.onRun(Am.java:406)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:124)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Comment by liyinchigithub** [comment]
补充：
Android 5.0以下的是可以

C:\Users\admin>adb -s 4200b99c4f571379 shell "pm clear "com.macaca.android.testing""
Success

Android 7.1.2便失败

adb -s 2f1c68127cf4 shell "pm clear "com.macaca.android.testing""
Failed

**Comment by xudafeng** [comment]
@zhangyuheng
