### ISSUE TITLE
XCTestWD.XCTestWD 不存在

### ISSUE THREAD

**Issue by ca-ssiee** [alibaba/macaca#803]
xcode导入开发者证书和配置文件后 Bundle Identifier 必须是以com.au开头，以致于在对xctestwd.xcodeproj进行冲签名时必须改成com.开头
这样在运行uirecorder 时 一直提示XCTestWD.XCTestWD 不存在

BundleId XCTestWD.XCTestWD does not exist.
xctest-client.js:195:18 [master] pid:13137 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:195:18 [master] pid:13137 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:281:14 [master] pid:13137 killing deviceLogProc pid: 13534
>> xctest-client.js:286:14 [master] pid:13137 killing runnerProc pid: 13506
>> xctest-client.js:206:16 [master] pid:13137 xctest client exit with code: 65, signal: null
>> xctest-client.js:161:16 [master] pid:13137 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:273:14 [master] pid:13137 Fail to start xctest: undefined
>> responseHandler.js:54:12 [master] pid:13137 Send Error Respone to Client: undefined

  InternalServerError: Internal Server Error
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:57:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by SamuelZhaoY** [comment]
参考该问题： https://github.com/alibaba/macaca/issues/782  检查xcode 版本， Bundle ID 没要求
