### ISSUE TITLE
macaca-ios报错Cannot find module 'xctestwd-frameworks-94'

### ISSUE THREAD

**Issue by wishchen** [alibaba/macaca#811]
用iOS真机做测试安装macaca-ios报错Cannot find module 'xctestwd-frameworks-94'
### 环境
Mac: macOS 10.13.4
xcode: Version 9.4 beta 
`npm i -g macaca-ios`报错
```
> xctestwd@1.3.28 install /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd
> node ./scripts/install.js

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'xctestwd-frameworks-94'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/scripts/install.js:71:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xctestwd@1.3.28 install: `node ./scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xctestwd@1.3.28 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
xctestwd-frameworks-94 没有找到对应的安装方法，这时候我要降xcode版本吗

**Comment by xudafeng** [comment]
@wishchen 重装一下

**Comment by wishchen** [comment]
@xudafeng  试了多次`npm i -g macaca-ios`没有解决,   把xcode降到了9.3 ok了

**Comment by SamuelZhaoY** [comment]
94 版本的依赖没找到吗

**Comment by xudafeng** [comment]
重装即可

https://github.com/macacajs/XCTestWD/commit/21352e36481d107009692f6900ca7f473a246051

**Comment by ManningZhang** [comment]
@xudafeng @macaca-bot @wishchen 我也遇到类似的情况，请问下是重装xcode即可吗？
