### ISSUE TITLE
macaca-ios报错Cannot find module 'xctestwd-frameworks-93.1'

### ISSUE THREAD

**Issue by chaozhangpower** [alibaba/macaca#819]
用iOS真机做测试安装macaca-ios报错Cannot find module 'xctestwd-frameworks-94'

环境
Mac: macOS 10.13.4
xcode: Version 9.3.1 (9E501)
cnpm i -g macaca-ios报错

[2/4] scripts.install xctestwd@1.3.29 › ios-utils@1.0.5 › devicelog@^1.0.2 finished in 1s
[3/4] scripts.install uiautomatorwd@* run "node ./scripts/build.js"
(node:4165) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ,,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

(node:4165) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3/4] scripts.install uiautomatorwd@* finished in 926ms
[4/4] scripts.install xctestwd@* run "node ./scripts/install.js"
module.js:544
    throw err;
    ^

Error: Cannot find module 'xctestwd-frameworks-93.1'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.29@xctestwd/scripts/install.js:71:21)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
xctestwd@* optional error: Error: Run "sh -c node ./scripts/install.js" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

xctestwd-frameworks-93.1 没有找到对应的支持库，需要如何安装

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/commit/e526232b494fb84b726ac547f548f034ba1fd504

**Comment by chaozhangpower** [comment]
Thanks
