### ISSUE TITLE
macaca在微信里点击某个小程序之后用.contexts()方法只获取到NATIVE_APP

### ISSUE THREAD

**Issue by ZTinoZ** [alibaba/macaca#824]
* **Macaca Version**:macaca-cli@2.1.2

* **Macaca Doctor Logs**:macaca-doctor version: 2.0.14

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.0.0 lower than v8.9.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3 lower than 9.2.0
{ Error: Command failed: which iproxy

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12) killed: false, code: 1, signal: null, cmd: 'which iproxy' }
  Command Line Tools: iproxy[usbmuxd] is uninstalled
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/Tino/Library/Android/sdk`
  Platforms is set to `/Users/Tino/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/Tino/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.7

  Installed driver list:

  android: 2.0.47
  chrome: 1.0.7
  electron: 2.0.3

* **Operate System**:macOS Sierra 版本：10.12.5 (16F73)

* **Programming Language**:nodejs

macaca在微信里点击某个小程序之后用.contexts()方法只获取到NATIVE_APP，照理应该还会有webview，而且如果用.currentContext()会显示null，请问是什么原因，初始化配置如下：
platformName: 'Android',
        platformVersion: '5.0.2',
        package: 'com.tencent.mm',
        activity: '.ui.LauncherUI',
        deviceName: '722c0f3e',//(MI 2)

**Comment by ZTinoZ** [comment]
已解决 安装TBS工具集即可
