### ISSUE TITLE
录制自动化脚本后，回放报错

### ISSUE THREAD

**Issue by taoziwyy** [alibaba/macaca#833]
PeachMacBook-Pro:~ wangyueying$ mocha test.Android2.js

  test.Android2 : WJX7N17318006668
    1) "before all" hook
    2) "after all" hook

  0 passing (20ms)
  2 failing

  1) test.Android2 : WJX7N17318006668
       "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object._errnoException (util.js:1022:11)
      at _exceptionWithHostPort (util.js:1044:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

  2) test.Android2 : WJX7N17318006668
       "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object._errnoException (util.js:1022:11)
      at _exceptionWithHostPort (util.js:1044:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

以上是报错log～新手尝试UIrecorder录制自动化～

**Comment by Stngle** [comment]
运行 npm run server ，启动 selenium standalone
