### ISSUE TITLE
iphone应用放置后台再调用api，session会断开

### ISSUE THREAD

**Issue by ztwo** [alibaba/macaca#839]
* **Macaca Version**:
2.1.3
* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.14

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.11.3

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.4.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home`
  ANDROID_HOME is not set
  gradle is installed, version: 4.9

  Installed driver list:

  ios: 2.0.34

* **Operate System**:
osx10.13.2 iphone模拟器

* **Programming Language**:
python2.7

测试环境：iphone虚拟机11.4

* 现象简述：启动macaca后，暂停调用macaca api，回到桌面，此时调用api(例如source)，xctest-client会报错
* 问题：为何使用app-inspector时，桌面状态下，并不会报错？

* 为何问此问题：长期使用macaca，iphone用例峰值接近300条，使用模拟器执行，xctest-client经常性偶发崩溃，通过排查，应用崩溃（无任何规律），会导致xctest-client崩溃

* 尝试过的方案：猜测xctest-client报错是因为发现异常，重试机制导致了session断开。
注释了xctestwd/lib/xctest-client.js 78行  retry方法（仅去掉了外层），依然会有问题

* 想要什么解决方案：可以像app-inspector一样，停留在桌面情况下，xctest-client不崩溃的解决方法吗？

```log
>> xctest-client.js:97:20 [master] pid:26484     t =    46.92s Find the Application "com.xxx.xxx" 0x6000000dcb60

>> xctest-client.js:97:20 [master] pid:26484     t =    46.92s     Snapshot accessibility hierarchy for app with pid 26690

>> xctest-client.js:97:20 [master] pid:26484     t =    47.93s     Find the Application "com.xxx.xxx" 0x6000000dcb60 (retry 1)

>> xctest-client.js:97:20 [master] pid:26484     t =    47.93s         Snapshot accessibility hierarchy for app with pid 26690

>> xctest-client.js:97:20 [master] pid:26484     t =    48.93s     Find the Application "com.xxx.xxx" 0x6000000dcb60 (retry 2)

>> xctest-client.js:97:20 [master] pid:26484     t =    48.93s         Snapshot accessibility hierarchy for app with pid 26690

>> xctest-client.js:97:20 [master] pid:26484     t =    49.02s     Assertion Failure: XCTestWDRunner.swift:31: Error getting main window -25215

>> xctest-client.js:97:20 [master] pid:26484 Fatal error: Unexpectedly found nil while unwrapping an Optional value

>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:97:20 [master] pid:26484 2018-08-02 16:59:51.813000+0800 XCTestWDUITests-Runner[26689:734069] Fatal error: Unexpectedly found nil while unwrapping an Optional value

>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:97:20 [master] pid:26484 2018-08-02 17:00:11.731838+0800 XCTestWDUITests-Runner[26836:737012] +[CATransaction synchronize] called within transaction

>> xctest-client.js:97:20 [master] pid:26484 2018-08-02 17:00:11.803277+0800 XCTestWDUITests-Runner[26836:737012] Running tests...

>> proxy.js:63:22 [master] pid:26484 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:56:12 [master] pid:26484 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:62:14 [master] pid:26484 Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

>> xctest-client.js:97:20 [master] pid:26484 2018-08-02 17:00:12.230580+0800 XCTestWDUITests-Runner[26836:737012] Continuing to run tests in the background with task ID 1

>> xctest-client.js:97:20 [master] pid:26484 
Restarting after unexpected exit or crash in XCTextWDRunner/testRunner(); summary will include totals from previous launches.


>> xctest-client.js:97:20 [master] pid:26484 Test Suite 'Selected tests' started at 2018-08-02 17:00:13.043

>> xctest-client.js:97:20 [master] pid:26484 Test Suite 'XCTestWDUITests.xctest' started at 2018-08-02 17:00:13.044

>> xctest-client.js:97:20 [master] pid:26484 Test Suite 'XCTestWDUITests.xctest' failed at 2018-08-02 17:00:13.045.
     Executed 1 test, with 2 failures (0 unexpected) in 0.000 (0.001) seconds
Test Suite 'Selected tests' failed at 2018-08-02 17:00:13.046.
     Executed 1 test, with 2 failures (0 unexpected) in 0.000 (0.003) seconds

>> xctest-client.js:97:20 [master] pid:26484 LLVM Profile Error: Failed to write file "default.profraw": Permission denied

>> xctest-client.js:195:18 [master] pid:26484 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.3.31@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:281:14 [master] pid:26484 killing deviceLogProc pid: 26515
>> xctest-client.js:286:14 [master] pid:26484 killing runnerProc pid: 26496
>> xctest-client.js:206:16 [master] pid:26484 xctest client exit with code: 65, signal: null
>> xctest-client.js:119:18 [master] pid:26484 simulator log process exit with code: null, signal: SIGKILL
```

**Comment by xingtao555** [comment]
解决了吗

**Comment by xudafeng** [comment]
目前没有压后台保活的办法
