### ISSUE TITLE
IOS里webview找到元素操作不了，报错not implemented yet,尝试用js触发点击还是报错，报错信息Can't find variable: $

### ISSUE THREAD

**Issue by luckerlion** [alibaba/macaca#840]
* **Macaca Version**: 2.1.3

* **Macaca Doctor Logs**: 
macaca-doctor version: 2.0.14

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.9.1 lower than v8.9.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.4.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/***/Downloads/android-sdk-macosx`
  Platforms is set to `/Users/***/Downloads/android-sdk-macosx/platforms/android-27`
  ADB tool is set to `/Users/***/Downloads/android-sdk-macosx/platform-tools/adb`
  Not accepted Android SDK license agreements
  gradle is installed, version: 4.3

  Installed driver list:

  android: 2.0.47 [out-of-date]
  chrome: 1.0.7
  electron: 1.1.17 [out-of-date]
  ios: 2.0.34

* **Operate System**: 
mac10.13.6 
IOS 11.3   + webview

* **Programming Language**: java

基本环境信息上面已写，应用本身是一个hybrid应用，当脚本运行到一个webview页面时，切换content到正确的webview页面，调用driver.source()可以打印web页面信息，通过xpath能查找到元素，但是再点击的时候报错，报错信息：
NotImplementedError: The method is not implemented yet.
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/.1.1.2@koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/.1.1.6@webdriver-server/lib/server/responseHandler.js:81:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/.4.6.0@co/index.js:81:24)
      at <anonymous>
      at runMicrotasksCallback (internal/process/next_tick.js:121:5)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

卡在这里不知怎么解决，于是想到这是个webview页面或者可以用jquery来操作元素，driver.execute("$('.verify-icon message').click()");
但是调用这个方法还是报错，Can't find variable: $      这下就真的纠结了，求助

**Comment by neohob** [comment]
把键盘隐藏掉试试

**Comment by SamuelZhaoY** [comment]
尝试一下其他的方法： /webdriver-dfn-error-code.js:errors['NotImplementedError'] = customizeError('NotImplementedError', 'The method is not implemented yet.' 说明这个click 函数找不到， 整体API 使用参考这里 https://macacajs.github.io/macaca-wd/
