### ISSUE TITLE
我的Android应用中集成了X5内核，无法切换WebView Context

### ISSUE THREAD

**Issue by 7-nights** [alibaba/macaca#848]
* **Macaca Version**:
2.1.3

* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.14

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.11.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
{ Error: Command failed: xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.exports.getXcodeVersion (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:39:38)
    at Object.exports.xcodeBuild (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:51:30)
    at exports.xcodeBuild.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at <anonymous>
  error: null,
  cmd: 'xcodebuild -version',
  file: '/bin/sh',
  args: [ '/bin/sh', '-c', 'xcodebuild -version' ],
  options: 
   { shell: true,
     file: '/bin/sh',
     args: [ '/bin/sh', '-c', 'xcodebuild -version' ],
     envPairs: 
      [ 'ANDROID_HOME=/Users/zhulingfeng/Library/Android/sdk',
        'TERM=xterm-256color',
        'SHELL=/bin/bash',
        'TMPDIR=/var/folders/54/l1hmy7hs29909bhznykw72dr0000gp/T/',
        'GRADLE_HOME=/Applications/Android Studio.app/Contents/gradle/gradle-4.1',
        'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.y6rBQWSiKj/Render',
        'USER=zhulingfeng',
        'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.woPPfQWsH1/Listeners',
        '__CF_USER_TEXT_ENCODING=0x1F6:0x19:0x34',
        'MAVEN_HOME=/Users/zhulingfeng/Library/apache-maven-3.5.4',
        'PATH=/Users/zhulingfeng/Library/apache-maven-3.5.4/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin::/Users/zhulingfeng/Library/Android/sdk/emulator:/Users/zhulingfeng/Library/Android/sdk/tools:/Users/zhulingfeng/Library/Android/sdk/platform-tools:/Applications/Android Studio.app/Contents/gradle/gradle-4.1/bin',
        'PWD=/Users/zhulingfeng/StudioProjects/sample-java',
        'JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home',
        'XPC_FLAGS=0x0',
        'XPC_SERVICE_NAME=0',
        'SHLVL=1',
        'HOME=/Users/zhulingfeng',
        'LOGNAME=zhulingfeng',
        'LC_CTYPE=zh_CN.UTF-8',
        '_=/usr/local/bin/macaca' ],
     killSignal: undefined,
     stdio: [ [Object], [Object], [Object] ] },
  envPairs: 
   [ 'ANDROID_HOME=/Users/zhulingfeng/Library/Android/sdk',
     'TERM=xterm-256color',
     'SHELL=/bin/bash',
     'TMPDIR=/var/folders/54/l1hmy7hs29909bhznykw72dr0000gp/T/',
     'GRADLE_HOME=/Applications/Android Studio.app/Contents/gradle/gradle-4.1',
     'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.y6rBQWSiKj/Render',
     'USER=zhulingfeng',
     'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.woPPfQWsH1/Listeners',
     '__CF_USER_TEXT_ENCODING=0x1F6:0x19:0x34',
     'MAVEN_HOME=/Users/zhulingfeng/Library/apache-maven-3.5.4',
     'PATH=/Users/zhulingfeng/Library/apache-maven-3.5.4/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin::/Users/zhulingfeng/Library/Android/sdk/emulator:/Users/zhulingfeng/Library/Android/sdk/tools:/Users/zhulingfeng/Library/Android/sdk/platform-tools:/Applications/Android Studio.app/Contents/gradle/gradle-4.1/bin',
     'PWD=/Users/zhulingfeng/StudioProjects/sample-java',
     'JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home',
     'XPC_FLAGS=0x0',
     'XPC_SERVICE_NAME=0',
     'SHLVL=1',
     'HOME=/Users/zhulingfeng',
     'LOGNAME=zhulingfeng',
     'LC_CTYPE=zh_CN.UTF-8',
     '_=/usr/local/bin/macaca' ],
  stderr: <Buffer 78 63 6f 64 65 2d 73 65 6c 65 63 74 3a 20 65 72 72 6f 72 3a 20 74 6f 6f 6c 20 27 78 63 6f 64 65 62 75 69 6c 64 27 20 72 65 71 75 69 72 65 73 20 58 63 ... >,
  stdout: <Buffer >,
  pid: 4390,
  output: 
   [ null,
     <Buffer >,
     <Buffer 78 63 6f 64 65 2d 73 65 6c 65 63 74 3a 20 65 72 72 6f 72 3a 20 74 6f 6f 6c 20 27 78 63 6f 64 65 62 75 69 6c 64 27 20 72 65 71 75 69 72 65 73 20 58 63 ... > ],
  signal: null,
  status: 1 }
  Xcode is uninstalled
{ Error: Command failed: which iproxy

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) killed: false, code: 1, signal: null, cmd: 'which iproxy' }
  Command Line Tools: iproxy[usbmuxd] is uninstalled
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zhulingfeng/Library/Android/sdk`
  Platforms is set to `/Users/zhulingfeng/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/zhulingfeng/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.6

  Installed driver list:

  android: 2.0.48

* **Operate System**:
macOS 10.13.6
Darwin daminimafeng.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

* **Programming Language**:
Java

我的应用中集成了X5内核，在使用macaca对WebView进行测试时，无法切换context，只能获取到NATIVE_APP。
log：
2018-09-05 10:34:10 Request:http://localhost:3456/wd/hub/session/7e28a906-1a1f-4b2a-83f6-113dbddc752a/contexts
2018-09-05 10:34:13 Response:{"sessionId":"7e28a906-1a1f-4b2a-83f6-113dbddc752a","status":0,"value":["NATIVE_APP"]}
2018-09-05 10:34:13 Request:http://localhost:3456/wd/hub/session/7e28a906-1a1f-4b2a-83f6-113dbddc752a/context:{"name":"NATIVE_APP"}
2018-09-05 10:34:13 Response:{"sessionId":"7e28a906-1a1f-4b2a-83f6-113dbddc752a","status":0,"value":null}
2018-09-05 10:34:15 Request:http://localhost:3456/wd/hub/session/7e28a906-1a1f-4b2a-83f6-113dbddc752a/element:{"using":"css","value":"#main-banner"}
2018-09-05 10:34:16 Response:{"sessionId":"7e28a906-1a1f-4b2a-83f6-113dbddc752a","value":"Argument was an invalid selector (e.g. XPath/CSS).","status":32}
2018-09-05 10:34:16 Response:{"sessionId":"7e28a906-1a1f-4b2a-83f6-113dbddc752a","status":0}
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 42.046 sec <<< FAILURE!
testCaseOne(macaca.client.AndroidSampleTest)  Time elapsed: 41.643 sec  <<< ERROR!
java.lang.Exception: Argument was an invalid selector (e.g. XPath/CSS).
        at macaca.client.common.Utils.handleStatus(Utils.java:162)
        at macaca.client.common.Utils.executeRequest(Utils.java:71)
        at macaca.client.common.Utils.postRequest(Utils.java:119)
        at macaca.client.common.Utils.request(Utils.java:140)
        at macaca.client.MacacaClient.findElement(MacacaClient.java:190)
        at macaca.client.MacacaClient.elementByCss(MacacaClient.java:263)
        at macaca.client.AndroidSampleTest.runOneTest(AndroidSampleTest.java:103)
        at macaca.client.AndroidSampleTest.testCaseOne(AndroidSampleTest.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Tests in error: 
  testCaseOne(macaca.client.AndroidSampleTest): Argument was an invalid selector (e.g. XPath/CSS).

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.440 s
[INFO] Finished at: 2018-09-05T10:34:16+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project macacatestsample: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/zhulingfeng/StudioProjects/sample-java/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by luckerlion** [comment]
这种问题没法解，你只能让开发在测试包里面不要用X5内核改用源生内核
