### ISSUE TITLE
在执行click时报错An element could not be located on the page using the given search parameters

### ISSUE THREAD

**Issue by wolp6635236** [alibaba/macaca#852]
* **Macaca Version**:
 2.0.14
* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.14

 Node.js checklist:

 node env: D:\Program Files\nodejs\node.exe
 node version: v8.11.1

 Android checklist:

 JAVA version is `1.8`
 JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_171`
 ANDROID_HOME is set to `D:\Android\android-sdk`
 Platforms is set to `D:\Android\android-sdk\platforms\android-28`
 ADB tool is set to `D:\Android\android-sdk\platform-tools\adb.exe`
 GRADLE_HOME is set to `D:\ChromeDownloads\gradle-4.10-all\gradle-4.10`

 Installed driver list:

 android: 2.0.48
* **Operate System**:
win7
* **Programming Language**:
java

操作步骤：
启动微信--点击进入发现页面
结果：
相同的xpath，用getText()方法可以获取到文本信息，使用click()方法却提示报找不到元素；

![image](https://user-images.githubusercontent.com/34854205/45741396-0ac2ff80-bc2a-11e8-8a0e-d8ea4893984b.png)

`2018-09-19 16:25:38 Request:http://localhost:3456/wd/hub/session:{"desiredCapabilities":{"reuse":3,"package":"com.tencent.mm","platformVersion":"7.1.2","platformName":"android","udid":"345b70469805","deviceName":"xiaomi","autoAcceptAlerts":true}}
2018-09-19 16:26:00 Response:{"sessionId":"ee728471-d9c7-4316-867d-b9bb7c0d5ba1","status":0,"value":{"reuse":3,"package":"com.tencent.mm","platformVersion":"7.1.2","platformName":"android","udid":"345b70469805","deviceName":"xiaomi","autoAcceptAlerts":true}}
2018-09-19 16:26:05 Request:http://localhost:3456/wd/hub/session/ee728471-d9c7-4316-867d-b9bb7c0d5ba1/element:{"using":"xpath","value":"//*[@text='发现']"}
2018-09-19 16:26:06 Response:{"status":0,"value":{"ELEMENT":"1"},"sessionId":"ee728471-d9c7-4316-867d-b9bb7c0d5ba1"}
2018-09-19 16:26:06 Request:http://localhost:3456/wd/hub/session/ee728471-d9c7-4316-867d-b9bb7c0d5ba1/element/1/text
2018-09-19 16:26:06 Response:{"status":0,"value":"发现","sessionId":"ee728471-d9c7-4316-867d-b9bb7c0d5ba1"}
获取到的文本:+++++++发现
2018-09-19 16:26:07 Request:http://localhost:3456/wd/hub/session/ee728471-d9c7-4316-867d-b9bb7c0d5ba1/element:{"using":"xpath","value":"//*[@text='发现']"}
2018-09-19 16:26:08 Response:{"status":0,"value":{"ELEMENT":"2"},"sessionId":"ee728471-d9c7-4316-867d-b9bb7c0d5ba1"}
2018-09-19 16:26:08 Request:http://localhost:3456/wd/hub/session/ee728471-d9c7-4316-867d-b9bb7c0d5ba1/element/2/click:{}
Exception in thread "main" java.lang.Exception: An element could not be located on the page using the given search parameters.
	at macaca.client.common.Utils.handleStatus(Utils.java:162)
	at macaca.client.common.Utils.executeRequest(Utils.java:71)
	at macaca.client.common.Utils.postRequest(Utils.java:119)
	at macaca.client.common.Utils.request(Utils.java:140)
	at macaca.client.commands.Element.click(Element.java:75)
	at cases.SimpleTest2.main(SimpleTest2.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
2018-09-19 16:26:08 Response:{"status":7,"value":"An element could not be located on the page using the given search parameters.","sessionId":"ee728471-d9c7-4316-867d-b9bb7c0d5ba1"}

Process finished with exit code 1`

**Comment by quxiaozha** [comment]
在手机的应用程序管理里边把macaca的那两个apk卸载，再跑试试

**Comment by wolp6635236** [comment]
> 在手机的应用程序管理里边把macaca的那两个apk卸载，再跑试试

非常感谢你的回答

我将macaca的两个apk卸载之后，重新跑用例，会再次安装com.macaca.android.testing.test这个apk。然后在微信中还是无法点击‘发现’这个按钮；

烦请看下以下脚本及日志，如果有遇到过这样的问题还请不吝赐教；

代码：
`package cases;

import com.alibaba.fastjson.JSONObject;
import macaca.client.MacacaClient;


public class SimpleTest2 {
    static MacacaClient driver = new MacacaClient();

    public static void setup() throws Exception {
        JSONObject porps = new JSONObject();
        porps.put("autoAcceptAlerts", true);
        porps.put("platformVersion", "7.1.2");
        porps.put("deviceName", "xiaomi");
        porps.put("platformName", "android");
        porps.put("udid", "345b70469805");
        porps.put("reuse", 3);
        porps.put("package", "com.tencent.mm");
        porps.put("activity", ".ui.LauncherUI");
        porps.put("androidProcess", "com.tencent.mm:appbrand0");
        JSONObject desiredCapabilities = new JSONObject();
        desiredCapabilities.put("desiredCapabilities", porps);
        driver.initDriver(desiredCapabilities);
    }

    public static void main(String[] args) throws Exception {
        setup();
        driver.sleep(5000);
        System.out.println("获取到的文本:+++++++"+driver.elementByXPath("//*[@text='发现']").getText());
        driver.sleep(1000);
        driver.elementByXPath("//*[@text='发现']").click();




        Thread.sleep(5000);
        driver.quit();
    }

}`

log：
`2018-09-27 17:39:04 Request:http://localhost:3456/wd/hub/session:{"desiredCapabilities":{"reuse":3,"package":"com.tencent.mm","activity":".ui.LauncherUI","platformVersion":"7.1.2","androidProcess":"com.tencent.mm:appbrand0","platformName":"android","udid":"345b70469805","deviceName":"xiaomi","autoAcceptAlerts":true}}
2018-09-27 17:39:25 Response:{"sessionId":"6a049da5-76b4-437e-9a5c-c27895d1dbd2","status":0,"value":{"reuse":3,"package":"com.tencent.mm","activity":".ui.LauncherUI","platformVersion":"7.1.2","androidProcess":"com.tencent.mm:appbrand0","platformName":"android","udid":"345b70469805","deviceName":"xiaomi","autoAcceptAlerts":true}}
2018-09-27 17:39:30 Request:http://localhost:3456/wd/hub/session/6a049da5-76b4-437e-9a5c-c27895d1dbd2/element:{"using":"xpath","value":"//*[@text='发现']"}
2018-09-27 17:39:31 Response:{"status":0,"value":{"ELEMENT":"1"},"sessionId":"6a049da5-76b4-437e-9a5c-c27895d1dbd2"}
2018-09-27 17:39:31 Request:http://localhost:3456/wd/hub/session/6a049da5-76b4-437e-9a5c-c27895d1dbd2/element/1/text
2018-09-27 17:39:31 Response:{"status":0,"value":"发现","sessionId":"6a049da5-76b4-437e-9a5c-c27895d1dbd2"}
获取到的文本:+++++++发现
2018-09-27 17:39:32 Request:http://localhost:3456/wd/hub/session/6a049da5-76b4-437e-9a5c-c27895d1dbd2/element:{"using":"xpath","value":"//*[@text='发现']"}
2018-09-27 17:39:33 Response:{"status":0,"value":{"ELEMENT":"2"},"sessionId":"6a049da5-76b4-437e-9a5c-c27895d1dbd2"}
2018-09-27 17:39:33 Request:http://localhost:3456/wd/hub/session/6a049da5-76b4-437e-9a5c-c27895d1dbd2/element/2/click:{}
2018-09-27 17:39:34 Response:{"status":7,"value":"An element could not be located on the page using the given search parameters.","sessionId":"6a049da5-76b4-437e-9a5c-c27895d1dbd2"}
Exception in thread "main" java.lang.Exception: An element could not be located on the page using the given search parameters.
	at macaca.client.common.Utils.handleStatus(Utils.java:162)
	at macaca.client.common.Utils.executeRequest(Utils.java:71)
	at macaca.client.common.Utils.postRequest(Utils.java:119)
	at macaca.client.common.Utils.request(Utils.java:140)
	at macaca.client.commands.Element.click(Element.java:75)
	at cases.SimpleTest2.main(SimpleTest2.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1`

**Comment by quxiaozha** [comment]
建议升级一下macaca和安卓驱动试一下，我本地用你的代码测试是ok的，可以点击。我的Macaca版本是2.1.3，android: 2.0.48

**Comment by wolp6635236** [comment]
> 建议升级一下macaca和安卓驱动试一下，我本地用你的代码测试是ok的，可以点击。我的Macaca版本是2.1.3，android: 2.0.48

我的版本号都给你一样，我换了两个小米手机都不行，最后换了魅族的手机。。可以正确执行了~~ 虽然不知道什么原因，还是很感谢你。
