### ISSUE TITLE
xcode更新版本后，macaca doctor提示Xcode is uninstalled

### ISSUE THREAD

**Issue by saling** [alibaba/macaca#853]
* **Macaca Version**:
2.1.3

* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.11.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
TypeError: Invalid Version: 9.4.1.0
    at new SemVer (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:305:11)
    at compare (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:578:10)
    at Function.lt (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:612:10)
    at Object.exports.xcodeBuild (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:56:16)
    at exports.xcodeBuild.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Xcode is uninstalled
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/saling/Library/Android/sdk`
  Platforms is set to `/Users/saling/Library/Android/sdk/platforms/android-28`
  ADB tool is set to `/Users/saling/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  android: 2.0.48
  electron: 2.0.3
  ios: 2.0.34

* **Operate System**:
Darwin LINGLINGXIA-MB0 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

* **Programming Language**:

1、更新xcode后，出现该问题，然后更新了mac操作系统的版本为10.13.6，问题还是复现
2、卸载macaca-cli ，然后删除bin目录下的macaca 软连接和/usr/local/lib/node_modules/macaca-cli 目录
3、sudo npm install -g npm@latest  
以上步骤后，该问题还是存在，跪求该问题如何解决呢？

**Comment by zhenwei12138** [comment]
ios.js 中 semver.lt(version, MIN_VERSION) 报错。可以手动改一下iOS.js 的源码。

**Comment by xudafeng** [comment]
@saling 升级系统，重装即可

**Comment by sisiea** [comment]
> This is the translated issue comment: @xudafeng
> 
> @saling Upgrade the system and reload it.

if I want to fix the problem，i must upgrade the system and reload it?
