### ISSUE TITLE
运行Android测试，Demo跑不起来，说是找不到build下面的apk

### ISSUE THREAD

**Issue by h3clikejava** [alibaba/macaca#854]
环境应该都是正常的，但是找不到原因。说是找不到build下面的apk。

* **Macaca Version**:
  2.1.3

* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.11.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
TypeError: Invalid Version: 9.4.1.0
    at new SemVer (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:305:11)
    at compare (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:578:10)
    at Function.lt (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:612:10)
    at Object.exports.xcodeBuild (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:56:16)
    at exports.xcodeBuild.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Xcode is uninstalled
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/H3c/Documents/sdk`
  Platforms is set to `/Users/H3c/Documents/sdk/platforms/android-9`
  ADB tool is set to `/Users/H3c/Documents/sdk/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  android: 2.0.48

* **Operate System**:
MacOS10.13.4

* **Programming Language**:
按照官网的demo，一步一步走，测试Android工程说缺少apk

  Error: >> uiautomator-client.js:42:14 [master] pid:8942 /Users/H3c/Documents/sample-nodejs/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk not found, please resolve and reinstall android driver
      at Logger.error (/Users/H3c/Documents/sample-nodejs/node_modules/xlogger/lib/xlogger.js:169:9)
      at UIAutomator.init (/Users/H3c/Documents/sample-nodejs/node_modules/uiautomatorwd/lib/uiautomator-client.js:42:14)
      at UIAutomator.init.throw (<anonymous>)
      at onRejected (/Users/H3c/Documents/sample-nodejs/node_modules/co/index.js:81:24)

>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:8942 Recieve HTTP Request from Client[2018-09-27 12:27:36]: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:8942 Send HTTP Respone to Client[2018-09-27 12:27:36]: 405 Method Not Allowed
>>     2) "after all" hook

>> 

>> 

>>   0 passing (3s)

>>   2 failing

>>   1) macaca-test/mobile-app-sample.test.js
       "before all" hook:
     Error: [init({"platformName":"Android","autoAcceptAlerts":false,"isWaitActivity":true,"app":"/Users/H3c/Documents/sample-nodejs/node_modules/android-app-bootstrap/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:128:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:88:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1092:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

>>   2) macaca-test/mobile-app-sample.test.js
       "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.

**Comment by quxiaozha** [comment]
检查下该路径下的apk是否正常生成了，或者你手工下一个丢进去

**Comment by cll1994** [comment]
@h3clikejava 这个问题你解决了吗？我遇到了同样的问题，上午跑的好好的，下午忽然这样了
