### ISSUE TITLE
使用touch报错

### ISSUE THREAD

**Issue by imajyo** [alibaba/macaca#857]
* **Macaca Version**:
2.1.3
* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /Users/majyo/.nvm/versions/node/v8.9.2/bin/node
  node version: v8.9.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
TypeError: Invalid Version: 9.4.1.0
    at new SemVer (/Users/majyo/.nvm/versions/node/v8.9.2/lib/node_modules/macaca-cli/node_modules/semver/semver.js:305:11)
    at compare (/Users/majyo/.nvm/versions/node/v8.9.2/lib/node_modules/macaca-cli/node_modules/semver/semver.js:578:10)
    at Function.lt (/Users/majyo/.nvm/versions/node/v8.9.2/lib/node_modules/macaca-cli/node_modules/semver/semver.js:612:10)
    at Object.exports.xcodeBuild (/Users/majyo/.nvm/versions/node/v8.9.2/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:56:16)
    at exports.xcodeBuild.next (<anonymous>)
    at onFulfilled (/Users/majyo/.nvm/versions/node/v8.9.2/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  Xcode is uninstalled
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `10`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  chrome: 1.0.7
  ios: 2.0.34
* **Operate System**:

* **Programming Language**:
js

模拟器 使用touch报错
![image](https://user-images.githubusercontent.com/23478550/46239760-ae04d900-c3cf-11e8-9bf7-aac159acfbe2.png)
![image](https://user-images.githubusercontent.com/23478550/46239764-b4935080-c3cf-11e8-8ea5-22273af18e07.png)

**Comment by xudafeng** [comment]
resolved
