### ISSUE TITLE
运行demo进行android测试，提示在bulid下没有apk-debug

### ISSUE THREAD

**Issue by cll1994** [alibaba/macaca#864]
>> uiautomator-client.js:42:14 [master] pid:65202 /usr/local/lib/node_modules/macaca-android/node_modules/_uiautomatorwd@1.0.60@uiautomatorwd/app/build/outputs/apk/app-debug.apk not found, please resolve and reinstall android driver
>> responseHandler.js:56:12 [master] pid:65202 Send Error Respone to Client: Error: >> uiautomator-client.js:42:14 [master] pid:65202 /usr/local/lib/node_modules/macaca-android/node_modules/_uiautomatorwd@1.0.60@uiautomatorwd/app/build/outputs/apk/app
* **Macaca Version**:
cll-mac:~ linglingcheng$ macaca -v

  2.1.3

* **Macaca Doctor Logs**:cll-mac:~ linglingcheng$ macaca doctor

  macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.12.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
TypeError: Invalid Version: 9.4.1.0
    at new SemVer (/usr/local/lib/node_modules/macaca-cli/node_modules/_semver@5.6.0@semver/semver.js:312:11)
    at compare (/usr/local/lib/node_modules/macaca-cli/node_modules/_semver@5.6.0@semver/semver.js:585:10)
    at Function.lt (/usr/local/lib/node_modules/macaca-cli/node_modules/_semver@5.6.0@semver/semver.js:619:10)
    at Object.exports.xcodeBuild (/usr/local/lib/node_modules/macaca-cli/node_modules/_macaca-doctor@2.0.15@macaca-doctor/lib/ios.js:56:16)
    at exports.xcodeBuild.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/_co@4.6.0@co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Xcode is uninstalled
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/linglingcheng/Library/Android/sdk`
  Platforms is set to `/Users/linglingcheng/Library/Android/sdk/platforms/android-28`
  ADB tool is set to `/Users/linglingcheng/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  android: 2.0.48
  ios: 2.0.35

* **Operate System**:macos    high sierra 10.13.4 (17E199)

* **Programming Language**:

**Comment by cll1994** [comment]
找到了解决办法了，更新下图标红的部分
![image](https://user-images.githubusercontent.com/44460704/47486400-d5d24a00-d872-11e8-9a8f-b9d96affe654.png)
方法来源是：https://testerhome.com/topics/8659/show_wechat

**Comment by rogerleocz** [comment]
有时doctor检查没问题，但是Android驱动安装过程中会有警告，所以过程中要注意检查，尽量减少报错和警告
