### ISSUE TITLE
nosmoke安装成功,但是无法执行nosmoke --help  

### ISSUE THREAD

**Issue by 123tanliheng** [alibaba/macaca#873]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by 123tanliheng** [comment]
C:\Users\tlh>nosmoke --help
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'macaca-reporter/test/mock'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Program Files\Nodejs\node_global\node_modules\nosmoke\lib\server\router.js:14:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by SamuelZhaoY** [comment]
安装最新版 NoSmoke
