### ISSUE TITLE
win10 how run macaca-test-sample-master？

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#88]
我下载了macaca-test-sample-master.zip  解压到了D:\macaca\macaca-test-sample-master下
执行 macaca run --verbose -d macaca-desktop-sample.test.js 后日志如下。

 D:\macaca\macaca-test-sample-master\macaca-test 的目录

2016/07/13  23:16    <DIR>          .
2016/07/13  23:16    <DIR>          ..
2016/07/18  15:53             1,614 macaca-desktop-sample.test.js
2016/07/13  23:16             1,437 macaca-mobile-browser-sample.test.js
2016/07/13  23:16             2,872 macaca-mobile-sample.test.js
2016/07/13  23:16                33 mocha.opts
               4 个文件          5,956 字节
               2 个目录 101,915,099,136 可用字节

D:\macaca\macaca-test-sample-master\macaca-test>platform=android macaca run --verbose -d macaca-desktop-sample.test.js
'platform' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\macaca\macaca-test-sample-master\macaca-test>macaca run --verbose -d macaca-desktop-sample.test.js
>> index.js:17:12 [master] pid:14388 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '169.254.166.89',
  host: 'cmd-PC',
  loaded_time: '2016-07-19 11:33:19' }
>> middlewares.js:17:10 [master] pid:14388 base middlewares attached
>> router.js:105:10 [master] pid:14388 router set
>> webdriver sdk launched
>>

>>

>>   macaca desktop sample

>> responseHandler.js:11:12 [master] pid:14388 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"browserName":"chrome","platformName":"desktop","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:14388 Creating session, sessionId: 50828aa2-0d56-47f5-8237-5efc1a7907dc.
>> session.js:31:14 [master] pid:14388 Error: Cannot find module 'macaca-chrome'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at detectDevice (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:28:20)
    at Object.createDevice (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:10:18)
    at next (native)
    at onFulfilled (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:65:19)
    at D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:54:5
    at Object.co (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:50:10)
>> please run: `macaca install chrome`
>> responseHandler.js:50:12 [master] pid:14388 Send Error Respone to Client: TypeError: Cannot set property 'proxyMode' of undefined
>> responseHandler.js:56:14 [master] pid:14388 TypeError: Cannot set property 'proxyMode' of undefined
    at Object.createDevice (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:16:20)
    at next (native)
    at onFulfilled (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:65:19)
    at D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:54:5
    at Object.co (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:118:63)
    at next (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:99:29)
    at onFulfilled (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:69:7)
    at D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:54:5
    at Object.co (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:50:10)

  TypeError: Cannot set property 'proxyMode' of undefined
      at Object.createDevice (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:16:20)
      at next (native)
      at onFulfilled (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:65:19)
      at D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:54:5
      at Object.co (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:50:10)
      at Object.toPromise (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:118:63)
      at next (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:99:29)
      at onFulfilled (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:69:7)
      at D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:54:5
      at Object.co (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:50:10)

>>
>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:14388 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:19:14 [master] pid:14388 Send HTTP Respone to Client: 405 Method Not Allowed
    2) "after all" hook

>>
  0 passing (361ms)
  2 failing

  1) macaca desktop sample "before all" hook:
     Error: [init({"autoAcceptAlerts":true,"browserName":"chrome","platformName":"desktop"})] The environment you requested was unavailable.
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:134:15
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) macaca desktop sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at null.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\callbacks.js:42:12)
      at cb (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:165:22)
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> Test completed!

**Comment by zenzhu** [comment]
1. 第一个报错是因为 windows 平台不支持 Makefile。
2. 没有成功装上 Android 插件。https://github.com/alibaba/macaca/issues/87
