### ISSUE TITLE
win10下macaca-test-sample (desktop测试通过，android测试报错)

### ISSUE THREAD

**Issue by Lostlover** [alibaba/macaca#89]
```
>> index.js:17:12 [master] pid:9136 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.1.6',
  host: 'Lostlover',
  loaded_time: '2016-07-24 12:45:30' }
>> middlewares.js:17:10 [master] pid:9136 base middlewares attached
>> router.js:108:10 [master] pid:9136 router set
>> webdriver sdk launched
>> platform: android

>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:9136 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoA
cceptAlerts":true,"platformName":"Android","app":"D:\\WebStorm\\e2e\\macaca\\macaca-test-sample-master\\app\\android-app-bootstrap.zip","browserName":"fire
fox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:9136 Creating session, sessionId: fa8f07a7-c950-4a3c-b67d-57cb6b23ca99.
>> helper.js:194:12 [master] pid:9136 Unzipping local app form D:\WebStorm\e2e\macaca\macaca-test-sample-master\app\android-app-bootstrap.zip
>> responseHandler.js:50:12 [master] pid:9136 Send Error Respone to Client: exec C:\Program Files (x86)\Android\android-sdk/platform-tools/adb devices erro
r with: Error: Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Program Files (x86)\Android\android-sdk/platform-tools/adb devices"
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���


  InternalServerError: Internal Server Error
      at Object.module.exports.throw (C:\Users\gaoyng\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\koa\lib\context.js:91:23)
      at Object.module.exports (C:\Users\gaoyng\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\responseHandler.js:53:
17)
      at throw (native)
      at onRejected (C:\Users\gaoyng\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:81:24)
      at process._tickCallback (node.js:369:9)

>> 
>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:9136 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:19:14 [master] pid:9136 Send HTTP Respone to Client: 405 Method Not Allowed
    2) "after all" hook

>> 


>>   0 passing (2s)
  2 failing


>>   1) macaca mobile sample "before all" hook:
     Error: [init({"autoAcceptAlerts":true,"platformName":"Android","app":"D:\\WebStorm\\e2e\\macaca\\macaca-test-sample-master\\app\\android-app-bootstrap
.zip"})] The environment you requested was unavailable.
      at D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:134:15
      at Request._callback (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at null.<anonymous> (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\callbacks.js:42:12)
      at cb (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:165:22)
      at D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\WebStorm\e2e\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)




>> Test completed!

```

**Comment by Lostlover** [comment]
```
  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v4.4.7

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `C:\Program Files (x86)\Android\android-sdk`
  Platforms is set to `C:\Program Files (x86)\Android\android-sdk\platforms\android-24`
  Android tools is set to `C:\Program Files (x86)\Android\android-sdk\tools\android.bat`
  ANT_HOME is set to `D:\apache-ant-1.9.7`
```

**Comment by xudafeng** [comment]
没问题的，请检查环境

#92
