### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by brucejcw** [alibaba/macaca#911]
>> TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.addDerivedInfoForFile (/builds/dana/dana-home/node_modules/_macaca-istanbul@1.0.6@macaca-istanbul/lib/object-utils.js:58:20)
    at Collector.fileCoverageFor (/builds/dana/dana-home/node_modules/_macaca-istanbul@1.0.6@macaca-istanbul/lib/collector.js:94:15)
    at /builds/dana/dana-home/node_modules/_macaca-istanbul@1.0.6@macaca-istanbul/lib/report/html.js:559:90
    at Array.forEach (<anonymous>)
    at HtmlReport.writeReport (/builds/dana/dana-home/node_modules/_macaca-istanbul@1.0.6@macaca-istanbul/lib/report/html.js:558:27)
    at /builds/dana/dana-home/node_modules/_macaca-istanbul@1.0.6@macaca-istanbul/lib/reporter.js:93:20
    at Array.forEach (<anonymous>)
    at Reporter.write (/builds/dana/dana-home/node_modules/_macaca-istanbul@1.0.6@macaca-istanbul/lib/reporter.js:87:30)
    at module.exports (/builds/dana/dana-home/node_modules/_macaca-reporter@1.3.7@macaca-reporter/lib/coverage.js:68:12)
    at done (/builds/dana/dana-home/node_modules/_macaca-reporter@1.3.7@macaca-reporter/lib/macaca-reporter.js:37:5)
    at MacacaReporter.done (/builds/dana/dana-home/node_modules/_macaca-reporter@1.3.7@macaca-reporter/lib/macaca-reporter.js:84:35)
    at done (/builds/dana/dana-home/node_modules/_mocha@5.2.0@mocha/lib/mocha.js:606:16)
    at Runner.<anonymous> (/builds/dana/dana-home/node_modules/_mocha@5.2.0@mocha/lib/runner.js:864:5)
    at emitNone (events.js:111:20)
    at Runner.emit (events.js:208:7)
    at /builds/dana/dana-home/node_modules/_mocha@5.2.0@mocha/lib/runner.js:851:12
    at /builds/dana/dana-home/node_modules/_mocha@5.2.0@mocha/lib/runner.js:690:9
    at next (/builds/dana/dana-home/node_modules/_mocha@5.2.0@mocha/lib/runner.js:303:14)
    at Immediate.<anonymous> (/builds/dana/dana-home/node_modules/_mocha@5.2.0@mocha/lib/runner.js:347:5)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by yihuineng** [comment]
问题久远关闭，如有问题，可再次提issue并提供详细复现路径
