### ISSUE TITLE
win10 macaca-mobile-sample.test.js 用例脚本android环境报了些错

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#92]
https://testerhome.com/topics/5483

win10环境下大体跑起来了macaca-mobile-sample.test.js  以下为执行输出，可以看到一些地方报error了
除了 一个截图保存路径的问题外，其他error请帮忙排查下。

D:\macaca\macaca-test-sample-master\macaca-test>macaca run  -d macaca-mobile-sample.test.js
>> webdriver sdk launched
>>

>>

>>   macaca mobile sample

INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: test=testStartServer
INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize

>> socket server ready
>> socket client ready
recive: {"cmd":"wake","args":{}}

return: {"success":true,"data":true}

recive: {"cmd":"find","args":{"strategy":"class name","selector":"android.widget.EditText","multiple":true}}

return: {"success":true,"data":[{"ELEMENT":"1"},{"ELEMENT":"2"}]}

recive: {"cmd":"setText","args":{"elementId":"1","text":"中文+Test+12345678"}}

return: {"success":true,"data":true}

recive: {"cmd":"find","args":{"strategy":"class name","selector":"android.widget.EditText","multiple":true}}

return: {"success":true,"data":[{"ELEMENT":"3"},{"ELEMENT":"4"}]}

recive: {"cmd":"setText","args":{"elementId":"4","text":"111111"}}

return: {"success":true,"data":true}

recive: {"cmd":"find","args":{"strategy":"name","selector":"Login","multiple":true}}

return: {"success":true,"data":[{"ELEMENT":"5"}]}

recive: {"cmd":"click","args":{"elementId":"5"}}

return: {"success":true,"data":true}

>>
>>     √ #1 should login success (48233ms)

  Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.236.101:5555 pull /data/local/tmp/screenshot.png C:\Users\cmd\AppData\Local\Temp\macaca-android-screenshot116625-7964-l8nsrc.png"

      at ChildProcess.exithandler (child_process.js:213:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:827:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>>
>>     1) #2 should display home

recive: {"cmd":"find","args":{"strategy":"name","selector":"HOME","multiple":false}}

ignored selector
return: {"success":true,"data":{"ELEMENT":"6"}}

recive: {"cmd":"click","args":{"elementId":"6"}}

return: {"success":true,"data":true}

recive: {"cmd":"find","args":{"strategy":"name","selector":"list","multiple":false}}

ignored selector

return: {"success":true,"data":{"ELEMENT":"7"}}

recive: {"cmd":"click","args":{"elementId":"7"}}

return: {"success":true,"data":true}

recive: {"cmd":"swipe","args":{"startX":200,"startY":400,"endX":200,"endY":100,"duration":500}}

return: {"success":true,"data":true}

>>
>>     √ #3 should scroll tableview (13494ms)

recive: {"cmd":"find","args":{"strategy":"name","selector":"Webview","multiple":false}}

ignored selector

return: {"success":true,"data":{"ELEMENT":"8"}}

recive: {"cmd":"click","args":{"elementId":"8"}}

return: {"success":true,"data":true}

  Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.236.101:5555 pull /data/local/tmp/screenshot.png C:\Users\cmd\AppData\Local\Temp\macaca-android-screenshot116625-7964-zw3aw7.png"

      at ChildProcess.exithandler (child_process.js:213:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:827:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

    2) #4 should display webview

>> chromedriver bin path: D:\nodejs\node-global\node_modules\macaca-android\node_modules\macaca-chromedriver\exec\chromedriver.exe
>> kill all chromedriver process success!
>> Starting ChromeDriver 2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> chromedriver ready with: {"sessionId":null,"status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"platform":"ANDROID","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"version":"39.0.0.0","webStorageEnabled":true}}

  Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.236.101:5555 pull /data/local/tmp/screenshot.png C:\Users\cmd\AppData\Local\Temp\macaca-android-screenshot116625-7964-jcjxms.png"

      at ChildProcess.exithandler (child_process.js:213:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:827:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

    3) #5 should go into webview

recive: {"cmd":"find","args":{"strategy":"name","selector":"Baidu","multiple":false}}

ignored selector

return: {"success":true,"data":{"ELEMENT":"9"}}

recive: {"cmd":"click","args":{"elementId":"9"}}

return: {"success":true,"data":true}

  Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.236.101:5555 pull /data/local/tmp/screenshot.png C:\Users\cmd\AppData\Local\Temp\macaca-android-screenshot116625-7964-gmq8kr.png"

      at ChildProcess.exithandler (child_process.js:213:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:827:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

    4) #6 should go into test

  Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.236.101:5555 pull /data/local/tmp/screenshot.png C:\Users\cmd\AppData\Local\Temp\macaca-android-screenshot116625-7964-w9sk8c.png"

      at ChildProcess.exithandler (child_process.js:213:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:827:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

    5) #7 should works with web

recive: {"cmd":"find","args":{"strategy":"name","selector":"PERSONAL","multiple":false}}

ignored selector

return: {"success":true,"data":{"ELEMENT":"10"}}

recive: {"cmd":"click","args":{"elementId":"10"}}

return: {"success":true,"data":true}

  Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.236.101:5555 pull /data/local/tmp/screenshot.png C:\Users\cmd\AppData\Local\Temp\macaca-android-screenshot116625-7964-19mhzl4.png"

      at ChildProcess.exithandler (child_process.js:213:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:827:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>>
>>     6) #8 should logout success

>>

>>
  2 passing (2m)
  6 failing

>>   1) macaca mobile sample #2 should display home:
     Error: [takeScreenshot()] Not JSON response
      at exports.newError (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\callbacks.js:59:17
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  2) macaca mobile sample #4 should display webview:
     Error: [takeScreenshot()] Not JSON response
      at exports.newError (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\callbacks.js:59:17
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  3) macaca mobile sample #5 should go into webview:
     Error: [takeScreenshot()] Not JSON response
      at exports.newError (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\callbacks.js:59:17
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  4) macaca mobile sample #6 should go into test:
     Error: [takeScreenshot()] Not JSON response
      at exports.newError (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\callbacks.js:59:17
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  5) macaca mobile sample #7 should works with web:
     Error: [takeScreenshot()] Not JSON response
      at exports.newError (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\callbacks.js:59:17
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  6) macaca mobile sample #8 should logout success:
     Error: [takeScreenshot()] Not JSON response
      at exports.newError (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\utils.js:139:13)
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\callbacks.js:59:17
      at D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\webdriver.js:179:5
      at Request._callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (D:\macaca\macaca-test-sample-master\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

>> Test completed!

**Comment by xudafeng** [comment]
截图报错啊

**Comment by zhangfeilynu** [comment]
test_case_1(macaca.client.AndroidSampleTest): syntax error, pos 1, json : Internal Server Error

**Comment by youngvery** [comment]
Error: chromedriver proxy error with: Error: read ECONNRESET
Error: chromedriver proxy error with: Error: connect ECONNREFUSED
请问报这两个错怎么解决呢？

**Comment by Cainiaotao** [comment]
Logger.error (C:\Users\tantao\AppData\Roaming\npm\node_modules\app-inspector\node_modules\xlogger\lib\xlogger.js:169:9)
    at UIAutomator.init (C:\Users\tantao\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomator-client\lib\uiautomator-client.js:31:12)
    at next (native)
    at onFulfilled (C:\Users\tantao\AppData\Roaming\npm\node_modules\app-inspector\node_modules\co\index.js:65:19)
    at process._tickCallback (node.js:369:9)
