### ISSUE TITLE
macaca调用execute方法,执行JavaScript,老是报错com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by wuzhengbiao** [alibaba/macaca#923]
* **Macaca Version**:最新

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:java

代码:
![image](https://user-images.githubusercontent.com/40415938/57515923-4db31e00-7346-11e9-9253-0d1d4c47b4e9.png)

报错日志::
![image](https://user-images.githubusercontent.com/40415938/57515782-03ca3800-7346-11e9-8f79-99f6e5cd8975.png)

java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String

	at macaca.client.commands.Execute.execute(Execute.java:21)
	at macaca.client.MacacaClient.execute(MacacaClient.java:1094)
	at Com.Execute.execute(Execute.java:164)
	at Testing.Tester.tester(Tester.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by wuzhengbiao** [comment]
希望大神指导一下

**Comment by xudafeng** [comment]
@wuzhengbiao 

https://github.com/macaca-sample/macaca-java-biz-sample/blob/2de3e7a39655df2444913ce0fe41c3253def578a/src/test/java/com/javademo/cases/SampleTest.java#L147

**Comment by wuzhengbiao** [comment]
谢谢
