### ISSUE TITLE
install chromedriver failed

### ISSUE THREAD

**Issue by jackal186** [alibaba/macaca#925]
* **Macaca Version**:
2.1.12
* **Macaca Doctor Logs**:
D:\sample-python-master>macaca doctor

  macaca-doctor version: 2.0.16

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v8.16.0

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `C:\Java\jdk1.8.0_66`
  ANDROID_HOME is not set
  GRADLE_HOME is not set

  Installed driver list:

  electron: 3.0.2
* **Operate System**:
WIN10-64
* **Programming Language**:
PYTHON

> macaca-chromedriver@1.1.2 install C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-chromedriver
> node ./bin/macaca-chromedriver install

>> version: 2.45
>> chromedriver cdn url: http://npm.taobao.org/mirrors/chromedriver/2.45/chromedriver_win32.zip
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ETIMEDOUT 114.55.80.225:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macaca-chromedriver@1.1.2 install: `node ./bin/macaca-chromedriver install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the macaca-chromedriver@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Server log:

>> session.js:58:10 [master] pid:13844 Creating session, sessionId: 2d0e5d7e-1099-4574-93df-8277371b8689.
>> session.js:35:16 [master] pid:13844 Browser must in (android, chrome, electron, ios, puppeteer)
>> responseHandler.js:56:12 [master] pid:13844 Send Error Respone to Client: Error: >> session.js:35:16 [master] pid:13844 Browser must in (android, chrome, electron, ios, puppeteer)
>> responseHandler.js:62:14 [master] pid:13844 Error: >> session.js:35:16 [master] pid:13844 Browser must in (android, chrome, electron, ios, puppeteer)
    at Logger.error (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\xlogger\lib\xlogger.js:169:9)
    at detectDevice (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:35:16)
    at Object.createDevice (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:13:18)
    at createDevice.next (<anonymous>)
    at onFulfilled (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)
    at C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)
    at Object.toPromise (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:118:63)
    at next (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:99:29)

  Error: >> session.js:35:16 [master] pid:13844 Browser must in (android, chrome, electron, ios, puppeteer)
      at Logger.error (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\xlogger\lib\xlogger.js:169:9)
      at detectDevice (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:35:16)
      at Object.createDevice (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:13:18)
      at createDevice.next (<anonymous>)
      at onFulfilled (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)
      at C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5
      at new Promise (<anonymous>)
      at Object.co (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)
      at Object.toPromise (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:118:63)
      at next (C:\Users\xxxx\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:99:29)

**Comment by paradite** [comment]
@jackal186 看起来是网络问题，我这面没有问题。试试用个不同的网络。

**Comment by xudafeng** [comment]
https://testerhome.com/topics/12280
