### ISSUE TITLE
macaca在init的时候报socket连接超时,怎么改连接超时的等待时间

### ISSUE THREAD

**Issue by wuzhengbiao** [alibaba/macaca#931]
* **Macaca Version**:最新

* **Macaca Doctor Logs**:

* **Operate System**:Windows10 64.

* **Programming Language**:java

代码:
    public MacacaClient MacacaInit() throws Exception {
        JSONObject jsono = new JSONObject();
        jsono.put("browserName", "chrome");
        jsono.put("platformName", "desktop");
        JSONObject desiredCapabilities = new JSONObject();
        desiredCapabilities.put("desiredCapabilities", jsono);
        desiredCapabilities.put("host", "127.0.0.1"); // custom remote host
        desiredCapabilities.put("port", Integer.parseInt(AssertionListener.port));

        driver.initDriver(desiredCapabilities);

        return driver;
    }
报错日志:
java.net.SocketTimeoutException: Read timed out
java.net.SocketInputStream.socketRead0(Native Method)
java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
java.net.SocketInputStream.read(SocketInputStream.java:171)
java.net.SocketInputStream.read(SocketInputStream.java:141)
org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
macaca.client.common.Utils.executeRequest(Utils.java:89)
macaca.client.common.Utils.postRequest(Utils.java:151)
macaca.client.common.Utils.request(Utils.java:172)
macaca.client.commands.Url.getUrl(Url.java:28)
macaca.client.MacacaClient.get(MacacaClient.java:1294)
Com.Execute.execute(Execute.java:28)
Testing.Tester.tester(Tester.java:66)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
org.testng.TestRunner.privateRun(TestRunner.java:767)
org.testng.TestRunner.run(TestRunner.java:617)
org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
org.testng.SuiteRunner.run(SuiteRunner.java:254)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
org.testng.TestNG.run(TestNG.java:1057)
org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by wuzhengbiao** [comment]
请大神告知下

**Comment by paradite** [comment]
macaca服务端在跑吗？是老项目最近突然坏的还是一个新的项目？

**Comment by wuzhengbiao** [comment]
> macaca服务端在跑吗？是老项目最近突然坏的还是一个新的项目？

服务端再跑,老项目,有时候偶尔会出现超时的情况

**Comment by paradite** [comment]
看了一下，Java这面是写死了的：
https://github.com/macacajs/wd.java/blob/master/src/main/java/macaca/client/common/Utils.java#L43-L44
欢迎提个PR，把timeout改大一些，或者配置化。

**Comment by wuzhengbiao** [comment]
感谢!

**Comment by zhechengmao** [comment]
我这边也遇到这个情况了，之前的老项目跑的好好地，最近只是重新安装了一下Android的驱动，然后就报超时了。。

java.net.SocketTimeoutException: Read timed out

	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at macaca.client.common.Utils.executeRequest(Utils.java:89)
	at macaca.client.common.Utils.postRequest(Utils.java:151)
	at macaca.client.common.Utils.request(Utils.java:172)
	at macaca.client.commands.Session.createSession(Session.java:40)
	at macaca.client.MacacaClient.initDriver(MacacaClient.java:1183)

**Comment by wuzhengbiao** [comment]
能不能改下连接超时等待的时间,最近连接经常时间超了报错@paradite

**Comment by paradite** [comment]
@wuzhengbiao 你自己改下提个PR吧，就是改个数字比较简单，我也不知道需要改成多少。代码就在这里：
https://github.com/macacajs/wd.java/blob/master/src/main/java/macaca/client/common/Utils.java#L43-L44
PR格式可以参考下这个：
https://github.com/macacajs/wd.java/pull/101/files

**Comment by paradite** [comment]
fixed in https://github.com/macacajs/wd.java/pull/103 https://github.com/macacajs/wd.java/pull/105
deployed to https://bintray.com/xudafeng/maven/macacaclient/2.0.27
