### ISSUE TITLE
PANIC: Missing emulator engine program for 'x86' CPU.

### ISSUE THREAD

**Issue by stephenwang1011** [alibaba/macaca#935]
在进行安卓录制脚本的时候，提示：PANIC: Missing emulator engine program for 'x86' CPU. 我看的是 他从/Users/young/Library/Android/sdk/tools/目录下执行 emulator启动模拟器命令，但是会报错，如果我在Users/young/Library/Android/sdk/emulator目录下执行启动模拟器的命令可以正常启动模拟器，是不是macaca 启动模拟器的目录不正确？
`>> no device, now create one from avd
(node:5661) UnhandledPromiseRejectionWarning: Error: Command failed: /Users/young/Library/Android/sdk/tools/emulator -avd android-9
PANIC: Missing emulator engine program for 'x86' CPU.

    at ChildProcess.exithandler (child_process.js:290:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:5661) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5661) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>> responseHandler.js:56:12 [master] pid:5661 Send Error Respone to Client: Wait For Condition timeout 60000

  InternalServerError: Internal Server Error
      at Object.throw (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:59:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at processTicksAndRejections (internal/process/task_queues.js:82:5)

(node:5661) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`

**Comment by xudafeng** [comment]
模拟器没有装成功

**Comment by stephenwang1011** [comment]
> 模拟器没有装成功

已经解决了
