### ISSUE TITLE
Android run sample error

### ISSUE THREAD

**Issue by thh0613** [alibaba/macaca#936]
* **Macaca Version**: 2.1.12

* **Macaca Doctor Logs**:
```
macaca-doctor version: 2.0.18


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.11.3

  iOS checklist:

  macOS version: 10.11.5
  Xcode Command Line Tools require version: 2347 and above
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
{ Error: Command failed: xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.exports.getXcodeVersion (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:44:38)
    at Object.exports.xcodeBuild (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:56:30)
    at exports.xcodeBuild.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  error: null,
  cmd: 'xcodebuild -version',
  file: '/bin/sh',
  args: [ '/bin/sh', '-c', 'xcodebuild -version' ],
  options:
   { shell: true,
     file: '/bin/sh',
     args: [ '/bin/sh', '-c', 'xcodebuild -version' ],
     envPairs:
      [ 'TERM_SESSION_ID=w0t1p1:006576DE-3374-4650-921F-8BD329304B31',
        'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.s9LvOoTyva/Listeners',
        'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.mOHJVcmixK/Render',
        'ITERM_PROFILE=thh',
        'XPC_FLAGS=0x0',
        'LANG=zh_CN.UTF-8',
        'PWD=/Users/taohuahua/workspace/autotest/sample-nodejs',
        'SHELL=/bin/zsh',
        'SECURITYSESSIONID=186a8',
        'TERM_PROGRAM_VERSION=3.0.4',
        'TERM_PROGRAM=iTerm.app',
        'PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/gradle:/Users/taohuahua/Documents/android_studio/sdk:/Users/taohuahua/Documents/android_studio/sdk/platform-tools:/usr/local/mysql/bin:/Users/taohuahua/Documents/flutter/flutter/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home:/Applications/010 Editor.app/Contents/CmdLine',
        'COMMAND_MODE=unix2003',
        'TERM=xterm-256color',
        'HOME=/Users/taohuahua',
        'TMPDIR=/var/folders/hy/zfnnr5ks3yv4p6srr9xb643m0000gn/T/',
        'USER=taohuahua',
        'XPC_SERVICE_NAME=0',
        'LOGNAME=taohuahua',
        'ITERM_SESSION_ID=w0t1p1:006576DE-3374-4650-921F-8BD329304B31',
        '__CF_USER_TEXT_ENCODING=0x1F5:0:0',
        'SHLVL=1',
        'ZSH=/Users/taohuahua/.oh-my-zsh',
        'PAGER=less',
        'LESS=-R',
        'LSCOLORS=GxFxCxDxBxegedabagaced',
        'LC_CTYPE=zh_CN.UTF-8',
        'ANDROID_HOME=/Users/taohuahua/Documents/android_studio/sdk',
        'GRADLE_HOME=/usr/local/bin/gradle',
        'JDK_PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home',
        'JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home',
        'SDK_TOOLS=/Users/taohuahua/Documents/android_studio/sdk/platform-tools',
        'FLUTTER=/Users/taohuahua/Documents/flutter/flutter/bin',
        'MYSQL=/usr/local/mysql/bin',
        'CLICOLOR=1',
        '_=/usr/local/bin/macaca' ],
     killSignal: undefined,
     stdio: [ [Object], [Object], [Object] ] },
  envPairs:
   [ 'TERM_SESSION_ID=w0t1p1:006576DE-3374-4650-921F-8BD329304B31',
     'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.s9LvOoTyva/Listeners',
     'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.mOHJVcmixK/Render',
     'ITERM_PROFILE=thh',
     'XPC_FLAGS=0x0',
     'LANG=zh_CN.UTF-8',
     'PWD=/Users/taohuahua/workspace/autotest/sample-nodejs',
     'SHELL=/bin/zsh',
     'SECURITYSESSIONID=186a8',
     'TERM_PROGRAM_VERSION=3.0.4',
     'TERM_PROGRAM=iTerm.app',
     'PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/gradle:/Users/taohuahua/Documents/android_studio/sdk:/Users/taohuahua/Documents/android_studio/sdk/platform-tools:/usr/local/mysql/bin:/Users/taohuahua/Documents/flutter/flutter/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home:/Applications/010 Editor.app/Contents/CmdLine',
     'COMMAND_MODE=unix2003',
     'TERM=xterm-256color',
     'HOME=/Users/taohuahua',
     'TMPDIR=/var/folders/hy/zfnnr5ks3yv4p6srr9xb643m0000gn/T/',
     'USER=taohuahua',
     'XPC_SERVICE_NAME=0',
     'LOGNAME=taohuahua',
     'ITERM_SESSION_ID=w0t1p1:006576DE-3374-4650-921F-8BD329304B31',
     '__CF_USER_TEXT_ENCODING=0x1F5:0:0',
     'SHLVL=1',
     'ZSH=/Users/taohuahua/.oh-my-zsh',
     'PAGER=less',
     'LESS=-R',
     'LSCOLORS=GxFxCxDxBxegedabagaced',
     'LC_CTYPE=zh_CN.UTF-8',
     'ANDROID_HOME=/Users/taohuahua/Documents/android_studio/sdk',
     'GRADLE_HOME=/usr/local/bin/gradle',
     'JDK_PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home',
     'JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home',
     'SDK_TOOLS=/Users/taohuahua/Documents/android_studio/sdk/platform-tools',
     'FLUTTER=/Users/taohuahua/Documents/flutter/flutter/bin',
     'MYSQL=/usr/local/mysql/bin',
     'CLICOLOR=1',
     '_=/usr/local/bin/macaca' ],
  stderr: <Buffer 78 63 6f 64 65 2d 73 65 6c 65 63 74 3a 20 65 72 72 6f 72 3a 20 74 6f 6f 6c 20 27 78 63 6f 64 65 62 75 69 6c 64 27 20 72 65 71 75 69 72 65 73 20 58 63 ... >,
  stdout: <Buffer >,
  pid: 74305,
  output:
   [ null,
     <Buffer >,
     <Buffer 78 63 6f 64 65 2d 73 65 6c 65 63 74 3a 20 65 72 72 6f 72 3a 20 74 6f 6f 6c 20 27 78 63 6f 64 65 62 75 69 6c 64 27 20 72 65 71 75 69 72 65 73 20 58 63 ... > ],
  signal: null,
  status: 1 }
  Xcode is uninstalled
{ Error: Command failed: which iproxy

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) killed: false, code: 1, signal: null, cmd: 'which iproxy' }
  Command Line Tools: iproxy[usbmuxd] is uninstalled
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/taohuahua/Documents/android_studio/sdk`
  Platforms is set to `/Users/taohuahua/Documents/android_studio/sdk/platforms/android-28`
  ADB tool is set to `/Users/taohuahua/Documents/android_studio/sdk/platform-tools/adb`
  gradle is installed, version: 5.0

  Installed driver list:

  android: 2.1.0
  location: /usr/local/lib/node_modules/macaca-android

  electron: 5.0.0
  location: /usr/local/lib/node_modules/macaca-electron

```
* **Operate System**: mac os  10.11.5

* **Programming Language**: node.js

```
npm run test:android

> sample-nodejs@1.0.0 test:android /Users/taohuahua/workspace/autotest/sample-nodejs
> cross-env platform=android npm run test:native


> sample-nodejs@1.0.0 test:native /Users/taohuahua/workspace/autotest/sample-nodejs
> macaca run --verbose -d ./macaca-test/mobile-app-sample.test.js

>> port: 3456 was occupied, changed port: 49192
>> index.js:15:12 [master] pid:73549 webdriver server start with config:
 { port: 49192,
  verbose: false,
  always: true,
  window: true,
  ip: '169.254.149.196',
  host: 'taohuahuadeMacBook-Pro.local',
  loaded_time: '2019-07-16 14:42:17' }
>> middlewares.js:17:10 [master] pid:73549 base middlewares attached
>> router.js:132:10 [master] pid:73549 router set
>> Macaca server started
[
  "/Users/taohuahua/workspace/autotest/sample-nodejs/node_modules/.bin/mocha",
  "./macaca-test/mobile-app-sample.test.js",
  "--colors",
  "--verbose"
]
>> Android App :/Users/taohuahua/workspace/autotest/sample-nodejs/node_modules/android-app-bootstrap/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk

>> >> macaca-coverage.js:14:10 [master] pid:73558 {"version":"1.0.3","runtime":"web"}

>> >> index.js:23:10 [master] pid:73558
{"version":"1.0.3","runtime":"web"}

>> >> macaca-coverage.js:14:10 [master] pid:73558 {"version":"1.0.3","runtime":"web"}

>> >> index.js:23:10 [master] pid:73558
{"version":"1.0.3","runtime":"web"}

>>

>>

>>   macaca-test/mobile-app-sample.test.js

```

**问题**
执行`npm run test:android`后，然后就卡死在 `macaca-test/mobile-app-sample.test.js`这一行中了。模拟器起了之后，也咩有安装`sample`中的`apk`.

**Comment by houseshi** [comment]
new version is fixed
please reinstall macaca-android
