### ISSUE TITLE
sample-nodejs Android环境运行失败

### ISSUE THREAD

**Issue by ShenYj** [alibaba/macaca#939]
* **Macaca Version**: 
v2.2.0

* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.18

  Network checklist:

  Error, please set hosts: ::1 localhost

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.16.0

  iOS checklist:

  macOS version: 10.14.5
  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 11.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/Shen/Library/Android/sdk`
  Platforms is set to `/Users/Shen/Library/Android/sdk/platforms/android-28`
  ADB tool is set to `/Users/Shen/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 5.5

  Installed driver list:

  android: 2.1.0
  location: /usr/local/lib/node_modules/macaca-android

  chrome: 1.1.0
  location: /usr/local/lib/node_modules/macaca-chrome

  electron: 5.0.0
  location: /usr/local/lib/node_modules/macaca-electron

  ios: 2.0.35
  location: /usr/local/lib/node_modules/macaca-ios

* **Operate System**: Mac OSX 10.14.5

* **Programming Language**:

- 配置完环境， ```$ npm run test:android```失败
```
[Shen@localhost ~/Desktop/sample-nodejs]$cat /Users/Shen/.npm/_logs/2019-08-12T00_58_55_975Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:android' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'pretest:android', 'test:android', 'posttest:android' ]
5 info lifecycle sample-nodejs@1.0.0~pretest:android: sample-nodejs@1.0.0
6 info lifecycle sample-nodejs@1.0.0~test:android: sample-nodejs@1.0.0
7 verbose lifecycle sample-nodejs@1.0.0~test:android: unsafe-perm in lifecycle true
8 verbose lifecycle sample-nodejs@1.0.0~test:android: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Shen/Desktop/sample-nodejs/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/Users/Shen/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/Shen/Library/Android/sdk/tools:/Users/Shen/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin
9 verbose lifecycle sample-nodejs@1.0.0~test:android: CWD: /Users/Shen/Desktop/sample-nodejs
10 silly lifecycle sample-nodejs@1.0.0~test:android: Args: [ '-c', 'cross-env platform=android npm run test:native' ]
11 silly lifecycle sample-nodejs@1.0.0~test:android: Returned: code: 1  signal: null
12 info lifecycle sample-nodejs@1.0.0~test:android: Failed to exec test:android script
13 verbose stack Error: sample-nodejs@1.0.0 test:android: `cross-env platform=android npm run test:native`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid sample-nodejs@1.0.0
15 verbose cwd /Users/Shen/Desktop/sample-nodejs
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:android"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error sample-nodejs@1.0.0 test:android: `cross-env platform=android npm run test:native`
22 error Exit status 1
23 error Failed at the sample-nodejs@1.0.0 test:android script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by houseshi** [comment]
new version is fixed
please  check you project is execute "npm i"
