### ISSUE TITLE
app-inspector 启动不了服务，提示：Internal Server Error

### ISSUE THREAD

**Issue by liyaoyao6342** [alibaba/macaca#946]
版本信息：xcode 10.3 macOS 10.14.6 iphone 12.4
之前一直是好的，一直用app-inspector查看iOS的树状结构，突然就挂掉了，网页提示：Internal Server Error，下面是我的macaca doctor的信息：
 macaca-doctor version: 2.0.18

  Node.js checklist:

  node env: /usr/local/homebrew/bin/node
  node version: v12.7.0

  iOS checklist:

  macOS version: 10.14.6
  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.3
  iproxy[usbmuxd] is installed at: `/usr/local/homebrew/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/homebrew/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/liyaoyao/Downloads/android-sdk-macosx`
  Platforms is set to `/Users/liyaoyao/Downloads/android-sdk-macosx/platforms/android-29`
  ADB tool is set to `/Users/liyaoyao/Downloads/android-sdk-macosx/platform-tools/adb`
  Not accepted Android SDK license agreements
  gradle is installed, version: 5.5

  Installed driver list:

  android: 2.1.0
  location: /usr/local/homebrew/lib/node_modules/macaca-android

  ios: 2.0.36
  location: /usr/local/homebrew/lib/node_modules/macaca-ios

下面是命令行的报错信息：
>> server.js:16:12 [master] pid:24652 server start with config:
 {
  port: 5678,
  verbose: true,
  udid: '25ff8f554eec8da683a00f0310291573f313a72f',
  ip: '172.16.48.223',
  host: 'wangruideMacBook-Pro-2.local',
  loaded_time: '2019-09-19 13:20:48'
}
>> app-inspector.js:45:12 [master] pid:24652 server start at: http://172.16.48.223:5678
>> xctest-client.js:56:14 [master] pid:24652 project path: /usr/local/homebrew/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:283:14 [master] pid:24652 xcode version: 10.3
>> XCTestWD version: 1.4.18
>> xctest-client.js:309:14 [master] pid:24652 Fail to start xctest: Error: ENOENT: no such file or directory, scandir '/usr/local/homebrew/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products'
Error: ENOENT: no such file or directory, scandir '/usr/local/homebrew/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products'
    at Object.readdirSync (fs.js:795:3)
    at /usr/local/homebrew/lib/node_modules/app-inspector/node_modules/xctestwd/lib/xctest-client.js:189:26
    at new Promise (<anonymous>)
    at XCTest.startBootstrap (/usr/local/homebrew/lib/node_modules/app-inspector/node_modules/xctestwd/lib/xctest-client.js:182:12)
    at startBootstrap.next (<anonymous>)
    at onFulfilled (/usr/local/homebrew/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
    at /usr/local/homebrew/lib/node_modules/app-inspector/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/usr/local/homebrew/lib/node_modules/app-inspector/node_modules/co/index.js:50:10)
    at toPromise (/usr/local/homebrew/lib/node_modules/app-inspector/node_modules/co/index.js:118:63) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/usr/local/homebrew/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products'
}
>> iOS device started: 25ff8f554eec8da683a00f0310291573f313a72f
>> inspector start at: http://172.16.48.223:5678
  <-- GET /
>> helper.js:94:16 [master] pid:24652 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)

**Comment by liyaoyao6342** [comment]
手动创建缺失文件即可
