### ISSUE TITLE
iOS录制之后回放脚本报错： Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by liyaoyao6342** [alibaba/macaca#958]
**macaca 版本**：2.0.18
**系统**：Mac
**手机**：iPhone8 /12.4.1
**macaca doctor**：没有报错
**备注**：Android录制回放没有问题
**复现步骤**：
1、启动macaca server
2、启动录制uirecorder --mobile test2.spec.js，录制成功
3、回放录制的脚本macaca run -p 4444 -d test2.spec.js --verbose，报错：

> >>     1) "before all" hook
> 
> >> 
> 
>   0 passing (39s)
>   1 failing
> 
>   1) test2.spec : 17:03:09 lockdown.c:660 lockdownd_client_new(): device udid: 25ff8f554eec8da683a00f0310291573f313a72f17:03:09 property_list_service.c:132 internal_plist_send(): sending 327 bytes17:03:09 service.c:144 service_send(): sending 4 bytes17:03:09 service.c:144 service_send(): sending 327 bytes17:03:09 property_list_service.c:137 internal_plist_send(): sent 327 bytes17:03:09 property_list_service.c:138 internal_plist_send(): printing 327 bytes plist:<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>	<key>Label</key>	<string>idevice_id</string>	<key>Key</key>	<string>DeviceName</string>	<key>Request</key>	<string>GetValue</string></dict></plist>17:03:09 property_list_service.c:205 internal_plist_receive_timeout(): initial read=417:03:09 property_list_service.c:211 internal_plist_receive_timeout(): 333 bytes following17:03:09 property_list_service.c:224 internal_plist_receive_timeout(): received 333 bytes17:03:09 property_list_service.c:250 internal_plist_receive_timeout(): printing 333 bytes plist:<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>	<key>Key</key>	<string>DeviceName</string>	<key>Request</key>	<string>GetValue</string>	<key>Value</key>	<string>yaoyao的 iPhone</string></dict></plist>17:03:09 lockdown.c:458 lockdownd_get_value(): success17:03:09 lockdown.c:469 lockdownd_get_value(): has a valueyaoyao的 iPhone [25ff8f554eec8da683a00f0310291573f313a72f]
>        "before all" hook:
>      Error: ENAMETOOLONG: name too long, mkdir '/Users/liyaoyao/Documents/macaca_case/screenshots/test2.spec : 17:03:09 lockdown.c:660 lockdownd_client_new(): device udid: 25ff8f554eec8da683a00f0310291573f313a72f17:03:09 property_list_service.c:132 internal_plist_send(): sending 327 bytes17:03:09 service.c:144 service_send(): sending 4 bytes17:03:09 service.c:144 service_send(): sending 327 bytes17:03:09 property_list_service.c:137 internal_plist_send(): sent 327 bytes17:03:09 property_list_service.c:138 internal_plist_send(): printing 327 bytes plist:<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-/'
>       at Object.mkdirSync (fs.js:839:3)
>       at mkdirs (test2.spec.js:142:16)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at mkdirs (test2.spec.js:141:12)
>       at Context.<anonymous> (test2.spec.js:96:17)
>       at callFn (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:372:21)
>       at Hook.Runnable.run (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:364:7)
>       at next (node_modules/_mocha@5.2.0@mocha/lib/runner.js:317:10)
>       at Immediate._onImmediate (node_modules/_mocha@5.2.0@mocha/lib/runner.js:347:5)
>       at processImmediate (internal/timers.js:439:21)

**Comment by liyaoyao6342** [comment]
录制脚本生成的代码：

const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const chai = require("chai");
const should = chai.should();
const JWebDriver = require('jwebdriver');
chai.use(JWebDriver.chaiSupportChainPromise);
const resemble = require('resemblejs-node');
resemble.outputSettings({
    errorType: 'flatDifferenceIntensity'
});

const rootPath = getRootPath();
const appPath = '';      //本地的app
const platformName = 'iOS';

module.exports = function(){

    var driver, testVars;

    before(function(){
        var self = this;
        driver = self.driver;
        testVars = self.testVars;
    });

    it('sleep: 8000', async function(){
        await driver.sleep(8000);
    });

    it('tap: 实战篮球 ( //*[@name="实战篮球"] )', async function(){
        await driver.wait('//*[@name="实战篮球"]', 30000).sendElementActions('tap');
    });

    it('sleep: 1000', async function(){
        await driver.sleep(1000);
    });

    function _(str){
        if(typeof str === 'string'){
            return str.replace(/\{\{(.+?)\}\}/g, function(all, key){
                return testVars[key] || '';
            });
        }
        else{
            return str;
        }
    }

};

if(module.parent && /mocha\.js/.test(module.parent.id)){
    runThisSpec();
}

function runThisSpec(){
    // read config
    let config = require(rootPath + '/config.json');
    let webdriverConfig = Object.assign({},config.webdriver);
    let host = webdriverConfig.host;
    let port = webdriverConfig.port || 4444;
    let testVars = config.vars;

    let specName = path.relative(rootPath, __filename).replace(/\\/g,'/').replace(/\.js$/,'');

    let arrDeviceList = getEnvList() || getDeviceList(platformName);
    if(arrDeviceList.length ===0 ){
        console.log('Search mobile device failed!');
        process.exit(1);
    }

    arrDeviceList.forEach(function(device){
        let caseName = specName + ' : ' + (device.name?device.name+' ['+device.udid+']':device.udid);

        describe(caseName, function(){

            this.timeout(600000);
            this.slow(1000);

            before(function(){
                let self = this;
                let driver = new JWebDriver({
                    'host': host,
                    'port': port
                });
                self.driver = driver.session({
                    'platformName': platformName,
                    'udid': device.udid,
                    'app': /^(\/|[a-z]:\\|https?:\/\/)/i.test(appPath) ? appPath : rootPath + '/' + appPath
                });
                self.testVars = testVars;
                let casePath = path.dirname(caseName);
                self.screenshotPath = rootPath + '/screenshots/' + casePath;
                self.diffbasePath = rootPath + '/diffbase/' + casePath;
                self.caseName = caseName.replace(/.*\//g, '').replace(/\s*[:\.\:\-\s]\s*/g, '_');
                mkdirs(self.screenshotPath);
                mkdirs(self.diffbasePath);
                self.stepId = 0;
                return self.driver;
            });

            module.exports();

            beforeEach(function(){
                let self = this;
                self.stepId ++;
            });

            afterEach(async function(){
                let self = this;
                let filepath = self.screenshotPath + '/' + self.caseName + '_' + self.stepId;
                let driver = self.driver;
                await driver.getScreenshot(filepath + '.png');
                let json = await driver.source();
                fs.writeFileSync(filepath + '.json', json);
            });

            after(function(){
                return this.driver.close();
            });

        });
    });
}

function getRootPath(){
    let rootPath = path.resolve(__dirname);
    while(rootPath){
        if(fs.existsSync(rootPath + '/config.json')){
            break;
        }
        rootPath = rootPath.substring(0, rootPath.lastIndexOf(path.sep));
    }
    return rootPath;
}

function mkdirs(dirname){
    if(fs.existsSync(dirname)){
        return true;
    }else{
        if(mkdirs(path.dirname(dirname))){
            fs.mkdirSync(dirname);
            return true;
        }
    }
}

function callSpec(name){
    try{
        require(rootPath + '/' + name)();
    }
    catch(e){
        console.log(e)
        process.exit(1);
    }
}

function getEnvList(){
    let strEnvList = process.env.devices;
    if(strEnvList){
        return strEnvList.split(/\s*,\s*/).map(function(udid){
            return {udid: udid};
        });
    }
}

function getDeviceList(platformName){
    let arrDeviceList = [];
    let strText, match;
    if(platformName === 'Android')
    {
        // for android
        strText = cp.execSync('adb devices').toString();
        strText.replace(/(.+?)\s+device\r?\n/g, function(all, deviceName){
            arrDeviceList.push({
                udid: deviceName
            });
        });
    }
    else{
        // ios real device
        strText = cp.execSync('idevice_id -l').toString();
        strText.replace(/(.+)\r?\n/g, function(all, udid){
            let deviceName = cp.execSync('idevice_id -d '+udid).toString();
            deviceName = deviceName.replace(/\r?\n/g, '');
            arrDeviceList.push({
                name: deviceName,
                udid: udid
            });
        });
        // ios simulator
        strText = cp.execSync('xcrun simctl list devices').toString();
        strText.replace(/\r?\n\s*(.+?)\s+\((.+?)\) \(Booted\)/g, function(all, deviceName, udid){
            arrDeviceList.push({
                name: deviceName,
                udid: udid
            });
        });
    }
    return arrDeviceList;
}
